### ISSUE TITLE
Choose a contractor is not convenient.

### ISSUE THREAD

**Issue by Urvdmih** [moneymanagerex/android-money-manager-ex#10]
When the chosen contractor - no buttons or select "OK". Have to push back, because of what happens accidentally come out of the wiring at all (twice tapnesh ago and everything necessary for a new skid)

**Comment by MisterY** [comment]
The most convenient option would be a one-tap selection of the payee. Then return to the previous screen.

**Comment by Chaos99** [comment]
Second that.

Also, setting the initial focus on the search field might sound convenient, but it automatically pops up the keyboard which hides half of the list.

Sorting the list by popularity of payees and hide the keyboard. Then a user would be able to get away with just one touch for his 10-12 most popular choices.

Pre-group popularity based on weekday/time of day and you will probably present the right choices 9-out-of-10 times.

Mark a payee as selected if the user has just created it would also save another touch.

**Comment by AlessandroLazzari** [comment]
This issue is solved on 2.0.0 version.
If you want you can try on alpha version
