### ISSUE TITLE
Budget: value per category take only the first sub-category into account

### ISSUE THREAD

**Issue by julientard** [moneymanagerex/android-money-manager-ex#1011]
Hello, 
I just discover your app on android and PC, and I love it !
However there are some bugs.
One is about the budget screen, aggregate by category.
In the column "actual", the value is the value of the first sub-category. There isn't a sum on all sub-category.
If screens needed, plz ask!

**Comment by MisterY** [comment]
Thanks for the submission. Please also feel free to look through the code and submit pull requests for any improvements and modifications you find useful. Preferably through a prior discussion in the issues list. Welcome to the club. :)

**Comment by MisterY** [comment]
Yes, please. A screenshot seems necessary.
I just checked the Budgets behaviour and everything seems to operate as designed. Could you please provide a more detailed explanation? Thanks.

**Comment by julientard** [comment]
I made a simple database example, plz see entached file.
So there is one budget on category: Food 50€
And two expenses, on sub-categories: 
- Food:Dining Out 20€
- Food:Groceries 10€
The total is 30€, but the displayed value for Food category is 20€, which is the first sub-category.
Hope this helps to understand !

[Example.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/498865/Example.zip)

**Comment by MisterY** [comment]
Thanks a lot for your contribution in pointing this out. This will be corrected in the next version, which is due today or tomorrow at the latest.
