### ISSUE TITLE
Floating button scrolls outside the view on Currencies list

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#103]
When scrolling down the list of currencies, the + button scrolls down off the screen.
Emulator, Jelly Bean 4.1.1.

**Comment by prannou** [comment]
The behavior of this type of button depends of the app : some apps hide the button when scrolling down and make it reappears when scrolling back up (as is the case here) and other apps always shows this button.
But I agree it would be better in this case to always show the button.

**Comment by AlessandroLazzari** [comment]
The floating action button was implemented in the mail so to hide automatically when the user scrolls through the lists. it is a standard behavior. If you feel a little useful that the button is hidden just remove the listener from the listview.
I would leave the standard behavior as in all other applications, but this is just my opinion.

**Comment by MisterY** [comment]
If this is how it behaves elsewhere, then it is fine. Actually, I'm just checking GMail, there the button stays constantly. In Google+ it scrolls down. 
Now that I think of it, I'm starting to like the behaviour. OK, so not a bug, then.

**Comment by AlessandroLazzari** [comment]
However, this is not a problem, but a choice of the developer....
If we like that the button is fixed, just change a line of code ;-)

2015-04-02 22:52 GMT+02:00 Alen Siljak <notifications@github.com>:
