### ISSUE TITLE
Adding a Payee crashes app

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1030]
>Add a payee via the entities menu. When I type the name and click OK, the app exits. On return, the payee has been added, but annoying that the app closes when I enter a name via this menu.

**Comment by vladimir-poleh** [comment]
Can't confirm on the latest dev branch.

**Comment by MisterY** [comment]
Great, thanks! I also cannot reproduce on the current Beta.
In that case, any app crash will be picked up by Crashlytics and we can correct the code as for any other unhandled exception.
