### ISSUE TITLE
"Change status" button yields empty form

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/android-money-manager-ex#1036]
Hello, 

When long pressing a operation, the change status button appear. However, clicking the button shows a form  with only the title "Change status"

![screenshot_2016-09-20-23-00-28](https://cloud.githubusercontent.com/assets/7243861/18688945/d8ffc1a4-7f86-11e6-9f98-e5230ca306b8.png)

I'm using version 2016.09.20.922-beta.

Cheers

**Comment by MisterY** [comment]
A screenshot would be great here. Thanks for the submission!

**Comment by MisterY** [comment]
Fixed with #1037
