### ISSUE TITLE
Options not visible on toolbar after long-tap; list of transactions in account

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#104]
When a transaction is long-tapped the header with options will appear but the options are not visible﻿. The header is completely white.
The buttons are still there and function normally.
Happens in both themes, light and dark.

**Comment by prannou** [comment]
I can't reproduce this bug on my phone : when I long tap on a transaction I can see the option menu to delete, duplicate or change status (green bar with white icons in light theme). Is this the options that does not appear for you ? Maybe a problem with a specific Android version (I use Android 5.0).

**Comment by AlessandroLazzari** [comment]
Yes the problem is only Jellybean Android version.
I will try this problem.

**Comment by AlessandroLazzari** [comment]
Fixed
