### ISSUE TITLE
Remote info gets forgotten

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1044]
The remote path is empty, no field for the remote changes.
See what causes this.
Could be the delayed upload when no network present or something similar.

**Comment by diggy128** [comment]
Please make this a top priority.
I'm using sync and since the last update I can't keep the databases in sync, and since I use the app for many users I have to manually insert records with sql every day to keep them in sync.

As I've noticed this happens after user 1 adds an entry and user 2 tries to sync. Then the app in user's 2 phone empties the remote path.

**Comment by MisterY** [comment]
This already **is** the top priority. However, there is still no reliable way to reproduce.
The scenario you describe is not resulting in the overwritten remote path, unfortunately. If you do notice any regularity, please let me know and I'll adjust and publish a new version right away.

**Comment by diggy128** [comment]
Haven't pin-pointed yet, but here is a case where it happens every time:
- Device A makes changes and uploads (automatically) to the cloud
- Database is synced (aka downloaded) automatically to device B
- Notification in device B pops up in top bar
- Open database in device B (always from the top bar notification)
= At password dialog no "database is up to date" toast shows
= Remote file path gets emptied (and so does the sync action in the menu, albeit this seems to be the result of not having a remote path to sync to).

**Comment by MisterY** [comment]
Excellent. Thanks, will check it out tonight probably. Perfect timing for the release on the 1st of the next month. ;)

**Comment by MisterY** [comment]
Thanks a lot @diggy128! Nailed it.

I've adjusted it so that the existing metadata will be reused, if found. Also, the sync heartbeat will be started on app start, if enabled. Sometimes the system or a user kills it, which stops the sync timer, I believe.
