### ISSUE TITLE
Make all preferences per-database and store them in each database

### ISSUE THREAD

**Issue by diggy128** [moneymanagerex/android-money-manager-ex#1048]
It would be more than helpful to have every setting stored in each database.
This way when syncing a database preferences would be included in the database and no separation would be made in app vs db preferences that leads to bugs like #1008.

Even more so preferences seemingly irrelevant to per-database use (eg theme) could also be used as a visual indicator as to what database is open.
Further more when syncing a database not only among several devices but also among several users it makes perfect sense to have central preferences set (much like a client-server app).

**Comment by MisterY** [comment]
Is it practical to be forced to set up the theme, date format, and other sync and startup preferences and filter for *each* database file?

**Comment by diggy128** [comment]
Well, when using a database across many devices (with the same user) or across many devices and many users it simply gives a central way to prepare and manipulate preferences globally.

For syncing however I'm most definately sure that it should be per database and clearly stated whether the current database is local only or synced with the cloud. 
Imagine this: I have a database I share with my family (that I sync to the cloud) and another one I use to keep track of my business expenses (that I use only locally on my phone). I can't tell when I'm using which and whether it syncs to the cloud.
for #986 I'll post some notes there.

**Comment by wolfsolver** [comment]
Take a look to latest version. almost everything is in database.
