### ISSUE TITLE
New or Edit transaction screen usability

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#1049]
Hi
I am a beta tester and I have troubles with the new layout for the New transaction screen.

I attache the old and new one lay out with the same transaction. There are several points:

1.- The most important is the notes field that now has an intra scroll vs the old auto expand. The old notes fields expands so it is easier for text input and review. Please consider it.

2.- Now there is too much screen real state wasted. see the two screen shots.

Note: the screen is 5.5" 1280x720 pixels.

<img src="https://cloud.githubusercontent.com/assets/8289274/18838416/047bed86-83cd-11e6-9c35-b38c39119200.png" width="200px" /> <img src="https://cloud.githubusercontent.com/assets/8289274/18838415/0452ba88-83cd-11e6-8b8e-485a75fc7250.png" width="200px" />

**Comment by Geoplace** [comment]
There are some icons that are intuitive enough to omit the text.

For example you could Omit the word "DATE" and universally everyone recognize the icon and date format. So you can save screen space there.

May be also the "AMOUNT" word could be omitted and the sign $ is self explanatory because you pre- populate it with $ 0.00

**Comment by MisterY** [comment]
Thanks a lot for the feedback! There are some constructive suggestions.
However, please note that:
- removing the title from the date would work here but not on the Recurring Transaction editor where there are two date fields.
- the same goes for the amount once the Transfer is selected. 

The point of releasing these Beta versions is exactly to get the type of feedback you are providing. These are not the definitive decisions but small steps in certain direction. I implement a few things and use the app to see if they improve or hinder the experience.
Icons in general should replace the titles. I'll see if I can find better icons that illustrate From/To concepts, for example.
The Notes multi-line is a bug. It is definitely set as a multiline text box but the parent control is limiting its expansion, I think. This will be corrected.

**Comment by MisterY** [comment]
Instead of "Account from" / "Account To" titles, an arrow icon could be used to indicate that the funds flow from the account/amount above to the account/amount below.

Account
Amount
||
V
Account
Amount
