### ISSUE TITLE
Force freeze the UI when doing sync

### ISSUE THREAD

**Issue by diggy128** [moneymanagerex/android-money-manager-ex#1061]
When syncing a DB to the cloud and have password set for the DB, you can still enter the application and enter transactions which could lead to conflicts it the DB was changed in the cloud.

So, during sync the app UI should be freezed to allow the sync to complete.

**Comment by MisterY** [comment]
Isn't this already the case?

**Comment by diggy128** [comment]
Unfortunately no, when the password screen shows, you can enter the password and view/edit the database BEFORE the "database is up to date" toast shows.

**Comment by MisterY** [comment]
That's true. The recommendation would be to wait a few seconds or perform the sync manually. Freezing the app every time the sync happens would lead to a very nasty user experience for everyone.

**Comment by diggy128** [comment]
Fair enough. Maybe the best thing would be to disable adding - editing transactions only during sync.
In any other way I'm afraid inevitably at some point, racing conditions will create a conflict in databases.

**Comment by MisterY** [comment]
Sure. I agree with the need to handle the synchronization locking better. We just need to find an elegant solution for it.
The recent changes are a good step in that direction. As of version 920, there are indicators for local and remote file changes. Perhaps an additional check just before the local file is replaced after download would be useful.
For the moment, it is necessary to keep this behaviour in mind and allow for possible changes in the cloud. This is one of the reasons I prefer to do my synchronization manually. 
The good thing is that the file won't be overwritten if there is a conflict. It will be marked specifically and the synchronization won't continue. What's missing now is the ability for the user to resolve that somehow.

**Comment by diggy128** [comment]
Have you come up with a way to resolve this?
It's a PITA as the database goes out of sync many times a week because of this behavior, and every time entries have to be recreated manually.

I've thought of an implementation as a temporary workaround:
Add an option in preferences that when set would force to wait for sync to complete before allowing changes to the database (using a sane timeout).

**Comment by MisterY** [comment]
In light of #1250, it is not likely that any new activity will be done in the synchronization area.
