### ISSUE TITLE
App force-closing within Brazil after BST in effect (yesterday)

### ISSUE THREAD

**Issue by maiaftv** [moneymanagerex/android-money-manager-ex#1078]
Every time I try to open an account, the application force-close. Setting the date to yesterday with the standard time (GMT-3), everything works fine. The problem occurs if I set the automatic date and time, thus using the BST (GMT-2).

Probably other users are affected, also. Please inform me if you need further help debugging the issue.

**Comment by MisterY** [comment]
Thanks for the report. [This commit](https://github.com/moneymanagerex/android-money-manager-ex/commit/820cd449f1d8db7c0c0b285616cf59ff55697824) is trying to handle that. Once the new Beta rolls out, please try with the transition date (16th?).

**Comment by MisterY** [comment]
Beta is just being published. Please reopen if the issue persists.

**Comment by rubensvm** [comment]
I am having the same problem and had mitigated it by using app version 2016_02_02_r766. The new beta version released yesterday didnt solve the problem.

**Comment by MisterY** [comment]
Duplicate od 1080.
