### ISSUE TITLE
"Illegal instant due to time zone off set transaction" error

### ISSUE THREAD

**Issue by anonimou0** [moneymanagerex/android-money-manager-ex#1080]
Brazil started light saving period on October 16th. 
The transactions on this particular day cannot be searched, showing the error attached.
When searching straight on the wallet, rolling down, the app force close.

Is it a configuration on my side that I should change?

**Comment by anonimou0** [comment]
![tmp_2847-screenshot_20161019-172734268425577](https://cloud.githubusercontent.com/assets/14253996/19534309/07bee90a-9622-11e6-81b0-e3ae3f81afef.png)

**Comment by MisterY** [comment]
It's a bug in JodaTime library.
Can you confirm that this happens with the current Beta version?

**Comment by rubensvm** [comment]
The problem continues even in the beta version.

**Comment by MisterY** [comment]
Converted to default Android/Java Date type. This should resolve the issue.

**Comment by rubensvm** [comment]
The app stop crashing every time we tried to register a expense to october 16th. Problem solved. Thanks.

**Comment by MisterY** [comment]
Great! Thanks for the confirmation. Please note that there was a massive transition from Joda Time date objects to the plain Java ones. There could be some formatting or parsing issues so please do report any irregularities.

**Comment by anonimou0** [comment]
thanks, @MisterY for the great response on this =)
