### ISSUE TITLE
Databas schema for android&desktop are different

### ISSUE THREAD

**Issue by firstrose** [moneymanagerex/android-money-manager-ex#1084]
More tables and indices are in desktop version.

So, open a desktop DB with android app will get annoying tips
![screenshot](http://i1.piimg.com/524586/979ee25a3893b145.gif)

**Comment by MisterY** [comment]
The latest database files from https://github.com/moneymanagerex/database are used in the Android app and the desktop app.
The screenshot shows an error about a duplicate index (IDX). Please check your database with any SQLite tool. This is not a schema issue.
