### ISSUE TITLE
Sync is not triggered when adding an entry via widget

### ISSUE THREAD

**Issue by diggy128** [moneymanagerex/android-money-manager-ex#1086]
I've setup sync with dropbox, and whenever I add an entry via the homescreen widget, syncing is not triggered before adding the entry so every time the database goes out of sync.
Even worst, since the database is shared between 3 different people, it happened many times that the other users have added entries and sync, while I have to manually recreate as many entries I've added since the time I added the entry via the widget.
This issue is related to #1061 in the sense that at least 3 times a week one has to pull the database from the cloud and manually enter several entries that were created since sync was not triggered or entered the entry before the sync completed.

**Comment by MisterY** [comment]
Do you have the "Upload the database immediately..." option activate in the settings?
I'm using the same scenario and have not experienced any issues with synchronization. I'm entering the transactions via the widget almost exclusively.

**Comment by diggy128** [comment]
Yes, all 3 users have the setting enabled.
