### ISSUE TITLE
Can not open .mmb on sdcard under android6

### ISSUE THREAD

**Issue by firstrose** [moneymanagerex/android-money-manager-ex#1088]
<img src="https://cloud.githubusercontent.com/assets/1551595/20702735/136daf5a-b654-11e6-8071-f94e807ac649.png" width="200px" />

But I can open is successfully after copy it into cellphone'storage

**Comment by MisterY** [comment]
Perhaps it is readonly?

**Comment by firstrose** [comment]
No. It's not readonly. Just different location.

**Comment by MisterY** [comment]
Can you try now, after #1278?

**Comment by firstrose** [comment]
Yes. It's OK now. Thank you.
Another question. Looks like the .mmb from sdcard will be copied to internal storage after opening, isn't it?

**Comment by MisterY** [comment]
Great!
Yes, now the db is always copied from the storage provider to a locally-accessible storage (even if it from SD, the app can't know that). Then it is copied back (synced) by pressing Synchronize button manually. 
The background and period sync should be implemented sometime later. The old sync logic needs to be rewritten.
