### ISSUE TITLE
Add a "Cleared" transaction status

### ISSUE THREAD

**Issue by ac0935p** [moneymanagerex/android-money-manager-ex#1091]
For credit card transactions (amongst others) it would be great to have a "Cleared" status between "None" and "Reconciled". Typically a transaction is entered on the day it is made, but not reconciled until the monthly statement is issued. In between those two events, transactions do appear on the online account and it is nice to be able to track those that have been listed and those that haven't yet.

I am a long-time user of Financisto, moving to MMX and this is the only feature I miss, so far.

**Comment by MisterY** [comment]
Fully agree. This would need to be coordinated with the desktop application team as the functionality needs to be supported across all the supported platforms. I would recommend creating an issue in moneymanagerex repository and linking here.

**Comment by Snaptags** [comment]
I'd second this improvement and added a [desktop issue](https://github.com/moneymanagerex/moneymanagerex/issues/1405).

**Comment by MisterY** [comment]
We could still introduce this status. With remark that it is not yet supported on desktop.
