### ISSUE TITLE
can not open database after system upgrade

### ISSUE THREAD

**Issue by ShosGithub** [moneymanagerex/android-money-manager-ex#1093]
Hi

I got a really difficult problem
Today i upgraded my phone from android 6 to 7
After the upgrade i found that i am no longer able to open my database
The app shows me that the password is not correct, however i use this app everyday, it is no way for me to input a wrong password.
I also tried to restore backups but neither of them can be opened.
Is there anyway to rescue my data? I used this app for years i really hope those records could not get lost.

I really appreciate if you could give me some advices.
Thank you.

**Comment by MisterY** [comment]
Duplicate. Please see #981

**Comment by ShosGithub** [comment]
Thanks for your reply.

2016年12月6日 04:47，"Alen Siljak" <notifications@github.com>写道：

**Comment by shaker214** [comment]
I have the same problem, I just got a new Android phone and MMEX worked fine on it until the Android system

**Comment by shaker214** [comment]
Until the Android system upgraded. After that, I keep getting a "passcode not match" error. Is there a workaround for this problem? I really like MMEX, on both my PC and my mobile device. I have been using this program for 6 years now.

**Comment by MisterY** [comment]
Yes, there is a solution. Please at least read the other comments.

**Comment by shaker214** [comment]
Ok, my apologies for not finding the solution last night, but yes, I was able to fix it today using the information found here. Basically, I fired up my old mobile device and removed the passcode, then removed and reinstalled Android money manager ex on my new device and linked to my Dropbox account. This time, I was able to download and view my information and upload to sync with my PC. I also re-entered my passcode using my Android 7 device and all is working well now! Thank you to all who have developed and tested this app. it is one of my favorite apps.

**Comment by shaker214** [comment]
A quick question though. I was fortunate to stool have my old mobile device in my possession to remove the old passcode. Many people trade in their old device, do this option isn't available to them. Just for future reference, is there a way to "uninstall" a major Android update temporarily to accomplish the task of removing the mmex passcode in the earlier version of Android for those people that do not have access to their older device?

**Comment by shaker214** [comment]
Still, not stool

**Comment by vladimir-poleh** [comment]
It seems that this is a reason of the problem:

`Passcode.java`
``` Java
    private String encrypt(String s) {
        String ret = null;
        try {
            if (Build.VERSION.SDK_INT <= 23) {
                ret = SimpleCrypto.encrypt(KEY, s);
            } else {
                // todo Encryptor.enc
                return s;
            }
        } catch (Exception e) {
            Timber.e(e, "encrypting passcode");
        }
        return ret;
    }
```

**Comment by MisterY** [comment]
@shaker214, thanks for the feedback. Glad that you managed to transition to Android 7.
 
Unfortunately, I am not sure what a proper solution for this issue would be. In 7, a certain encryption functionality has been removed and is therefore not possible to decrypt the previously-set pin codes.
I find the whole pin "protection" useless, to be honest. Until the full file encryption is supported, this is simply more inconvenience for the actual user then for any sort of attacker trying to get to the data.

**Comment by vladimir-poleh** [comment]
Why not use classic scheme of the hashes comparing? It is just local PIN code, no need to think about high security as file is not encrypted anyway. Main problem of this solution - we need to think about users with existing PIN.

**Comment by MisterY** [comment]
Exactly. The problem is that the previous encoding scheme is incompatible with anything else and a full migration is required for all the users.
I was hoping that the desktop team would adopt the encryption which is also supported on Android but that has not happened yet.

**Comment by shaker214** [comment]
Yes, I would like to see encrypted db support, but until then, I do like having a pin on my mobile device just to keep "easy access" of my information to a minimum.I basically use this app for record keeping and to cross check my bank's records anyway. I really appreciate all the hard work you guys are doing to make this app available.

**Comment by Trainrecktr8** [comment]
ok let's roll

Adadsphinn Jedi master deadpool TR8NINJA
