### ISSUE TITLE
Security flaws in Android app

### ISSUE THREAD

**Issue by ErezYalon** [moneymanagerex/android-money-manager-ex#1096]
We found security flaws that enable a malicious app to extract the password and sensitive info from your app. Who should I contact about this? Seems like reporting it publicly doesn't make much sense.

Best,
Erez Yalon
Checkmarx Application Security Lead

**Comment by Trainrecktr8** [comment]
thanks again

Adadsphinn Jedi master deadpool TR8NINJA

**Comment by MisterY** [comment]
Hi! Thanks for the notification. This is an Open Source project and the source code is available for anyone to read, analyse, and improve.
The current implementation of the pin protection appears to be adequate for the intended purpose.
Naturally, any improvement in that regard is welcome and pull requests will most likely be accepted.
