### ISSUE TITLE
Catagories/Payee search freezes

### ISSUE THREAD

**Issue by gdixith** [moneymanagerex/android-money-manager-ex#1099]
using latest version of MMEx for Android
whenever I try to enter a category or payee which is in my local **indian language Kannada** MMEX freezes
Please help
thank you

**Comment by Trainrecktr8** [comment]
how can I help

Adadsphinn Jedi master deadpool TR8NINJA

**Comment by wolfsolver** [comment]
@gdixith is Still present in latest version?
