### ISSUE TITLE
Loan accounts: no category name and wrong icon

### ISSUE THREAD

**Issue by Spoker** [moneymanagerex/android-money-manager-ex#1102]
Hi,

I think there is something wrong with the loan account category.
The text is missing and the icon doesn't match the other icons.

<img src="https://cloud.githubusercontent.com/assets/4959883/22168091/b2f804d2-df6a-11e6-9497-c05356b0a3c3.jpg" width="200px" />

**Comment by MisterY** [comment]
What is a Loan account? How do you create one?

![image](https://cloud.githubusercontent.com/assets/462445/22170256/012482a0-df7c-11e6-8270-1f5448bd5603.png)

**Comment by Spoker** [comment]
You can create one from mmex desktop version 1.3.x.

**Comment by MisterY** [comment]
I see. Unfortunately, there is no support in the mobile app for this type of account. Someone would need to add that.

**Comment by Spoker** [comment]
I am by no means a developer, but I have forked the repo and was able to build it in android studio.
Now I would like to add this feature.

I have added the 'Loan' and 'Shares' account types to the enum Accounttypes. I can't find the graphics for these categories however. Where are these located?

**Comment by MisterY** [comment]
Hi, @Spoker, the graphics are in the font-icon library. Check Android-Iconics library and how it works. There are Font Awesome and Google Material libraries currently included with the project. There should be something that matches the accounts.
However, just adding these types will not be enough for people to use them. You'll need to handle displaying of these accounts on the home screen, add them to the calculation of the balance, as well adding an account transaction list and editors for individual items. Not all of these are required at once, of course, but are needed to completely implement the support for these types of accounts.

**Comment by Spoker** [comment]
I made a bit of progress. I added the account types in the home screen and made them translatable.
I could also set an icon for Shares accounts, but not for loan accounts.
I don't see the difference why loan accounts will not show the icon.
You can follow my progress here:
https://github.com/Spoker/android-money-manager-ex/tree/UpdateIcons

**Comment by ljw10** [comment]
I have absolutely 0 experience here, but am interested in getting this working, too.  Based off the code you posted I would guess that the investment icon isn't working either, and that you have to add:

`holder.imgAccountType.setImageDrawable(icon);`

at the end of each.

**Comment by Spoker** [comment]
Thanks @ljw10 , that just solved the problem! Nice catch.
I will re-submit the PR to the dev channel.

**Comment by MisterY** [comment]
Thanks! Released as beta 969. Do close this item once confirmed in beta test.

**Comment by Spoker** [comment]
Beta 969 confirmed as working. Closing issue.
