### ISSUE TITLE
App crashes on exit every time

### ISSUE THREAD

**Issue by colourqueen** [moneymanagerex/android-money-manager-ex#1108]
I started having the issue after upgrading to v1.3.1 (DB v7) on Windows 10 x64 and have just upgraded to v1.3.3 in an attempt to clear it but it is still happening.
Every time I exit Moneymanger, I get a crash with debug reports. I have sent it in for analysis but reattach the xml file here.  Any updates on the database are saved and synchronized ok with my android version via dropbox.
[MoneyManagerEx.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/834299/MoneyManagerEx.zip)

**Comment by MisterY** [comment]
Hi, could you please post to the correct repository? This is a repository for Android version of Money Manager Ex. Thanks!
