### ISSUE TITLE
Latest release lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [moneymanagerex/android-money-manager-ex#1111]
Hopefully just forgotten: the latest Release lacks the `.apk` file on `releases/`. Could you please add it again? Thanks in advance!

**Comment by MisterY** [comment]
Thanks for the remainder. Yes, had some issues with compiling the .apk for a couple of days, after upgrading Android Studio and several libraries. Now that this is finally settled, I thought it would be better to publish a Beta version first to see if everything still works as expected.
If everything goes ok after all the Beta members have installed the app, I'll be releasing the stable version.
Will amend the release info now.

**Comment by IzzySoft** [comment]
Thanks! Will be [picked up](https://apt.izzysoft.de/fdroid/index/apk/com.money.manager.ex) then as soon as it's available :innocent:

**Comment by MisterY** [comment]
Great! Thanks for sharing!

**Comment by IzzySoft** [comment]
Anytime! Feel free to link (next to the Playstore link), updates usually appear within 24h of your adding them to the corresponding new tag. Folks w/o Playstore access will be happy to have an alternative – as they can use my repo with the F-Droid client and will be notified of updates automatically.

Thanks for making your app available freely and open-source, keep up the good work!

**Comment by MisterY** [comment]
That's fantastic as I've never managed to set up F-Droid repo.
Do you host only the stable version or Beta also?

**Comment by IzzySoft** [comment]
There's no separate "beta channel" in my repo. I usually pick up what was tagged, so it's up to the developer(s). I can, however, distinguish between "release" and "pre-release" – and configure my updater to ignore or not ignore pre-releases. By default, I pick them up both – unless pre-releases are too unstable for end-users to be considered. I'd rather prefer not to maintain multiple repos – so when in doubt, just let me know to skip pres. As I keep signatures unchanged, users still could cross-update if you e.g. tell them to "try the latest pre-release to check whether X works". If the `.apk` is the same you upload to playstore, they could even easily switch between sources ;)

**Comment by MisterY** [comment]
OK, I see.
I decided to take an approach of creating a separate app for Beta so that it can be installed in parallel to the stable one. The other approach is not very practical as the users would need to uninstall, leave the Beta channel, and install again. This way it's two separate apps so it is easy to go back to the stable version if something goes wrong in the pre-release.
We have them here: [Stable](https://play.google.com/store/apps/details?id=com.money.manager.ex) and [Beta](https://play.google.com/store/apps/details?id=com.money.manager.ex.beta).
But no worries, I was just wondering.

**Comment by IzzySoft** [comment]
Yes, I've seen that. And if those are different package names, I could in fact tread them as different apps. But it would be a mess to keep them apart from the same repo (I had to mod my updater for that); plus with the ~20M I reserve per app (I run all this on my "personal budget", there's no financial backing behind my "altruistic task"), I'd rather have a wider spectrum of apps available in that space, to be honest :wink:

**Comment by MisterY** [comment]
Sure, you're absolutely right. I appreciate the effort. Will keep this issue open as a reminder to add the repo link to the app's homepage as another distribution channel if that's ok. Thanks!

**Comment by IzzySoft** [comment]
By all means, of course that's OK :+1:

**Comment by MisterY** [comment]
Added the link to the app's homepage. 
I'm not sure if I can initiate the rescan once a new release is published.

**Comment by IzzySoft** [comment]
Thanks a lot! How about doing the same for the `README.md` here at Github, next to the Playstore link? :smiley_cat:

Rescan: Not sure what you're referring to. If it's about my script picking up the `.apk`, it will do so as soon as there's a new tag with an `.apk` attached, no rescan from your end needed. The script knows which `apk` it already has, and only checks newer releases then.
