### ISSUE TITLE
Bug: Report where money goes are in wrong currency

### ISSUE THREAD

**Issue by mehranm** [moneymanagerex/android-money-manager-ex#1113]
I have used two different currencies in my accounts. One account is in US and another in AUS. However, the report is converting amounts to AUS dollar not the other way around as default currency is in US dollar.
Thanks
Mehran

**Comment by mehranm** [comment]
Does it depend on the current rates?

**Comment by mehranm** [comment]
I found out, that if I change currency rates and say Aus is 0.7 and US 1. The numbers are converted to US dollars. The reports generated cannot produce two separate lists for both currencies?

**Comment by MisterY** [comment]
At the moment, the reports are always in base currency.
