### ISSUE TITLE
Gdrive sync

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1114]
Problem with Gdrive sync....
Lost sync in any device

**Comment by MisterY** [comment]
This seems to be the most important issue at the moment. Pull requests with solution are welcome.

Here is the CloudRail changelog: https://github.com/CloudRail/cloudrail-si-android-sdk/blob/master/changelog.txt

The deadline for Google authentication update seems to be April 20. I'm not sure what exactly is changing but Google is making too many breaking changes as of late.

**Comment by MisterY** [comment]
CloudRail library was updated as it includes a fix for Google Drive file handling.
Also, OAuth2 was implemented as the previous version will be outdated by Google on April 20.
