### ISSUE TITLE
problem with recurring transactions

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/android-money-manager-ex#1116]
I'm using mmex on both android (v. 2017.4.16.954-beta from google play) and mac (v. 1.3.3) and I'm having problem with recurring transactions. All the recurring transactions have been created from an older mmex desktop version (probably v. 1.1 or 1.2). On desktop mmex, everything work fine: On "date paid", mmex automatically enter recurring transaction to occur on "date due".  However, these same transactions entered from android mmex 1/ are not entered automatically in the database (minor problem) and 2/ the notification to enter the transaction appear on "date paid" (same behaviour as desktop), but to be paid on "date paid" too.  

thanks for your help.

Cheers.
Xavier.

**Comment by MisterY** [comment]
Hi,
There is no support yet for automatic entry of recurring transactions in the mobile app. Anybody willing to implement this is free to do so. The pull requests are encouraged.
Duplicate of #89.

**Comment by xraynaud** [comment]
ok, but what about the date problem ? the fact that recurring transactions are entered on the wrong date makes recurring transaction unusable when working with both android and desktop version. Is this a problem of my own db or and inconsistency between both versions ? 
Thanks.

**Comment by MisterY** [comment]
Sorry, I missed that second part of the issue.
Yes, I'd say the behaviour is different, in that case. In the mobile app, the Due Date is the due date for the payment, while the pay date is the suggested date of payment. The date is adjustable in the edit screen before the transaction is entered. The assumption being that we are making a payment before the due date.

**Comment by xraynaud** [comment]
The main interest for me would be to have the same behaviour as with the desktop app. Also, I like to be able to foresee what will happen on my bank account for the next couple of weeks. So if  I have a payment that should be paid on the 15th, I like to have it entered in the database on the 1st.

**Comment by MisterY** [comment]
Related: #89

**Comment by wolfsolver** [comment]
Can you give a try to latest release?
