### ISSUE TITLE
Scan QR code for adding transactions

### ISSUE THREAD

**Issue by Crazyphil** [moneymanagerex/android-money-manager-ex#1119]
In Austria, since April 2017, for all cash transactions in every business, a printed bill has to be handed out to the customer. On every such bill there has to be a QR code containing details about the transaction (most importantly, the amount; [specification in German](https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20009390&FassungVom=2017-04-01)).

I plan to add a button in addition to the "+" for adding a transaction via the ZXing Barcode Scanner, where in the ideal case a user just has to save the transaction without any changes, because the data is already filled in correctly.
The settings would contain another menu for configuring the scanning process, e.g. creating split transactions by VAT rate or mapping certain identifiers to Payees.

The whole process should be held as generic as possible, so that additional machine-readable bill formats can be added at any time. However, before I start implementing it, I would ask for feedback: is this functionality that would fit the Android version of Money Manager Ex? Do my proposed changes fit into the general workflow?

**Comment by MisterY** [comment]
Hi! Thanks a lot for offering to add this functionality. I would say that it should easily fit into the existing app. The new transaction screen is already exposed to the widget and the SMS input so adding another widget would fit.
I guess this does not require database schema changes, therefore it is limited only to the mobile app.
Please, go ahead and let me know should you have any questions or comments. Thanks again for the contribution!
