### ISSUE TITLE
app crashes on first Dropbox download

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#112]
After app installation from Play Store (beta 1), selecting Dropbox file, the app crashed on both Nexus 7 tablet and Galaxy S3 phone. Android 5.0.
To be tested on emulator.

**Comment by MisterY** [comment]
Logcat shows some errors due to drivers, which could be due to custom ROM.
There are also lots of messages about SpannableStringBuilder - spans can not have zero length.

**Comment by AlessandroLazzari** [comment]
Can you post a logcat?

**Comment by AlessandroLazzari** [comment]
I was not able to simulate the error with my nexus 5 updated to android
5.0.2

**Comment by MisterY** [comment]
I can't seem to get to that state now. Tried deleting the cached files, reinstalling the app, etc.
Seems to only appear when I download a *new* version of the app. Otherwise my settings seem to stay and the Dropbox file is already set.
Let's hope this is only my ROM. If it happens again I'll try to get the logcat early.
