### ISSUE TITLE
Feature Request: "Payers" under "Entities"

### ISSUE THREAD

**Issue by snhv** [moneymanagerex/android-money-manager-ex#1120]
Hi,
Under "Entities", besides "Payees", we also need "Payers" as well. Thank you.

**Comment by MisterY** [comment]
Hi, thanks for the suggestion. Payers and Payees are the same in the context of the application. They are a counterparty with whom the funds are exchanged.
Don't know why but in Quicken they are also called Payees, not Payers. I don't think a new distcinction is neccessary.

In any case, this should first be discussed with the desktop team as the mobile app needs to match the functionality. I'd recommend opening an issue in the MoneyManagerEx repository. Thanks!

**Comment by MisterY** [comment]
In all the finance apps I've seen, the counter-parties are called Payees, not Payers.
