### ISSUE TITLE
Bug report: Force close when first adding a new Payee directly

### ISSUE THREAD

**Issue by snhv** [moneymanagerex/android-money-manager-ex#1121]
Hi, I'm on Android 5.1.
After installing the app, adding a new Payee directly (i.e. through Entities, not through adding a new Transaction) will force close the app. The new Payee however is added and correctly listed when reopening the app. Continued adding Payees directly repeats the bug.
The bug stops after adding a new Payee through adding a new Transaction, i.e. now adding a new Payee directly won't result in a force close.
Hope I made myself clear. Thanks.

**Comment by MisterY** [comment]
Thanks for reporting.

**Comment by snhv** [comment]
I take back that "_The bug stops after adding a new Payee through adding a new Transaction, i.e. now adding a new Payee directly won't result in a force close._"
Today I added a few new Payee and the app forced close every single time, but the Payees were successfully added.
My phone is Meizu M2 Note.

**Comment by LucidComplex** [comment]
I can confirm this. Apparently the default action after adding a payee is to save it and close the activity. I assume it's to close the activity after adding a new payee for a transaction. The bug here is that even when you manually go to the payees section, adding a payee would close the app.

**Comment by MisterY** [comment]
This should be resolved in 966.
