### ISSUE TITLE
Passcode do not match after upgrading OS to 7.0

### ISSUE THREAD

**Issue by javierseixas** [moneymanagerex/android-money-manager-ex#1125]
Hi! Since I updated to Android OS 7.0 passcode doesn't work. When I write my password, the app shows a message "Passcode do not match".

It's de current encryption incompatible with the new version of the OS?

I found out that the logic is in the [`SimpleCrypto`](https://github.com/moneymanagerex/android-money-manager-ex/blob/master/app/src/main/java/com/money/manager/ex/passcode/SimpleCrypto.java) class, and for how it is using the Build Version to Encrypt and Decrypt, looks like the problem.

Thanks!

**Comment by MisterY** [comment]
You are unfortunately correct. The crypto provider was removed in 7.
Please have a look at #981 for the workaround.

**Comment by LindaDnl** [comment]
So is there a fix for this issue? Or is just time to find a new money manager app??
