### ISSUE TITLE
Vehicle in combo box transaction

### ISSUE THREAD

**Issue by ricardoglezf87** [moneymanagerex/android-money-manager-ex#1126]
When I selected the vehicle don't show the content, the combobox only show accounts that its is not asset

**Comment by ricardoglezf87** [comment]
Occur the same with the stocks created

**Comment by MisterY** [comment]
Hi, could you please provide some more information? Sorry, I have no idea what you are trying to say here.

**Comment by ricardoglezf87** [comment]
Ok, I'm Sorry for my bad English, I gonna Put a Photos for explain me well. On the Windows App I have a actives type vehicles called Corsa and Kymco, i have a loan called Ptmo Corsa and 3 investement funds called CABK COMUNICACIONES FI, Fondo Naranja S&P 500 and ING DIRECT FN Ibex 35FI:

![screenshot_20170707-082752](https://user-images.githubusercontent.com/10882986/27947767-21c18cc8-62ef-11e7-9651-ca0d3f46be2e.png)

![screenshot_20170707-082812](https://user-images.githubusercontent.com/10882986/27947776-2b067bea-62ef-11e7-8871-67fd004bde06.png)

when I Click on them for view the transactions, The app show the transaction of Ahorros Account,and don't allow select the account that i said previously:

![screenshot_20170707-082932](https://user-images.githubusercontent.com/10882986/27948039-275085da-62f0-11e7-89d3-dd978e1ab0c7.png)

**Comment by MisterY** [comment]
Thanks.
This is by design. Only transactional accounts are shown in this list.
The investment accounts are handled separately, through Watchlist and Portfolio views. And I'm not sure about Asset account type. That functionality I have never used.

**Comment by MisterY** [comment]
That functionality is contained in #429, which is not implemented yet.
