### ISSUE TITLE
Identify the Account and do the transaction by reading SMS

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1129]
Could you please add a feature to read the SMS and create the transaction automatically without manual intervention

**Comment by MisterY** [comment]
Please have a look at #185.
If that matches your needs, you can help out by testing the feature and providing some feedback. Thanks!

**Comment by velmuruganc** [comment]
Yes, it is a same issue and I am happy to test. Plz share me the app that needs to be tested

**Comment by MisterY** [comment]
Great! With the stable version this should work. I'm not sure if it would work with the Beta version as the namespace may be changed during the build. See the specs at #185, try creating a task with Tasker and see if it works and/or if any adjustments are required. Thanks!

**Comment by velmuruganc** [comment]
Actually, I am tester and dont hav knowledge in Android dev. Will it possible to provide app?

**Comment by MisterY** [comment]
This functionality is already implemented in the Money Manager Ex for Android app.

**Comment by velmuruganc** [comment]
Is there any setup to configure this features. I don't see it is working in my mobile

**Comment by velmuruganc** [comment]
I am using version 2017.06.30.957. Is there any new version?

**Comment by velmuruganc** [comment]
Any help on this.
