### ISSUE TITLE
Split in recurring Transaction

### ISSUE THREAD

**Issue by Douki31** [moneymanagerex/android-money-manager-ex#113]
Using version 2.0.0-beta1

Using a recurring transactions edited using the PC version, I am now able to consult the reccurring transations with the -SPLIT- category on my android phone.

However when I want to enter the next occurence on the android phone, the split transaction is deleted.

**Comment by MisterY** [comment]
Confirmed. Thank you for the bug report!

**Comment by Douki31** [comment]
I will wait the fix to enter the next occurence then :)
Thanks to you to support this very very nice App.
Cédric

**Comment by MisterY** [comment]
implemented
