### ISSUE TITLE
Wrong Account Balance value and Reconciled Balance value in cash accounts

### ISSUE THREAD

**Issue by MiCkOf** [moneymanagerex/android-money-manager-ex#1132]
Wrong Account Balance value and Reconciled Balance value in cash accounts, on a Desktop version all seems ok.
I don't think that this calculation has to do with the database.

**Comment by MisterY** [comment]
Could you provide some more details? I, for example, have been using the app daily for years and have not noticed any discrepancies. What do you mean by "wrong"?

**Comment by MiCkOf** [comment]
I have a Cash account and in the transactions view there is a small bar on the top that inform us for the Account Balance and the Reconciled Balance, also on every transaction bellow the value there is a calculation of the balance, there is a mismatch between them. for example the on the last transaction the calculated balance value is 3.27 and on the top the Account Balance and Reconciled Balance value is 6.84.
On the other hand in the Desktop Application (Linux OS) everything looks fine. Also I checked the database with an SQLite Editor and everything looks fine.

**Comment by MiCkOf** [comment]
This is a screen shot of my cellphone if this helps [https://www.dropbox.com/s/pwbl5q4aizydwgi/Screenshot_2017-07-07-09-00-02.png?dl=0](url)

**Comment by MiCkOf** [comment]
I have to mention that I don't have any problem with all the other account types (Bank Account, Credit Cards, etc).

**Comment by MisterY** [comment]
I suspect a corrupt database. Please see #606.

**Comment by MiCkOf** [comment]
Solved, Thanks MisterY for the support, you where wright the database was corrupted.

**Comment by MisterY** [comment]
Good to see that it is resolved! Thanks for the feedback.

**Comment by MisterY** [comment]
I've also updated #606 with some steps to identify and resolve this issue.

**Comment by ggraziotti** [comment]
I noticed that, if on account I show historical data no problem with balance. If I show the others intervals, actual and reconciled balance are different. This information is useful to solve ?
