### ISSUE TITLE
Issue with display of actual balance vs reconciled balance

### ISSUE THREAD

**Issue by DruplexThanks** [moneymanagerex/android-money-manager-ex#1136]
Hi,
I was previously using the android app before i synchronized my DB with the desktop app(windows). I went ahead and did a few transaction via the desktop app and made sure the DB was synchronized. On opening the same db on the android app i noticed that the amount displayed as the actual balance was totally different with that of the reconciled balance yet i had reconciled all my expenses. On the desktop app is displaying okay and i have no issues with it.

What would be the issue?

**Comment by MisterY** [comment]
Please try searching through the closed issues. Thanks.

**Comment by DruplexThanks** [comment]
Trust me, i already did that before writing the issue down. It would be
better if you would point me to link for the solution

**Comment by MisterY** [comment]
Have you tried searching for "balance" and then checking for anything that matches?
Like "https://github.com/moneymanagerex/android-money-manager-ex/issues?utf8=%E2%9C%93&q=is%3Aissue%20balance".
There will be several identical issues. If you have any suggestions on how to make this topic more prominent, I'm all ears.

**Comment by DruplexThanks** [comment]
Done. Thank you. Issue was resolved by exporting and importing the DB.

**Comment by MisterY** [comment]
Awesome! Good to see that. 
Unfortunately, there's not much that can be done from within the app itself. Perhaps running the integrity check on start would help.

**Comment by MisterY** [comment]
#1138

**Comment by ggraziotti** [comment]
noticed that, if on account I show historical data no problem with balance. If I show the others intervals, actual and reconciled balance are different. This information is useful to solve ?
