### ISSUE TITLE
Run the integrity check before opening the database

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1138]
Due to possible database corruption and subsequent problems, it might be useful to run the database integrity check before opening the database.
This would help to identify any possible issues early.

**Comment by ggraziotti** [comment]
I noticed that, if on account I show historical data no problem with balance. If I show the others intervals, actual and reconciled balance are different. This information is useful to solve ?

**Comment by MisterY** [comment]
@ggraziotti, did you run integrity check on the database? See Database Settings page.
There are no issues with the code. The cause for discrepancy is (in most cases) a corrupted database.
See #606

**Comment by ggraziotti** [comment]
I see #606, but is hard to implement.

That's a software for Windows, to check DB an solve problem automatically ?

Inuse: Android version: 2017.11.07.967, with Android 8-oreo.

I have on one account, difference balance as show on transaction and on the top of the screen, how to solve. On PC 1.4.0 alpha version, that's ok. (Sync with gdrive).

Also if I try "Verify integrity of DB", respond: "error:file database corrupted". If I try test on schema respond with 2 errors

How to solve ? 

May be can I use create new database, but I'm unable to use it.

TKS

Giorgio

**Comment by ggraziotti** [comment]
I will try this: 
"Klausen, the amounts differed - solved.
Using DbBrowser, the data was exported from transactions table to CSV, table was deleted, and then imported from CSV. This solved the problem, confirming that there was a physical damage to the database file."

Posted by MisterY on #606 issue

**Comment by ggraziotti** [comment]
On the DB, desktop software version 1.4.0, I do not have this table, but transaction are in "ALL DATA"or "CHECKINGACCOUNT_V1". I do not have "transactions" table. With table I have to export and import ?

**Comment by MisterY** [comment]
I think "CHECKINGACCOUNT_V1" is the table that contains all transactions. You can have a look around the tables. I'm sure you'll figure out which is the one with transactions.
