### ISSUE TITLE
inconsistency between mmex desktop and android in status field of checkingaccount_v1 table

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/android-money-manager-ex#1141]
In the last 1.4-alpha version of MMEX, unreconciled transaction have status 'N', while previous version had an empty field. This makes MMEX android do not show new transaction added from the desktop application. I believe one of the changes is to change  "<item></item>" to " <item>N</item>" on line 55 of file android-money-manager-ex/app/src/main/res/values/arrays.xml. 
The program does not compile on my Mac so I don't know if this change is suffiencient to make both db fully compatible again

**Comment by poznachowski** [comment]
This happened to me as well. I want to try suggested fix, but I failed to properly build the project (dev branch). I'm Java dev, but have nothing in common with Android dev. If someone would help me setting up the project I'd like to help on this one.

**Comment by MisterY** [comment]
@poznachowski, what kind of issues do you have building the project?

**Comment by VerebLaszlo** [comment]
I also have this problem with Android Beta and Linux 1.4.0~alpha versions of MMEX.
When I tried to set all transactions to Reconciled, the transfers between accounts aren't visible on Android anymore and I can't get them back anymore.

**Comment by MisterY** [comment]
@VerebLaszlo, could you inspect the records in the database and compare the reconciled transactions done in the desktop app and the Android app?

**Comment by VerebLaszlo** [comment]
It seems it only happens if I set ALL transactions to any other status except None. The problem was, that the Status became NR, RN or RR depending where I set to reconciled.  When I changed the value to R (or deleted the N) it was correctly visible on the Android app.

**Comment by Spoker** [comment]
Is this different status setting for both accounts (eg NR, RN, RR, ...) a feature or a bug?
I've had issues with it as well.

**Comment by MisterY** [comment]
There are no two-letter statuses in Android version. Obviously, the logic for this has changed in the desktop version.

**Comment by VerebLaszlo** [comment]
I think it only changed in the Linux version, with the Windows version I can set the status correctly to one letter.

**Comment by Spoker** [comment]
I have had the issue as wel but I don't have Linux, so I guess it will be on Windows as well.

**Comment by lexa2** [comment]
Affects me to. I've done my own investigations prior to looking for an existing issue on GitHub and can confirm that Android version does not show transactions with status set to "N" at all. Editing database manually changing "N" to "" (empty string) makes transactions appear with "None" status - as expected.

Suggested fix would be to treat both "N" and "" as a "None" status in Android version thus allowing for compatibility with both 1.3.x and 1.4.x branches of desktop MMEx. Unfortunately I'm not a Java expert (my field of expertise is *nix DevOps and assembler/C/C++/Pascal/Python/Ruby/Perl development) so I can't implement a proper fix myself. OTOH I bet the fix should be a trivial one so I hope someone with Java and Android experience would step up and fix this thing soon-ish :-).

**Comment by VerebLaszlo** [comment]
I think that only will solve the problem for simple transactions, not for transfers between accounts, e.g. status can be "NR"!

**Comment by lexa2** [comment]
@VerebLaszlo Of course it will only fix what it was designed to fix, check PR comments for more info.

**Comment by wolfsolver** [comment]
Solved in latest release 202401...
