### ISSUE TITLE
Custom Fields on android version

### ISSUE THREAD

**Issue by trecords** [moneymanagerex/android-money-manager-ex#1147]
Hi,

I want to know is there are custom fields option on Android version of MMEX. If not are you going to implement it on future?

Thanks,
Totu.

**Comment by MisterY** [comment]
There are currently no custom fields implemented in the mobile version.

**Comment by luisdev** [comment]
@trecords, can you share more info. What kind of custom fields were you requesting here?

**Comment by wolfsolver** [comment]
Custom field is enhancement on desktop versione
https://forum.moneymanagerex.org/viewtopic.php?t=9480#p20309
