### ISSUE TITLE
Problem whith security code

### ISSUE THREAD

**Issue by ThomasDeligiannis** [moneymanagerex/android-money-manager-ex#1149]
I have problem whith anrdoid app.......i dont remember the security code????

**Comment by ThomasDeligiannis** [comment]
....what can i do??????

**Comment by ThomasDeligiannis** [comment]
????????

**Comment by MisterY** [comment]
Please have a look at the support forum or search the closed items here. This issue is related to Android 7 and has been resolved earlier.
Duplicate: #1093
