### ISSUE TITLE
Can't open forms due to updated libraries

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1153]
After upgrading Android Studio (+Gradle, +Support Library, etc.) the app crashes at certain locations:
- ~~Payees can't be edited~~
- ~~Accounts can't be edited~~
- ~~security prices can't be downloaded~~
- ~~About form can't open~~
- ~~editing Asset Allocation classes~~
- ~~account quick info~~

**Reason**
There is an FontIcon library exception when opening certain forms. Some values may have been deprecated. 
Underlying cause is "Can't convert value at index 5 to dimension". Something has changed in the Android base libraries or the support libraries.
Some report that issue appears with Gradle plugin 3, [link](https://stackoverflow.com/questions/46947665/error-inflating-class-info-hoang8f-widget-fbutton).

**Solutions:**
- Migrate to Iconics for displaying font icons. Replace custom icons with
  - Google Material icons, ([link](https://material.io/icons/))
  - Font Awesome icons, ([link](http://fontawesome.io/icons/))
- use Tab Layout [link](https://stackoverflow.com/questions/26540078/use-tab-with-new-toolbar-appcompat-v7-21). An alternative would be to use bottom navigation [component](https://github.com/aurelhubert/ahbottomnavigation) instead of tab strip.

**Comment by MisterY** [comment]
Several identified places have been rewritten. Please report any other places in the app where the app crashes.

**Comment by robvinall** [comment]
The "about" option also stops the app. This brings up the error message but the app stays active.

**Comment by MisterY** [comment]
Thanks, @robvinall. [Link](https://github.com/astuetz/PagerSlidingTabStrip/issues/315) to the cause of this one.

**Comment by MisterY** [comment]
@robvinall, thanks! That's another issue discovered in the upgrades.
Resolved in 963 by replacing a custom PagerSlidingTabStrip with TabLayout from the design library.

**Comment by MisterY** [comment]
Beta 964 resolves all the crashes related to deprecation of drawing the resources.
