### ISSUE TITLE
Error on syncronize database with Google Drive

### ISSUE THREAD

**Issue by itaroiu** [moneymanagerex/android-money-manager-ex#1158]
Hi,

Since last update to version 2017.11.05.966-beta, it gives error when it tries to synchronize database with Google Cloud.

The error says: Local file is different from the remote! Error!

**Comment by MisterY** [comment]
Hi! Have you confirmed the file name is the same in the synchronization settings?
I have not noticed any differences with the Dropbox sync.

**Comment by FerdinandoLM** [comment]
Dropbox sync works for me, but pushing the FAB button to add an entry crashes the app.

**Comment by itaroiu** [comment]
@Mistery Hi! Yes the remote file and local file have the same names. I even manually copied the remote file to local folder and it gives me the same error. I'm not using anymore Dropbox because it gaves conflicts on syncronization, but with Google Drive it worked like a charm until this new update. All the best!

**Comment by MisterY** [comment]
Just a thought - what happens if you force upload or download? Can you perform synchronization normally after that? 
There was no changes in the code apart from upgrading the dependent libraries, like CloudRail, which talks to the cloud providers.

**Comment by ggraziotti** [comment]
On download force same error. On upload just "error"

**Comment by ggraziotti** [comment]
May be an error on new code for "upgrading the dependent libraries, like CloudRail, which talks to the cloud providers" ?

**Comment by ggraziotti** [comment]
Should be a problem with Android OREO ?

**Comment by ggraziotti** [comment]
I solved with 957 version

**Comment by MisterY** [comment]
I don't know if it helps but I'm not experiencing any issues with Dropbox. Can't remember the last time it had any issues at all, in fact. 
If you find what the problem is, please submit a pull request. Thanks.

**Comment by itaroiu** [comment]
After last update everything works like expected. Good work! Thanks!

**Comment by MisterY** [comment]
Thanks for the feedback!
