### ISSUE TITLE
App getting crashed on selecting Enter Next Occurrence 

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1159]
With recent upgrade, app getting crashed when I select enter next Occurrence from repeat transaction. Most of the time, I use this feature. Plz fix it on priority.

**Comment by velmuruganc** [comment]
App getting crashed even if I try to edit repeat transaction

**Comment by velmuruganc** [comment]
Same issue with new transaction as well

**Comment by MisterY** [comment]
Thanks for the report. Could you please report the exact version number?

**Comment by MisterY** [comment]
The earliest I might have an hour or two to look into this would be next weekend, if I'm lucky.
Hope someone else can help out earlier.
Beta testing did not result in any errors reported so I'd recommend that you join the beta testing by using the Beta version and report any issues before they reach production releases. Thanks!

**Comment by mrfleetwood** [comment]
I've this problem too since I updated to version 2017.11.06.966 today. I'm signed on beta testing releases and did not have this problem yesterday.

**Comment by MisterY** [comment]
@mrfleetwood, thanks for the info. Can you confirm if the issue is only with the release version or with both - beta and release?

**Comment by mrfleetwood** [comment]
2017.11.06.966 version only. Didn't have this problem yesterday with the beta version, updated app today and faced it immediately.

**Comment by MisterY** [comment]
That's helpful, thanks! I've located the cause and will publish the updated version soon.
