### ISSUE TITLE
App crashes when pushing FAB button

### ISSUE THREAD

**Issue by FerdinandoLM** [moneymanagerex/android-money-manager-ex#1160]
After the last update the FAB button leds to a force close of the application.

This happens also while creating a new database or when trying to edit an existing database. 

Tried this on a Samsung Galaxy S8 with touchwiz, on a Note 3 with Lineage rom and on an emulated android run by Nox, all three with the same behavior.

**Comment by MisterY** [comment]
This is fixed in build 967 and is related to #1159.
