### ISSUE TITLE
Error: Débit is not a constant in com.money.manager.ex.core.TranscationTypes

### ISSUE THREAD

**Issue by drspoke** [moneymanagerex/android-money-manager-ex#1161]
Hello,
When I open an account on my Android ( last version....) i have this message non stop:
"Error: Débit is not a constant in com.money.manager.ex.core.TranscationTypes"
I don't have this message for all others accounts....
Could someone help me ?

Thanks

**Comment by MisterY** [comment]
Hi, 
Thanks for the initial report. Could you provide some more details, like the version number, language used (locale), when and where does the error appear and/or any other possibly relevant details?
