### ISSUE TITLE
Local filename different from remote

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1162]
When I try to sync my DB from gdrive to Android APP, the software respond as object. On desktop OK. How to solve ? I have beta app on Android and last alpha release on desktop.

**Comment by MisterY** [comment]
You can start from the [home page](http://android.moneymanagerex.org/) and check the Documentation links.

**Comment by MisterY** [comment]
Please note that GitHub is for issues with the application code. All support issues are handled in the support forums (by volunteers like you and me).

**Comment by ggraziotti** [comment]
Tks
