### ISSUE TITLE
Getting error "No enum constant com.manager.ex.investment.ExchangeRateProviders.Yahoo.Yql"

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1164]
Getting error "No enum constant com.manager.ex.investment.ExchangeRateProviders.Yahoo.Yql". How to change the provider here? Also my share price is not getting downloaded

**Comment by MisterY** [comment]
Yahoo closed their APIs a few days ago.
I have removed the options to select Yahoo as the provider but the old settings probably stay. It was an unfortunate emergency on top of everything else.

**Comment by velmuruganc** [comment]
I have changed the provider and I could able to get the rates
