### ISSUE TITLE
Configure Status visibility

### ISSUE THREAD

**Issue by denis-peshkov** [moneymanagerex/android-money-manager-ex#1165]
As an user of this app, I'd like to configure use or not **satus** of operation. So in case when I don't like to use it, I'd like it will be hidden everywhere.

P.S.
Guys, I'm not an android developer, of course I can try to implement it, but if somebody can help - welcome! 
I really need help.

**Comment by MisterY** [comment]
Can you describe what you mean in more detail?

**Comment by denis-peshkov** [comment]
I don't want use status, that is mean that I'd like have only one status (recorded). So it will be nice after switch off use status in configuration have hide all what is related to status on all forms:
- when I see transactions by card (reconciled balance) 
- when add/edit transaction (status)
- i.e.

**Comment by Spoker** [comment]
In my opinion, as the status of a transaction is very important (eg. void vs reconciled) and this influences the calculations that are made, hiding the status does not seem to add value.

Maybe you want to take a look at the setting 'Standard status' in the 'General' menu. Here you can set up the default status for every new transaction (eg 'reconciled'). Then you do not have to worry about the status anymore as it will be set by default.

**Comment by MisterY** [comment]
@denis-peshkov, thank you for the suggestion. This, as you say is a "nice-to-have" feature, which would also require enormous amount of work with the benefit to the application being, in my view, next to 0.
If you do not want to use Status then just don't use it. 
However, if anyone is willing to spend time and implement this so that it does not break existing functionality, I will gladly accept a pull request.

**Comment by MisterY** [comment]
This is an important feature on all platforms and an essential part of a personal finance package.
As previously mentioned, if you do not want to use the Status, then simply ignore it.
You are also free to submit a pull request with the desired functionality as long as it is backwards-compatible. There are plenty of users who do use the status field.
I don't really use it on the mobile device but it is essential in the real book, on the desktop.
