### ISSUE TITLE
allow importing GnuCash categories

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1166]
Add an option to import categories from GnuCash account export (.xml) file.

Note: this is difficult as we only support 2-level hierarchy (category + subcategory). One way to solve would be to break the longer categories at the first level only.

**Comment by wolfsolver** [comment]
I think that this is a companion app of desktop version. so import gnucash into pc version and than sync dB with AMMX.

Can this be closed?
