### ISSUE TITLE
Local filename different from the remote

### ISSUE THREAD

**Issue by dzimaj** [moneymanagerex/android-money-manager-ex#1168]
I change to Google drive synchronization,  and now when I use MME on my PC, I have a problem on my android , There is info : Local filename different from the remote
Then I have to change the name of my base file i Then it is ok
What I'm doing wrong ?
Uninstaling and install again , cleared the memory of aplication , but only changing the name helps

**Comment by dzimaj** [comment]
Recently I have used Dropbox,  and There was no such problems

**Comment by cbrokaw** [comment]
I am having the same issue. Running Oreo on Pixel 2.

**Comment by fillipvt** [comment]
I can confirm the same issue on MacOX: can't sync from mobile using Google Drive

**Comment by ggraziotti** [comment]
I have the same problem. Should be a problem with Oreo ? I have it and you ?

**Comment by dummy84** [comment]
I have Android Marshmellow and still have this problem.

I have found the code that is responsible for this action (android-money-manager-ex/app/src/main/java/com/money/manager/ex/sync/SyncService.java)

// check if name is same
        if (!localFile.getName().toLowerCase().equals(remoteFile.getName().toLowerCase())) {
            Timber.w("Local filename different from the remote!");
            sendMessage(SyncServiceMessage.ERROR);
            sendStopEvent();
            return;
        }

But since I have 0 experience in Android development, I couldn't even build an apk with this section commented to see whether it can be skipped.
But the question is: why is .equls returns false? I even tried to rename my db to 1.mmb - still the same result.

**Comment by MisterY** [comment]
This is to prevent overwriting a wrong file. As you correctly noticed, the problem is that the two names are different when they should not be.

**Comment by ggraziotti** [comment]
The versions after 957 have all this problem. Witch 957, work fine. With the follows versions, beta or stabile, the problem persist. Can someone solve It. I have Android 8.1.

**Comment by d03j** [comment]
a heap of people seam to be having the same problem (https://forum.moneymanagerex.org/viewtopic.php?f=20&t=7332&p=16040&hilit=android+windows#p16040).

I'm on Android 6.0.1 with MMEX 2018.01.02.976, I can normally sync ok with another Android 7.0 MMEX 2018.01.02.976. The problem seem to occur when I use MMEX 1.3.3 on a Win 10 machine but only after a while.

**Comment by d03j** [comment]
not sure if this helps: I've been testing it further and the problem only seems to occur when I save the file in windows. It syncs to google drive without a problem but MMEX on android doesn't like it. copying the remote file over MMEX local version using ES File Explorer resolves the conflict. So, as dummy84 and Mister Y, said for some reason android thinks the file names are different.

**Comment by MisterY** [comment]
Can you confirm if the Dropbox sync works correctly with the same file?

**Comment by d03j** [comment]
Just tried Dropbox. It does sync correctly.

**Comment by MisterY** [comment]
I will check if there is a new version of CloudRail library. Not much else can be done on MMEx side.

**Comment by MisterY** [comment]
OK, there is an updated CloudRail library. As per [changelog](https://github.com/CloudRail/cloudrail-si-android-sdk/blob/master/changelog.txt) there are some updates to GDrive. Will release new beta soon. Please report after trying out build 978.

**Comment by d03j** [comment]
I still don't have 978 available on my google play store. I'll test it as soon as my phone downloads it.

**Comment by MisterY** [comment]
I have the same issue on my tablet with Lineage OS but not on the phone with a provider ROM. Not sure what Google changed this time but I might need to post Betas on GitHub as well.

**Comment by MisterY** [comment]
Here we go - https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2018.02.21.979-beta

**Comment by MisterY** [comment]
#1278 is the way forward
