### ISSUE TITLE
Add a support for loan accounts

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1170]
Desktop Version supports for the loan account. 

![image](https://user-images.githubusercontent.com/29807533/33373237-02d81570-d527-11e7-9717-97950a419c56.png)

If we open such a db, we dont see the Loan Account Description. Ref. below snapshot. Please add the same in Android app as well.

![image](https://user-images.githubusercontent.com/29807533/33373351-79fc3708-d527-11e7-9286-9127d8811e25.png)

**Comment by Spoker** [comment]
I have been trying this, but have very little time and experience. You can
check out my fork.

Op 29 nov. 2017 12:35 schreef "Velmurugan Cithaiyan" <
notifications@github.com>:

**Comment by MisterY** [comment]
I guess it goes for everyone else. If someone has time and desire to work on this, please feel free to implement.

**Comment by MisterY** [comment]
I would assume the request would include full functionality. Meaning, 
- accounts can be edited,
- transactions can be edited,
- reports include this account type, etc.
From what I understand, so far we can only display their value on the home screen?

**Comment by Spoker** [comment]
I've been searching where the code is to enable the display of loan and shares accounts in the account selector, but haven't found it.
(I mean, when you click on an account, the account is displayed on top of the screen in a selection list. Where is that code?)
You can see I still have to learn a lot...

**Comment by MisterY** [comment]
Thanks a lot, guys!
