### ISSUE TITLE
Default Category & Sub Category value should be -1 in place of null for new payee

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1171]
Default Category & Sub Category value should be -1 in place of null when we add new payee thru Android App. Desktop app setting these values as -1. 

App getting crashed if I call below line with null Category & Sub Category, but works fine if it is -1, i mean if it is created from Desktop App.

mCommon.setCategoryFromPayee(mCommon.transactionEntity.getPayeeId());

**Comment by velmuruganc** [comment]
I am adding following two lines in the createNew payee method,

payee.setCategoryId(-1);
payee.setSubcategoryId(-1);

**Comment by MisterY** [comment]
Thanks!
