### ISSUE TITLE
STATUS problem between desktop 1.4.0 alpha 2 version and android 659 version

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1177]
I have a problem with some transfer from/to my accounts.
On desktop STATUS of transfers is all OK.
On Android I can't see transactions and acconts balance are inconsistency.
I modified some previous status of transactions with desktop app version.

Seems to be that if I modify transactions on desktop, I have problem with android version.

To solve can I use a previous version of desktop and/or different android version ?

Can some suggest me android and windows versions to use without problem.

Thanks 

Giorgio

**Comment by Spoker** [comment]
I have had a similar issue.
With http://sqlitebrowser.org/ I saw there were transactions with status 'RR' instead of 'R'.
Changing all 'RR' statuses to 'R' fixed this. Don't know where these 'RR' statusses come from.

**Comment by ggraziotti** [comment]
I Will try this and report

**Comment by ggraziotti** [comment]
TKS I solve it.

**Comment by ggraziotti** [comment]
I have another problem ONLY with android app. Inconsistancy balance on one credit card account. 

On upper box I have incorrect balances. On balance showing down single transaction I have correct balance.

like:

BALANCE: -1.439,56
RECONCILIATED BALANCE: -1.439,56

Balance on transaction box: -1.469,13. (THIS IS THE CORRECT BALANCE).

Can u help me ?

**Comment by MisterY** [comment]
Yes. Please search this repository or the support forum. This issue has been mentioned a few dozen times. Thanks.
