### ISSUE TITLE
Automate the building and publishing process

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1182]
See https://github.com/codepath/android_guides/wiki/Automating-Publishing-to-the-Play-Store

A build server should build the sources, run the tests, and produce the apk file, upload to Play Store, publish as a Release on GitHub, and create release notes.

**Comment by vladimir-poleh** [comment]
I think that build + tests and produce APK + upload to Play Store + publish GitHub Release should be two different steps in deployment process.
Build + test can be executed automatically for each push to the GitHub repository, but deploy to the Play Store should be triggered manually.

**Comment by MisterY** [comment]
It's just an idea at this stage. :)
I've activated build on commits but have not managed to make it work properly. Currently I'm quite busy with [GnuCash Portfolio](https://github.com/MisterY/gnucash-portfolio) project.
However, it would be nice to have all the steps involved working. Then it would be possible to manage when and which get activated.

**Comment by vladimir-poleh** [comment]
I can take a look to the deployment. What Continuous Integration system is used now (if used)?

**Comment by MisterY** [comment]
Travis-CI should be active on check-ins and/or pull-requests:
https://travis-ci.org/moneymanagerex/android-money-manager-ex

**Comment by Spoker** [comment]
There seems to be a problem with accepting the license agreement for MMEX Icon Fonts, resulting in the build failing. Don't have experience with this, hopefully anyone knows how to address this.

**Comment by MisterY** [comment]
Yes, that's what it says but I did not have enough time to check what the real problem is. The main app goes through just fine by using the same Android version (27).

**Comment by MisterY** [comment]
Travis fixed. Good start.

**Comment by MisterY** [comment]
There are currently two available options:

1. use Travis CI deploy option to push to Github Releases tag. This would work well with repository-based stores, like F-Droid.
2. switch to GitLab and use their build and deploy pipeline. This is similar to the above, only with repository migration, which is not so convenient.

**Comment by MisterY** [comment]
GitLab seems fairly simple to set up. The advantage is that everything is integrated and the build results can be automatically available for download.

**Comment by MisterY** [comment]
This will be happening automatically with #827
