### ISSUE TITLE
Recurring transaction reminder notification doesn't appear 

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1185]
When I launch the app, notification appears and disappears in a sec and doesn't stay back.

AMMEX Version tested 2017.12.19.972.
Android version 7.1.1

**Comment by velmuruganc** [comment]
@MisterY , could you please have look at this issue. I have tried to fix this, but i could not. This fix will help me on #1188.

**Comment by MisterY** [comment]
I had a couple of reminders in the past few days so I'm not sure why you are experiencing this issue. Nobody else confirmed, either.

**Comment by MisterY** [comment]
Seems you are right. In the latest version, the recurring transactions notification does not show up due to missing notification channel. This could have been a result of recent changes. 
Comparing to some old code would help.

**Comment by MisterY** [comment]
I think I've fixed all notifications as well as background services issues in Android 8.
Any feedback is more than welcome as I can only test in emulator!
Look for beta 975.

**Comment by velmuruganc** [comment]
Still, I have the same issue in my mobile. Notification blinks and disappears immediately.

**Comment by velmuruganc** [comment]
@MisterY , still I have issue with notification in my Sony mobile (Android 7.1.1, API 25). I tried to debug, but I couldn't get anything. Any idea

**Comment by MisterY** [comment]
I had that only once so far. No idea what causes it. 
We remove the notification in the Main, I believe, on app exit and/or start. But that should not be called in other cases.
Can you confirm that in an emulator it works differently?

**Comment by velmuruganc** [comment]
Emulator works fine with API 25, but not in my Sony Mobile.

**Comment by MisterY** [comment]
You might want to try debugging directly on the phone, then? There's no way for any body else to experience that issue unless they have the same phone with the same OS version and the same level of patches. 
There were some strange issues earlier. Always caused by vendors packing or hacking some strange versions of libraries. You can also try flashing LineageOS and compare.

**Comment by velmuruganc** [comment]
If I add .setOngoing(true), then notification stays back for MMEX. Is there any impact using this?

**Comment by MisterY** [comment]
Yes, a significant one: https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setOngoing(boolean)
It stays forever.

Please don't use that to fix issues specific to one phone model and one OS version. Try to fix your phone software, not the app. The app works just fine for thousands of users. See if you can find the exact cause why the notification disappears on that specific phone. I'm sorry that I don't have a more specific hint on how to resolve this.

**Comment by MisterY** [comment]
That's good to hear! Glad you found the culprit. :)
I have LineageOS but no issues whatsoever.
