### ISSUE TITLE
balance different between Pc and Android

### ISSUE THREAD

**Issue by Ombry** [moneymanagerex/android-money-manager-ex#1189]
In pc the balance of all accounts is ok. In Android there are big differences...I think that in Android  a major of the transfers are omitted. 
If I create a new transfer operation in pc it's syncronise with android.
But my  pc database was created by import from different QIF files, so I think that old transfers are omitted from android.

Sorry for my bad English.

**Comment by MisterY** [comment]
Please provide a clear test case that demonstrates the issue. 

1. Try creating a new database and then compare the balances.
2. Check your date range selection in the transaction view.
3. See #606 

The issue will be reopened if you can demonstrate a real problem.
