### ISSUE TITLE
BUG: Unable to Select category in "Where the Money goes"

### ISSUE THREAD

**Issue by zindlsn** [moneymanagerex/android-money-manager-ex#1193]
When selected Error  is: Attepmt to invoke virtual method '... intValue() on a null object reference

**Comment by roskoff** [comment]
Wich version do you have installed? Would you mind to share the categories listed in the report?

**Comment by zindlsn** [comment]
Version: 2018.01.02.076
You mean the names of the categories? It doesnt work for any of them

**Comment by vladimir-poleh** [comment]
Related to #1213. Seems to be fixed.
