### ISSUE TITLE
Alpha numeric account number are not supported in MMEX Android

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1194]
Alpha numeric account number are not supported in MMEX Android. Desktop version allows us to enter alpha numeric values as shown in below,

![image](https://user-images.githubusercontent.com/29807533/34666800-13ca9464-f48c-11e7-8f1f-030f19a31f6a.png)

**Comment by velmuruganc** [comment]
@MisterY , could you please tell me how to clone/merge the latest dev branch to my existing fork. This is to get the changes done by others to my fork.

**Comment by MisterY** [comment]
Hi,
You should add this repository as an "upstream" remote and Fetch or Pull the changes from it.
There is a nice guide on GitHub about the process.

**Comment by velmuruganc** [comment]
this is fixed in the latest beta
