### ISSUE TITLE
ERROR OPENING READABLE DATABASE' .  

### ISSUE THREAD

**Issue by Mercerhelen** [moneymanagerex/android-money-manager-ex#1197]
I have a Acer Tablet running android version 5.1 and a Samsung smartphone using android version 7.

Unfortunately the Acer tablet cannot see the data.mmb file which is in the Dropbox/apps/moneymanagerex Mobile folder.  When I try and open this file in Dropbox using Moneymanager ex , an error is displayed stating 'ERROR OPENING READABLE DATABASE' .  

I have no problems reading the data.mmb file from my Smartphone and until yesterday I was using a Samsung tablet running on android version 4.4 which was also able to read the file.  Sadly this no longer works hence I now have this Acer tablet version 5..1

I also have a Acer Chromebook but unfortunately this does not support Money Manager Ex.    

Can you advise what I need to do , in order for the  Acer tablet to read the file.  I am not a technical person .

Thank you

**Comment by papick13** [comment]
Bonjour
J'ai  réinstallé  MMex (version de google store 2.15.8) sur ma tablette (android 4.4.2). Depuis, le message "error opening readable database" clignote et la base ne s'ouvre pas. S'il  vous plaît , pouvez vous m'aider

**Comment by wolfsolver** [comment]
Need to be closed since new 2023 version is aligned with desktop version 1.7.0
