### ISSUE TITLE
Dropbox/Apps/Money Manager Ex Mobile is empty (not...)

### ISSUE THREAD

**Issue by guill69f** [moneymanagerex/android-money-manager-ex#1198]
Hi, hope I am posting at the right place...
I have MMex installed on different machines and devices (Mac, Win10 PC, Linux Mint PC, Samsung S8 etc.) and i tried to install it now on a Samsung S2 pad. While it's working smoothly everywhere, I don't manage to get it working on the S2, due to sync issues with Dropbox. I keep on getting the message: "the folder Dropbox/Apps/Money Manager Ex Mobile is empty".

I know it isn't because all other devices have it as source. I read in another thread that another user had better luck installing a MMex data base on a Money Manager Ex Android folder: it doesn't work either for me as I keep on getting the same error message.

Alternatively I tried to access the database through some other apps, like Google Drive or Solid Explorer, or even the Dropbox app but it doesn't help (MMex says, when trying Dropbox, that "the path to the database doesn't exist" -own translation).

I don't get it, as it working perfectly on my other Samsung device. Any suggestions?

Thanks!

**Comment by MisterY** [comment]
Deprecated since #1278
