### ISSUE TITLE
Pin Keypad Size

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1202]
Hi,

Not sure if biometric (fingerprint) support will be possible in the near future but either way, is it possible to re-design the PIN key entry pad design. The current design have small flat numeric buttons that are not suitable for larger hands and this can slow the log in process as it is very easy to mis-enter the PIN. With larger / taller buttons, this will be a little easier. Hopefully this will be possible without losing landscape screen support.

Thanks for your help.

**Comment by andrepg** [comment]
@MisterY I've already forked the repo. I'll try to make this screen more confortable next weeks :)

**Comment by MisterY** [comment]
Great!
