### ISSUE TITLE
Couple of Bugs

### ISSUE THREAD

**Issue by AC-T** [moneymanagerex/android-money-manager-ex#1203]
I've noticed a couple of issues with the Android App:

Phone:  Nexus 5X, Oreo 8.1.0
Android App:  2018.02.10.978-beta

Sorry, I have no experience in coding, so can't help with any suggestions for a fix.

Issue:  Reports > Payee results in app crashing.

Issue:  From  Category Report or "Where the Money Goes" report, tapping on any category in the report gives the following:
Error: Attempt to invoke virtual method 'int-java.lang.integer.intValue()' on a null object reference

**Edit:  Just realized the second issue is already reported in #1193.  Sorry about that.**

Thanks,

Art

**Comment by MisterY** [comment]
Thanks for reporting.
