### ISSUE TITLE
(OneDrive) Incorrect Passcode on synced database

### ISSUE THREAD

**Issue by reinhart1010** [moneymanagerex/android-money-manager-ex#1205]
In order to reproduce this issue, you need to have at lease 2 Android devices running the same app with OneDrive synchronization turned on.

1. Set up a passcode (5 digit) on a synced MMEX database on an Android device (Device A).
2. Upload the database to OneDrive.
3. On another Android device (Device B), download the uploaded database from OneDrive

Entering the correct passcode for the same database in Device B will throw an "Incorrect Passcode" error, while entering in Device A will unlock the database as normal.

**Additional Device Info**

+ **Device A**: LG K10 (2016) LTE, Android 6.0 (Marshmallow)
+ **Device B**: Samsung Galaxy J7 Pro (2017), Android 7.0 (Nougat)

**Comment by MisterY** [comment]
Have you tried the [suggestion](https://github.com/moneymanagerex/android-money-manager-ex/issues/981#issuecomment-247590735) in #981?

**Comment by reinhart1010** [comment]
Sorry for late reply.
The main idea was to sync files between an Android 7.0 and an Android 6.0 device.
If I enter a new passcode in Device A and sync it over OneDrive, then open the same database in Device C (Samsung Galaxy Note 4, Android 6.0), I got this error:
```
Error: last block incomplete in decryption
```
The suggestion in #981 only works if the device is being upgraded to Android 7.0 from previous versions, while I originally wanted to have it work with both Nougat and pre-Nougat devices.

In addition to that, does the new passcode for Android 7.0 work in desktop as well?

**Comment by MisterY** [comment]
Deprecated
