### ISSUE TITLE
Insert new transaction by transaction the applicant with split categories

### ISSUE THREAD

**Issue by AlessandroLazzari** [moneymanagerex/android-money-manager-ex#122]
In the list of recurring transactions the user presses "Enter" Next Occurence" on a recurring transaction with split categories, in the new transaction are not reported by the split categories, not even the flag split.

**Comment by MisterY** [comment]
Correct. I noticed this today. Need to see how is the preferred category stored in the desktop version when there are split categories.

**Comment by MisterY** [comment]
Yep, this is the same as #113
