### ISSUE TITLE
logo/icon proposal 

### ISSUE THREAD

**Issue by Tobaloidee** [moneymanagerex/android-money-manager-ex#1220]
Good day @moneymanagerex

I am a designer and I want to ask your permission to design a logo/icon for the app.
Thank you and Best Regards!

Tobaloidee

Edit: related issue in the Art repository ([here](https://github.com/moneymanagerex/Art/issues/1))

**Comment by MisterY** [comment]
Hi, @Tobaloidee, and thanks for the offer. You may also want to contact the desktop and include them into the discussion if the icon affects the overall MoneyManagerEx brand.
As for the Android app icon, you could attach a draft proposal and explain some pros and cons of the new icon vs the existin one(s). 
Cheers

**Comment by Tobaloidee** [comment]
Hi Sir, thanks for the response.I will show my draft asap..thanks again!
Best regards!

**Comment by Tobaloidee** [comment]
I will start designing for the Android App Sir..Thanks!

**Comment by Tobaloidee** [comment]
Hello Sir @MisterY , here are the links to my design..please let me know your opinion or if you have a suggestion.Thanks!

ICON
http://res.cloudinary.com/tobaloidee/image/upload/v1521730001/MONEYMANAGEREX/MMEX-01.png

LOGO IDEA
http://res.cloudinary.com/tobaloidee/image/upload/v1521729838/MONEYMANAGEREX/logo_idea.png

BENEFITS-IMPROVEMENTS
http://res.cloudinary.com/tobaloidee/image/upload/v1521729839/MONEYMANAGEREX/benefits_improvements.png

LOGOTYPES
http://res.cloudinary.com/tobaloidee/image/upload/v1521729834/MONEYMANAGEREX/logotypes.png

Im hoping for your positive response. Best regards! Thanks!

Tobaloidee

**Comment by MisterY** [comment]
Thank you!
https://github.com/moneymanagerex/moneymanagerex/issues/1491

**Comment by MisterY** [comment]
I keep updating my comment above so this is just a notification. Thanks!

**Comment by MisterY** [comment]
Also, if you have some other ideas willing to share, please feel free to suggest in-app graphics. Normally, I add SVGs to a custom font and use that in the app.

**Comment by Tobaloidee** [comment]
Hi Sir @MisterY  I'm glad that you liked my design. I will make those adjustments and attached the links in the Art repository of MMEX.. Thanks so much!

**Comment by Tobaloidee** [comment]
Just finished the editing Sir.. I made an issue in the Art repo and put the links there. Thanks!

**Comment by slodki** [comment]
Please continue discussion at moneymanagerex/Art#1

**Comment by MisterY** [comment]
@slodki, this is a feature request that has a significant visual effect for the application and the discussion about that should happen here. The change in the app will also reference this request. 
The comments on aspects of the design can be done in the Art repository.

**Comment by MisterY** [comment]
<img src="http://res.cloudinary.com/tobaloidee/image/upload/v1521861605/mmex_coin-04_qzl0uh.png" width="200px" />

**Comment by velmuruganc** [comment]
@MisterY , looks good, but could you please replace the Star with $ and see which one looks good

**Comment by Tobaloidee** [comment]
here sir..

![dollar sides-03](https://user-images.githubusercontent.com/36028424/37900818-eaacc12e-3121-11e8-9223-f4d442478dad.png)

**Comment by velmuruganc** [comment]
$ icon looks fine for me

**Comment by Tobaloidee** [comment]
Thanks Sir..

**Comment by MisterY** [comment]
$ refers to a very specific set of currencies that are not even the majority of our users so I would stick with the stars.
I would put X into perspective, as if it is horizontal on the ground under the M bird. And make it a bit smaller so that M's get more space.
Other than that, let's see if other contributors chip in some comments.

**Comment by Tobaloidee** [comment]
![perspective x-01](https://user-images.githubusercontent.com/36028424/37901536-13698f96-3124-11e8-9fc8-6a170417a172.png)

**Comment by MisterY** [comment]
Summarizing here the latest versions...

<img src="https://user-images.githubusercontent.com/36028424/38087533-0d70ee18-338b-11e8-96b0-b0f9d4f29151.png" width="200px" />
<img src="https://user-images.githubusercontent.com/36028424/38087538-11999a8a-338b-11e8-9760-b466b2028be6.png" width="200px" />

**Comment by vladimir-poleh** [comment]
As for me new icon can't say anything about the purpose of the application. Also it contains small elements that will be lost on the small screens. And this icon does not fit [Material Icons guideline](https://material.io/guidelines/style/icons.html).

**Comment by Tobaloidee** [comment]
Hi Sir @MisterY  , I am glad that you are using it in the next beta. I have uploaded all the needed high resolution files and formats here in my drive's link 

https://drive.google.com/drive/u/0/folders/1U5O9YuID7CGGrw6FkY1G5ts4z3h1yd81

I have included the B&W versions onf the designs and their logotypes.Here's the summary

![presentation](https://user-images.githubusercontent.com/36028424/38849656-c0e46f48-423f-11e8-9d5f-14cae5d9412d.png)

All of these I am gladly giving to you under <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

Thank you for letting me work with the project and best regards!
-Tobaloidee

**Comment by Tobaloidee** [comment]
Hi Sir @MisterY , how was the project doing? good day Sir.

**Comment by MisterY** [comment]
Hi, @Tobaloidee, I was offline this last week and still need to set up a dev environment. No rush. It's a volunteer hobby project.
This is the next on my to-do list for AMMEX but the time is in a short supply. There are also some database changes that I will need to implement due to changes in the desktop version so I might do these together after we coordinate. Thanks again for your efforts!

**Comment by Tobaloidee** [comment]
It's okay Sir, goodluck and best regards to you!
