### ISSUE TITLE
Summary.

### ISSUE THREAD

**Issue by wdoviedoc** [moneymanagerex/android-money-manager-ex#1221]
Summary of all account does not work.
Samsung SM-A310M
Android 7.0
Compilation # NRD90M.A310MUBU2CQG2
Thank. 
Walter.

**Comment by MisterEco** [comment]
Hi, this issue is available for me, too. Mi Max 2. The widget works ok before, on this phone.

Thanks

**Comment by luisdev** [comment]
Shouldn't github-actions close this as: **reason:"not planned"** instead of: **reason:completed**?
