### ISSUE TITLE
Search Parameters do not display filters in dropdowns

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1223]
Scenario
- select a filter using a dropdown (i.e. account, status, currency)
- see the results
- go back

The criteria are not shown. They are kept, however. This is visible if a search is triggered again, without making any changes on the search parameters form.

The current workaround is to manually reset the search form and redo the search.

**Comment by wolfsolver** [comment]
Resolved in 2024.01.05
