### ISSUE TITLE
Dataset from getObjectFromUri not getting the properties of dataset

### ISSUE THREAD

**Issue by leslieharland** [moneymanagerex/android-money-manager-ex#1224]
When I set the constructor to accept DataType.TABLE explicitly, provider always get DataType.QUERY. 
So is the dataset still in play, since it takes the QUERY upon creation (as it is the first value of DataType enum).

**Comment by MisterY** [comment]
Could you please provide some context here?

**Comment by leslieharland** [comment]
Is there a reason for complicating things? The repo could still exist without Dataset. 
I'm trying to understand more. Thankssss

**Comment by MisterY** [comment]
You're right. Closing.
