### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by dibon-github** [moneymanagerex/android-money-manager-ex#1226]
Good day Im a graphics designer and I would like to ask your permission to design a material style/ flat logo for your project as it is the new trend nowadays. Hope to get a positive feedback from you for this matter. Best regards!

**Comment by MisterY** [comment]
Hi, @dibon-github, thanks for the proposal. You might wanna have a look at #1220 and also initiate an issue in related repositories as the logo relates to the whole MoneyManagerEx project, not only to the Android app.
I would be happy to see your ideas and consider including them in the app.
Cheers

**Comment by dibon-github** [comment]
Heres is my draft design sir, feel free to comment any suggestion you want changed. 
![logo-mmx](https://user-images.githubusercontent.com/31919065/38415608-952e03b0-39c4-11e8-8867-93adc3d666fe.png)

**Comment by dibon-github** [comment]
The dollar bill literally indicates the money and the arrow indicates the management of money.

**Comment by luisdev** [comment]
I think I prefer the existing logo.
