### ISSUE TITLE
Transcations not showing up when added through the latest  Ubuntu app

### ISSUE THREAD

**Issue by TobiasDev** [moneymanagerex/android-money-manager-ex#1228]
Hello,
I've just started testing MME as it got all functionality I want to have in this type of app. However, I have a problem. I added a lot of transactions in the desktop application but none of them show up in the mobile app. When I go into the budget mode I see in the category what I have spent, but I can't actually see any of my transactions.

**Comment by p2635** [comment]
For me, it's the other way around. I tested android and then copied the mmb to pc and my transactions do not show. (Although I haven't tried it desktop-> mobile). This sucks so I think I will stick with pc for now.
