### ISSUE TITLE
Channel is unrecoverably broken and will be disposed!

### ISSUE THREAD

**Issue by AlessandroLazzari** [moneymanagerex/android-money-manager-ex#123]
In JellyBean the application random crash with similar error:

452-506/system_process E/InputDispatcher﹕ channel '528adc38 com.money.manager.ex/com.money.manager.ex.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

We are able to investigate and some of us to simulate and understand why it happens?

**Comment by MisterY** [comment]
When do you get this?
I see some other ones, like can't find a file, or no permissions to chown. Will report if they keep happening.

**Comment by AlessandroLazzari** [comment]
is a crash really weird and it happens random. On the emulator Nexus 4 with Android 4.3 never happens with the emulator Nexus 7 with Android 4.3 it happens random, changing accounts, opening a transaction, or opening the drawer....in a manner precisely abnormal.

**Comment by AlessandroLazzari** [comment]
Some improvements:
https://github.com/moneymanagerex/android-money-manager-ex/commit/d666850c22b55ba41b79edd771657c11f0fbe330
and
https://github.com/moneymanagerex/android-money-manager-ex/commit/f34f0d7441e9f792cc1317605b12b49759b208a9

**Comment by MisterY** [comment]
Did you manage to get this again after the code optimizations?

**Comment by AlessandroLazzari** [comment]
I tried again after optimizations. The application seems to be much more stable. Even if it is still, much less to the previous versions, crash, always, with the usual error.

**Comment by MisterY** [comment]
If it is anything close to this: http://stackoverflow.com/questions/12459719/why-i-am-getting-error-channel-is-unrecoverably-broken-and-will-be-disposed
all I can say is - madness! Every developer has identified a different cause for this error! :))

**Comment by MisterY** [comment]
This article could be useful: http://android-developers.blogspot.ru/2009/01/avoiding-memory-leaks.html

**Comment by AlessandroLazzari** [comment]
This is one of the worst mistakes a developer can find. Our
user/collaborator has solved the problem by doing the "wipe dalvik cache",
this error is sheer madness...

**Comment by AlessandroLazzari** [comment]
>
> ​
> This article could be useful:
> http://android-developers.blogspot.ru/2009/01/avoiding-memory-leaks.html


​Already done!​​

2015-04-22 10:33 GMT+02:00 Alessandro Lazzari <lazzari.ale@gmail.com>:

> This is one of the worst mistakes a developer can find. Our
> user/collaborator has solved the problem by doing the "wipe dalvik cache",
> this error is sheer madness...
>

**Comment by MisterY** [comment]
I have never experienced this nor seen it reported. Let's reopen if it happens again.

**Comment by rsanas1** [comment]
I got a similar error on Nexus One Api 19

07-26 14:55:56.940 1756-1903/system_process E/InputDispatcher: channel 'ad3e20a0 com.delta.dev/com.delta.activity.SplashActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-26 14:55:57.010 2053-2053/com.android.launcher E/EGL_emulation: tid 2053: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)

**Comment by HakorimanaEmmanuel** [comment]
Got the same Issue!
Has anyone solved it ?

**Comment by mykfrost** [comment]
I always get this error. Who solved it ?

**Comment by jnawaz** [comment]
I've manged to reproduce this error consistently by revoking app permissions such as locations. Currently have same issue. Will try memory optimisation.

**Comment by FitApps7** [comment]
2019-08-07 09:23:02.561 2208-2322/system_process E/InputDispatcher: channel 'c34c731 app.package/StartAcitivity1 (server)' ~ Channel is unrecoverably broken and will be disposed!

I get this error on emulator android version 10.

**Comment by HUANG-z** [comment]
why?

**Comment by StanleyJuma-cyber** [comment]
Getting the same error after changing some code on my login page, anyone with a solution. ive tried everything seams like ill have todo tha app again!! wHY
