### ISSUE TITLE
Crashes on screen rotation 

### ISSUE THREAD

**Issue by tykees** [moneymanagerex/android-money-manager-ex#1232]
When i tried to do some setting on the general settings, clicking on  Application Language, Theme, Default Status and Default Payee including Per-Database, if anyone of the listed features are clicked on and the screen orientation is being changed and changed back to the initial orientation it crashes the app....Pls check these behavior....Thank you

**Comment by wolfsolver** [comment]
Not sure regarding the issue 

Anyway app work in both portraits and landscapes mode 

Can be close
