### ISSUE TITLE
DB Downgrade must not be allowed

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/android-money-manager-ex#1234]
https://github.com/moneymanagerex/moneymanagerex/issues/1632

**Comment by MisterY** [comment]
To the best of my knowledge, this should already be the case. See i.e. https://stackoverflow.com/questions/43200408/cant-downgrade-database-from-version-n-to-n-1-on-samsung

If there are evidence to the contrary, please provide them here for evaluation and discussion.

**Comment by gabriele-v** [comment]
But Android MMEX isn't using default because it has an override for OnDowngrade to do nothing:
https://github.com/moneymanagerex/android-money-manager-ex/blob/fcc4ea08cf28c94fd8e8c57a3727f9209d200ba1/app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java#L134

From other users feedback, seems that DB Version it's actually downgraded but without any change on DB. This means that for example if DB was at V10 and app expects V8 then we will have a DB with V8 but with structure of V10.
MMEX Android should throw an exception and don't allow to open DB if DB Version is greater than expected version.

**Comment by gabriele-v** [comment]
I don't know SQLiteOpenHelper but I think that downgrade of version (IE pragma version = 8) it's managed outside of onDowngrade function, so that's the reason why the DB it's still downgraded (just for version, not for schema) also if onDowngrade override isn't doing anything.

**Comment by MisterY** [comment]
So, what would be the suggested solution, then?

**Comment by gabriele-v** [comment]
> MMEX Android should throw an exception and don't allow to open DB if DB Version is greater than expected version.

I don't know how to do it (I've never coded for Android) but I think that you should throw an exception (so downgrade it's stopped) and show message or whatever in onDowngrade override.

In example, actually in MMEX desktop we have this message:
`MMEX database version [x] doesn't work with this MMEX version. Please upgrade MMEX to newer version.`

**Comment by MisterY** [comment]
I'll try to remove the blank override of onDowngrade and revert to the default behaviour. Since upgrades/downgrades on Android are handled by the system at the initialization stage, the only viable option seems to be throwing an exception, which is what happens by default anyway.
