### ISSUE TITLE
Remove non-OS file synchronization

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1238]
Extract cloud sync into a plugin?
Move all synchronization code into a separate plugin that can be installed separately. Synchronization is not a key application functionality.
This way, cloud sync would work if a plugin is installed.
This would allow adding plugins for other services.

Removal of non-open libraries would also satisfy the inclusion criteria for F-Droid.

[Related](https://github.com/moneymanagerex/android-money-manager-ex/issues/1250) issue.

Resources:

- [Android Library](https://developer.android.com/studio/projects/android-library)
- [SO question](https://stackoverflow.com/questions/13644539/how-can-i-create-android-application-plugins-extensions-that-can-be-installed-as)

**Comment by andrepg** [comment]
Just a comment: extract cloud to sync could be a great improvement, but I disagree that cloud sync is not a key functionality. 

In fact, I personally move to MMEX because of the facility in sync databases across devices (using OneDrive or Google Drive, or others). But one killing feature that I found in MMEX was exactly seamless working sync. 

MMEX is great, after and above all!

**Comment by MisterY** [comment]
Thanks for the comment, Andre. What I mean is that this is a finance app, not a file synchronizer. What we made in addition is that the database file can reside outside the app folder, and it is not being locked by the app. This allows for any file sync solution to be applied. 
Since this is an Open Source app, I would love to see it available on F-Droid. However, the use of closed-source libraries makes it impossible at the moment. Pulling the sync code into a separate plugin would make that possible and, as mentioned earlier, would also allow others to write plugins that support any service one wants.

**Comment by MisterY** [comment]
Ref: https://gitlab.com/fdroid/rfp/issues/17
Try to create a flavor that does not include the event handlers for synchronization.

**Comment by MisterY** [comment]
https://github.com/moneymanagerex/android-money-manager-ex/issues/1250

**Comment by MisterY** [comment]
#1278 resolves this.

**Comment by pczarnopys** [comment]
Hi guys!
@MisterY I can't agree that synch with cloud is not main feature. For me and may others was reason for chosing MMEX. If you don't bealive me just check comments on Google Play. You've removed sync, but did you ensure that plugins are available? If you want to make MMEX part of F-droid maybe you can fork classic version of app?
