### ISSUE TITLE
Syncing via OneDrive not working

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/android-money-manager-ex#1240]
https://github.com/moneymanagerex/moneymanagerex/issues/1707
> Have an issue where I have mmex set up on both Android and windows, it syncs ok when I make a change on Windows, but anything I do on my Android phone doesn't sync back to my desktop app. Why? What is a fix?

**Comment by EriveltonMS** [comment]
apparently all sync methods are failing, I tested gDrive, Dropbox and Onedrive without success, on Android 8. Until the 10th was normal, which makes me wonder if the problem is not Cloudrail.

**Comment by MisterY** [comment]
I can only confirm that I had no issues at all with Dropbox in about two years.

**Comment by bluehelo** [comment]
Turned off Battery Saver under battery settings and it appears everything is operating normally now. Will need others to try the same to verify

**Comment by MisterY** [comment]
Please try the latest beta, see #1278
