### ISSUE TITLE
Android notification settings are all the same name

### ISSUE THREAD

**Issue by pcolmer** [moneymanagerex/android-money-manager-ex#1244]
![screenshot_20180701-101251](https://user-images.githubusercontent.com/1979931/42133455-4c10d4c2-7d22-11e8-9662-73ef5a33b3ea.png)

As can be seen from this screenshot, all of the different categories of notifications for the app have the same text.

Can we have something more informative, please?

Thanks.

**Comment by wolfsolver** [comment]
Think notification is no more available in latest version.
