### ISSUE TITLE
Possibility to hide different accounts on different devices

### ISSUE THREAD

**Issue by MisterEco** [moneymanagerex/android-money-manager-ex#1246]
Hello,

Please analyse the possibility to add an option to hide some accounts (eg. after synchronisation) some sort of flag that will keep the account/accounts hidden on concrete / specific device.

Thanks,

**Comment by MisterY** [comment]
Could you be a bit more elaborate on what exactly and where should be hidden?
There is already an option to show only favourite accounts. That seems more than enough for what you are currently asking.

**Comment by MisterEco** [comment]
Hi, as I understand hidden account on android app does not keep hidden status on another android device. I mean that if I'll hide an account on an android device and I will sincronise database with another android device in such case the account marked as hidden on 1st device will keep hidden status on the second device?

**Comment by MisterY** [comment]
That's correct. As an Android-specific setting, this information is only stored on the device, not in the database.

**Comment by MisterEco** [comment]
That's why I've wanted something at the level of database. Let me explain the reason: Me and my wife we had different accounts. On desktop version the info needs to be cumulative, but on Android device we will manage own accounts separately.
of cource if that make sense for you.

Thanks,

**Comment by vladimir-poleh** [comment]
Flag for the Favorite Account is stored in the database so if you are using favorites they will be same for all devices. But option to hide favorites is stored on the device, not in the DB. In this case you can't have different sets of the hidden accounts on the different devices.

**Comment by MisterY** [comment]
Ah, OK. My understanding was the opposite but that makes sense. The two users in this case would want to see different sets of accounts on their devices. Hm, in that case this would break the compatibility with the desktop version, according to the clarification from @vladimir-poleh.
