### ISSUE TITLE
Remove built-in database synchronization

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1250]
Most problems with the app come from the synchronization. Since this is a finance app, it should leave the file synchronization to a solution specialized for that purpose. A sync module can either be added as a separate app or a 3rd-party solution can be used (Synchting, FolderSync, etc.).

The fact that the app supports external storage locations (SD card) allows for any 3rd-party solution to work without any issues.

The sychronization component is a closed-source module that prevents the app from being distributed via F-Droid.

**Comment by Whisprin** [comment]
I understand the reasoning behind this given the limited resources and the issues that arise. 

But maybe you can reconsider and take a look at e.g. Keepass2Android. 
It's open source as well and does support a number of cloud providers natively. There's a build flavour for F-Droid without proprietary resources.
https://github.com/PhilippC/keepass2android/tree/ee6b7c4fe0257af35eed0eed09c83721db72e94c/src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage

Using the SD-card as the external storage means, that any application is able to read/write the database. That's just something to take into consideration. Also an external sync app may not know exactly when a file is updated resulting in conflicting versions.
E.g. Keepass2Android is able to merge simultaneously edited databases, something a generic sync app cannot do.

And if you remove the sync component please consider implementing the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) for selecting files. For example the Nextcloud Android app supports it. This way an app can open a file transparently from a cloud provider or from local storage.

Just my two cents. Thanks a bunch for this awesome tool

**Comment by MisterY** [comment]
Thanks for the hints! The Storage Access Framework is definitely worth looking into. Still needs to be confirmed if the SQLite Helper will work with whatever it returns when a file is selected. And, Murphy's Law confirmed, that does not seem to be the [case](https://grokbase.com/t/gg/android-developers/154279qhac/use-new-storage-access-framework-to-write-sqlite-database).

If the experience using Dropbox original APIs is a lesson, we should stick to having a separate sync tool. It would be nice if they integrated with MMEX events. But that's why the Intents are for, I guess.

A good and sustainable alternative still needs to be found, though. 

And, as usual, should someone want to tackle this, pull requests are welcome. :)
