### ISSUE TITLE
Where is the currencies table? [Crowdin]

### ISSUE THREAD

**Issue by ikkoup** [moneymanagerex/android-money-manager-ex#1257]
Hi,
I couldn't find the currencies table/strings in Crowdin. Thus, I cannot translate them like the desktop version.

Thanks!

**Comment by MisterY** [comment]
Could you elaborate a bit more on what you mean by currencies table? The names of the currencies? 

These should be included with the other strings but need to confirm. Searching the code for one name would help.

**Comment by slodki** [comment]
Desktop MMEX stores names of the currencies not in app code but in database rows, loaded by SQL query. Special scripts are used to mark them for translation and then add to the rest of translatable strings from C++ code and consolidate into .pot/.po files.
