### ISSUE TITLE
Cant open database from sd card

### ISSUE THREAD

**Issue by Leon5x** [moneymanagerex/android-money-manager-ex#1262]
Hello, 
for whatever reason I cannot open a database from the sd card in my device.
I am using nextcloud for synchronization. When I move the file by hand to the internal storage I can open it, but that doesn't work with the sd card. 

The Error message is: This extension is not recognised as a valid database.

It looks like the app is using its own file picker dialog and therefore doesnt ask for the (extra needed) permission to read/write on the external sd card. 

Another problem is that I cannot open the database from within nextcloud with the "open in" dialog, the app seems to not register for opening of .mmb files.

Could you please help me?

Version: 2018.02.26.981

**Comment by MisterY** [comment]
Can you try now, after #1278? This should work with any provider, including NextCloud, directly. It should not be required to resort to custom synchronization solutions.

**Comment by Leon5x** [comment]
Now I can open the files when it is stored on the sd card, thanks!

But I can't choose money manager in the "open with" dialog in the nextcloud app. In total commander I can choose money manager, so i guess this is a bug in the nextcloud app. 

App Version: 2019.02.14.994

**Comment by MisterY** [comment]
A question in relation to that - does NextCloud show up in your list of storage providers? I don't see it but just want to confirm.
It would be a good idea to request it to register as a storage provider, in which case MMEX would pull the file directly from it.

**Comment by Leon5x** [comment]
Yeah in fact it registers as a storage provider. So I can choose the file from nextcloud directly in the file picker dialog. Thanks!

**Comment by MisterY** [comment]
Hm, great. Now I wonder why I don't see it. Was just about to report in https://github.com/nextcloud/android/issues/2258
Thanks for the info!
