### ISSUE TITLE
not able to open the database anymore

### ISSUE THREAD

**Issue by mr10008** [moneymanagerex/android-money-manager-ex#1263]
I'm using Windows MMEX 1.4.0 and the latest Android app as well. For long time the database that run on PC could easily be opened on Android version (phone running Marshmallow).
Now that I changed to a new phone running Oreo (8.0.0) I'm not able to open the database anymore - the app is asking for a password that I never have set up.
How to fix that?

Even setting up completely new database does not work anymore.
Any ideas how to fix it?

Thanks

**Comment by velmuruganc** [comment]
Are you using released version of android app or beta?

**Comment by mr10008** [comment]
I tried with both the released version 2018.02.26.981 and the beta 2018.09.09.985 and neither of them work.

**Comment by Snaptags** [comment]
I'm using 2018.11.15.987. The only change is that the app just crashes without any further dialogs.

**Comment by Snaptags** [comment]
Note beyond: The widget kept on working all the time, all transactions I entered using the widget were entered in the database correctly! So I really don't see what's the problem here :-(

**Comment by Snaptags** [comment]
v2018.02.26.981 is the last working version, something commited after this version broke database handling…

**Comment by MisterY** [comment]
Can you create a new database from within the app?

**Comment by MisterY** [comment]
Meaning that the change after v2018.02.26.981 is that you installed a new version of desktop application which upgraded a database schema. This is what broke database handling.

**Comment by Snaptags** [comment]
How should I open a new version of the desktop app when the latest version is 1.3.3 (Mar 04, 2017)?
My existing database has v7, if I create a new database in the app this database also has version 7…

**Comment by Snaptags** [comment]
Sorry, but my problem is indeed only loosely related to this, i.e. I just opened a new issue providing more details: https://github.com/moneymanagerex/android-money-manager-ex/issues/1279
In my case everything works fine after disabling the database passcode.

**Comment by wolfsolver** [comment]
Give a try to latest 202401 series
