### ISSUE TITLE
Transaction Marked Duplicate - money value should not affect the account balance

### ISSUE THREAD

**Issue by CraftingGamerTom** [moneymanagerex/android-money-manager-ex#1265]
Case:
Two transactions have been made. They both represent the same transaction - creating the second transaction was a mistake.
To fix this, the second transaction is set as a duplicate. The second transaction still affects the balance of the account.

Specific Case:

|Transaction| Value | Balance | Type |
|-|-|-|-|
|Milk| -2.50 | 97.50| reconciled |
|Milk| -2.50 | 95.0| duplicate |

The balance should be 97.50 since the type is `duplicate`.

**Maybe I am confused. Is this not the way duplicate was intended? In this case can we define somewhere what the different types are for?

**Comment by MisterY** [comment]
Just a quick question - did you try the same with the desktop version? What is the behaviour there?

**Comment by CraftingGamerTom** [comment]
Sorry for the late response. I have not tried it there.

**Comment by MisterY** [comment]
The reason I'm asking is that this app was implemented as a mobile companion to the desktop app so not a big deviation in features is expected. On one hand that is a fairly limiting factor but, on another, it offers existing users peace of mind knowing that both apps are behaving exactly the same.
