### ISSUE TITLE
Google Play publishing issues

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1267]
Currently, publishing to the Play Store is not possible due to issues regarding policy.
The incident has been reported to the support but no response so far has been received.

![image](https://user-images.githubusercontent.com/462445/48269937-13b99b80-e439-11e8-90b5-09e9d865a888.png)

**Comment by MisterY** [comment]
![image](https://user-images.githubusercontent.com/462445/48269920-07354300-e439-11e8-8d22-93c3712e0a9c.png)

**Comment by MisterY** [comment]
If this does not work out, we might re-register or move to another repository, i.e. #827

**Comment by MisterY** [comment]
No updates are possible, whether .apk distribution *or* update of the description. The app is effectively lost.
To have the Play Store presence, a new developer account must be created and the app namespace changed. However, this still would not guarantee that the app would be accepted as there could be other issues with the new policies.

**Comment by MisterY** [comment]
Beta version has passed the publishing process successfully (?!). The Production version is exactly the same but is still being rejected.

**Comment by MisterY** [comment]
The Prod version was accepted, as well. No idea how and why but it works now.

**Comment by vladimir-poleh** [comment]
It is Google, sometimes they do weird things without any explanations.
