### ISSUE TITLE
issue with syncing of data.mmb

### ISSUE THREAD

**Issue by Mercerhelen** [moneymanagerex/android-money-manager-ex#1270]
My moneymanager ex app has just been automatically updated to 2018.11.15.987.

Now with the sync option on, a new Cloudrail screen appears and forces me to a PCloud login page.   I had to create an account but now it says 'Error: File or Folder not found'.
It is no longer updating my Dropbox data.mmb file and everything I do , now it forces me to this Pcloud login page.   The only way to stop this is to turn synchronisation off. 

https://user-images.githubusercontent.com/35166310/48669889-9f9c8900-eb05-11e8-8152-83820d626f46.png

**Comment by Maeveen** [comment]
I have this exact same issue. Should I create a folder myself or something ? If yes, where/with which name/what should be inside ? Thanks in advance

**Comment by Mercerhelen** [comment]
Hello Maeveen
Nobody replied to me on my issue but I resolved it for myself by going into Settings,  Synchronization, and changed the Provider to Dropbox.   For some reason , it had changed  to Pcloud! 
Hope that helps?

**Comment by Maeveen** [comment]
It worked ! Thanks a lot !

**Comment by MisterY** [comment]
This is interesting to know. The default provider has been changed to pCloud but any saved providers should have stayed in the settings. After finding a bug with pCloud API, I stopped using the built-in sync.
I'm temporarily using a 3rd-party sync while looking into creating a PWA version of the app.

**Comment by MisterY** [comment]
You can try the latest beta which includes #1278
