### ISSUE TITLE
All accounts widget shows cumulative amount

### ISSUE THREAD

**Issue by MisterEco** [moneymanagerex/android-money-manager-ex#1271]
Hello, for some period of time all accounts widget shows only one cumulative amount and without showing account list. Please check.

Thank you.

**Comment by luisdev** [comment]
I just tried this, but both the available widgets - "Summary 4x1" and "All Accounts 4x3" - don't seem to work at all in AMMEX version 2024.01.10 (1011). They don't show any account info or balances.

**Comment by luisdev** [comment]
I just tried this, but both the available widgets - "Summary 4x1" and "All Accounts 4x3" - don't seem to work at all in AMMEX version 2024.01.10 (1011). They don't show any account info or balances.

In addition, I cannot resize the widgets to fill the ugly gaps on the left of each widget:

![Screenshot_20240111_060740_One UI Home.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/1124791/d6a2ee21-ed6c-4d87-a12e-bc75bce37666)

**Comment by wolfsolver** [comment]
Same of #1323

**Comment by MisterEco** [comment]
![Screenshot_2024-01-16-06-55-26-829_com miui home](https://github.com/moneymanagerex/android-money-manager-ex/assets/41244229/9981a295-9baa-4738-af9c-c50acfdcc776)

**Comment by wolfsolver** [comment]
Duplicate of #1323 #1248

Il mar 16 gen 2024, 06:01 MisterEco ***@***.***> ha scritto:

**Comment by luisdev** [comment]
github-actions likes to close issues that are still unresolved!  This is still a problem for me in version 2024.05.09 (1032)

See #1323 (which has laso been closed.) Can we re-open these?
