### ISSUE TITLE
Database downgrade from version 13 to 7

### ISSUE THREAD

**Issue by rohamkocka** [moneymanagerex/android-money-manager-ex#1273]
Hello, I upgraded my DB under Windows, and it works fine. Under Ubuntu I had to upgrade from LTS to "mainstream" to open my DB-- it was still OK, but under Android I cannot open my DB anymore, there are 2 error messages:
"Can't downgrade database from version 13 to 7"
and "Attempt to invoke virtual method" (etc.)
Neither with stable nor with beta.

**Comment by gianni5252** [comment]
Anche io ho lo stesso problema di rohamkocka2. Anche i messaggi che appaiono sullo smartphone sono uguali. Si prega di risolvere il problema. Grazie

**Comment by XidRanReb** [comment]
I still have the same error with 2019.01.09.989 :/

Anything upcoming ? :)

**Comment by andrepg** [comment]
It's a problem related to database prefixes. The alpha version of MMEX desktop has removed some prefixes inside database this hasn't changed in mobile companion app. Seems that a new version it's coming to resolve these problems, but without ETA.

**Comment by slodki** [comment]
Not only table names were changed - all changes can be listed [here](https://github.com/moneymanagerex/database/tree/master/incremental_upgrade)

**Comment by MisterY** [comment]
#1347

**Comment by wolfsolver** [comment]
No more relevant.

Now android and pc work on same schema (thanks to @guanlisheng )

Close issue
