### ISSUE TITLE
Multiple users per account

### ISSUE THREAD

**Issue by Jomme5** [moneymanagerex/android-money-manager-ex#1275]
Share an account with multiple users over the cloud

# How?
+ A shareable database that is synced in the cloud(e.g. Google drive) and is accessible by multiple users. This means that the apps should work with multiple databases at once, so you don't have to share all your accounts with multiple users. This is, I think more difficult to implement. For example: Account 1 and account 2 or in my private database, account 3 is in the shareable database and has read/write permissions for other users.

+ One database, also on box or G-drive, accessible for multiple users where accounts can be (in)visible for specific users and other are reachable for specific users. Thus: shared accounts/ private accounts on one shared database.

+ In both cases, you could easily transfer 'money' from and to different databases or different accounts from multiple users.

+ Practical example: you want to share expenses with your partner and also let your partner alter the shared account from her/his phone.

Thx,
J

**Comment by MisterY** [comment]
I don't think this scenario is supported or even foreseen. This is a **personal** finance program. 
On the other hand, there's nothing stopping one from synchronizing any number of devices or users through a 3rd-party solution. 
Also please note that this is not a support forum.

**Comment by MisterEco** [comment]
+1

**Comment by guanlisheng** [comment]
@MisterEco and @Jomme5, I would suggest continuing the general discussion in the project forum. https://forum.moneymanagerex.org/viewforum.php?f=10
