### ISSUE TITLE
Pincode doesn't work anymore but fingerprint does

### ISSUE THREAD

**Issue by aardbol** [moneymanagerex/android-money-manager-ex#1280]
I set a pincode on my database and activated the fingerprint feature. I reset my phone and imported the backup of the database that has the pin code activated. What I then noticed is that the same pin code doesn't work anymore, I can't open the database with it, however, I still can with my fingerprint.

This is quite a big issue because I can also not deactivate or change the pincode anymore, not by entering the pincode, nor with my fingerprint.

Can I deactivate it in another way? This database has many years of records and I can't risk of losing it if the fingerprint doesn't work anymore.

**Comment by Snaptags** [comment]
Workaround: uninstall the app, then download this release and install it manually: https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2018.02.26.981
After removing the passcode you should be able to use newer versions again.

**Comment by MisterY** [comment]
You can remove the pin code using a tool that can modify sqlite databases. I think it is in one of the settings tables, having a name like android.passcode or something along those lines. Should be fairly easy to locate.

**Comment by SJK55** [comment]
I have had the same issue but worse in using it on Samsung Galaxy Tab (new) it bombs completely! Works on PC still and Android Moto G6 plus ok but same issue of pin code being ignored

**Comment by aardbol** [comment]
I finally found the time to remove it :). It didn't work with the app that was linked, but the advice of @alensiljak made it work. It was a row called MOBILEPASSCODE that I removed. I'm using the latest version flawlessly!
