### ISSUE TITLE
Enable delayed synchronization via SAF

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1287]
Create a delayed background task which triggers database synchronization after changes have been made.

Eventually, create a continuous periodic background synchronization.

**Comment by velmuruganc** [comment]
@MisterY , Can you make these changes on priority. As of now, the sync is not working for me. Also I am not expect in these area to make changes. Can you?

**Comment by MisterY** [comment]
@velmuruganc, I'm away from my dev box for at least a week. Some things I can do in a Web IDE but I cannot test before the release.
