### ISSUE TITLE
Transaction Widget is not visible

### ISSUE THREAD

**Issue by bquinlan** [moneymanagerex/android-money-manager-ex#1290]
I just updated to the latest version on Google Play.  After the update the transaction widget (1x1) on my home screen continued to work, but was completely invisible.  I removed it and added it again, but I continue to have the same problem.

I'm running Android 8.0.0 with a November 1, 2018 security path on an LG V30.

**Comment by MisterY** [comment]
Noticed the same after the support library update but didn't have the chance to look at it.
Any pointers and pull requests welcome.

**Comment by MisterY** [comment]
#1300
