### ISSUE TITLE
About and Info cause crashes

### ISSUE THREAD

**Issue by bquinlan** [moneymanagerex/android-money-manager-ex#1291]
I just updated to the latest version on Google Play.  The About and Settings -> Info options now immediately crash the app.

I'm running Android 8.0.0 with a November 1, 2018 security path on an LG V30.

**Comment by velmuruganc** [comment]
Yes, I am also getting same crash with Android 7.1.1

**Comment by MisterY** [comment]
Thanks for reporting! These are caused by the changes in the support libraries and introduction of androidx namespace. The built-in migration tools in Android Studio did not do a good job, unfortunately.

**Comment by MisterY** [comment]
Ref https://developer.android.com/jetpack/androidx/migrate

**Comment by MisterY** [comment]
AppBarLayout
android.widget.TableLayout

**Comment by MisterY** [comment]
Also TabLayout
