### ISSUE TITLE
Split transactions crash

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1296]
As a result of the support libraries, and the new androidx namespace, the Split Transactions view is not opening.

**Comment by MisterY** [comment]
CoordinatorLayout namespace problem with androidx upgrade.

**Comment by MisterY** [comment]
RecyclerView

**Comment by ibnuda** [comment]
Sorry for replying this closed issue. I'm still experiencing crash when I tap split category button.

**Comment by MisterY** [comment]
@ibnuda, can you please provide at least some details? The original cause of this exception has been fixed. If you are experiencing some issues then please provide logs, screenshots or some other relevant information, unless you can debug yourself and submit a pull request with the correction for that specific scenario.

**Comment by ibnuda** [comment]
Where can I find the log file?

**Comment by ibnuda** [comment]
OK, I've sent the log with "issue #1296" as the subject.
