### ISSUE TITLE
Unable to syncronize database with OneDrive

### ISSUE THREAD

**Issue by Gen1usCat** [moneymanagerex/android-money-manager-ex#1297]
I was make a clean install of **2019.02.13.992-release** version.
I open a database via OneDrive provider, it not syncronizes after changes (also a manual syncronize not work). It shows a message that the file up-to-date already.
I work temporary with Google Drive provider, it works well.

**Android 7.0**
**OneDrive 5.25.1**

**Comment by MisterY** [comment]
Thanks, now tracking in #1306
