### ISSUE TITLE
Dropbox synchronization option is missing

### ISSUE THREAD

**Issue by PARTISAN0** [moneymanagerex/android-money-manager-ex#1298]
After last update the Dropbox synchronization option is missing.

**Comment by dl200010** [comment]
My app updated and stopped syncing to dropbox all together. I uninstalled and reinstalled the app and now it forces you to open or create a database, but not set up the sync. It mentions the sync at the beginning, but there is no way to setup the sync.

**Comment by chq-matteo** [comment]
It should be related to this https://github.com/moneymanagerex/android-money-manager-ex/issues/1250

**Comment by dl200010** [comment]
Since #1250 removed the synchronization, how do we sync with dropbox now? I had to downgrade using GitHub releases to get this to work again. It won't even update when sync was set up already on a previous version.

**Comment by MisterY** [comment]
Duplicate. See #1292
