### ISSUE TITLE
Support for new DB format and encryption?

### ISSUE THREAD

**Issue by TobiasDev** [moneymanagerex/android-money-manager-ex#1299]
I love using Money Manager EX for staying in control of my money, however I've noticed there are two things missing from the mobile app compared to the desktop. 

1. A new database format. As soon as I upgrade my database to MMEX 1.4's version I can no longer use the mobile app with it. (Therefore I'm currently using an old version on desktop since mobile is a must for me)
2. On desktop I can encrypt my database so even if someone were to get hold of it they wouldn't be able to read it. However, if I turn on encryption the mobile app no longer works.

My question is if these two things are something that is planned to be added in the mobile version?

**Comment by MisterY** [comment]
Duplicate. See
#1273, #1245
#135
