### ISSUE TITLE
Repeating Transaction activity crash, because 'Monthly (last day)' options missing from app

### ISSUE THREAD

**Issue by thdls55** [moneymanagerex/android-money-manager-ex#13]
These options are provided on the desktop, but not on Android:

* Montly (last day), `BILLSDEPOSITS_V1.REPEAT = 15`
* Montly (last business day), `BILLSDEPOSITS_V1.REPEAT = 16`

When entering or viewing such transactions on Android, the activity will crash:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.RepeatingTransactionActivity}: java.lang.IndexOutOfBoundsException: Invalid index 15, size is 15
    ...
    at com.money.manager.ex.RepeatingTransactionActivity.onCreate(RepeatingTransactionActivity.java:511)

Thanks.

**Comment by AlessandroLazzari** [comment]
Fix commit: https://github.com/AlessandroLazzari/android-money-manager-ex/commit/06b0910cc2656cc2c3cab477684350191492e2ab
