### ISSUE TITLE
No Cloud provider works properly

### ISSUE THREAD

**Issue by CDevel** [moneymanagerex/android-money-manager-ex#1301]
Sorry for opening another sync issue. After the latest release I have changed from Dropbox to Onedrive and Google Drive. All 3 behaves the same more or less. It initially downloads the DB but when you make any change on Desktop and then try to synchronize the app in Android the app crashes. Also I noticed that in Android -> Settings there is no more the cloud settings selection.

**Comment by MisterY** [comment]
Thanks, now tracking with #1306 as it contains the error logs.
