### ISSUE TITLE
Getting error "Gradle DSL method not found: 'versionCode()'" on build

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1303]
Following are the error. Can some one help me?

ERROR: Gradle DSL method not found: 'versionCode()'
Possible causes:
The project 'android-money-manager-ex_fork' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
Upgrade plugin to version 3.3.1 and sync project

The project 'android-money-manager-ex_fork' may be using a version of Gradle that does not contain the method.
Open Gradle wrapper file

The build file may be missing a Gradle plugin.
Apply Gradle plugin

**Comment by MisterY** [comment]
I noticed that as a warning in today's builds. Did you try a clean build?
Which gradle and JDK are you using?

**Comment by velmuruganc** [comment]
I am using following versions. 

![image](https://user-images.githubusercontent.com/29807533/52793772-78b60a80-3094-11e9-87f2-6d3d3c17a754.png)

**Comment by MisterY** [comment]
I'm not getting the error with the same settings. Built several versions today for release.

**Comment by velmuruganc** [comment]
I could able to build using gradle-5.1.1

**Comment by MisterY** [comment]
ok, great to hear! It should stay on that version for a while, anyway.
I downgraded recently to allow building on F-Droid as 5.1.1 was the last supported version.
