### ISSUE TITLE
Unable to open database on Android app

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#1308]
The Android app. Has the path to the database set correctly (see screen shot) but it didn't open.
Throw the message "database not synchronized"

Version 2019.02.14.993 release
Android 9.

I'm also has the beta version and open the same database from the same path just fine.

**Comment by MisterY** [comment]
It seems that the Release version at the Play Store is one version behind, for whatever reason.

**Comment by MisterY** [comment]
Rolled out 994 again.

**Comment by Geoplace** [comment]
Hi

I've upgraded to 994.
1.- Clic menu button and "Open Database"
2.- Tap the "Other" Folder Option
3.- Search the MoneyManagerEx Folder and select the databse.mmb file
4.- The app only shows the Welcome Screen where shows the path to the database "storage/emulated/0/MoneyManagerEx/datos-mony.mmb
5.- The file doesn't open.
6.- When I close and open the de app the first Time throw's the message "Your database is not syncronized. Please set up Dropbox syncronization"
7.- The last time I use de dropbox app and I open a database from there but was not syncing so I want to open again the local file but it failed.

**Comment by Geoplace** [comment]
Now I out of access on both mmex versions.

1.-Go to a drop box folder with a database file.
2.-Tap the file and select mmex app from the system dialog to open it.
3.-Mmex app opens but faild to load the database.
4.-I try to switch back to the local copy but the app faild to open it.
5.- Throws the message: "Your database is not syncronized. Please set up Dropbox syncronization"

If you need more info to solve the issue please ask for.

**Comment by Geoplace** [comment]
I uninstalla the beta version and reinstall it.

I try to open de existing database but nothing there is still the problem. 

Here are a the screenshots. 
![screenshot_20190218-database open first time dialaog](https://user-images.githubusercontent.com/8289274/52967120-ae961000-336e-11e9-8702-e37f05ca9783.png)
![screenshot_20190218-unable to open database due to dropbox failure](https://user-images.githubusercontent.com/8289274/52967121-ae961000-336e-11e9-80b2-573eb9d2dbe6.png)

**Comment by Geoplace** [comment]
It's seems the database is corrupted. I've lost the past 3 days changes.

**Comment by Geoplace** [comment]
Here is the corrupted database that i'm unable to open.

[datos-mony20150716.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/2876846/datos-mony20150716.zip)
