### ISSUE TITLE
Syncronization configuration not available

### ISSUE THREAD

**Issue by ellisonalves** [moneymanagerex/android-money-manager-ex#1314]
In the app configuration it is not possible to see the options for synchronization as shown in the following wiki https://github.com/moneymanagerex/android-money-manager-ex/wiki/Dropbox-synchronization

**Comment by MisterY** [comment]
This is correct, as specified in #1278 and related.
By using Storage Access Framework there is no need to have built-in libraries to access cloud services.
The missing part is #1294.
