### ISSUE TITLE
Drop Google+ from all source files

### ISSUE THREAD

**Issue by funrider1** [moneymanagerex/android-money-manager-ex#1319]
Drop reference to Google+ from all Source files because end of live of G+ is at the end of August 2019.

Google+ is still referred in some files as G+.

I can try to do that ... but I could not assign issue to me :-(

**Comment by MisterY** [comment]
You can reference the issue or even just submit the pull request.
Somebody from the desktop team would need to add you to the android group, I think.

**Comment by funrider1** [comment]
done with pull request #1320 - more occurrences on Crowdin I will change

**Comment by MisterY** [comment]
You can also submit this change separately to the copyright change. Just create a different branch.
Also, you can delete the code completely instead of commenting it. It will stay in the file history in git.
