### ISSUE TITLE
Widgets not available

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1323]
In the current version, the widgets are not available.
996

**Comment by wolfsolver** [comment]
AMME - 2023.12.27
Seems that widget are available, but not working

**Comment by bquinlan** [comment]
The widgets all seem to just open the app.  I end up on whatever screen I was using last, no matter which widget I select.

**Comment by luisdev** [comment]
github-actions likes to close issues that are still unresolved!  This is still a problem for me in version 2024.05.09 (1032)

See #1271 (which has laso been closed! Can we re-open these?
