### ISSUE TITLE
Crash when calling asset allocation menu item and edit stock transaction

### ISSUE THREAD

**Issue by funrider1** [moneymanagerex/android-money-manager-ex#1326]
If the menu item "asset allocation" is selected, the APP crashes.

Version 2019.02.24.1 (996)

02-28 19:10:16.057 21941 21941 D Typeface: fontPath: 
02-28 19:10:16.087 21941 21941 D AndroidRuntime: Shutting down VM
02-28 19:10:16.087 21941 21941 E AndroidRuntime: FATAL EXCEPTION: main
02-28 19:10:16.087 21941 21941 E AndroidRuntime: Process: com.money.manager.ex, PID: 21941
02-28 19:10:16.087 21941 21941 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.assetallocation.overview.AssetAllocationOverviewActivity}: android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating class **android.support.v7.widget.LinearLayoutCompat**

_=> should that not be **androidx.appcompat.widget.LinearLayoutCompat**_

02-28 19:10:16.087 21941 21941 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
02-28 19:10:16.087 21941 21941 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)

**Comment by funrider1** [comment]
Looks like the same error caused the crash when try to edit stock transactions.

02-28 19:20:15.908 25194 25194 E Android-Iconics: Can't init: com.mikepenz.mmex_icon_font_typeface_library.MMEXIconFont
02-28 19:20:15.908 25194 25194 D AndroidRuntime: Shutting down VM
02-28 19:20:15.908 25194 25194 E AndroidRuntime: FATAL EXCEPTION: main
02-28 19:20:15.908 25194 25194 E AndroidRuntime: Process: com.money.manager.ex, PID: 25194
02-28 19:20:15.908 25194 25194 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.investment.PriceEditActivity}: android.view.InflateException: Binary XML file line #64: Binary XML file line #64: Error inflating class android.support.v7.widget.Toolbar
02-28 19:20:15.908 25194 25194 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
02-28 19:20:15.908 25194 25194 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
02-28 19:20:15.908 25194 25194 E AndroidRuntime: at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-28 19:20:15.908 25194 25194 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)

**Comment by funrider1** [comment]
I have identified the source files, but I have no idea what I have to change to fix the problem. Sorry

**Comment by MisterY** [comment]
Good work. Exactly as you say, i.e.
the old value `LinearLayoutCompat` should be replaced by `androidx.appcompat.widget.LinearLayoutCompat`.
This is all a result of the Support libraries migration and the Android Studio wizard that ran on the project but did not update everything correctly. I think the wizard was from Beta2 version and in the meantime the androidx support libraries were published in a release version.
This unfortunately coincided with the sync changes and are causing additional app crashes. Which has also unfortunately coincided with the F-Droid move and inability to have a separate Beta testing version, at least for the time being.

**Comment by funrider1** [comment]
@mistery does it make sense from your point of view if i review the source code for all "android.support" occurences?

**Comment by MisterY** [comment]
If you have time to do that, certainly! I assume that most of the controls have been updated, since I replaced the controls in all the views for the reported exceptions. There might be only a few left in the views I have not opened.
Thanks!

**Comment by funrider1** [comment]
Targets
    Occurrences of 'android.support.v7' in Project
Found Occurrences  (6 usages found)
    Production  (6 usages found)
        app  (6 usages found)
            layout  (6 usages found)
                activity_asset_allocation_overview.xml  (3 usages found)
                    activity_asset_allocation_overview.xml  (3 usages found)
                        57 <android.support.v7.widget.LinearLayoutCompat
                        80 </android.support.v7.widget.LinearLayoutCompat>
                        82 <android.support.v7.widget.Toolbar
                activity_budget_edit.xml  (1 usage found)
                    activity_budget_edit.xml  (1 usage found)
                        64 <android.support.v7.widget.Toolbar
                activity_price_edit.xml  (1 usage found)
                    activity_price_edit.xml  (1 usage found)
                        64 <android.support.v7.widget.Toolbar
                toolbar.xml  (1 usage found)
                    toolbar.xml  (1 usage found)
                        30

**Comment by wolfsolver** [comment]
Need to be close since asset management is no more active in app
