### ISSUE TITLE
TransID must be continuous or the data disapear.

### ISSUE THREAD

**Issue by tim-hub** [moneymanagerex/android-money-manager-ex#1327]
I tried to insert and update records in the sqlite db.

and after delete some rows. I found the android app does not work well, no data display in any account except the one which transid is 1. all others (after 50) no display.

but all good on pc version.

after I trying to modify db, make trans id to continuous, android app work well.

**Comment by MisterY** [comment]
Why would you make such a conclusion? Can you create a few transactions in the app, delete one in the middle and see if it still works? It certainly does for me and has for years.
I would guess that it is more likely that manual tampering with the data is causing problems.

**Comment by tim-hub** [comment]
> Why would you make such a conclusion? Can you create a few transactions in the app, delete one in the middle and see if it still works? It certainly does for me and has for years.
> I would guess that it is more likely that manual tampering with the data is causing problems.

Yes, this makes sense, but what happened is that after I updated all ids to make them continuous, it works again.

```
update set id = id -50 where id > 50;
```

**Comment by MisterY** [comment]
I still believe you are on a wrong track but, who knows, perhaps we learn about another strange issue with sqlite.
I've seen some strange cases on this project so far with numeric fields, hence I would focus on the way you insert the records. I know this may make no sense but SQLite has a funny way of storing values. See if there is a difference if values are stored as numbers vs strings.
For example, I've had different results when running an SQL query in a client vs fetching the data through the data adapter. 
You may find these cases in the history here, usually referring to discrepancy or mismatch in running account balance.
Anyway, I don't believe the gap in IDs would cause any issues and, even if it did, I'd have no idea how to adjust that. If you look at the code, it's all standard SQL queries.

**Comment by MisterY** [comment]
Also try it on another device and compare the SQLite version. I think I added that information to the database settings window.

**Comment by tim-hub** [comment]
Sorry. Wrong issue.

It is because consensus between sqlites of app and pc. If I force to overwrite it, fix the issue. So this is an issue of Syncthing. sorry.
