### ISSUE TITLE
Document the F-Droid deployment process

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1328]
Write down findings from F-Droid deployment procedure. Auto-update takes care of this.

Also, write down the steps for publishing the Beta versions.

**Comment by MisterY** [comment]
Auto-updater picks up tags from the source code repository and automatically builds and publishes the releases.

There is a work-in-progress item to exclude Beta releases from auto-updater.
Beta releases currently require manual submission of an entry in the .yml file.
Pre-release (Beta) versions will not be offered as updates but will be visible in the versions list, allowing manual update for beta testers.
