### ISSUE TITLE
Reload the database after sync download

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1330]
Display the notification that the database is being downloaded.
After download, nothing happens. The current view should be refreshed and data reloaded.

**Comment by luisdev** [comment]
I'm not sure how to test this in the latest MMEX and AMMEX, but the title, "display the notification that the database is being downloaded" sounds like the right thing to do after MMEX files have been downloaded.

**Comment by wolfsolver** [comment]
I think that with latest release sync work quite fine and this issue can be close.
