### ISSUE TITLE
Include Bitcoin and Ethereum As Part of Base Currency

### ISSUE THREAD

**Issue by autofreak** [moneymanagerex/android-money-manager-ex#1337]
The world is changing fast, in as much as I love this app, I would love to create personal account using cryptocurrency as base currency.

**Comment by trymeouteh** [comment]
Please add BTC, ETH, LTC, BCH, DASH, XMR, & DGB. If more can be added the better!

**Comment by reinhart1010** [comment]
Currently you are able to add this as a new currency, but starting from MMEX database version 8 (currently version 7 is used in Android) you will be able to tag currencies as either fiat/traditional or cryptocurrency. (The MMEX database is a file where your MMEX data are stored, in `.mmb`)

A database upgrade is being discussed #1347.
