### ISSUE TITLE
Google Play Link dead

### ISSUE THREAD

**Issue by kolbma** [moneymanagerex/android-money-manager-ex#1340]
Like in #1267 the link to Google Play isn't working.
The App doesn't seem to be in Play anymore.

**Comment by MisterY** [comment]
Correct, the app has been suspended on Google Play. The only available distribution is currently on F-Droid (either through the app or by direct download).

**Comment by kolbma** [comment]
Then remove the links to Google Play on the Website!

**Comment by MisterY** [comment]
Perhaps if you referred to a specific web site.

**Comment by kolbma** [comment]
https://www.moneymanagerex.org/
https://www.moneymanagerex.org/download

**Comment by MisterY** [comment]
These are managed by somebody in the desktop team. A request might need to be sent to the webmaster of that site.
The Android app's subdomain is https://android.moneymanager.org
