### ISSUE TITLE
App crashed when I clicked the plus sign to on Budget list.

### ISSUE THREAD

**Issue by cckole** [moneymanagerex/android-money-manager-ex#1341]
### Actual behavior

The app crashed when I clicked on the plus sign in the project list

### Expected behavior

I expected to be able to write my budget list when I clicked on the plus icon

### How to reproduce

- Download and launch the app

- Click the menu button on the top left side

- locate "Budget" in the list of the features

- Click on it. A new page will open.

- Below the new page by the right, you will find a plus icon colored green.

- Click on that Icon and note the crash

### Reproducing the bug

https://youtu.be/ixZ8uya5_L8

***Device used*** : Teckno Spark K7

***Version*** : Android 7.0

**Comment by MisterY** [comment]
This  does not work on my device (9) but it does in an emulator (7.1), so I can't reproduce. Will need to spend some more time setting up the dev environment.
Or, if someone has a log, please submit. It would help identify the issue.

**Comment by Backfighter** [comment]
Since 2019.03.30.998-beta it works on my device (Android 9).

**Comment by MisterY** [comment]
Thanks for the confirmation!
