### ISSUE TITLE
MMEx in Play Store

### ISSUE THREAD

**Issue by JEANPAUL51** [moneymanagerex/android-money-manager-ex#1345]
Good morning,
I no longer find the "Money Manager ex for android" app in Play Store: has it been removed and if so how can I get updates?
Thanks for feedback.
Gian Paolo Bassetti

**Comment by MisterY** [comment]
Hi, please have a look at the web page for information links: http://android.moneymanagerex.org/

**Comment by CraftingGamerTom** [comment]
Where can we get more information about the suspension? Is this something that is actively trying to be resolved? What was the cause? The app missing from the play store is highly inconvenient and vastly lowers the chances of continued development IMO.
