### ISSUE TITLE
Feature Request: Attach image with transactions

### ISSUE THREAD

**Issue by trymeouteh** [moneymanagerex/android-money-manager-ex#1349]
Please add a feature to attach an image and also be able to take a image within the app that can be attached to the transaction.

This handy for taking images of receipts, or even the item you bought.

When storing the image data, if the database is encrypted the image should be encrypted too.

For the mobile camera access will be required but no camera feature is needed for desktop applications.

**Comment by MisterY** [comment]
There is already #11. I think these are the same request, effectively.
