### ISSUE TITLE
Samsung Galaxy Tab 4 (Android 5.0.2) Model SM-T530 Bombs with latest release of MM Ex

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/android-money-manager-ex#1351]
Whenever the last version came out my Galaxy Tab 4 bombs trying to run MM Ex. Having trouble finding older version to see if fixes the issue on tablet

**Comment by luisdev** [comment]
I don't think "github-actions bot closed this as [completed]" is the correct way to close this. No changes have been made to MMX for this?

**Comment by wolfsolver** [comment]
I think is standard behaviour of stale workflow. Anyway this issue is very old and refer to a older version of AMMEX. Tested on tablet work fine now
