### ISSUE TITLE
Sync android gdrive 987 version

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1355]
I have a problem to sync dB with my gdrive.

Google page say:

401. Questo è un errore.

Errore: deleted_client

Il client OAuth è stato eliminato.

Richiedi dettagli
client_id = 576599958315-eplsbf760onv3hljsp5h6mmrk34btg5s.apps.googleusercontent.com
state =
portata = https: //www.googleapis.com/auth/drive
response_type = codice
pronta = consenso
tipo_accesso = connesso
redirect_uri = com.money.manager.ex: / oauth2redirect
suppress_webview_warning = true

È tutto quello che sappiamo.

**Comment by MisterY** [comment]
Unfortunately, there's next to nothing that we can do now in MMEX. All the content handling was offloaded to the system and content providers.
You can ask in the support forum and see if others are experiencing the same issue.

**Comment by alerque** [comment]
All the handling is _supposed_ to be offloaded, but my experience is it I'n't yet passing things off very well. I don't know about this specific issue, but I'm confident there is more to do to properly interface with the system's file handling. I keep having to resort ho ADB to get my files synced and that shouldn't be necessary.

**Comment by manmeetjammu** [comment]
There should not be an issue with gdrive.

Did you followed the proper steps.

1.Upload the data.mmb(create it by opening MMex if fresh install) from data folder of Money manager ex with grive app.

2. Then make this file available offline and in link sharing "on" (in details and activity of above file) click "any body edit ".( Never change these two options again or you will have conflict)

3. Then in MMex open this file by clicking Open Database>Other chose grive and then open the above uploaded file. Cautioun: it will replace the local data.mmb. Rename local data.mmb after uploading to grive if you want to save it.

I never got problems after I learned this . I did this on five andriods. No problem. Update latest from f-droid not available on playstore.

**Comment by votocek** [comment]
I have tried it with Google Drive and it was not reliable. Mobile app version 2019-02-19.995 (the newest from Google Play store).
 
The synchronization way from mobile app. to Google Drive seems to be OK. When I change the MMEX database in the mobile app and use manually synchronize option then it uploads the database on Google Drive. OK.

But the other way of synchronization is not working. I change the MMEX database on my laptop and upload it to Google Drive. But mobile app. doesn’t synchronize the changed database – neither automatically nor manually when a use synchronize option in the MMEX application. It keeps telling me “Not synchronizing. Files have not been modified”. MMEX mobile app. keeps using the local copy of the database. How to enforce downloading the MMEX database from Google Drive?

It seems that there is one solution – force to stop the MMEX mobile app., start it again and choose “Open database | Other”, find it on Gdrive manually and open it. This solution is not easy at all.

**Comment by manmeetjammu** [comment]
The version you have mentioned is not the latest. It had glitches after that devloper Or Playstore stoped distributing MMEx plj . You can see it because you installed it before the Ban On App from playstore. Others cannot find this app. The below version has problems fixed many. Sync works.

The latest variant is 2019.04.10.1000-beta (1000) and is available on F-droid only

https://f-droid.org/en/packages/com.money.manager.ex/

And even every thing right without any reason After a month or two I still get a message "Your local or remote database has conflict" sort of message.

Better luck

Previous comment.
https://github.com/moneymanagerex/android-money-manager-ex/issues/1355#issuecomment-500591837
