### ISSUE TITLE
Bug found in  android-money-manager-ex  The application crashes when I click on the active pass code

### ISSUE THREAD

**Issue by saraji-ali** [moneymanagerex/android-money-manager-ex#1361]
# Project Information

* Repository: https://github.com/moneymanagerex/android-money-manager-ex
* Project Name: android-money-manager-ex

# Expected behavior

When I click on the active passcode, then the option should be displayed where I can enter my password or fingerprint

# Actual behavior

The application crashes when I click on the active pass code

# How to reproduce

1-[Download ](https://github.com/moneymanagerex/android-money-manager-ex/releases)the app and open it
2- Click the horizontal three line on the top left
3- select the Settings option
4- Then click Security Options
5- click on Active passcode
6- see the bug 

* Browser/App version: 2019.02.14.994
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190509_145833](https://user-images.githubusercontent.com/50115498/57446022-8a78fb00-7208-11e9-89fc-2f8983b24561.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>D/AndroidRuntime( 7364): Shutting down VM

E/AndroidRuntime( 7364): FATAL EXCEPTION: main

E/AndroidRuntime( 7364): Process: com.money.manager.ex, PID: 7364

E/AndroidRuntime( 7364): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/hardware/fingerprint/FingerprintManager;

E/AndroidRuntime( 7364): 	at com.money.manager.ex.PasscodeActivity.onCreate(PasscodeActivity.java:164)

E/AndroidRuntime( 7364): 	at android.app.Activity.performCreate(Activity.java:6178)

E/AndroidRuntime( 7364): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

E/AndroidRuntime( 7364): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

E/AndroidRuntime( 7364): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime( 7364): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime( 7364): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime( 7364): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 7364): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 7364): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 7364): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 7364): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 7364): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 7364): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime( 7364): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.hardware.fingerprint.FingerprintManager" on path: DexPathList[[zip file "/data/app/com.money.manager.ex-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

E/AndroidRuntime( 7364): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

E/AndroidRuntime( 7364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

E/AndroidRuntime( 7364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

E/AndroidRuntime( 7364): 	... 14 more

E/AndroidRuntime( 7364): 	Suppressed: java.lang.ClassNotFoundException: android.hardware.fingerprint.FingerprintManager

E/AndroidRuntime( 7364): 		at java.lang.Class.classForName(Native Method)

E/AndroidRuntime( 7364): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

E/AndroidRuntime( 7364): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

E/AndroidRuntime( 7364): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

E/AndroidRuntime( 7364): 		... 15 more

E/AndroidRuntime( 7364): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
</code></pre>

**Comment by MisterY** [comment]
This version of the app is not the latest one. Can you try with the latest published beta?
https://f-droid.org/app/com.money.manager.ex

**Comment by facebook-786** [comment]
sir  also am facing  this issue on 2019.04.10.1000-beta  version

**Comment by facebook-786** [comment]
Sir @Money-Manager
 please review my post

**Comment by p2635** [comment]
I get the same problem on 2019.04.10.1000-beta version (version currently offered by f droid). Samsung Galaxy S10e

**Comment by wolfsolver** [comment]
Resolved in 2024.01.05

Ca be closed
