### ISSUE TITLE
lost database

### ISSUE THREAD

**Issue by omar96daoud** [moneymanagerex/android-money-manager-ex#1365]
I created a new database, then when I went to reopen the old one, it appears it's completely empty.
I tried a search on the phone for all .mmb files, but could not find anything else than the one that looks empty.
Any hope for me recovering the lost DB?

**Comment by CraftingGamerTom** [comment]
I cannot reopen databases either anymore. I can open the exact same database on Linux but cannot open it in the Android App

**Comment by uli-on** [comment]
Same here, obviously. 

On top, all categories and restructuring therein, all translations, everything is reset to the default values, too.

**Comment by studiofuga** [comment]
This happened also here. MacOS version, 2 hours of work importing and tagging expenses, then the day after, no data therein anymore. Very disappointing. Any clue how to debug / diagnose it?

**Comment by Nightingale-Robin** [comment]
Had precisely the same thing happen to me. Lost 2 months of data. Somehow the original database is overwritten?

**Comment by studiofuga** [comment]
@Nightingale-Robin I don't know. I checked with Time Machine but the only version I have is the one with no data. It seems like as the data is not dumped on the disk.
Unfortunately having the need to work with it, I had to switch to GnuCash -- Sorry guys.

**Comment by uli-on** [comment]
This happened again today with the data of 5 months(!), after trying to grasp all the impenetrable UI points where I can star/unstar an account and and then simply pressing the back button to get to the start page. All data lost!

No official statement here in 5 months, no comment, no hope to get this fixed: Bye, Money Manager Ex!
