### ISSUE TITLE
Cannot open databases on Android

### ISSUE THREAD

**Issue by CraftingGamerTom** [moneymanagerex/android-money-manager-ex#1366]
I can open the exact same database on Linux but I cannot open it on Android. It looks like an empty database - asking me to create a new account. 

LG G6
Android 8
Tried on version `2019.02.14.994` & version `2019.02.19.995` (google play latest at the moment)

**Comment by slodki** [comment]
#1347?

**Comment by CraftingGamerTom** [comment]
@slodki I'm not convinced. I had not opened this database on the computer in many months prior to this issue. I opened in on the pc (from a backup synced to google drive) after the issue started.

Is there documentation somewhere I can read up on to see how to open the data.mmb and check it? I'm interested in working on getting this fixed but I have not contributed to the project before.

**Comment by slodki** [comment]
mmdb is a normal sqlite3 database file. There are many tools supporting this db format.

**Comment by CraftingGamerTom** [comment]
Opened DB that cannot be opened within the Android App
![image](https://user-images.githubusercontent.com/10101712/59150485-8819e480-89f2-11e9-80ef-469db2406b5c.png)

It seems that it does not contain the 'breaking changes' referenced in #1347 . I appear to be using DB version 7

![Screenshot_2019-06-08-13-35-33](https://user-images.githubusercontent.com/10101712/59150529-2f971700-89f3-11e9-9aa5-4b28dde5863a.png)

**Comment by CraftingGamerTom** [comment]
This has been fixed using the latest code in `dev` (todays code) 2019-06-15
Data now loads. Seems a bit unstable though. An exact copy of the DB will not load. I have no information on this though to go much further

**Comment by XidRanReb** [comment]
Sounds a bit stupid but... is there a dev apk somewhere ?

**Comment by kripton** [comment]
> This has been fixed using the latest code in `dev` (todays code) 2019-06-15

Which commit are you referring to? The latest commit I can see in https://github.com/moneymanagerex/android-money-manager-ex/tree/dev is from May, 17th. I cannot see any commits from 2019-06-15 ?

**Comment by wolfsolver** [comment]
Resolved in 2023.12.27
