### ISSUE TITLE
Transactions template

### ISSUE THREAD

**Issue by dezerb** [moneymanagerex/android-money-manager-ex#1367]
HI, I would like to suggest new feature "transaction template"
I add a lot of similar transactions like "bus tickets". They are almost every time the same. 
They are two possibilities to realize it:
- new button "transactions from template" where we could select template or other transaction? 
- or when the payee is selected there could be load last amount and category 
I would like to hear you opinion and feedback.

**Comment by vomikan** [comment]
Try copy/past ))

**Comment by dezerb** [comment]
I know this function, but it isn't exactly what I would like to see. 
Copy/paste could be not efficient und intuitive by typing transaction to more than one account.

**Comment by luisdev** [comment]
To test:
- Open an account
- Tap the New Transaction icon
- Tap the Payee field. MMXA shows all your payees.
- Select the payee you want to pay.
- MMXA creates a new transaction with the payee selected. The last category that you used for this payee is also selected. But, the 'Amount' and 'Notes' and 'Transaction Number' values are not carried through.

So, perhaps if all the values could be carried through (i.e., the Amount, Notes and Transaction Number, etc. mentioned above) them this problem would be partially solved.

MMX Android also has the Recurring Transactions function, but that's for recurring transactions that happen regularly, not for "ad-hoc" transactions that you want to capture irregularly.

**Comment by wolfsolver** [comment]
Hi, can you explain a real situation for this feature?
