### ISSUE TITLE
Split category transactions are budgeted in whole, not as part of the sum

### ISSUE THREAD

**Issue by uli-on** [moneymanagerex/android-money-manager-ex#1368]
When I query "Reports" > "Where does my money go" and tap an entry there, I can see a split category transaction appearing under both its subcategories, but both times with the total of the cash receipt, not its single amounts. I.e. the last line there shows an incorrect total by adding the second/wrong sub-category's amount to the total, differing from the sum shown immediately on "Where does my money go", which is the correct one.

The same, wrong, addition of totals is made by following these steps: From the sidebar menu > Entities > Categories, tap/hold a category. Select "Show transactions". The total amount from the split transaction is shown, also for the second category from the split transaction.

**Comment by dezerb** [comment]
Probably the same view is also used in "search" 
search -> select some category -> search button 
will result with the sum that will also include amounts from split transactions from other categories.
