### ISSUE TITLE
Donation link incorrect

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/android-money-manager-ex#1374]
@MisterY I recently donated to the android moneymanagerex and realized it went to you. Since you aren't on the project anymore would you be kind enough to forward it to the appropriate person?
Also, if someone could update the donation link so funds are disbursed correctly.

PS: now that you've seen the limitations on the ledger program, aren't you ready to come back to the project anyway haha :)

**Comment by MisterY** [comment]
Hi, @user8446, I did not receive any notifications about donations coming to my accounts. Where exactly did you send the donation?

**Comment by user8446** [comment]
Hi @MisterY 
It went to android@moneymanagerex.com through PayPal
