### ISSUE TITLE
Automatic credit card repayment

### ISSUE THREAD

**Issue by G-krash** [moneymanagerex/android-money-manager-ex#1375]
Maybe I didn't study the features as extensively as I should have had, but I couldn't find a way to automatically replenish a credit card's balance. 

Consider this, a credit card in its simplest form, allows for a certain credit limit each month, and at a certain period debt accumulated (let's call it **X**) has to be repaid or interest rates will start applying. Automated payments are often provided in-house from banks, drawing funds from the card holder's bank account. 

So, it would be convenient for Money Manager ex to be able to recognize **X** in a recurring transaction and then automatically drawing the amount from a cash account at the end. I hope that the app's infrastructure would allow for such a feature to be implemented without extensive tweaks. 

Optional bonus features would be warnings if the connected account is nearing **X**.

**Comment by siowena** [comment]
Given my bank either runs the credit card statement and hence balance owed on either the 10th or 11th of the month (or 1day of the week if this is a weekend) how would you expect moneymanager to know when the bank has run the statement?

Also, not all transactions you've entered before the date of the statement (e.g. 10th) will be on the statement as sometimes it can take 1-2days between expense and the posting on the CC account.

The best way I've found to do this is have a auto-transaction to transfer from bank to CC but prompt for the amount.
