### ISSUE TITLE
 Support sub sub categories (multiple nested levels)

### ISSUE THREAD

**Issue by ypid** [moneymanagerex/android-money-manager-ex#1376]
Hi,

Applications like GnuCash or KMyMoney can have as many nesting levels of categories as you like. What is the reason to limit it to categories and subcategories only?

**Comment by wolfsolver** [comment]
Now money manager ex in desktop app support nested category with multilevel. Need to manage also on AMME.

**Comment by wolfsolver** [comment]
I try to handle nested category.

Update coming soon

**Comment by wolfsolver** [comment]
> [!CAUTION]
> This is draft concept. Take a look to [My branch](https://github.com/wolfsolver/android-money-manager-ex/tree/one_category_list)

# DRAFT: setup one_category_list using recursive model

[OneCategoryList](https://github.com/moneymanagerex/general-reports/tree/master/packages/Category/OneCategoryList)

# Main Idea
Alter Concept from `Category / SubCategory` into one of
* Use `fullCategoryName / none` in all reference that request to show categories
* Use `CategoryBaseName and ParentCategoriName` if request to handle multilevel

Main Change:
* SQL
	* add one_category_list.sql
	* Alter query_alldata.sql for using recursive category
	* alter query_categorysubcategory.sql for using recursive category
	* alter query_mobiledata.sql for using recursive category
* Java
	* adapt CategoriesReportFragment
	* adapt CategoryRepository
	* adapt CategoryService
	* adapt ViewMobileData

Test execution:
- [ ] Category List
- [ ] Category Edit
- [ ] Category Add - Root
- [ ] Category add - Child
- [ ] Category Delete
- [ ] Report Category
- [ ] Report Income/Expence
- [ ] Search view
- [ ] Transaction List
- [ ] Transaction Edit
- [ ] Transaction Add

Somethigs else?

**Comment by wolfsolver** [comment]
@guanlisheng wuold you try to take a look to my branch? any suggestion?
Does make sense to move into new branch in original repository or I pull request on master (but some feature are missing and need more test)

**Comment by guanlisheng** [comment]
please file a wip PR

**Comment by luisdev** [comment]
Watching this... Looks interesting.

**Comment by ulfranky** [comment]
Just wanted to add that I just ran into that issue. I created the Category structure on the desktop and synced it with the Android phone. Changed some transactions on the phone and did not see all categories with subcategories (multiple levels). Selected the lowest level I can see (first subcategory) but that does not cut it for me. I have to go back to the desktop to select the appropriate subcategory.

**Comment by guanlisheng** [comment]
@wolfsolver , can you help continue Category improvement?

**Comment by wolfsolver** [comment]
Yes. It's one of my goal, I also use subsubsubcategory in desktop version and for now I will create transaction with followup flag in mobile version and then adjust in desktop.
But as you know this require a deep change... And I'm not so good as Android developer ;)

**Comment by wolfsolver** [comment]
new (beta) version of nested category available via PR #1760 
Need to be activate in setting --> beavhiour --> Use nested category
