### ISSUE TITLE
Synchronization conflict - both files have been modified

### ISSUE THREAD

**Issue by rickysaurav** [moneymanagerex/android-money-manager-ex#1378]
I am experiencing the same issue as #1369 
Trying to sync between my computer and my android device fails whenever there's been some changes on my computer, reporting that both files have been modified.

On investigating the database there seems to be a bug where the last modified date of every local database copy changes whenever the app is restarted. The checksums of the database before and after the restart are different  implying that there was definitely some writes on the database.

Nothing in the logcat stands apart from a few queries that happen each restart.
```
V/ 10-31 03:07:17.375 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/QueryBillDeposits
V/ 10-31 03:07:17.375 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/QueryBillDeposits
V/ 10-31 03:07:17.405 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/accountbills
V/ 10-31 03:07:17.405 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/report_income_vs_expenses
V/ 10-31 03:07:17.405 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/accountbills
V/ 10-31 03:07:17.405 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/report_income_vs_expenses
V/ 10-31 03:07:17.425 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/currencyformats
V/ 10-31 03:07:17.426 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/currencyformats
V/ 10-31 03:07:17.453 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/currencyformats
V/ 10-31 03:07:17.453 MmxContentProvider(12330): Querying URI: content://com.money.manager.ex.provider/currencyformats
```
The current workaround seems to be always force pull by reopening remote file again instead of synchronising.

**Comment by firstrose** [comment]
NEVER sync database between desktop version and android version.

When you copy desktop version to your mobile, android-money-manager-ex will create some categories in your database file.

**Comment by grumphus** [comment]
Pretty sad about this when I first discovered the error. I wish there was a simple money management app that supports cloud syncing for both mobile and desktop.
