### ISSUE TITLE
Amount field broken in Search

### ISSUE THREAD

**Issue by gauravjl** [moneymanagerex/android-money-manager-ex#1379]
In Search dialog, 'Amount from' and 'Amount to' fields are not set. If you set these values, they remain empty and are not used for searching.

This has been broken for quite some time now. I recently upgraded to MIUI Global 11.0.5, but it still is broken.

**Comment by luisdev** [comment]
What is MIUI Global?

**Comment by gauravjl** [comment]
MIUI Global is Android OS variant used on Xiaomi devices.
I have moved to Samsung device now with Android 14 installed but the issue is still visible. The issue seems to be irrespective on underlying Android flavor or version.
Steps to reproduce:
1. Click on Search button at top.
2. In Search dialog, enter values in 'Amount from' and 'Amount to' fields. Notice that both fields remain empty even after entering values.
3. Click on Search button at top. Notice that the search results are not filtered based on the amounts entered in 'Amount from' and 'Amount to' fields.

**Comment by wolfsolver** [comment]
Issue is still present in 2023.12.27.

Set value to search field is not working
Example video:

https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/c31dc0a4-6e08-498e-94d1-a7f9be6c1429

**Comment by guanlisheng** [comment]
please have a try on https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.01.01.1008

**Comment by wolfsolver** [comment]
Great. It's ok.

Tested with 2024.01.01 pre release

Also tested search by sub category and work (issue #1487)
