### ISSUE TITLE
Donate page not showing up

### ISSUE THREAD

**Issue by llukee** [moneymanagerex/android-money-manager-ex#1387]
![Screenshot_20200105-181527](https://user-images.githubusercontent.com/31471027/71783498-da060580-2fe7-11ea-9df8-55dd0e20dcd2.png)

I really like this app so I would love to donate, but sadly the donate page through the menu is broken.

And: What about a web version built inside nextcloud?

Best

**Comment by luisdev** [comment]
In version 2023.12.12 (1005) the Donate button takes me to the PayPal page for Alen Siljak. I believe Alen is no longer active in the MMX Android project.

How can the donations function be redone so that donations go to the people who are still actively developing the MMX applications?
