### ISSUE TITLE
Synchronization missing on latest android on f-droid

### ISSUE THREAD

**Issue by erotavlasme** [moneymanagerex/android-money-manager-ex#1389]
Hi,
I'm using the latest version of mmex available in [f-droid](https://f-droid.org/en/packages/com.money.manager.ex/).
The synchronization function does not work. Since I have a rooted phone, I manually copied the database. However, on GNU/linux mmex 1.3.3, many values have payee error.

**Comment by tim-hub** [comment]
yeah, the reason is that android version, payee is optional, but on desktop payee is required, but it supposed to not break your db
