### ISSUE TITLE
Performance improvement suggestion 

### ISSUE THREAD

**Issue by cataloque** [moneymanagerex/android-money-manager-ex#1390]
Dear developers,
When loading images, Google suggests us to cache the bitmaps that can be reused, so as to keep a fluid and fast-loading UI.Android documentation says" The BitmapFactory.decode* methods should not be executed on the main UI thread if the source data is read from disk or a network location (or really any source other than memory)."

I noticed that in the following menthod,  "BitmapFactory.decode*" method was used in UI thread :
(1).com.caverock.androidsvg.SVGAndroidRenderer: android.graphics.Bitmap checkForImageDataURL();
(2).com.caverock.androidsvg.SimpleAssetResolver: android.graphics.Bitmap resolveImage();
(3)com.evernote.android.job.util.support.XmlUtils: android.graphics.Bitmap readBitmapAttribute()

For performance considerations, it is better to move these operations to worker threads (e.g., via AsyncTask).
Could you kindly have a look at this issue? Thanks.

**Comment by nutza249949** [comment]
8
