### ISSUE TITLE
Export and synchronization functions not available

### ISSUE THREAD

**Issue by erotavlasme** [moneymanagerex/android-money-manager-ex#1395]
Hi,
I have installed the latest MMX 2019.02.19.995 from f-droid on android 9 stock and on lineage os 17.1 (android 10).
The export function is not available: Menu->Settings->Databases->Export is grey.
The synchronization function does not work: Menu->Synchronization gives "Invalid remote URI. Please re-open the database".
On lineage os 17.1 with root I can manually copy the data.mmb file (../com.money.manager.ex/files/databases/) while into stock android it is not possible.
How can I solve this?

**Comment by scaidermern** [comment]
Same for me on Android 10 (LineageOS) and Money Manager Ex 2019.04.10. Settings->Databases->Export is greyed out.

**Comment by karenc31** [comment]
Same problem 🤔

**Comment by tim-hub** [comment]
> Same problem 🤔
> Android 10, MMEx Version 2019.04.10.1000-beta
> In addition, the last time I opened the app, my whole database had been cleared and every entry was gone. 😡

same recently
