### ISSUE TITLE
Android file location

### ISSUE THREAD

**Issue by Patricen1** [moneymanagerex/android-money-manager-ex#1398]
**Describe the bug**
Hello,

Using the Android version, i would like to use a database folder location different from default location. I can pick-up a file from another folder, but afterwards mmex stores the database in default folder.
Ils there a way to override this?

Patrice
**To Reproduce**
1. Open a database file from any folder
2. Make any modification
3. The file from original location remains unchanged, modifiés file us stored in mmex default folder

**Expected behavior**

**Screenshots**

**Device Information:**
 - Device: [e.g. LG G7 ThinQ]
 - OS: [e.g. Android 8.1]
 - App Version: [e.g. 22]

**Additional context**

**Comment by tim-hub** [comment]
I recently realised this problem as well. which made loss my half of year data, which is so annoying.

**Comment by vomikan** [comment]
Please report it here:
https://github.com/moneymanagerex/android-money-manager-ex/issues
