### ISSUE TITLE
Playstore link not working anymore.

### ISSUE THREAD

**Issue by aczire** [moneymanagerex/android-money-manager-ex#1399]
The link to playstore https://play.google.com/store/apps/details?id=com.money.manager.ex is not working anymore.

**Comment by Reaper10** [comment]
any news on a fix on this?

**Comment by user8446** [comment]
You can d/l the version you need from F-Droid: https://f-droid.org/en/packages/com.money.manager.ex/

**Comment by Reaper10** [comment]
thanks I loke on google play two

**Comment by akostadinov** [comment]
I was thinking about this. On the one hand I don't want to use google play. But then apps don't gain popularity.

**Comment by Korb** [comment]
The (dead) link to Google Play in the README.md file is still not fixed (removed).

![Screenshot 2022-08-01 at 19-32-02 moneymanagerex_android-money-manager-ex Android version of Money Manager Ex](https://user-images.githubusercontent.com/3509797/182198802-3e07d6c9-9884-4988-8764-181ac5d79133.png)
> We're sorry, the requested URL was not found on this server.

**Comment by user8446** [comment]
I just checked and it's not on F-Droid either. I thought one of F-Droid's advantages was to not go through this - even if an app isn't being maintained it shouldn't just disappear. 

You can d/l a release version from the github releases here: https://github.com/moneymanagerex/android-money-manager-ex/releases

The latest on F-Droid was v2019.04.10.1000-beta which I couldn't find on github so I uploaded it here: https://1drv.ms/u/s!AvkTbCcqh2KdnjFR6ybCGhz0FpDD?e=hfah5S

**Comment by Korb** [comment]
@user8446, I thought this issue was not about the ability to download the application, but about updating the help documentation. Which, with its current appearance, suggests that the project is _(almost)_ dead.

**Comment by Korb** [comment]
The dead link to Google Play in the README.md file is still not fixed or removed.
