### ISSUE TITLE
Money Manager EX Will not open existing large database on Samsung Galaxy TAB A

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/android-money-manager-ex#1404]
Running Android 9 on both Moto G6 Plus and Samsung Galaxy TAB A. Existing database of 7M in size opens fine through Google Drive when accessing with Moto G6 Plus or PC. 
Samsung will create new database but always bombs when opening the same database. I've tried Microsoft One Drive and Drop Box. none work opening this file on the Tablet. Why. Is there a fix?

**Comment by vomikan** [comment]
Please report this issue here:
https://github.com/moneymanagerex/android-money-manager-ex
