### ISSUE TITLE
Add image (receipt) on expense & income

### ISSUE THREAD

**Issue by faizalsb** [moneymanagerex/android-money-manager-ex#1409]
**Is your feature request related to a problem? Please describe.**
 A problem arise when I have to include receipt for my expense and gift for future reference and record.

**Describe the solution you'd like**
User can alternatively upload image(receipt) for payment proof

**Comment by luisdev** [comment]
+1
Voting to keep this open. It would be a nice feature.

**Comment by aarthofer** [comment]
+1

**Comment by MisterEco** [comment]
+1

**Comment by guanlisheng** [comment]
android and desktop would share the same idea https://moneymanagerex.org/docs/features/attachments/

**Comment by guanlisheng** [comment]
android would display the attachment path and preview (if permission ok) since [v2024.04.21](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.04.21.1029)
