### ISSUE TITLE
Calendar for entering date doesn't show 6th row easily

### ISSUE THREAD

**Issue by yaomtc** [moneymanagerex/android-money-manager-ex#1417]
**Describe the bug**
It is a bit difficult to scroll down to just the right position to get May 30th and May 31st to stay on-screen. This month takes up six rows. (My calendar week starts on Sunday.)

**To Reproduce**
1. Create a new transaction.
2. Tap the date to modify.
3. Scroll to May 2021.
4. Scrolling slightly too fast/far brings you to June, and scrolling slightly too slow/short makes the calendar pop back up to show May 1st, hiding May 30-31.

**Expected behavior**
It should not pop back up if there are six rows.

**Screenshots**
![Uploading Screenshot_20210607-212824.png…]()

**Device Information:**
 - Device: Pixel 4a
 - OS: Android 11 (GrapheneOS)
 - App Version: 2019.04.10.1000-beta (F-Droid)

**Comment by yaomtc** [comment]
Just tried latest release, issue is still there on my Pixel 6a. A bit difficult to select December 31st. Workaround can be to select the 30th, hit OK and then arrow right.

**Comment by luisdev** [comment]
Can't you just tap-and-hold the calendar and then scroll up to reveal the 31st?

**Comment by yaomtc** [comment]
It has a tendency to snap to a scrolling position showing one month or the other, so the 31st gets pushed above or below edges of the box.

https://github.com/moneymanagerex/android-money-manager-ex/assets/5534045/e8dd525c-f69f-4556-9526-07e336177988

Testing to get this video was practice so now I've got a better feel for it.

Is this not a custom calendar, some Android provided thing?

**Comment by luisdev** [comment]
The new date picker in 2024.01.04 (1009) looks great!

**Comment by guanlisheng** [comment]
thanks @luisdev
