### ISSUE TITLE
Cryptography APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [moneymanagerex/android-money-manager-ex#1420]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 18 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on android-money-manager-ex (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve android-money-manager-ex's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by vomikan** [comment]
The project has not been developed for about two years.
