### ISSUE TITLE
Add a way to swap the from and to account when transaction type is Transfer

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1421]
Add a way to swap the from and to account when transaction type is Transfer

Describe the solution you'd like
Add new button after the From Account and should swap a/c on click

Ref. for More Info: https://github.com/Money-Manager-SaaS/android-money-manager-ex-fork/issues/16

**Comment by velmuruganc** [comment]
@tim-hub , @MisterY ,

Could you please provide me the access to change the labels and Assignees?

**Comment by BanCrash** [comment]
> Could you please provide me the access to change the labels and Assignees?

Hi @velmuruganc I've see that you are creating commits on your own repository, do you want to continue the development or they are just few contributions that you wanted to make?

I am interested on using money manager ex on Android too, that's why I'm asking.

Regards

**Comment by velmuruganc** [comment]
Hi @BanCrash, I would like to continue the development/contribution to something which can be possible from my side. I am not a core developer, but I started learning development and started contributing to some features that will add value to my day-to-day life.

I started working on this ticket and want to change the label as Bug and assign to myself, but I don't have access. It will be good if I can get the access.

**Comment by vomikan** [comment]
> Hi @BanCrash, I would like to continue the development/contribution to something which can be possible from my side. I am not a core developer, but I started learning development and started contributing to some features that will add value to my day-to-day life.
> 
> I started working on this ticket and want to change the label as Bug and assign to myself, but I don't have access. It will be good if I can get the access.

Could you, please, send a pull request?
