### ISSUE TITLE
Hi @PaulusThe1  - The Android version has not kept pace with the desktop version due to lack of developers able/willing to support it.

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/android-money-manager-ex#1422]
Hi @PaulusThe1  - The Android version has not kept pace with the desktop version due to lack of developers able/willing to support it.

@vomikan I can't seem to transfer the issue to the Android app issue tracker, perhaps you can.

_Originally posted by @whalley in https://github.com/moneymanagerex/moneymanagerex/issues/4163#issuecomment-1028319082_

**Comment by luisdev** [comment]
> Hi @PaulusThe1 - The Android version has not kept pace with the desktop version due to lack of developers able/willing to support it.
> 
Is there any documentation or tracker issues describing the minimum changes that need to be done with the app to make it compatible with the latest version of MMX Desktop, incl the new 1.7 version?
