### ISSUE TITLE
F-Droid build has GMS dep

### ISSUE THREAD

**Issue by linsui** [moneymanagerex/android-money-manager-ex#1425]
**Describe the bug**
It's pulled in by com.evernote:android-job, which is depracated anyway. Could you please use `androidx.work:work-runtime` instead? Thanks!

**Comment by licaon-kter** [comment]
@guanlisheng any news? https://github.com/moneymanagerex/android-money-manager-ex/blob/2023.11.20.999/app/build.gradle#L185

**Comment by guanlisheng** [comment]
not yet thought some of the packages have been updated recently. 

would you please send a PR ?

**Comment by guanlisheng** [comment]
hi @linsui , @licaon-kter ,

just shot a PR to F-droid repo and seems it is okay now.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14340

would you mind taking a look at your convenience ?
