### ISSUE TITLE
Currency conversion stopped working

### ISSUE THREAD

**Issue by bobgmx** [moneymanagerex/android-money-manager-ex#1427]
I'm working with two currencies, transferring funds between accounts, as well as recording expenses.

Previously, the program would autmatically convert the value of currencies being transferred. Recently it just stopped. 

I uninstalled & reinstalled the latest version. I even created a new database for my accounts. Still, no automatic conversion as it did before. I'm going a bit nuts trying to figure out what I may have done wrong. The exchange rates do update when I click the currency icon.

I am using: Version: 1.5.18 64-bit
• Built on Jul 27 2022 22:24:57
• Database version: 7 • (aes128cbc)
• Git commit: 6dba91a (2022-07-28)
--on Windows 10

Any suggestions of what I might do to get it working again would be appreciated.

Thanks very much!
Kind regards,
Robert

**Comment by renato-mmex** [comment]
do not understand, the error occurs now under the **android or the Windows version**.
Also, a screenshot would help a lot

**Comment by vomikan** [comment]
As far as I remember, we chose automatic conversion. You need to specify the amounts manually.
