### ISSUE TITLE
Add support to auto-sync to a cloud provider? 

### ISSUE THREAD

**Issue by Ronkn** [moneymanagerex/android-money-manager-ex#1429]
Would be a nice feature for this to sync to a nextcloud server or other cloud provider, automatically after changes are made. My wife would use the app too so it would be nice the app on other devices notice the change to the database, and refresh itself.

I realize this project is basically dead but just in case it's forked, maybe this will be included?

Thanks to the original author for what you've done so far.

**Comment by colourqueen** [comment]
An older version (2018 11 15 982) does actually sync with OneDrive and DropBox - I still run it for that reason..
However the whole android version is now incompatible with the newest desktop version due to database changes.
