### ISSUE TITLE
Where do o download Android app

### ISSUE THREAD

**Issue by lejothomas** [moneymanagerex/android-money-manager-ex#1431]
Hi

Where do i download the Android app.

I went to Fdroid, google play, etc.

Sorry if I am blind

Lejo

**Comment by whalley** [comment]
You can get the APK here: https://github.com/moneymanagerex/android-money-manager-ex/releases though not sure how useful it is as it's no longer actively maintained and will very likely not work with latest Desktop MMEX DB.

**Comment by guanlisheng** [comment]
hi @lejothomas , going to close the thread
