### ISSUE TITLE
Transfer database from android version to PC

### ISSUE THREAD

**Issue by Myseniortrip** [moneymanagerex/android-money-manager-ex#1432]
I'm trying to transfer my database from my android device to a PC based version. Below is the app version I have.

![Screenshot_20221025-195356_Money Manager Ex](https://user-images.githubusercontent.com/116693540/197909887-c78a5e1b-1ade-4c5b-b5f9-edd5bfd6dffa.jpg)

I can open the database on the current PC version; however I'm getting a debug issue report. How do I correct?
![Uploading 16667460923548657999286964549275.jpg…]()

I'd like to be able to access on my computer and android device, but not sure if that is possible anymore? I completed the bug report but not sure where to go from there?

Blake

**Comment by whalley** [comment]
See.... https://forum.moneymanagerex.org/viewtopic.php?t=10709
