### ISSUE TITLE
Database not opening in Android app

### ISSUE THREAD

**Issue by cmdaniel28** [moneymanagerex/android-money-manager-ex#1437]
**Describe the bug**
The app will not open my database. The database is opening fine on my desktop app and has just been updated, but the app will not open the same file. 

**To Reproduce**
1. Go to 'Menu...'
2. Click on '..Open database'
3. Scroll down to '.Other...'
4. Select file from google drive
5. See error

**Expected behavior**
Usually the database file opens normally and I can use and update the information on the app

**Screenshots**

**Device Information:**
 - Device: Samsung Galaxy A40]
 - OS: Android 11
 - App Version: 2019 02.19.995 (link on Money Manager site does not lead to any other version) 
![Screenshot_20221123-110903_Money Manager Ex](https://user-images.githubusercontent.com/25515125/203533370-92cf6745-d115-467d-98ce-d214aae192f1.jpg)
![Screenshot_20221123-110937_Money Manager Ex](https://user-images.githubusercontent.com/25515125/203533400-10e19635-615d-41a7-aeaa-9c4f892efb5b.jpg)
![Screenshot_20221123-110920_Money Manager Ex](https://user-images.githubusercontent.com/25515125/203533389-31aad23b-9d91-44ce-b9f0-8ceab1421287.jpg)

**Additional context**

**Comment by erottensteiner** [comment]
What version of the desktop app do you use?

**Comment by erottensteiner** [comment]
What version of the windows desktop app do you use? The last version that is compatible with the android port of MMEx is version 1.5.21 - look at https://forum.moneymanagerex.org/viewtopic.php?t=10716

**Comment by cmdaniel28** [comment]
I’m on 1.6.1. Perhaps I need to downgrade. Not sure whether I’ve maybe left it too late to downgrade the database though, so I may just need to live without Android: how long ago was 1.5.21?  Thanks for getting back to me. Christine From: Ernst RottensteinerSent: 27 November 2022 16:04To: moneymanagerex/android-money-manager-exCc: cmdaniel28; AuthorSubject: Re: [moneymanagerex/android-money-manager-ex] Database not opening in Android app (Issue #1437) What version of the windows desktop app do you use? The last version that is compatible with the android port of MMEx is version 1.5.21 - look at https://forum.moneymanagerex.org/viewtopic.php?t=10716—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by guanlisheng** [comment]
@cmdaniel28 , let's try the latest pre-release of android mmex.
