### ISSUE TITLE
Move "discard" to the right-hand side

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#145]
When cancelling the edit of a transaction, the confirmation ("discard" option) should be on the right-hand side of the dialog.

**Comment by MisterY** [comment]
code complete

**Comment by AlessandroLazzari** [comment]
By default, the negative button is to the left and not right.
I am attaching, for example, the AlertDialog of Google Calendar

![image](https://cloud.githubusercontent.com/assets/7428710/7134947/208f80f0-e2a2-11e4-9d94-0208bcc3f27d.png)

**Comment by AlessandroLazzari** [comment]
Android guidelines: http://developer.android.com/guide/topics/ui/dialogs.html

**Comment by MisterY** [comment]
I find that counter-intuitive and always go for the wrong button.
The cases here (http://developer.android.com/design/patterns/confirming-acknowledging.html) always show the confirmation on the right side. I.e. click Cancel -> "do you want to cancel?" -> Yes is on the right. Canceling the option is always on the left.
But true that the calendar example above has it the other way. I'll look for some more cases. There must be a reason that I'm expecting the confirmation to be on the right-hand side. I got used to it by using other apps. Can't be just a personal preference. :)

**Comment by MisterY** [comment]
Yes, see. In the guidelines link you posted, the confirmation of the option is always on the right. ;)

**Comment by MisterY** [comment]
I find that the dialog code also hints to the same. The right-hand option is the "positive" one. For example, for "do you want to cancel editing?" the positive option is "Yes, I want to cancel editing". It is a bit counter-intuitive as there is a cancellation of a cancellation involved.

**Comment by AlessandroLazzari** [comment]
I normally always try to follow the guidelines of google. it isn't always said that this method is correct..

**Comment by MisterY** [comment]
True. In the guidelines, though, the confirming option is on the right-hand side in every single picture. :)
So, what do we do in this case?

**Comment by MisterY** [comment]
Here are some more arguments to convince you :)

http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/

http://www.google.com/design/spec/components/dialogs.html#dialogs-content

http://stackoverflow.com/questions/13644448/android-alertdialog-move-positivebutton-to-the-right-and-negativebutton-on-the-l

http://ux.stackexchange.com/questions/1072/ok-cancel-on-left-right

**Comment by MisterY** [comment]
From the Google design specs (link above):
<quote>
Actions

Dialogs present a focused and limited set of actions, which are generally affirmative or dismissive.

Affirmative actions are placed on the right side and continue the process. Affirmative actions may be destructive, like Delete or Remove.

Dismissive actions are placed directly to the left of affirmative actions and return the user to the originating screen or step in the process.

Dismissive and affirmative action text can be Cancel/OK or can be more specific active verbs or verb phrases that indicate the outcome of the decision.
</quote>

**Comment by AlessandroLazzari** [comment]
:+1:

**Comment by MisterY** [comment]
:)

**Comment by MisterY** [comment]
Thanks!
