### ISSUE TITLE
Not working with encrypted database

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/android-money-manager-ex#1454]
**Describe the bug**
I can't open encrypted databases, however unencrypted databases are working as expected.

**To Reproduce**
1. Create an encrypted database (.emb file)
2. Go to open database and try to open it
3. App will crash

**Expected behavior**
Should ask you to enter the password of the encrypted database.

**Screenshots**

**Device Information:**
 - Device: Xiaomi Redmi Note 10 Pro
 - OS: Android 13
 - App Version: 2023.11.27.1001 (pre-release)

**Additional context**
@guanlisheng let me know if there is something I can do for debug the issue.

**Comment by guanlisheng** [comment]
thanks @BanCrash , the encryption is in the backlog.

**Comment by BanCrash** [comment]
> thanks @BanCrash , the encryption is in the backlog.

Ahh, okay!

**Comment by guanlisheng** [comment]
@BanCrash can you help to test out [the latest pre-release](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.02.26.1020)?

note it supports SQLCipher v4 (AES256) encryption, which is slightly different from the desktop one (AES128).

**Comment by BanCrash** [comment]
> @BanCrash can you help to test out [the latest pre-release](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.02.26.1020)?
> 
> note it supports SQLCipher v4 (AES256) encryption, which is slightly different from the desktop one (AES128).

Sure, tonight or tomorrow, when I have free time, I'll do it.

**Comment by BanCrash** [comment]
> @BanCrash can you help to test out [the latest pre-release](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.02.26.1020)?
> 
> note it supports SQLCipher v4 (AES256) encryption, which is slightly different from the desktop one (AES128).

I've been testing creating a new database since an already created with desktop is not working, I assume that is normal because of what you've said. But the question is, would desktop one get an update to get the new encryption in order to have a full-compatibility among databases?

By the way, one bug that I've found is that when you open a desktop database with android app, it will throw again and again the error "error: file is not a database". I mean, it won't stop showing the same popup until you close the app or switch to another database. I think it should be shown only once.

**Comment by guanlisheng** [comment]
thanks @BanCrash.  SQLCiper may help here to covert it from a plain desktop database if you used it before.

@AlessandroLazzari FYI.  the overall flow does need some polish.

**Comment by guanlisheng** [comment]
@BanCrash, can we close this?

**Comment by BanCrash** [comment]
> @BanCrash, can we close this?

Well, the idea behind was to have a cloud syncronized backup to be able to update the database in both places (desktop and mobile), but I don't know if this should be handled by adding support on the desktop version for the new encription.

**Comment by guanlisheng** [comment]
it will as I replied, and temp target is v1.7.2.
