### ISSUE TITLE
split transaction error creation

### ISSUE THREAD

**Issue by Zeit08** [moneymanagerex/android-money-manager-ex#1464]
**Describe the bug**
I get an error toast message when I create a split transaction (multi category). 3 toasts messages appear, the first is that a error occured in a table to create a split trans. See video.

**Device Information:**
A14, Version 2023.12.01 (not the v18)

https://github.com/moneymanagerex/android-money-manager-ex/assets/45097367/c5eebcfd-137c-4ee2-b627-29da60416801

When I quit from the transaction editing, and I select discard, the transaction has still been saved. but entering the transaction details shows that the amount has not been splitted and the second category is empty

**Comment by guanlisheng** [comment]
@Zeit08 
please have a try on https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2023.12.11.1004
