### ISSUE TITLE
Database Saving

### ISSUE THREAD

**Issue by pdelamotar** [moneymanagerex/android-money-manager-ex#1465]
**Describe the bug**
When I open a database and edit it the changes are not saved in the original file

**To Reproduce**
1. open a data base
2. create any transaction and save
3. go to the file and make a copy then open that copy using ammex

**Expected behavior**
The copy should have the changes from the original file but these are not there, it is as if everything has been saved in another directory that is not Android/data

**Screenshots**

**Device Information:**
 - Device: Samsung A24
 - OS: Amdroid 14
 - App Version: 2022.12.06.1003

**Additional context**

**Comment by guanlisheng** [comment]
hi @pdelamotar, may I have your cloud storage? 

by the way, did you try `menu-> synchronize` after the transaction was saved?

**Comment by pdelamotar** [comment]
With the new version the problem was solved so I proceed to close
