### ISSUE TITLE
IzzyOnDroid inclusion

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/android-money-manager-ex#1468]
@IzzySoft

I think it would be great for this to be included in your repo for the users.

**Comment by IzzySoft** [comment]
See: #1425 

And: No.

```
Offending libs:
---------------
* Google Ads (/com/google/ads): Ads,NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

Doesn't meet the inclusion criteria of my repo either.

**Comment by vladimir-poleh** [comment]
> Google Ads (/com/google/ads): Ads,NonFreeComp

There is no Google Ads.

**Comment by guanlisheng** [comment]
yup, there is no Google Ads.

seems Firebase is not allowed either.

**Comment by luisdev** [comment]
What is IzzyOnDroid?

**Comment by IzzySoft** [comment]
@luisdev that's me – and often used as short-hand for [my repo](https://apt.izzysoft.de/fdroid) (like in this case) or [my Android website](https://android.izzysoft.de/).

**Comment by guanlisheng** [comment]
> See: #1425
> 
> And: No.
> 
> ```
> Offending libs:
> ---------------
> * Google Ads (/com/google/ads): Ads,NonFreeComp
> * Google Mobile Services (/com/google/android/gms): NonFreeComp
> * Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
> * Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
> * Firebase Installations (/com/google/firebase/installations): NonFreeNet
> 
> 5 offenders.
> ```
> 
> Doesn't meet the inclusion criteria of my repo either.

hi @IzzySoft
all 5 offenders have vanished in the master branch would you mind having a check again, thanks

**Comment by IzzySoft** [comment]
Checking the latest release APK:

```
Offending libs:
---------------
* Google Ads (/com/google/ads): Ads,NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

Checking the latest pre-release:

```
Offending libs:
---------------
* Amplitude Android SDK (/com/amplitude): Tracking

1 offenders.
```

OK, that looks much better. Still, sensitive data and tracking don't go well together. How's Amplitude configured? Is it opt-in? Where's data transmitted to?

**Comment by guanlisheng** [comment]
may I have F-droid's policy overall? then I can self-evaluate first.

**Comment by IzzySoft** [comment]
That's on their website. But the topic of this issue is my repo I guess, where the inclusion criteria are slightly different. If Amplitude is not opt-in, it means the `Tracking` anti-feature must be applied. If it's opt-in, it won't apply. This rule is for both, F-Droid's and my repo.

**Comment by guanlisheng** [comment]
hi @IzzySoft , 
with https://github.com/moneymanagerex/android-money-manager-ex/pull/1510,  it's opt-in now 

would you take a look again at your convenience ?

**Comment by IzzySoft** [comment]
Opt-Out is not Opt-In. I'm no Android dev, but to me the code suggests "enable all Tracking, then check if the user has opted out (and if so disable it again)" (lines 149f in the linked code of `MmexApplication.java`). Opt-In would be "check if opted in and only if so enable tracking" – i.e. exactly the other way around.

Don't get me wrong, having the chance to opt out is better than not to. But this means before one can opt out, there's already tracking data sent – which is a clear violation of GDPR (you're only permitted to send with the explicit and informed consent of the user).

**Comment by guanlisheng** [comment]
I am not an Android dev either...

the code only enable tracking when user check the option in the initial run (sure thing,it would be changed at any time)

![Screenshot_20240112_085805](https://github.com/moneymanagerex/android-money-manager-ex/assets/721973/7b6950c0-3f53-48da-97ef-38b3c6f8c54e)

**Comment by IzzySoft** [comment]
Not sure where that screenshot comes from. I've checked the latest release and then even the pre-release. For me, that screen ends with "Default Payee". The "Send anonymous data usage" option is missing. There also was no question for it on the initial run. Yes, after the onboarding the app opened with the settings screen, but as outlined that setting was missing. But the library is there. So are we talking about the same build variant – which results in the APK which is attached to releases?

That said: if it's clearly opt-in and remains a FOSS library (so no proprietary components in), I'd accept AMMX into my repo. I'd need some "metadata" then, like description and screenshots. Ideally in Fastlane structures you maintain, so they are kept up-to-date (my updater would fetch those with each new release then). No need for the Fastlane binaries, I'd just need the text files and the graphics (see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance). Could that be done?

**Comment by guanlisheng** [comment]
https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.01.12.1012 has the screenshot.

still studying the details how to prepare for F-Droid...

**Comment by IzzySoft** [comment]
Confirmed with that release, thanks!

> still studying the details how to prepare for F-Droid...

May I suggest you start with setting up Fastlane structures (for description and screenshots; no need to install its binaries, just the metadata suffice)? You can use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance there. Once set up, just give me a ping and I can immediately include it with my repo.

Apart from that: [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid) is easier to understand than the "official documentation" :wink:

**Comment by guanlisheng** [comment]
many thanks.

I just found https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.money.manager.ex.yml, 
it seems major document preparation is in place, but one critical piece is still #1425,  is that correct?

**Comment by IzzySoft** [comment]
> btw, where can i find the build/verify result from f-droid?

https://monitor.f-droid.org/builds/log/com.money.manager.ex/1013

(so for future builds, you just need to substitute the `versionCode` at the end of that URL). Taken from the current build cycle's [monitor](https://monitor.f-droid.org/builds/running).

**Comment by guanlisheng** [comment]
thank you, @IzzySoft !

**Comment by wolfsolver** [comment]
Finally available on fdroid
https://f-droid.org/packages/com.money.manager.ex/
