### ISSUE TITLE
cannot open database on desktop now I am using the new android release

### ISSUE THREAD

**Issue by BenoitBotton** [moneymanagerex/android-money-manager-ex#1469]
**Describe the bug**
on opening my database on desktop ( v 1.6.4 flatpack on Manjaro Linux and Win11 23H2) I get the following error:
MMEX database version 19 doesn't work with this MMEX version

**To Reproduce**
1. add transaction(s) on android
2. synchronise database
3. go to desktop and open database

**Expected behavior**
open my database on desktop and see the transactions entered on android

**Screenshots**

**Device Information:**
 - Device: Google pixel 6a
 - OS: Android 14
 - Cloud Storage: syncthing
 - App Version: 2023.12.01.1002

**Additional context**

**Comment by pdelamotar** [comment]
you downloaded the one that is compatible with the beta version, you must download the one that ends with "v18"

**Comment by BenoitBotton** [comment]
Yes, I have repaired that now. It would be good to have clear indications
on the release page.
There is nothing indicating it is beta, the other one is marked as v18 so
looked as the'special' one to me

Benoit

**Comment by guanlisheng** [comment]
alternatively, you can upgrade desktop mmex to v1.7 as well.
