### ISSUE TITLE
Database tables missing

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1473]
Hello,

From years I have an error message on the database schema verification.

Two tables are missing SETTING_V1 and USAGE_V1

I don't know how to repair this. But happy to see that devs were resumed for this best money management application.
So perhaps have you an idea of how to repair this.

**Device Information:**
 - Device: POCO M3 PRO 5G
 - OS: Android 13
 - App Version: 2023.12.12 (1005)

**Comment by guanlisheng** [comment]
hi @jeepcook, would you share some screenshots?  especially for database related.

Regarding the two tables missing, I am afraid it might require a manual fix.

**Comment by jeepcook** [comment]
Hi,

Here are the screenshots. This is not a big problem, these messages appear only when I check the database.

![Screenshot_2023-12-15-12-25-06-427_com money manager ex~2](https://github.com/moneymanagerex/android-money-manager-ex/assets/17811804/2e526940-7d5d-4196-9eb1-50a163e30332)
![Screenshot_2023-12-15-12-24-40-376_com money manager ex~2](https://github.com/moneymanagerex/android-money-manager-ex/assets/17811804/e863e4b6-fb4d-4dfc-90ee-3112b53f069f)

**Comment by guanlisheng** [comment]
ok, 

if you are familiar with SQLite3, you can open the database file and execute the following DDL SQL 

1. https://github.com/moneymanagerex/database/blob/master/tables.sql#L448-L454
2. https://github.com/moneymanagerex/database/blob/master/tables.sql#L479-L485


please sync the database after SQLs execution

**Comment by jeepcook** [comment]
Done with sqlite online. Now it's ok, I have no more errors.

Thanks for your support.

**Comment by jeepcook** [comment]
I will close the issue. But just a question, what are the content of these 2 tables ?

**Comment by guanlisheng** [comment]
they are purely used by desktop mmex today. just as the table name says, it is to store some setting and usage data.

**Comment by jeepcook** [comment]
ok thanks
