### ISSUE TITLE
Add a Notes field to the Split Transaction screen

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/android-money-manager-ex#1475]
**Is your feature request related to a problem? Please describe.**
This is not a problem, but rather a "new feature" request.

**Describe the solution you'd like**
When you create a Split Transaction in the MMX Android app, the Split Transaction screen has two sections: the **Category** field and the **Amount** field. Please could a third field called **Notes** be added. This should be a text field where you can capture a note about each item in the split transaction.

**Describe alternatives you've considered**
Not Applicable. Currently you can only add a note on the New Transaction screen. But these are notes for the overall transaction and you cannot use this field to capture notes for a specific category in the split transaction.

**Additional context**
This is a screenshot of the current MMX Andrid split screen:

![Money Manager Ex - CURRENT Split Screen](https://github.com/moneymanagerex/android-money-manager-ex/assets/1124791/c4f5a9d2-baf4-4240-ad26-a7e09354e0f9)

And this is a screenshot of the proposed MMX Andrid split screen with the new Notes field:

![Money Manager Ex - PROPOSED Split Screen](https://github.com/moneymanagerex/android-money-manager-ex/assets/1124791/65938b19-4d54-4680-a78b-71c3e9e99bbd)

**Comment by pdelamotar** [comment]
I think we would also need the labels field since it is also in the desktop beta, which may already be ready for next week

**Comment by luisdev** [comment]
> I think we would also need the tags field since it is also in the desktop beta, which may already be ready for next week

That would be lovely. See #735
