### ISSUE TITLE
Donate screen date display issue

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/android-money-manager-ex#1477]
**Describe the bug**
The date in the copyright notice on the Donate screen is not displayed correctly.

**To Reproduce**
1. Tap on the sandwich icon to open the MMX menu.
2. Tap About
3. Tap Donate
4. See how the date next to the copyright character is displayed: 2012-%1$d. I presume that should be a valid date.

**Expected behavior**
The correct date should be displayed. Instead, you see : 2012-%1$d

![Screenshot_20231222_065138_Money Manager Ex.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/1124791/718d0733-f966-427e-953a-cbf78c1528e8)

**Device Information:**
 - Device: Samsung S22 Ultra
 - OS: Android 13 - One UI 5.1
 - Cloud Storage: OneDrive
 - App Version: 22023.12.12 (1005)

**Additional context**
NA

**Comment by guanlisheng** [comment]
the screen is deprecated.

**Comment by luisdev** [comment]
Deprecated - how?
Has the donations function been retired? If so, shouldn't the Donate button be removed?

In version 2023.12.27 (1007), tapping on the Donate button on my Samsung S22 Ultra device now does nothing.

**Comment by luisdev** [comment]
Linked ussue #1374

**Comment by guanlisheng** [comment]
thanks for pointing this out, and this button clean up would be next step

**Comment by luisdev** [comment]
Just a note, for reference...
See https://github.com/moneymanagerex/android-money-manager-ex/issues/1374#issuecomment-549737489 where [alensiljak] implied that he had retired from the MMX Android project in 2019... So, donations should go to the people that are currently active on the project (like guanlisheng)
