### ISSUE TITLE
Translated texts are not transferred

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/android-money-manager-ex#1488]
translated texts are not taken over from https://crowdin.com/project/android-money-manager-ex/de

**Comment by renato-mmex** [comment]
https://crowdin.com/editor/android-money-manager-ex/4/en-de?view=comfortable&filter=basic&value=0#q=entities
Version: 2024.01.16 (1014)
<img width="353" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/76920138/c4c69a30-3cd4-4c3b-846d-279f2a6a219c">
2024.01.16 (1014)

**Comment by guanlisheng** [comment]
I c

today it is from https://github.com/moneymanagerex/android-money-manager-ex/blob/master/app/src/main/res/values-de/strings.xml#L428

it seems there needs an update from crowdin.
