### ISSUE TITLE
Missing table SETTING_V1 and USAGE_V1?

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1499]
** Bug**
On a new fresh create DB on Desktop, from AMMEX perform "Check DB Schema" under "Setting" -> "Database", show that there are missing table SETTING_V1 and USAGE_V1.

**Expected behavior**
Not sure regarding the correct behavior, seems that this table are not used inside code. Maybe need to be clean from code after V19?

**Comment by n-stein** [comment]
Those tables are the ones in the mmexini.db3 settings database. They are not part of the transaction database.

**Comment by Centsible1** [comment]
Please fix this ASAP because I can't access my financial database.

**Comment by jeepcook** [comment]
Already had an issue about this and fixed, see #1473

**Comment by n-stein** [comment]
> Already had an issue about this and fixed, see #1473

Although adding those tables does resolve this particular issue, the solution is to remove them from `tables.sql` as they should not be part of the transaction database.
