### ISSUE TITLE
Unable to open database on Mixplorer: AMMX vanishes from the screen.

### ISSUE THREAD

**Issue by siddharthagudgunti** [moneymanagerex/android-money-manager-ex#1502]
**Describe the bug**
I have a database shared in my local Samba share. I open the same file from both Windows(11) and Android (v10). Recently moved to MMX v1.7.0 (on windows) and eventually DB is migrated to v19.
Great to see that AMMX got traction and being updated frequently now. So, downloaded the latest 2024.01.05.1010 release apk and installed. Tried to open the latest file (v19) and the AMMX app just vanished from screen. In the recents, I can see the app, and when clicked goes back to first screen of create/open dialog.
Note that, I don't see any error or stack trace on the android.

**Fall back:**
I have been using the v18 for now, with AMMX v1.6.4.

**Device Information:**
 - Device: Redmi Note 7 pro
 - OS: Android 10
 - Cloud Storage: Samba v 1.1
 - App Version: 2023.01.05.1010

**Comment by wolfsolver** [comment]
Do you use an encrypted database?

**Comment by siddharthagudgunti** [comment]
> Do you use an encrypted database?

Nope. Just mmb file. 
Please let me know if there is a way to get stack trace some way in mobile.

**Comment by guanlisheng** [comment]
hi @siddharthagudgunti, 
did you try creating a new database from v2023.01.05.1010 or copy your database file to the phone then open it?

**Comment by siddharthagudgunti** [comment]
> hi @siddharthagudgunti, did you try creating a new database from v2023.01.05.1010 or copy your database file to the phone then open it?

I have the same samba share mapped from mobile (with MixPlorer app) as well as windows laptop, and Open the same file from AMMX.
Once failed to open from mapped drive, I tried following but no success.
1. Copied the mmb file from smb share to internal storage of mobile and tried to open.
2. Tried to create new database file (which gets created), but same failure when try to open the copied file or the remote file.

**Comment by guanlisheng** [comment]
can you share some screenshots that MMEX4Anroid w/ the newly created database file?  e.g.  settings -> database

**Comment by siddharthagudgunti** [comment]
> can you share some screenshots that MMEX4Android w/ the newly created database file? e.g. settings -> database

Sure. 
![Screenshot_2024-01-08-15-49-29-972_com money manager ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/7006840/32fdedfc-273b-4f83-968b-bb63cd2f3b8b)

**Comment by guanlisheng** [comment]
cool.  
the file name in the remote path is 6503?  i think it should be your_data.mmb as well.

Can you manually copy your desktop database file to the above folder and try to open it from MMEX4Android?

**Comment by siddharthagudgunti** [comment]
> cool. the file name in the remote path is 6503? i think it should be your_data.mmb as well.
> 
> Can you manually copy your desktop database file to the above folder and try to open it from MMEX4Android?

Thanks for quick reply.  BTW, I have two questions:
1. Why the remote path is pointing to Documents?
2. I can actually see the your_data.mmb file created in Downloads folder in Internal Memory of mobile. Below screenshot. So, little confused on to which location I should copy this your_data.mmb file? (or specifically my other data file from samba share)?
![IMG_20240108_161214](https://github.com/moneymanagerex/android-money-manager-ex/assets/7006840/f361be8b-a48c-4263-a9d9-e14f696db53c)

**Comment by guanlisheng** [comment]
remote path here is the one you need to copy to.

the two tables missing will not impact the app. whether your mmex4android work properly on your copied database file?

**Comment by guanlisheng** [comment]
if the answer is positive,  would you show me some screenshots of how you open the Samba file from MMEX4Android?

**Comment by siddharthagudgunti** [comment]
> remote path here is the one you need to copy to.
> 
> the two tables missing will not impact the app. whether your mmex4android work properly on your copied database file?

I am able to open locally (internal memory of mobile) copied file. Yes, the missing tables are not impacting operation.

**Comment by guanlisheng** [comment]
that's weird.

anyway, can you try [ammx-2024.01.05-release-v18.apk](
https://drive.google.com/file/d/1q_UJFJEczDvJ0_jdRIXCx9SXhmGz8B2Q/view?usp=sharing)

**Comment by siddharthagudgunti** [comment]
> that's weird.
> 
> anyway, can you try [ammx-2024.01.05-release-v18.apk](https://drive.google.com/file/d/1q_UJFJEczDvJ0_jdRIXCx9SXhmGz8B2Q/view?usp=sharing)

Thanks. Could not check it immediately as I was away from home. Just now tested it. Same result: i.e. If I open the file with Mixplorer the crash happens and opens successfully when use the default filemanager.

**Comment by siddharthagudgunti** [comment]
Well... I am not sure, what more information I can provide. I am successfully able to open the file (remote & local with same Mixplorer) when using the 2023.12.06-v18 version of AMMX, but not using 2024.01.05-v18 or release version of AMMX.
Can you please let me know what all info required?

**Comment by guanlisheng** [comment]
might be something from Mixplorer....as it works well with the default filemanager as expected.

**Comment by siddharthagudgunti** [comment]
> might be something from Mixplorer....as it works well with the default filemanager as expected.

But this problem is not observed when using ammx-2023.12.06-release-v18.apk release package.

**Comment by guanlisheng** [comment]
if possible, you can re-check ammx-2023.12.06-release-v18.apk or ammx-2023.12.06-release.apk with your current phone. 

the two share the exact code on this piece, and you statemented the later had issue either...

**Comment by siddharthagudgunti** [comment]
> if possible, you can re-check ammx-2023.12.06-release-v18.apk or ammx-2023.12.06-release.apk with your current phone.
> 
> the two share the exact code on this piece, and you statemented the later had issue either...

Thanks for giving hints. Now I tried with ammx-2023.12.06-release.apk, and found it to be working OK. However, there was an error message (something on the lines of `not an error`) popped up briefly and went off. So, I took the LOGCAT from about menu. Attached is for your reference. Does it give any hints?
[Subject-1206-releaseapk.txt](https://github.com/moneymanagerex/android-money-manager-ex/files/14164258/Subject-1206-releaseapk.txt)

**Comment by guanlisheng** [comment]
if still not working, i would like to mark Mixplore as known issue here and our major target is to support native file explorer.

**Comment by siddharthagudgunti** [comment]
> if still not working, i would like to mark Mixplore as known issue here and our major target is to support native file explorer.

I tried latest ammx-2024-02-02-release.apk as well as ammx-2023-12-12-release.apk. Seems like I can recreate the issue from 2023-12-12 release one (both v18 and release apks).

Yes please go ahead with your plan. Mine can be just one scenario, I like all other improvements you have done. Thanks.

**Comment by siddharthagudgunti** [comment]
Also, I checked the #1471  merge request it seems some code related to SELECTED_FILE  (app/src/main/java/com/money/manager/ex/home/MainActivity.java line 319) is commented out. Could it be because of that?

**Comment by guanlisheng** [comment]
hi @siddharthagudgunti, 
can you try the latest release again?

**Comment by siddharthagudgunti** [comment]
> hi @siddharthagudgunti, can you try the latest release again?

Tried again with 2024-03-16-release.apk, without success. Same issue which was originally mentioned.  In the meantime, using the 2023-12-06-release.apk successfully.

**Comment by guanlisheng** [comment]
ok.... 
i added the code (you mentioned) back in apk (https://drive.google.com/file/d/1adbTNIsGBawEukogULl_Mppo2f2jAhCH/view?usp=sharing), can you have a try?


seems Mixplore does not support SAF and previous code is to open local file.

**Comment by guanlisheng** [comment]
thanks @siddharthagudgunti,

as we are fully switched to Android SAF,  if it is too difficult, we are inclined to make it as a known issue.

refer to: https://www.esper.io/blog/android-dessert-bites-28-file-manager-loophole-closed-73891524

**Comment by siddharthagudgunti** [comment]
> thanks @siddharthagudgunti,
> 
> as we are fully switched to Android SAF, if it is too difficult, we are inclined to make it as a known issue.
> 
> refer to: https://www.esper.io/blog/android-dessert-bites-28-file-manager-loophole-closed-73891524

Sure. Thanks.

**Comment by guanlisheng** [comment]
closing this as we are going to support SAF only.
