### ISSUE TITLE
Transaction number is set to 1 on new transaction

### ISSUE THREAD

**Issue by gauravjl** [moneymanagerex/android-money-manager-ex#1513]
**Describe the bug**
On creating a new transaction, the Transaction Number field is set to 1. It should be empty.

**To Reproduce**
1. Go to Home.
2. Click on '+'
3. See the value in Transaction Number.

**Expected behavior**
The Transaction Number field should be empty by default. For a user who does not use this field it is tedious to remove the number every time.
Optional: Provide a setting to control if this field should be auto-increasing value or empty.

**Device Information:**
 - Device: Samsung A52s 5G
 - OS: Android 14
 - Cloud Storage: OneDrive
 - App Version: 2024.01.05

**Comment by guanlisheng** [comment]
thanks @gauravjl for reporting this. it was on purpose to solve https://github.com/moneymanagerex/android-money-manager-ex/issues/1405

you are not alone and we have similar reports in the project forum https://forum.moneymanagerex.org/viewtopic.php?t=10983

your suggestion makes sense and will consider it in the coming release or pre-release.

**Comment by guanlisheng** [comment]
hi @gauravjl , please have a try https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.01.12.1012

**Comment by gauravjl** [comment]
This works now.
Tested with 2024.01.12 (1012) pre release
