### ISSUE TITLE
Notification missing PendingIntent.FLAG_IMMUTABLE

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1519]
Try to restore notification by add PendingIntent.FLAG_IMMUTABLE

**Comment by guanlisheng** [comment]
hi @wolfsolver , as you are going to fix this and a PR would be sufficient to avoid dup github issues.

**Comment by wolfsolver** [comment]
@guanlisheng just a question is the code in app/src/main/java/com/money/manager/ex/sync/SyncNotificationFactory.java still used? 
Anyway I change it to be compliance with R.String and have channel name and description as language depending.
