### ISSUE TITLE
Display credit limit on credit card accounts

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#152]
This could also include a visual representation of the credit amount in terms of percentage of the credit limit, perhaps on the dashboard.
It is an important concept for credit card accounts.

Related issue at the desktop version: https://github.com/moneymanagerex/moneymanagerex/issues/451

**Comment by AlessandroLazzari** [comment]
:+1:

**Comment by MisterY** [comment]
The data schema has been adjusted to support this. https://github.com/moneymanagerex/database/pull/16

**Comment by MisterY** [comment]
There is a field CreditLimit now.
