### ISSUE TITLE
Remote immediate synchronization issue

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1525]
The parameter's synchronization "load the database immediately after a change" seems to not working correctly.

In fact if I do a modification, new operation for example, the database /Android/data/com.money.manager.ex/files/databases/comptes.mmb is updated immediately (verification done with adb shell). But the remote database isn't updated. 
I have to close and to reopen ammex to have a new backup of the database on the remote server. In fact, I think this action is done by the parameter "synchronization at startup".

So the parameter "load the database immediately after a change" isn't correctly functional.

Ask me if you want I do some other tests.

Thanks

**Device Information:**
 - Device: POCO M3 Pro 5G
 - OS: Android 13 / Miui 14
 - Cloud Storage: gDrive
 - App Version: 2023.01.12 1012

**Comment by pdelamotar** [comment]
I also had that problem for some reason it doesn't sync immediately, but after a while, I think what really works is synchronization every so often

**Comment by guanlisheng** [comment]
this immediate sync has a flaw and will hide the option in the next release(s) to reduce noises.

**Comment by jeepcook** [comment]
> this immediate sync has a flaw and will hide the option in the next release(s) to reduce noises.

Why disable rather than fix. Immediate synchronization allows you to switch from the Android version to the PC version without delay.

**Comment by guanlisheng** [comment]
as less is more
