### ISSUE TITLE
Load only needed currencies on startup

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#153]
If we would load only the currencies used in the currently filtered accounts, would this help performance? Memory usage might be smaller as there are too many currencies and probably nobody ever would use all of them (except on the currencies list screen). Hopefully this would also help speed up the application startup.
<s>This is just a guess at the moment. Any opinions?</s>

Note: Load single currency when required and use the currency utils as the cache?

**Comment by AlessandroLazzari** [comment]
You want to change the class CurrencyUtilis, by loading only the currencies of the accounts in the database?

**Comment by MisterY** [comment]
Yes, something like that. I'm wondering if we need to load all the available currencies when, in general, most people will use a few at most.
I am not sure what impact does this have on performance. When I have some time, I can try to implement an option to load only a few currencies and see if that makes a difference. I'd like to see your opinion.

**Comment by MisterY** [comment]
What I mean is to load only needed currency at any one time. For the Currencies list we load all. But for Dashboard we load only the ones used in visible accounts, needed to calculate totals. And so on.

**Comment by MisterY** [comment]
After this change, it would be good to clear the static list of currencies once they have been loaded in the Currencies screen, to get the memory back.

**Comment by MisterY** [comment]
The currencies are now cached as needed.
