### ISSUE TITLE
New notes field in split transaction shows "Notes" text

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/android-money-manager-ex#1530]
**Describe the bug**
When you create a new split transaction in 2024.01.16 (1014) , the Split Transaction screen contains the "Notes" text in the new  Notes field. This field should be blank by default. That "Notes" string is not necessary.

**To Reproduce**
1. Create a new transaction.
2. Click the icon to create a split transaction.
3. Look in the Notes field. It shows the word "Notes". 
4. Add another category to the split. It also shows the "Notes" string in the Notes field.
5. Tap on the Notes field. That "Notes" string dissappears, allowing you to enter your own note.

**Expected behavior**
The Notes field should be blank by default. It shouldn't contain the "Notes" text. It is not necessary - the field label already says "Notes". Repeating it in the field is superfluous.

But THANK YOU for adding this new Notes field!

**Screenshots**
![Screenshot_20240117_051449_Money Manager Ex.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/1124791/6ea97a06-a0a0-4817-8155-4f7d2ca937a3)

**Device Information:**
 - Device: Samsung S22 Ultra
 - OS: Android 13
 - Cloud Storage: N/A
 - App Version: 2024.01.16 (1014)

**Additional context**
N/A

**Comment by wolfsolver** [comment]
This is standard behaviour. Note is in gray and is a placeholder exactly as payee
![Screenshot_20240120-221629-557.png](https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/3537dc80-6c86-4b27-b966-b7533e8c5aeb)

**Comment by guanlisheng** [comment]
agreed.

@luisdev can you help to close the issue if there is no outstanding issue

**Comment by luisdev** [comment]
> This is standard behaviour. Note is in gray and is a placeholder exactly as payee ![Screenshot_20240120-221629-557.png](https://private-user-images.githubusercontent.com/3205448/298308037-3537dc80-6c86-4b27-b966-b7533e8c5aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTE4NTMsIm5iZiI6MTcwNjE5MTU1MywicGF0aCI6Ii8zMjA1NDQ4LzI5ODMwODAzNy0zNTM3ZGM4MC02Yzg2LTRiMjctYjk2Ni1iNzUzM2U4YzVhZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjljZGFjNjdkOGE5ZDdhMDg3NmY0YjExNjIxOGY1YTk0NjFjYjgyNzkyZmE2OTViY2NkNzgwMjgzZGQ0ZjZkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xpY2N7EzaGj1uYYQtNYTOj5aH2690V0bOpECJgcYoJ8)

Yes, on this screen it's ok to show the "Note" string because there isn't a "Note" label - it's just the icon.

But on the Split Screen window there are no icons - it uses the words, so the "Notes" string is duplicated:
![Screenshot_20240125_161035_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/1124791/5bdd4eba-3e3e-46f3-af52-f0733c6de9fd)
To me it seems a bit repetative to show the "Notes" string twice - **on the Split Transaction screen**.

**Comment by wolfsolver** [comment]
You would prefer "insert a note"?
Same behaviour of category, where there is "select category"

**Comment by luisdev** [comment]
Ok, "insert a note" would work too.

**Comment by luisdev** [comment]
The fix done in #1569 looks good. Thanks for fixing this.
