### ISSUE TITLE
Search Error in reports 

### ISSUE THREAD

**Issue by m4nuel89** [moneymanagerex/android-money-manager-ex#1532]
Hallo, the search doesn't work when:

1. Go to "reports"
2. Click on "where the money goes"
3. Time "last year"
4. Click on something 
5. See error (nothing)

When you start the search with the same parameters. It works.

 - App Version: 2024.1.16

Thanks.
BR
Manuel

**Comment by guanlisheng** [comment]
@wolfsolver , can you help to take a look?

**Comment by wolfsolver** [comment]
Seems that report search for only first category and not for subcategory. I'll try to take make root cause analysis in the weekend.
