### ISSUE TITLE
currency comma issue

### ISSUE THREAD

**Issue by Flexmaen** [moneymanagerex/android-money-manager-ex#1534]
**Describe the bug**
This affects the windows version as well as android:

On the desktop:
1. In the Settings (Extra/Options/General) set "de_DE" as currency format, wich will be 1.234.567,89
2. create a new bank account with 1500,50 which will turn into 1.500,50
3. right click bank account and select "edit account"
4. for example, value there is "1.500,50" you want to change it to "1.580,90"
5. delete last 4 numbers, start typing. You cannot type a comma anymore (,) since the point (.) is mistaken for a comma.

On Android:
- copy your mms file from PC to your Android device
- after opening, numbers still will be shown with . instead of , as comma.

**Comment by wolfsolver** [comment]
hi @Flexmaen can you share a test mmb?

**Comment by wolfsolver** [comment]
Understand! seems that LOCALE setting or Currency setting is not used in app and value is allway shown (anywhere) . @guanlisheng have any suggestion?

**Comment by Flexmaen** [comment]
> hi @Flexmaen can you share a test mmb?

There you go:
[test.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/13999406/test.zip)

Are the locale settings in the mmb?
But since this also seems to be an issue of the desktop app should I file a bug there too?

**Comment by Flexmaen** [comment]
Is this fixed already?
