### ISSUE TITLE
New update (2024.01.13) can't open old database (2019.02.24)

### ISSUE THREAD

**Issue by jorgeEF** [moneymanagerex/android-money-manager-ex#1543]
Hi, I just updated to latest version and at the first launch it just could open up the db I've been using since few years.

**To Reproduce**
1. Update to latest release
2. Launch money manager ex
3. It offers to create a new account while showing errors that old db can't be loaded

**Expected behavior**
Load my years old db as usual.

**Screenshots**
![Screenshot_20240125_234450_Money Manager Ex.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/44306359/4213e6af-5064-4cc8-91c5-8b5ebb1a5479)

![Screenshot_20240125_234441_Money Manager Ex.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/44306359/798b3dfc-915c-44b2-95e9-31e28c11d6b1)

**Device Information:**
 - Device: Samsung A34
 - OS: Android 14
 - Cloud Storage: 
 - App Version: 2024.01.13

**Comment by Centsible1** [comment]
When I check the integrity of the database in the newest version it says, "Tables missing in database". This seems to be the reason I can't open my database in this new version of your app. Please fix ASAP because I can't access my database to see it.

**Comment by jorgeEF** [comment]
I've luckily had a backup of my db.
I manage to load the backup.into.de.new version without any problem, but the old db that the new version couldn't open at the beginning it when corrupt without any chance to fix it.

**Comment by guanlisheng** [comment]
@Centsible1 and @jorgeEF , can you share what's the old version.

**Comment by jorgeEF** [comment]
> @Centsible1 and @jorgeEF , can you share what's the old version.

https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2019.02.14.994 or 2019.02.24.1 that isn't listed anymore...

**Comment by guanlisheng** [comment]
That's a little bit old. 
I can manually fix/upgrade the old db if you share it with me.

**Comment by jorgeEF** [comment]
> That's a little bit old. 
> I can manually fix/upgrade the old db if you share it with me.

Well.. that's the last official version until end of 2023 where development returned, most MMex users are probably still on that version.
I don't need to fix my db now, I managed to load it into the new version but just after a couple of attempts because I had a backup. If attempt fails it corrupts the db.. I suggest you to look into it because people that didn't upgrade yet are probably gonna end with a corrupted db that won't load on the old version neither.

**Comment by guanlisheng** [comment]
Great.  I think there are backups in the cloud storage by default.

can you share the detailed experiences or best practices for such an upgrade? this will benefit many guys.

**Comment by jorgeEF** [comment]
> Great.  I think there are backups in the cloud storage by default.
> 
> can you share the detailed experiences or best practices for such an upgrade? this will benefit many guys.

1. Check integrity and fix any db inconsistency before upgrade.
2. Backup db
3. Uninstall MMex v2019
4. Install latest MMex 2024 version
5. Load backed up db.

Important: do not upgrade from 2019 to 2024 directly as it will probably corrupt your db.

**Comment by wolfsolver** [comment]
Or you can use desktop version for upgrade...

**Comment by guanlisheng** [comment]
@Centsible1 , did the above help?
