### ISSUE TITLE
App animations and transitions should be disabled when disabled in the OS

### ISSUE THREAD

**Issue by tomasz1986** [moneymanagerex/android-money-manager-ex#1545]
**Is your feature request related to a problem? Please describe.**

Currently, the app doesn't follow the OS settings regarding disabling animations and transitions (e.g. using the accessibility options in the Android settings).

**Describe the solution you'd like**

The app should follow the OS settings, e.g. if animations have been disabled in the Android accessibility settings, then there should be no animated transitions in the app.

**Describe alternatives you've considered**

At the moment, there doesn't seem to be any workaround for the problem.

**Additional context**

I'm sensitive to animated transitions (i.e. they can make me dizzy), so I always try to disable them whenever possible.

Tested with Money Manager Ex version 2024.01.23.

**Comment by guanlisheng** [comment]
thanks @tomasz1986 for reporting this.  would you mind sharing a screen video to demo the animations?

**Comment by tomasz1986** [comment]
> thanks @tomasz1986 for reporting this. would you mind sharing a screen video to demo the animations?

I haven't had the time to do the recording, but I see that you've fixed the issue anyway! Thank you very much. I'm going to test it once it gets released and report back if there are any problems.
