### ISSUE TITLE
 Account types available on Desktop are different to Android app

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/android-money-manager-ex#1551]
**Describe the bug**
User [Bobb](https://forum.moneymanagerex.org/memberlist.php?mode=viewprofile&u=45594) reported the following issue in the Android and Desktop forums.
See the posts here:
https://forum.moneymanagerex.org/viewtopic.php?t=10988
https://forum.moneymanagerex.org/viewtopic.php?t=10987

**To Reproduce**
I've seen the update Android update 2024.01.10 (1011) on Facebook and downloaded it.

First response, very happy with the improving software, a credit to ALL developers - THANK YOU!

I have noticed a couple of differences between Android and Windows apps, and terminology affects how entries in accounts are displayed, if at all.

Windows version 1.7.0 64 bit
Account types available

Cash
Checking
Credit card
Loan
Term
Asset
Shares

Android 2024.01.10 (1011)
Account types available

Cash
Checking
Investment
Term
Credit card
Loan
Shares

In the Windows version I have listed my house under assets,. and I can see the entry in Account view. However, on Dashboard view Assets are '0'

When I open the updated file created in Windows, in the Android version the Account House appears as an asset in Home (Dashboard), but when I open the account I don't get the details of the asset, it opens one of my Bank Accounts. I assume its an issue with the links between Asset and Investment etc., and the different account types across the two platforms.

**Comment by guanlisheng** [comment]
thanks, @luisdev, and I believe you can also fix the issue. btw, can you rename the issue name to better desc the issue (and to avoid the misleading as well).

**Comment by luisdev** [comment]
Thanks @guanlisheng, but I just copied and pasted the message from the forum. I didn't experience the problem myself.
Are you saying that this is a MMX setup issue, not a bug?

**Comment by guanlisheng** [comment]
great to reproduce and understand the issue. this might be a  good opportunity for you

**Comment by guanlisheng** [comment]
hi @luisdev , i think it is configured here and can you have a look?
https://github.com/moneymanagerex/android-money-manager-ex/blob/master/app/src/main/res/values/arrays.xml#L76-L84

**Comment by guanlisheng** [comment]
Your guess is almost right and you can verify it by making changes.  
we expect you can help to resolve this issue if you are willing
