### ISSUE TITLE
Budget screen crashes

### ISSUE THREAD

**Issue by gauravjl** [moneymanagerex/android-money-manager-ex#1553]
**Describe the bug**
On clicking on a year in the budgets list the app crashes

**To Reproduce**
1. Go to Budgets list
2. Click on a year

**Expected behavior**
Budget should be displayed for the clicked year.

**Device Information:**
 - Device: Samsung A52s
 - OS: Android 14
 - Cloud Storage: Onedrive
 - App Version: 2024.02.02.1017

**Screenshot**
![Screenshot_20240204_130724_Money Manager Ex.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/16308065/91395bfb-16c2-4748-a8c3-59c055249225)

**Comment by guanlisheng** [comment]
hi @gauravjl, thanks for reporting this issue.

can you share more logs or data if possible as we can't reproduce the issue.

**Comment by gauravjl** [comment]
I am getting 'Error: Failure from system' on clicking Logcat button. I will try to get logs later.

One thing to note, I have not created  budget for 2024. When I click on a budget year the app either crashes or goes back to the Home screen.

**Comment by guanlisheng** [comment]
thanks.
Maybe you can try it with MMEX4Destkop, as the two are compatible and your data is on oneDrive.  i suspect it was due to some dirty data

**Comment by gauravjl** [comment]
Here are the logs ay Error level.

E/ 02-04 17:04:19.565 oney.manager.ex( 9392): Not starting debugger since process cannot load the jdwp agent.
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): FATAL EXCEPTION: main
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): Process: com.money.manager.ex, PID: 9392
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.money.manager.ex.domainmodel.Category.getParentId()' on a null object reference
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.money.manager.ex.datalayer.BudgetEntryRepository.loadForYear(BudgetEntryRepository.java:99)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.money.manager.ex.budget.BudgetAdapter.populateThreadCache(BudgetAdapter.java:249)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.money.manager.ex.budget.BudgetAdapter.setBudgetYearId(BudgetAdapter.java:201)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.money.manager.ex.budget.BudgetDetailFragment.setUpAdapter(BudgetDetailFragment.java:143)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.money.manager.ex.budget.BudgetDetailFragment.onCreateView(BudgetDetailFragment.java:105)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at android.os.Handler.handleCallback(Handler.java:958)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at android.os.Looper.loopOnce(Looper.java:230)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at android.os.Looper.loop(Looper.java:319)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at java.lang.reflect.Method.invoke(Native Method)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/ 02-04 17:04:49.438 oney.manager.ex(14996): Not starting debugger since process cannot load the jdwp agent.
E/ 02-04 17:04:53.593 chromium(14996): [ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
E/ 02-04 17:05:17.230 NotificationUtils(14996): Unable to found resourceId: [notification_channel_fileoperation_conflict__description]
E/ 02-04 17:05:17.230 NotificationUtils(14996): java.lang.NoSuchFieldException: No field notification_channel_fileoperation_conflict__description in class Lcom/money/manager/ex/R$string; (declaration of 'com.money.manager.ex.R$string' appears in /data/app/~~zrt9m8A_3UZ397uDiqMvXA==/com.money.manager.ex-hSeMrhsgYaIiVOSXrKY4hQ==/base.apk!classes2.dex)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at java.lang.Class.getDeclaredField(Native Method)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at com.money.manager.ex.utils.NotificationUtils.createNotificationChannel(NotificationUtils.java:72)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncNotificationFactory.getNotificationForConflict(SyncNotificationFactory.java:160)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncService.showNotificationForConflict(SyncService.java:357)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncService.triggerSync(SyncService.java:299)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncService.onHandleWork(SyncService.java:139)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ 02-04 17:05:17.230 NotificationUtils(14996): 	at java.lang.Thread.run(Thread.java:1012)
E/ 02-04 17:05:17.231 NotificationUtils(14996): Unable to found resourceId: [notification_channel_fileoperation_conflict__description]
E/ 02-04 17:05:17.231 NotificationUtils(14996): java.lang.NoSuchFieldException: No field notification_channel_fileoperation_conflict__description in class Lcom/money/manager/ex/R$string; (declaration of 'com.money.manager.ex.R$string' appears in /data/app/~~zrt9m8A_3UZ397uDiqMvXA==/com.money.manager.ex-hSeMrhsgYaIiVOSXrKY4hQ==/base.apk!classes2.dex)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at java.lang.Class.getDeclaredField(Native Method)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at com.money.manager.ex.utils.NotificationUtils.createNotificationChannel(NotificationUtils.java:72)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncNotificationFactory.getNotificationForConflict(SyncNotificationFactory.java:160)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncService.showNotificationForConflict(SyncService.java:357)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncService.triggerSync(SyncService.java:299)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at com.money.manager.ex.sync.SyncService.onHandleWork(SyncService.java:139)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ 02-04 17:05:17.231 NotificationUtils(14996): 	at java.lang.Thread.run(Thread.java:1012)
E/ 02-04 17:06:04.610 chromium(14996): [ERROR:page_load_metrics_update_dispatcher.cc(179)] Invalid first_paint (unset) for first_image_paint 1.238 s
E/ 02-04 17:06:04.721 chromium(14996): [ERROR:page_load_metrics_update_dispatcher.cc(179)] Invalid first_paint (unset) for first_image_paint 1.238 s
E/ 02-04 17:06:13.349 oney.manager.ex(28976): Not starting debugger since process cannot load the jdwp agent.
E/ 02-04 17:06:22.150 chromium(28976): [0204/170622.150031:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
E/ 02-04 17:07:15.057 oney.manager.ex( 3803): Not starting debugger since process cannot load the jdwp agent.
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): FATAL EXCEPTION: main
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): Process: com.money.manager.ex, PID: 3803
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.money.manager.ex.domainmodel.Category.getParentId()' on a null object reference
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.money.manager.ex.datalayer.BudgetEntryRepository.loadForYear(BudgetEntryRepository.java:99)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.money.manager.ex.budget.BudgetAdapter.populateThreadCache(BudgetAdapter.java:249)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.money.manager.ex.budget.BudgetAdapter.setBudgetYearId(BudgetAdapter.java:201)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.money.manager.ex.budget.BudgetDetailFragment.setUpAdapter(BudgetDetailFragment.java:143)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.money.manager.ex.budget.BudgetDetailFragment.onCreateView(BudgetDetailFragment.java:105)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at android.os.Handler.handleCallback(Handler.java:958)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at android.os.Looper.loopOnce(Looper.java:230)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at android.os.Looper.loop(Looper.java:319)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at java.lang.reflect.Method.invoke(Native Method)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/ 02-04 17:07:50.469 AndroidRuntime( 3803): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/ 02-04 17:07:50.577 oney.manager.ex( 6092): Not starting debugger since process cannot load the jdwp agent.
E/ 02-04 17:07:53.327 chromium( 6092): [0204/170753.327647:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
E/ 02-04 17:07:53.328 chromium( 6092): [0204/170753.328054:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
E/ 02-04 17:07:53.400 cr_TrackExitReasons( 6092): Failed to parse JSON from file.

**Comment by guanlisheng** [comment]
thanks @gauravjl ,

this exception shows there is a problematic category in table `BUDGETTABLE_V1`. 

can you try the sample database file through MMEX4Desktop? 
meanwhile, MMEX4Android will add some protection code to enhance the robustness. 

> E/ 02-04 17:04:19.565 oney.manager.ex( 9392): Not starting debugger since process cannot load the jdwp agent.
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): FATAL EXCEPTION: main
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): Process: com.money.manager.ex, PID: 9392
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.money.manager.ex.domainmodel.Category.getParentId()' on a null object reference
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): at com.money.manager.ex.datalayer.BudgetEntryRepository.loadForYear(BudgetEntryRepository.java:99)
E/ 02-04 17:04:48.834 AndroidRuntime( 9392): at
