### ISSUE TITLE
Category entries appear incorrectly, and differently, in the Transaction list and in the Recurring Transaction list

### ISSUE THREAD

**Issue by bquinlan** [moneymanagerex/android-money-manager-ex#1558]
In the main list of transactions, any entry without a Sub-Category appears with the Category name repeated.  For example:
Gifts Given : Gifts Given

In the list of Recurring Transactions, any entry without a Sub-Category appears with "null" as the primary Category.  For example:
null : Gifts Given

To reproduce in the Transaction list:
Create a new Transaction and specify a Category without a Sub-Category.

To reproduce in the Recurring Transactions list:
Create a new Recurring Transaction and specify a Category without a Sub-Category.

Expected Behavior:
Any Category without a Sub-Category should appear with just the Category name.  It should not be preceded by another copy of the same Category name or by "null".  For example:
Gifts Given

Screenshots of each screen are attached:
![Screenshot_20240204_185553_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/182284/61bf263f-ddf6-4919-9325-1981f08c40ad)
![Screenshot_20240204_185608_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/182284/50a59089-d493-46fe-a4c7-ce58a4acde68)

Device: Samsung Galaxy S23 Ultra
OS: Android 14
App Version: 2024.01.23 (1016)

**Comment by guanlisheng** [comment]
thanks @bquinlan for reporting this.

as the first step, we will unify both for consistency purposes which will be available from the next release 

the furture action will be performed based on resource.
