### ISSUE TITLE
Move option to open database into the settings

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#156]
In the Database Settings screen.

Add an option to open database. As this is probably not such a frequent operation, we could remove it from the drawer?

**Comment by prannou** [comment]
I agree. I think this is not often used and could be moved to the settings.

**Comment by AlessandroLazzari** [comment]
I am not very agree, however, if you consider it more correct, you can proceed. I can't tell you the number of users who use it, but I think they are different users that use this feature.
If you proceed with the implementation, enter a note in the changelog of the displacement of the feature.

**Comment by MisterY** [comment]
If you have any concerns I'd rather not implement at the moment. There are better things to add in the meantime.
Sooner or later we will run out of space in the drawer so we can revisit this then.

**Comment by AlessandroLazzari** [comment]
How do you prefer? It is the same for me! For version 2.0, since we have
already changed so many things, I wouldn't go to change this.
But as I wrote above, if appropriate, you may proceed.

**Comment by MisterY** [comment]
Let's leave it for the moment. Does not make much difference right now.

**Comment by MisterY** [comment]
This feature did not make sense in the older versions as the users could not navigate to the app storage to see the databases. Now, with external storage being the default, it makes more sense.
What we are missing is #70, the option to create a new db from within the app.
