### ISSUE TITLE
A couple of useful features for MoneyManagerEX

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1572]
Hi,

I've used MoneyManagerEX on Android for years and wonder if the following features could be considered:

1) Under Look and Feel can the light dark theme update automatically with the phone?

2) Is it possible to set up a feature for Recurring Transactions to enter them automatically on the day they are set to trigger rather than issue a notification?

3) Give the option to move the app database cache and/or the remote file location?

4) Give the ability to switch on and off Biometric use.

5) Make the Passcode entry buttons bigger.

6) Have ability to tweak the lock out timings (e.g. after so long of inactivity or after going to different app)

Hope some of these can make it into future releases

Cheers

**Comment by guanlisheng** [comment]
thanks @smjohns .
can you share what's your current mmex details, saying version and devices

**Comment by smjohns** [comment]
HI. I am running 2024.02.02  (1017) on a Samsung S22 running latest genuine Android 14 update.

**Comment by guanlisheng** [comment]
thanks.  did you enable sending usage data?

**Comment by smjohns** [comment]
I hadn’t but have now :)

**Comment by guanlisheng** [comment]
hi @smjohns , 
today we can choose(to be accurate: open) remote file location, and the cache is still within app's private storage.
- [ ] 3, Give the option to move the app database cache and/or the remote file location?

**Comment by smjohns** [comment]
Item 2 has now been implemented but the others are yet to be discussed / progressed.

**Comment by wolfsolver** [comment]
Item 2 also improved with PR #1742

**Comment by wolfsolver** [comment]
> Item 2 has now been implemented but the others are yet to be discussed / progressed.

I think is better to split this issue into many issue so each one can be solved with specific thread
