### ISSUE TITLE
Passcode Keypad Not working after cancelling biometric

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1573]
**Describe the bug**
If you cancel out of entering biometric either on opening the app or changing the passcode, the app displays a keypad but this fails to work. The reason is that the cursor is not automatically being moved to the first field. When you manually select the first field, the default keyboard covers the numbers keypad. 

**To Reproduce**
1) Launch Money with passcode set up.
2) Cancel Biometric
3) try to use keypad to enter code. (It does nothing).
4) Select first keypad blank field (virtual keyboard appears she covers keypad)

**Expected behavior**
It would be great if on cancelling the biometric, the cursor defaults to the first field  so the keypad can be used.

**Screenshots**
Will try to attach

**Device Information:**
 - Device: Samsung S22
 - OS: Android 14 (Jan Security Patch)
 - Cloud Storage: N/A
 - App Version: 2024 02 02 1017

[Screenshot_20240213_221149_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/2214c632-0b3d-4ad6-bba4-c884e5090fe0)

**Additional context**

**Comment by smjohns** [comment]
Other screenshot
![Screenshot_20240213_221212_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/2f08e3c7-b659-40a8-9990-d7483533c343)
![Screenshot_20240213_221221_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/74803811-d11e-4b2d-bbdb-ff4110dd7133)

**Comment by guanlisheng** [comment]
Hi @smjohns , 
thanks for using mmex4android. this issue has been addressed and a quick fix is on the way.

as a workaround in your case, you can click inverse triangle (v) to quite system input and use MMEX's one.
