### ISSUE TITLE
Database synchronization error message

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/android-money-manager-ex#1588]
MMEX Version 2024.02.08 (1018)
Android 10

My .mmb is located on my Windows 11 computer and is provided via a share with the CIFS document provider under Android 10.
The database can be loaded and edited without any problems, but the synchronization is confirmed first:
`Both the local database and the database in the online storage have been modified!`
But then this error message appears
<img width="391" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/76920138/f95bbb4a-4f93-48e8-8134-9325b6961209">

and the original database is not modified.

**Comment by guanlisheng** [comment]
can you show the mtime for each to see whether it is modified?  also a step list to reproduce it if possible.

**Comment by renato-mmex** [comment]
I have done many different tests and could not find the cause.
After setting up the CIFS connection again, this message no longer appeared.
I did not test with 1019 because it is not available under F-Droid.

But I did find a few problems:
a) if I switch from one database to another, the now open database is displayed, but not synchronized. After a restart of MMEX it works. Apparently the flags for synchronization are not reset when the database is changed.
b) if I change an account title, I cannot perform the synchronization. It should be possible to perform a manual synchronization at any time.
c) sometimes MMEX aborts when opening and synchronizing a database without an error message.
d) during synchronization I get the message "Both the local database and the database in the online storage have been modified!" but the wheel in the header still turns for a long time, sometimes minutes.

**Comment by guanlisheng** [comment]
thanks for the details. @wolfsolver, would you help to take a look as well?

**Comment by guanlisheng** [comment]
hi @renato-mmex , the [apk in the google drive](https://drive.google.com/file/d/1adbTNIsGBawEukogULl_Mppo2f2jAhCH/view?usp=sharing) should resolve all about the issues. please have a try.

all these fix will go to next release (1022) soon .

**Comment by renato-mmex** [comment]
the answer from CIFS:
No, CIFS Documents provider don't has the message.
I think the message is displayed by Money Manager Ex.

https://github.com/wa2c/cifs-documents-provider/issues/70

**Comment by guanlisheng** [comment]
we knew it was from mmex.... 
can you try the latest release version: v2024.03.19

**Comment by renato-mmex** [comment]
Sorry, I forgot to mention that I tested again with the last version 2024.03.26.1025.
