### ISSUE TITLE
Last Updated Date

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/android-money-manager-ex#1590]
Last Updated Date is not inserted in the bookings.

**Comment by guanlisheng** [comment]
ideally,  we should use `CURRENT_TIMESTAMP` as the default value of `LASTUPDATEDTIME`...

anyway, it needs an explicitly set now.

![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/721973/9bfeeb6c-88bb-4161-bc20-56c8be44e077)
