### ISSUE TITLE
Pool request

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1592]
**Describe the bug**
When open the app, on boot sync paper this message.

Oneplus 7
Android 12
MMX version 2024.02.15

![Screenshot_2024-02-24-11-23-12-06_56d4659ac84df734ec7538fc9956390c](https://github.com/moneymanagerex/android-money-manager-ex/assets/18198681/93d0602b-aa66-4982-81c1-049d1ef6be77)

**Comment by renato-mmex** [comment]
the app version 2023.12.06 is no longer up-to-date, see: https://github.com/moneymanagerex/android-money-manager-ex/releases or on F-Droid

**Comment by ggraziotti** [comment]
> the app version 2023.12.06 is no longer up-to-date, see: https://github.com/moneymanagerex/android-money-manager-ex/releases or on F-Droid

I have 2024.02.15 version

**Comment by guanlisheng** [comment]
hi @ggraziotti , what's your storge to sync database? Syncthing?

**Comment by guanlisheng** [comment]
hi @ggraziotti, can you try v2023.03.07? we performed a lot of changes database side.

**Comment by guanlisheng** [comment]
closing it and tracking related in #1638
