### ISSUE TITLE
Create a github stable branch and a beta one

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1603]
Currently there is only one github branch for ammex.

The content of the 1020 update seems to be too major to be used as daily build. The next releases will contain daily usable updates and the encrypt modifications. So not sure this one can be used as daily.

So I think at least one more branch could be usefull to separate this type of updates.

Hope you understand this request.

Thanks

Currently installed version: 2024.02.15-1019

**Comment by guanlisheng** [comment]
thanks @jeepcook and your suggestion makes 100% sense.

if we leave the password empty/blank, there is no much difference from 1019.

**Comment by guanlisheng** [comment]
would we close this to keep github issue clean?

**Comment by jeepcook** [comment]
Yes you can. It was just a suggestion.
