### ISSUE TITLE
Cannot edit/update transactions on Android App

### ISSUE THREAD

**Issue by hack-wizard** [moneymanagerex/android-money-manager-ex#1608]
**Describe the bug**
Editing any transaction produces a null length pointer error and fails.  This happens with newly created transactions as well as existing ones.  Creating the transaction works, but attempting to edit it after creation reproduces the exact same error.  This is a serious problem for me as I use this app exclusively to reconcile my finances.

**To Reproduce**
1. Attempt to edit transaction, changing date, status, type, abount, etc.
2. Hit checkmark on top right to save.
3. Small error pops up as described above

**Expected behavior**
The transaction changes should be applied and saved...

**Screenshots**
The error toasts are not screen-shottable on my device...

**Device Information:**
 - Device: Google Pixel 7 Pro
 - OS: Graphene OS (Android) 14
 - Storage: Phone storage
 - Encrypted: no
 - App Version: 2024.02.26 (1020)

**Additional context**
See Logcat export:
[MoneyManagerExLogcat.md](https://github.com/moneymanagerex/android-money-manager-ex/files/14526286/MoneyManagerExLogcat.md)

**Comment by guanlisheng** [comment]
thanks @hack-wizard, we had a similar report in #1605 as well.

it was fixed in the upcoming release 2023.03.07 (f-droid needs some time while github release is done).

**Comment by hack-wizard** [comment]
Thanks for the quick response, any idea how long it will be before the izzyondroid repo updates?

**Comment by guanlisheng** [comment]
at least 1 week

**Comment by hack-wizard** [comment]
Ok, so due to how Graphene handles app sources, I'll need to back up and uninstall everything to try the beta.  Does exporting the database save the recurring transactions too?

**Comment by marcdw1289** [comment]
Actually, uninstalling MMEx never touches the database that is stored in internal storage ( `/sdcard/MoneyManagerEx/` for instance.). You can copy it somewhere just in case.
If the db is in the cloud that won't be touched either.

**Comment by hack-wizard** [comment]
> Actually, uninstalling MMEx never touches the database that is stored in internal storage ( `/sdcard/MoneyManagerEx/` for instance.). You can copy it somewhere just in case. If the db is in the cloud that won't be touched either.

I'm on Graphene, not stock android.  A stand alone APK will install in a separate memory space, unless I'm understanding the documentation wrong.

**Comment by hack-wizard** [comment]
Ok never mind, misunderstood what you said.  I exported the files and it saved everything but a few app settings.  I'm trying the beta and it looks good, thanks for the help and great software!

**Comment by luisdev** [comment]
> Actually, uninstalling MMEx never touches the database that is stored in internal storage ( `/sdcard/MoneyManagerEx/` for instance.). 

Did I readcthat right? Does that mean that the database is left behind when you uninstall MMEx? So if a user was intending to permanently remove MMEx from their phone, the database would remain? Surely it should be removed as part of the uninstallation?
What if the user was uninstalling MMEx to give the phone to someone else? Or sell it...?

**Comment by guanlisheng** [comment]
you are correct that your data, your control.


from https://forum.moneymanagerex.org/viewtopic.php?p=24565#p24565, you can also tell that the data is placed in separated storage

**Comment by marcdw1289** [comment]
> What if the user was uninstalling MMEx to give the phone to someone else? Or sell it...?

Not a problem. Just delete the directory. Simple.
Behavior is nothing to be alarmed about. Lots of software would/will store some data in `/storage/emulated/0/`. Sometimes considered shared data. Individual app settings, backups, work spaces, other downloads, maps, etc.
Things one may not want gone after uninstalling or clearing data of an app.
I have ancient directories from apps not used or installed going back years.
It is up to the user to maintain internal storage.
Know what's on the phone.
If giving a phone to someone it is your duty to do a thorough cleaning.
