### ISSUE TITLE
Unable to edit a Payee name 

### ISSUE THREAD

**Issue by bquinlan** [moneymanagerex/android-money-manager-ex#1609]
When I edit the name of a Payee and tap OK it pops up an error message:
Attempt to get length of null array.

The edit is not saved.

The Payee name should be changed, but it is not.

**Device Information:**
 - Device: Samsung S23 Ultra
 - OS: Android 14
 - App Version: 2024-02-26 (1020)

**Comment by guanlisheng** [comment]
thanks @bquinlan , we had a similar report in https://github.com/moneymanagerex/android-money-manager-ex/issues/1605 as well.

it was fixed in the upcoming release 2023.03.07 (f-droid needs some time while GitHub release is done).
