### ISSUE TITLE
Unable to update transaction

### ISSUE THREAD

**Issue by bquinlan** [moneymanagerex/android-money-manager-ex#1610]
Trying to change an existing transaction does not work.

I open an existing transaction and tap on the amount.  I backspace to remove the last digit and enter a different one.  I tap OK to save the new amount.  The new amount appears on the transaction details screen.  No problems so far.

When I tap the checkmark to save the edited transaction I get a series of error messages.  The first is:
Attempt to get length of null array.

I haven't been able to copy the details of the second, but it begins:
Update failed, content:...

That is followed the final message:
Updating transaction failed.

The transaction list screen should appear with the edited transaction shown.

 - Device: Samsung S23 Ultra
 - OS: Android 14
 - App Version: 2024-02-26 (1020)

This, and several other errors, started when I updated from the previous version to the most recent version.  I had not seen error messages until after the update.

**Comment by guanlisheng** [comment]
thanks @bquinlan , we had a similar report in https://github.com/moneymanagerex/android-money-manager-ex/issues/1605 as well.

it was fixed in the upcoming release 2023.03.07 (f-droid needs some time while GitHub release is done).
