### ISSUE TITLE
Payee error

### ISSUE THREAD

**Issue by heberjeur** [moneymanagerex/android-money-manager-ex#1613]
Describe the bug

To Reproduce

    Go to add operation
    Fill fields
    Save
    See error

Expected behavior
It saved but I see those errors

**Screenshots**
![Screenshot_20240310-083014_Money Manager Ex_1](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/20a6b8cf-0e81-45f7-b8ff-1cb03683740b)
![Screenshot_20240310-202310_Money Manager Ex_1_1](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/dd823790-4822-41d9-afef-5a4f5a3e0064)
![Screenshot_20240310-083738_Money Manager Ex_1](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/56cb6ecf-7f54-4f7e-8eed-ed9db8b35fc9)
![Screenshot_20240310-083209_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/2f1c04fd-8e22-4f7f-9adc-e2be4a68f2ee)
![Screenshot_20240310-083153_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/9087419f-43c1-4370-8513-a80e4f383aab)
![Screenshot_20240310-083148_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/88cae836-4829-4439-b9b8-ef16928d7a57)

**Device Information:**
 - Device: Samsung A50
 - OS: Android 11
 - Storage:  Phone storage 
 - Encrypted: [e.g. Yes]
 - App Version: 2024.02.26

**Additional context**

**Comment by guanlisheng** [comment]
thanks @heberjeur 
i just addressed the issue and an incorrect conflictAlgorithm caused it during the insert and update. will roll out a release shortly in f-droid.  

the github release is ready
