### ISSUE TITLE
Version 2024.03.07 prompts for password

### ISSUE THREAD

**Issue by marcdw1289** [moneymanagerex/android-money-manager-ex#1616]
**Describe the bug**
When I try to open the local database (Personal.mmb) with this version it asks for a password. Quite sure that should not be.
Tapping OK without a password or just backing out would produce toast messages similar the one posted in #1588 and/or the app closes.

**To Reproduce**
1. Go to 'Open Database'
2. Select 'Other'
3. Open 'Personal.mmb' or applicable database
4. Prompt for password appears

**Expected behavior**
Unencrypted database should just open.

**Screenshots**

**Device Information:**
 - Device: Motorola G5 Pus potter
 - OS: Havoc OS, Android 9
 - Storage: Phone storage + Syncthing (itself a problem but issues exist for that)
 - Encrypted: No
 - App Version: 2024.03.07

**Additional context**
Had to downgrade to 2024.02.15.

**Comment by guanlisheng** [comment]
hi @marcdw1289 , 
I am interested in your phone storage + syncthing issue. can you share more?

**Comment by marcdw1289** [comment]
Upon thinking again I believe there is no syncthing issue.
I was fighting with DecSync at the same time I was testing with MMEx and was frustrated.

The MMEx database gets synced just fine. On the target device I would open the app and not see changes thus thinking it was no working. Been using the 2018.11 version for so long I was expecting "instant gratification". 😁

Then I remembered a discussion that mentioned the difference between the 'local' data (`/data/data/moneymanagerex/`) vs internal storage (`/sdcard/MoneyManagerEx/`).

So I assume I have to manually open the syncthinged database(?). If so then things are fine but correct me if not. Still trying to get the hang of things.

**Comment by guanlisheng** [comment]
you might need to setup periodically sync 

here you go https://youtube.com/shorts/zxQHkbXhWok?si=wTn4DNBJBcsHzPe3

**Comment by bballmaster** [comment]
I have a suspicion about the syncthing problem. The problem with synchronization is that AMMEX makes some change to the local database immediately after it opens a db. It forces this change to be pushed to the sync-folder:

1. if there were no changes to the remote db from another devices: "Database stored successfully".
2. if there were changes to the remote db from another device: "Both the local and the remote files have been modified".

In the second case I have to create a copy of the last remote db in my sync folder and open it with AMMEX as a new db. Which leads me to the first case, where I have to use only AMMEX on my phone, so there would be no changes to the remote db from another devices and no conflicts.

It all works even with a new clean db created with AMMEX:

1. create a db with AMMEX in the remote sync-folder;
2. create an account in it - just to make it not empty;
3. wait until the new db is synced on desktop;
4. open the new db on desktop;
5. make any change - create another account;
6. wait for sync to be completed to your mobile;
7. open AMMEX and get your "Both files have been modified".

**Comment by guanlisheng** [comment]
hi @bballmaster, 
The desired behavior is that every device modifies and performs the change sync in time. multi modifications to a single file are problematic and will result in a conflict.

once conflicted, we can force push to and pull from the remote (depending on which is the ground truth). re open is a kind of force pull.

in your example, a sync (manual or periodical) is needed between 2 and 3.  this is to reflect the changes to the new db in your sync-folder.

this [arch](https://forum.moneymanagerex.org/viewtopic.php?p=24565#p24565) might explain it a little bit and MMEX is leverageing the external storage service to data sync.

**Comment by bballmaster** [comment]
Hi @guanlisheng.

Thanks for your answer.

I totally get the scheme of cloud storage synchronization, and I don't expect it to be possible to make multiple chacges to one flie. The described problem occures in the item 7 in my example. The "Sync on start" option is on, but AMMEX does not pull the modified db file from the remote folder, but immediately after the start modifies the local db file (without my participation) and tries to push it to the remote folder - here happens the conflict.

The expected behavior is that with the "Sync on start" option on AMMEX would know where the latest changes are and at the start:

- if the remote file was changed last, AMMEX should pull it;
- if the local file was changed last, AMMEX should push it to the remote folder.

Am I wrong with this logic?

**Comment by guanlisheng** [comment]
you logic is correct,  seems you just forgot to push it to the remote after 2 /before 3 (as i said).  
can you try follow my suggestion to perform a sync (eithor manual or period, e.g. restart the app)?

**Comment by bballmaster** [comment]
Sure. I checked thoroughly multiple times.

Here is how to reproduce my steps:

1. Open AMMEX on a phone and create a new DB in a folder being synced via Syncthing, so the db file appears on the second device almost immediately.
2. Wait for one minute and create the first account in the db.
3. Go to Settings -> Synchronization and perform "Upload".
4. Close AMMEX.
5. Wait for the db file to be synced to the second device (I can see it, when the modification time changes, as I wait one minute before any db change).
7. Open the synced db file on the second device with the desktop MMEX.
8. See the first account and in one minute create the second one.
9. Wait for the db file to be synced to the phone - as you can see the file modification time changed.
10. Open AMMEX on the phone.
11. Get the conflict message - "Both the local and the remote files have been modified", just one created account - the first one.

After I wrote this sequence I did it all once again - same result. Do you see what I miss? Or can you reproduce it the same way?

**Comment by guanlisheng** [comment]
These 10 steps are much clearer and it is expected to work. the root cause is to be addressed.

Can you change step 3 by clicking Synchronize in main menu?

**Comment by guanlisheng** [comment]
btw, you are using v2024.03.07, correct?  maybe we can start a new issue separately.

**Comment by bballmaster** [comment]
https://github.com/moneymanagerex/android-money-manager-ex/issues/1616#issuecomment-1999606776

Sure. Just tried it with "Synchronize" action - no difference.

And sorry I didn't mention the version before: I was still using the previous release - [2024.02.15.1019](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.02.15.1019) because of some other issues. The thing is that the search in selects became case-sensitive for cyrillic symbols, and subcategories do not unfold while searching with capital letters. Had no time to report.

And I just reproduced it all with the latest release - [2024.03.07.1021](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.03.07.1021).

**Comment by guanlisheng** [comment]
@wolfsolver, can you take a look at the category issue?

in terms of sync, I reproduced it once time.  still not sure the root case why local file mtime is not determined properly. 

a workaround is to click `Synchronize` action one more time until you see the message `The database is up to date`.

**Comment by guanlisheng** [comment]
hi @bballmaster, can you try the latest apk via https://drive.google.com/file/d/1adbTNIsGBawEukogULl_Mppo2f2jAhCH/view?usp=sharing . i tested and it works well on your steps.

**Comment by marcdw1289** [comment]
Closing. The password issue was addressed.
The syncthing "issue" is no more. Everything in that regard is working fine.
