### ISSUE TITLE
Change the transaction to Reconciled on the pop-up does not work 

### ISSUE THREAD

**Issue by robvinall** [moneymanagerex/android-money-manager-ex#1632]
Cannot reconcile a payee on the pop-up 

**To Reproduce**
1. Go to 'payee'
2. Click on hold then the tag icon to generate a pop-up'
3. Select reconcile 
4. See error as nothing happens 

**Expected behavior**
Previously one or multiple payee could be selected and reconciled 
![Screenshot_20240321-074826](https://github.com/moneymanagerex/android-money-manager-ex/assets/33311560/a95a1348-1b29-4f0d-9739-1dc63c8d5ea6)

**Screenshots**

[](url)
**Device Information:**
 - Device: [pixel 7a]
 - OS: [e.g. Android 13]
 - Storage: [phone]
 - Encrypted: [e.g. no]
 - App Version: [e.g. 2024.03.19]

**Additional context**

**Comment by guanlisheng** [comment]
hi @robvinall, thanks for trying mmex and reporting the issue.

can you show more detailed steps to re-produce the issue?

**Comment by guanlisheng** [comment]
hi @robvinall, ignore me. 

Just reproduced this shortcut issue.  seems it is not a good design and impl. and you can use regular way to update transaction's status.

**Comment by robvinall** [comment]
Hi it has worked untill now. I have been using it that way since I started
using MMex in 2014.

Rob

**Comment by guanlisheng** [comment]
addressed the root cause and it was introduced since [v2024.03.16](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.03.16.1022)

**Comment by robvinall** [comment]
Awesome, thanks for the update!
