### ISSUE TITLE
Payee field being optional

### ISSUE THREAD

**Issue by Seif-el-din** [moneymanagerex/android-money-manager-ex#1634]
**Is your feature request related to a problem?

-  Yeah, I generally don't care about the payee information. So, having to fill it every time now is really frustrating

**Describe the solution you'd like**

- Have an option in the settings to have the choice whether to fill in the payee field or not 

**Additional context**
![Screenshot_20240322_033229_Money Manager Ex.jpg](https://github.com/moneymanagerex/android-money-manager-ex/assets/148765543/994bea26-81e2-475e-b10c-7306f4501860)

**Comment by guanlisheng** [comment]
thanks @Seif-el-din, maybe we can have a default payee to simplify it.

@renato-mmex and @whalley, thoughts?

**Comment by luisdev** [comment]
In my opinion, not using the payee field defeats the purpose of using a program like MMX to track your finances. Why wouldn't you want to know who you are paying your money to and who you are receiving money from?

But anyway...

If you don't want to capture the real payee field, just create one dummy payee and use that one for every transaction.

**Comment by guanlisheng** [comment]
hi @Seif-el-din, you can achieve a similar result by setting `Default Payee` as `Last`
![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/721973/5bdabb82-04b2-4a95-8bde-acb5fde6af32)
