### ISSUE TITLE
Period Navigation & Comparative Analysis for Reports

### ISSUE THREAD

**Issue by heberjeur** [moneymanagerex/android-money-manager-ex#1636]
** Is your feature request related to a problem? **

The current inability to compare easily between different periods in MoneyManagerEx poses a significant challenge for users. Without a streamlined method for navigating through months and years, users find it difficult to compare financial data across different timeframes efficiently. This limitation hampers their ability to track trends, analyze spending patterns, and make informed financial decisions effectively.

* Describe the solution you'd like **

I propose implementing a navigation feature that allows users to easily move between months and years with simple left and right buttons. Additionally, there should be a point to return to the current month for quick reference.

** Describe alternatives you've considered **

Alternatively, another approach could be to create a new screen featuring a table containing the 12 months of the year along with corresponding data on payee. Additionally, another screen or table could be implemented specifically for categories, allowing users to compare and analyze financial information in a more structured and detailed manner.

** Additional context **

![Screenshot_20240324-105646_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/15a6dc5f-52e7-493e-b56f-31b80630b22e)

**Comment by guanlisheng** [comment]
thanks, @heberjeur, can you also help with implementation?
