### ISSUE TITLE
Renaming error

### ISSUE THREAD

**Issue by shay4567** [moneymanagerex/android-money-manager-ex#1637]
**Describe the bug**
Attempting to rename a category or a payee results in: "error: attempt to get lenght of null array"

**To Reproduce**
1. Go to "categories" or "payees"
2. Hold on a name
3. Click edit
4. Rename
5. Click ok

**Expected behavior**
The item gets renamed

**Device Information:**
 - Device: Xiaomi Mi 9t Pro
 - OS: Android 14 (Evolution X)
 - Storage: Phone storage
 - Encrypted: Yes
 - App Version: 2024.03.19

**Comment by guanlisheng** [comment]
thanks @shay4567 , this is confirmed and going to be fixed in next release.

**Comment by guanlisheng** [comment]
thanks for trying encryption. it would be opened by https://github.com/guanlisheng/wxsqliteplus in desktop as well.

**Comment by guanlisheng** [comment]
please checkout https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.03.26.1025
