### ISSUE TITLE
Wrong database path

### ISSUE THREAD

**Issue by shay4567** [moneymanagerex/android-money-manager-ex#1641]
**Describe the bug**
Opening the app for the first time asks to create or open a database int he internal storage. Setting up a database in the Documents/MME folder results in your_data.mmb being 0 bytes. The path specified in settings/database is: /storage/emulated/0/Android/data/com.money.manager.ex/files/databases/your_data.mmb and can't be changed. Opening the app other times results in a looping error message: "Error: the passphrase appears to be cleared. This happens bydefault th..." and impossibility to modify the previously set database (no data from it is shown in the app)
**To Reproduce**
1. Open the app after clean install
2. Create/open a database located in Documents/MME or similar folder
3. Close and open the app a second time

**Expected behavior**
The path chosen is remembered and the app functions normally

**Device Information:**
 - Device: Xiaomi Mi 9t Pro
 - OS: Android 14, Evolution X
 - Storage: 128 gb internal
 - Encrypted: Yes
 - App Version: 2024.03.26

**Additional context**
This was actually present in the previous version 2024.03.19 as well
Opening Setting/database after the app enters the buggy state (second opening) results in returning to home screen

**Comment by guanlisheng** [comment]
there is an assumption that *.mmb is not encrypted, saying leave password empty/blank.

**Comment by reaffirm** [comment]
Also seeing this error on Android.

Note: I've even tried tapping the menu and going to load database and inputing the password, but I still get the looping error message.

**Comment by guanlisheng** [comment]
thanks @reaffirm, there is much room for uex.

1. for unencrypted files, please use `*.mmb` suffix and leave the password blank.
2. for the encrypted one,  please use `*.emb` suffix and set your password.

**Comment by reaffirm** [comment]
@guanlisheng, when I do that then when I reopen the `*.emb` file, it's just blank and doesn't have the accounts I set up. Is there some save button I have to press before closing it?

**Comment by guanlisheng** [comment]
reopening the app should be sufficient.  while reopening the file means force pulling from the remote. 


sync and setting -> sync will be helpful here.

**Comment by guanlisheng** [comment]
hi @shay4567 , closing this and feel free to re-open

**Comment by imagochan** [comment]
> thanks @reaffirm, there is much room for uex.
> 
> 1. for unencrypted files, please use `*.mmb` suffix and leave the password blank.
> 2. for the encrypted one,  please use `*.emb` suffix and set your password.
> 

With this info I just left the password blank for a mmb file and it worked! Hopefully this gets addressed in the future or just put a disclaimer when entering a password in case the file type is not emb
