### ISSUE TITLE
Database Error when first opening DB

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1642]
**Describe the bug**
Was running 15/02/24 version as 19/03/24 version on FDroid does not allow you to add or edit Payees. Uninstalled this and installed latest pre-release version (26/03/24 1025). Had to uninstall all other versions first.

Launched new version and asked it to open my money file from Google Drive. It asked my to enter protecting code, which it accepted, but then issues an error about the DB not being recognised as a valid file. I closed the app and relaunched it and it opened the DB without further problem. 

Only see the error when first launching app after new install and opening existing DB file. File passes integrity and schema check

**To Reproduce**
1. Completely uninstall Money Manager.
2. Install latest pre-release version 1025.
3. Launch app and locate db file in Google Drive.
4. MMEX asks for security pin so enter that. 
5. Error displayed and app in background returns to initial boot up page.
6. Close app
7. Reopen app and fingerprint entry requested and after this or pin is used the app works fine with open dB.

**Expected behavior**
Should open dB without error

**Screenshots**
![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/45fa8801-bcae-4432-9295-dbca46478627)
![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/329df7e8-acfa-46ec-989f-61e2abeb28cf)
![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/71cb5b55-5cfc-4a1c-b35a-9089780cfd5f)

**Device Information:**
 - Device: Samsung Galaxy S22
 - OS: 14 (1/3/24 security patch)
 - Storage: 256gb only 76gb used
 - Encrypted: [e.g. Yes]
 - App Version: [e.g. 2024.03.26 (1025)]

**Additional context**
This issue also exists on 2024.03.19 but not 2024.02.15

**Comment by guanlisheng** [comment]
hi @smjohns please leave password empty/blank for non-encrypted file (*.mmb)

**Comment by smjohns** [comment]
Thanks for the quick response. Retried as per your instructions and error did not occur. 

Hopefully you will be able to come up with a friendlier way of handling that out bypassing when file is not encrypted?
