### ISSUE TITLE
some errors while use Settings

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1643]
**Describe the bug**
some errors while  use

**To Reproduce**
1.Phone language Arabic
2. App language default (Arabic)
3. Open setting then per-database
4. Error will appear
5. Open setting then look & feel
6. Error will appear

**Device Information:**
 - Device: Redmi note 12
 - OS:  Android 14
 - Storage:  Phone storage
 - Encrypted: no
 - App Version: 2024.03.24
 - 
[temp--125561127.txt](https://github.com/moneymanagerex/android-money-manager-ex/files/14804492/temp--125561127.txt)

**Comment by guanlisheng** [comment]
thanks @islam2hamy 

Might be due to some configuration.   it should not block normal use, correct?

**Comment by guanlisheng** [comment]
also, can you share a screenshot of per-database and look & feel

**Comment by islam2hamy** [comment]
![Screenshot_٢٠٢٤-٠٣-٢٩-١٨-٣٣-٥٥-٥٢٣_com money manager ex-edit](https://github.com/moneymanagerex/android-money-manager-ex/assets/7989030/0f653467-b42a-4724-91e6-988a4a914792)

**Comment by islam2hamy** [comment]
![IMG_٢٠٢٤٠٣٢٩_١٨٣٧١١](https://github.com/moneymanagerex/android-money-manager-ex/assets/7989030/467b1ac8-8016-4ca8-8343-7f9860f29e90)

**Comment by islam2hamy** [comment]
also typing 1000 , make number appear not correctly

https://github.com/moneymanagerex/android-money-manager-ex/assets/7989030/e45ddbb6-faa2-4f4d-9e9e-ec9424984e06

**Comment by islam2hamy** [comment]
> also typing 1000 , make number appear not correctly
> 
>  Screenrecorder-2024-03-29-18-38-14-940.mp4

@guanlisheng 

create  new issue ?

**Comment by guanlisheng** [comment]
yes, please.  similar with #1534

**Comment by islam2hamy** [comment]
> ![Screenshot_٢٠٢٤-٠٣-٢٩-١٨-٣٣-٥٥-٥٢٣_com money manager ex-edit](https://private-user-images.githubusercontent.com/7989030/318095890-0f653467-b42a-4724-91e6-988a4a914792.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzA1MTMsIm5iZiI6MTcxMzczMDIxMywicGF0aCI6Ii83OTg5MDMwLzMxODA5NTg5MC0wZjY1MzQ2Ny1iNDJhLTQ3MjQtOTFlNi05ODhhNGE5MTQ3OTIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMjAxMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTUyZDcyZGUwNDYyNmM3OTdiOTgyMzNlMTA1ZGM2ZGIzYjU4YjFlOTc5MzRjMjcyY2IxYzUzYmEyMDFhNGFkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9kjhF431Kx84Lbo3j0rn2eCC9cICGsyhwps0gJ8SOMs)

Hello @guanlisheng 
please note that , selecting "financial year : start month" making this error disappear

**Comment by islam2hamy** [comment]
> ![IMG_٢٠٢٤٠٣٢٩_١٨٣٧١١](https://private-user-images.githubusercontent.com/7989030/318096447-467b1ac8-8016-4ca8-8343-7f9860f29e90.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzA1MTMsIm5iZiI6MTcxMzczMDIxMywicGF0aCI6Ii83OTg5MDMwLzMxODA5NjQ0Ny00NjdiMWFjOC04MDE2LTRjYTgtODM0My03Zjk4NjBmMjllOTAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMjAxMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdmYmJhMTVkMzQ2MjJhODAwZTVkODFjYTc3NTVmNWZiMDk4NzI4ZjZkOGU4ZTdhYjVlYzkxYzZhNDBiNDdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4LEcpUQKW71UtLsMNweRW2hx0VC6--mdXw9cqbfYRSQ)

Hello @guanlisheng 
please note that , selecting "date format" making this error disappear

**Comment by guanlisheng** [comment]
yup, `date format` is mandatory so far,  related to #1460 


can we close this out?

**Comment by islam2hamy** [comment]
So you will add adefult value if null in the next release ?

**Comment by guanlisheng** [comment]
no plan yet. as known issue, and end user would set it up properly.
