### ISSUE TITLE
Category disappeared after its subcategory rename 

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1645]
**Describe the bug**
Category disappeared after rename

**To Reproduce**
1.Create new category
2. Close the app
3. Open the app
4. Rename the created category

**Expected behavior**
New name will appear

**Device Information:**

- Device: Redmi note 12
- OS: Android 14
- Storage: Phone storage
- Encrypted: no
- App Version: 2024.03.26

p.s: Logcat button doesn't work

**Comment by guanlisheng** [comment]
hi @islam2hamy

can you try out https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.04.01.1026 ?

**Comment by islam2hamy** [comment]
> hi @islam2hamy
> 
> can you try out https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.04.01.1026 ?

hi @guanlisheng 

it is work

**Comment by islam2hamy** [comment]
P.s : reinstall the app and reopening the DB , make me all DB changes , as it is a new DB

**Comment by guanlisheng** [comment]
that's sad.

seemed you didn't sync the change to your phone storage.  it should be synced period once you set it up (settings -> sync)

**Comment by islam2hamy** [comment]
> that's sad.
> 
> seemed you didn't sync the change to your phone storage. it should be synced period once you set it up (settings -> sync)

Ok will try it
thank you
