### ISSUE TITLE
Time (HH:mm) in transaction 

### ISSUE THREAD

**Issue by ilvinc3nt** [moneymanagerex/android-money-manager-ex#1649]
**feature request**

is it possible to add time in addition to date in transactions input?

**Comment by guanlisheng** [comment]
hi @ilvinc3nt 

so far, the mmex schema doesn't support this yet.  while we have DateTime field to track the last updated time https://github.com/moneymanagerex/android-money-manager-ex/issues/1590


@whalley , @vomikan , and @renato-mmex , any comment?

**Comment by whalley** [comment]
This is now supported in the desktop 1.7.1 beta version. https://github.com/moneymanagerex/moneymanagerex/issues/2729

**Comment by guanlisheng** [comment]
Great.  

can you verify whether the scheme, data, and application are compatible?
