### ISSUE TITLE
Download new currency deletes default list of currencies, search for new currencies fails even after updating

### ISSUE THREAD

**Issue by jcjc1233** [moneymanagerex/android-money-manager-ex#1653]
# Bug Report: android-money-manager-ex

## Description
In the app, when attempting to use a specific currency, even after updating currencies, the app will not search for or display new currencies. It will also delete all the other currencies when you choose one of them for the first time

## Environment
- **Device Info**: Samsung S22 Ultra
- **android-money-manager-ex Version**: 2024.02.15 (1019)
- **Android Version**: 14
- **Stacktrace**: Bug does not cause a crash
- **Is it a Duplicate?**: No

## Steps to Reproduce
1. Open App
2. Click “hamburger” icon
3. Click on Entities
4. Click on Currencies
5. Click on the download button
6. Observe that no currencies will be downloaded
7. Attempt to search and use any new currency fails (example: US dollar or USD)

## Expected Behaviour
The app is supposed to show a list of downloaded currencies to choose from. Initially, you can select a currency before downloading, but once the download button is pressed, all other currencies are deleted and cannot be used.

## Actual Behaviour
After pressing the download button, the list of currencies is either not updated or is cleared, preventing the selection and use of new currencies.

![WhatsApp Image 2024-04-08 at 23 00 26_0b4ae5cb](https://github.com/moneymanagerex/android-money-manager-ex/assets/98419894/da87c326-4237-40c3-a63c-c879e0fc261d)

**Comment by guanlisheng** [comment]
thanks @jcjc1233  

uncheck `show only used` from the ... in up-right might help

![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/721973/91d6d4fd-185a-4042-80f1-247d436d9a81)

**Comment by jcjc1233** [comment]
Oh ok I tried that and it worked
