### ISSUE TITLE
Unable to record a zero operation when there is sub-operations

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1656]
I am unable to record an operation with sub operations with a total amount of 0 euros. I have a message saying that the total amount can't be negative. I can validate a zero operation only when there is no sub operation.

Hope I am clear

See screenshots
![Screenshot_2024-04-13-08-42-02-794_com money manager ex-edit](https://github.com/moneymanagerex/android-money-manager-ex/assets/17811804/e453a292-5ad5-4bc3-af8c-bfb6b64ed4cf)

![Screenshot_2024-04-13-08-42-37-804_com money manager ex-edit](https://github.com/moneymanagerex/android-money-manager-ex/assets/17811804/13849b6d-116b-4472-a2fc-4191369f9973)

Thanks

**Device Information:**
 - Device: Poco M3 Pro 5G
 - OS: Android 13
 - Encrypted: No
 - App Version: 2024.04.01.1026

**Comment by guanlisheng** [comment]
thanks @jeepcook . 

this is a known issue (though not hard to change) and we added zero amount for transaction via #1491

**Comment by jeepcook** [comment]
No the 1491 solved the 0 transaction amount. But it doesn't work with split transactions.
