### ISSUE TITLE
Crash when select modify in recurrent transactions

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1665]
Bug introduced with 1027 version.

In recurrent transactions menu, just select an operation and choose modify, the application crash.

Have to rollback to 1026.

**Comment by guanlisheng** [comment]
thanks @jeepcook ,

how about other transactions & entities modifications?

**Comment by guanlisheng** [comment]
please try https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.04.16.1028

**Comment by jeepcook** [comment]
Hello,
It's fixed.
Thanks for your quick reaction :-))
