### ISSUE TITLE
Show Chart for Currencies not working. When clicked blank screen appears

### ISSUE THREAD

**Issue by jcjc1233** [moneymanagerex/android-money-manager-ex#1666]
### Description
In the app, when I want to show a chart for a specific currency the screen will show blank with no error message at all.

### Environment
- Device Info: Samsung S22 Ultra 
- android-money-manager-ex Version: 2024.02.15 (1019)
- Android Version: 14
- Stacktrace: Bug does not cause a crash
- Is it a Duplicate?: No

### Steps to Reproduce
1. Open App
2. Click “hamburger” icon
3. Click on Entities
4. Click on Currencies
5. Choose currency type (e.g., From which country)
6. Click on show currency chart
7. Screen will go blank 

### Expected Behaviour
The app is supposed to show the complete chart of the selected currency.

### Actual Behaviour
![WhatsApp Image 2024-03-22 at 21 07 19_071f2941](https://github.com/SOEN345-WINTER2024/discussion/assets/98419894/a0d420eb-2796-409c-841f-aa6bf3dc4501)

### After clicking show chart this is the blank screen
![WhatsApp Image 2024-03-22 at 21 07 19_6e605848](https://github.com/SOEN345-WINTER2024/discussion/assets/98419894/f2dba96f-e927-4da8-9e34-e40bbd48ab80)

**Comment by guanlisheng** [comment]
thanks @jcjc1233 

there is some room for currency features. 
btw, can you confirm whether #1653 is still an issue?

**Comment by wolfsolver** [comment]
The issue is due yahoo endpoint. taking EUR as example the app call "http://chart.finance.yahoo.com/z?s=EUREUR=x&t=5d&z=m" witch actually does not work.
Does anyone know a different free service to get currency graph?
