### ISSUE TITLE
F-Droid: Don't mark Pre-release version as suggested

### ISSUE THREAD

**Issue by nizarus** [moneymanagerex/android-money-manager-ex#1670]
In F-Droid the Pre-release versions are marked as suggested version and are updated automatically.

Actually the Pre-release Version 2024.04.15 is marked as suggested (https://f-droid.org/en/packages/com.money.manager.ex/) but, according to github, the last "stable" version is 2024.04.01.

**Comment by guanlisheng** [comment]
thanks, @nizarus for reminding me.  
it will be marked as release once f-droid finished the publish (as it always has a delay).
