### ISSUE TITLE
Can't open MMEX file from Nextcloud application (F-Droid version)

### ISSUE THREAD

**Issue by DanielChesters** [moneymanagerex/android-money-manager-ex#1673]
**Describe the bug**
I cannot open a MMEX file from Nextcloud, I don't have option to selection Nextcloud application in file picker.

**To Reproduce**
1. Click on hamburger menu in MMEX application
2. Go to 'Open Database'
3. Click on 'Other'
4. Click on hamburger menu in file picker
5. Don't find Nextcloud provider

**Expected behavior**
Option to select Nextcloud file provider and get MMEX file from it.

**Screenshots**
![Screenshot_20240421_164510_Files](https://github.com/moneymanagerex/android-money-manager-ex/assets/291102/472223fc-bb01-4b50-b3ad-37c703739d1a)

**Device Information:**
 - Device: Samsung Galaxy S23+ (SM-S916B/DS)
 - OS: Android 14/One UI 6.1
 - Storage: Internal Storage + Nextcloud (at least, I want to use Nextcloud)
 - Synchronization: For the moment off, but I want to set to on with Nextcloud.
 - Encrypted: N/A, I think
 - App Version: 2024.04.01, but it is the same with 2024.04.15.

**Additional context**
I use version 3.28.2 of Nextcloud app from F-Droid

**Comment by nizarus** [comment]
Can't reproduce this. In my case all is OK. 
- Android 13
- Same for Nextclod app 3.28.2 from F- Droid
![IMG_20240421_193105](https://github.com/moneymanagerex/android-money-manager-ex/assets/17108772/5a5f1281-158e-4d19-8d17-5326f34518e2)

**Comment by guanlisheng** [comment]
thanks, both.

hi @DanielChesters
Please always keep Synchronization on as both phone storage (e.g. Documents) and cloud storage are **external** storage to the app.

btw, can you click the Pipimi (phone)? it may help explore more storages

**Comment by guanlisheng** [comment]
just to ensure that you installed NextCloud and it was running well on your phone?
