### ISSUE TITLE
Some Reports submenus not opening

### ISSUE THREAD

**Issue by heberjeur** [moneymanagerex/android-money-manager-ex#1679]
**Describe the bug**
The submenus under the Reports menu (categories, where the money goes, where the money comes) are not functioning as expected starting of this version "2024.04.15.1027".

**To Reproduce**
1. Open the MoneyManagerEx application.
2. Navigate to the Reports menu.
3. Attempt to click on the following submenus: categories, where the money goes, where the money comes.

**Expected behavior**
I expected the submenus to display their respective content or perform their intended functions when clicked.

**Screenshots**
![Screenshot_20240421-024427_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/11852634/8fb383b1-9546-4750-bc74-b53a4d268361)

**Device Information:**
- Device: Samsung
- OS: Android 11
- Storage: Phone storage
- Synchronization: No
- Encrypted: No
- App Version: 2024.04.15.1027

**Additional context**
The issue persists consistently across multiple attempts.

**Comment by guanlisheng** [comment]
hi @heberjeur , please upgrade to v2024.04.21

related to #1674

**Comment by guanlisheng** [comment]
btw,  better to enable synchronization

**Comment by heberjeur** [comment]
> hi @heberjeur , please upgrade to v2024.04.21
> 
> related to #1674

I tried it, and the issue persists; I have the same problem

**Comment by guanlisheng** [comment]
my bad memory... the fix has not shipped yet.

**Comment by guanlisheng** [comment]
we just rolled out github [v2024.04.29 release](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.04.29.1030), F-Droid might need a few days.

please try.
