### ISSUE TITLE
dropbox and syncthing sync don't work properly

### ISSUE THREAD

**Issue by elgidiom** [moneymanagerex/android-money-manager-ex#1681]
**Describe the bug**

Sync and storage in dropbox doesnt work properly. The data seems to be saved in dropbox but the dropbox database actually is not updated

**To Reproduce**
1.  Create a database and save directly in dropbox
2. make any transactions

you would notice that dropbox database is not update

**Expected behavior**
The dropbox database is update 

**Device Information:**
 - Device: samsung galaxy A14
 - OS: Android 13
 - Storage: dropbox
 - Synchronization: on and off
 - Encrypted: Yes
 - App Version: 2024.04.21

**Additional context**
Dropbox not works properly. Even if i import the database, some times the app doesnt show any transactions

**Comment by guanlisheng** [comment]
what's your synchronization setting?  the screenshot on [F-Droid](https://f-droid.org/packages/com.money.manager.ex/) is a good example.

**Comment by elgidiom** [comment]
![Screenshot_20240428_090941_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/159052818/37826149-f887-4715-959b-af363300d812)

now i moved the source of database but still dont working. I think that the issue is with sync in general.

i dont know how see the logs, but some times an no file error appear after "remote database update" message

**Comment by guanlisheng** [comment]
Based on the screenshot,  your database is in your shared(external) storage: Documents.  

Each app restart or the interval you set,  the app will sync the data between application folder and your Documents folder.

**Comment by elgidiom** [comment]
Texto original
1.434 / 5.000
Resultados de traducción
Resultado de traducción
I will explain my case to you in detail.
First, I left Dropbox because sync never worked. Now I put my database on external SD storage and synchronized with syncthings to my PC (settings in mmex sync on startup). That's what's happening:

1) my database named db.mmb is in the directory and on my PC with the same modification date
2) if I do a transaction from the application and restart it, what I expect to happen is the database in the directory is updated, but no, instead db.mmb stays the same and another database called db is created. sync-conflict- (name continues).mmb
3) the new database has changes but the original does not

![imagen](https://github.com/moneymanagerex/android-money-manager-ex/assets/159052818/1ceb7951-100a-4dac-97c7-187cc9ff04d1)

IN DROPBOX
1) the process is repeated. The Dropbox database and the application start in sync.
2) I make a transaction in the app and force the sync (a sync successful message appears)
3) the first sync works but then it starts creating other files and the original continues without modifications

![imagen](https://github.com/moneymanagerex/android-money-manager-ex/assets/159052818/ce334923-c6f8-4b9f-9b1c-99104858ee74)

after that, more files are created but the original one (the files that the application actually uses remain outdated?

after that other files are created but original (the files apps actuallly uses remaining downdated?

**Comment by guanlisheng** [comment]
thanks @elgidiom ,

Both `DropBox` and `Shared Storage + Syncthing` are good options.

for MMEX4Android, its sync has two stages:
1. bi-sync between the application folder and your chosen folder (Documents or Dropbox)
2. Syncthing or Dropbox bi-syncs between local storage and remote (either desktop and cloud)

based on your screenshots, the conflict happened in stage 2. Can you list your detailed steps?

you can refer to https://github.com/moneymanagerex/android-money-manager-ex/issues/1571

**Comment by guanlisheng** [comment]
https://moneymanagerex.org/docs/features/usecloud/ This is also helpful to explain current sync

**Comment by elgidiom** [comment]
Hi @guanlisheng looking at the bug you mentioned. I searched for system updates and found a few. After installation, syncing with Dropbox works pretty well. It's not perfect, it still creates some error files sometimes, but with manual syncing or reopening the app, the main file syncs.

![imagen](https://github.com/moneymanagerex/android-money-manager-ex/assets/159052818/356dd96f-a48c-4ee3-9b64-cb900fd59991)

In logs is this.
![imagen](https://github.com/moneymanagerex/android-money-manager-ex/assets/159052818/4411d72f-bb5f-4f24-8f93-eea425c36ed1)

thank you for your awesome job!

**Comment by guanlisheng** [comment]
Great that it works somehow.  we will keep enhancing the synchronization and encryption.

would you help close the issue?
