### ISSUE TITLE
"Income vs. Expenses" report calculates share transaction with transfer type incorrectly

### ISSUE THREAD

**Issue by nistvan86** [moneymanagerex/android-money-manager-ex#1684]
When creating a share transaction for a stock investment (this type of transaction can be only created on the desktop app at the moment) and specifying the funding account (which is not a Share account) in the transaction details with transaction type "withdrawal + transfer" (which means the stock gets funded from the account) the transaction gets calculated incorrectly as expense in the Android app's "Income vs. Expense" report. The desktop Money Manager Ex correctly indentifies this as transfer.
(haven't tried but very likely the "deposit + transfer" combination gets also incorrectly calculated as income)

**Comment by guanlisheng** [comment]
#1551 related
