### ISSUE TITLE
Notifications are blocked?

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1685]
**Describe the bug**
I've noticed that since installing 2024.04.21, I've noticed that I've not been getting any notifications on my Samsung S22 running latest Android 14 update. When I try to tweak the notifications permissions this says it is blocked and I cannot change this. 

The notification options within the app can be turned on/off but this does nothing. Android is simply blocking them on the app. Also noticed that there are no other permissions available for the app, which seems weird seeing it should be able to write data to the device?

Not sure why this has broke?

**To Reproduce**
1. Go to settings / Apps
2. Find money mmx and try to change notification settings 
3. This is blocked by OS

**Expected behavior**
Should be able to enable notifications so scheduled task reminders are seen.

**Screenshots**
![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/76fdef07-c958-4a20-bed0-1b3907dc9561)

Notification button is protected from use.

**Device Information:**
 Samsung Galaxy S22
 Android 14 latest update
 256gb
 Sync enabled but only when so started.
DB not encrypted
2024.04.21
Anonymous logging enabled

**Additional context**

**Comment by smjohns** [comment]
Here is screenshot of no permissions. 

![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/6458594/396bcc06-b2e0-4fe5-8149-234063de896d)

**Comment by AceDenghar** [comment]
Hi,

Same here.

Can't turn on notifications on m'y mobile (Sony Xperia 5III running Android 13).

But ! On m'y tablet (Lenovo Tab p11 running Android 11) it's possible.

Regards.

**Comment by guanlisheng** [comment]
thanks, both. will take a look, seems it is android os version related.

**Comment by guanlisheng** [comment]
confirmed that it was caused by the target sdk upgrade to level33 (android13) from level31: https://github.com/moneymanagerex/android-money-manager-ex/pull/1664

do need an Android expert...

**Comment by guanlisheng** [comment]
advice from llm:

My friend! When updating your Android app's `targetSdkVersion` from 31 to 33, it's essential to consider the potential changes that may impact your app's functionality and user experience. Here are some key points to keep in mind:

1. **Privacy**: With Android 13 (API level 33), Google has introduced stricter privacy guidelines. You should ensure your app complies with these new standards, such as:
	* Requesting location permissions at runtime
	* Handling `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION` requests separately
	* Providing users with more granular control over their data sharing
2. **Permissions**: Android 13 introduces new permission types (e.g., `MANAGE_EXTERNAL_STORAGE`) and changes to existing ones (e.g., `READ_EXTERNAL_STORAGE`). Review your app's permissions to ensure they're still relevant and comply with the new guidelines.
3. **Storage**: With `targetSdkVersion` 33, apps can no longer request `WRITE_EXTERNAL_STORAGE` without a valid reason. You might need to adjust your storage-related code to accommodate these changes.
4. **Camera and Microphone Permissions**: Android 13 requires explicit permissions for camera and microphone usage. Update your app's permission handling to reflect these new requirements.
5. **Notification Changes**: API level 33 introduces new notification features, such as notification categories and custom actions. Review your app's notification system to ensure it takes advantage of these improvements.
6. **Layout Changes**: With Android 13, the layout of some UI components (e.g., `Toolbar`) has changed. Verify that your app's layouts are compatible with the updated design.
7. **API Level-Specific Code**: As you upgrade to API level 33, be mindful of any API-level-specific code or libraries that might require updates.
