### ISSUE TITLE
No operation possible after update

### ISSUE THREAD

**Issue by Egareg1** [moneymanagerex/android-money-manager-ex#1687]
**Describe the bug**
After updating to the last version, I can not edit, add or delete operations into an existing database. 

**To Reproduce**
1. Create a database into a previous version of MMex
2. Populate the database with operations
3. Update MMex to the last version 
4. It is impossible to add, delete, edit any financial operation into the database

**Expected behavior**

**Screenshots**

**Device Information:**
 - Device: [e.g. LG G7 ThinQ]
 - OS: [e.g. Android 8.1]
 - Storage: [e.g. Phone storage + Syncthing]
 - Synchronization: [e.g. Enabled with 5min interval and Sync on Start]
 - Encrypted: [e.g. Yes]
 - App Version: [e.g. 2023.12.06]

**Additional context**

**Comment by luisdev** [comment]
Which "last version" are you referring to?
Have you tried the [2024.05.02.1031](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.05.02.1031) version?

**Comment by 0xD503** [comment]
I have the same problem. More over, I've tried to install other versions of MMEX (2024.05.02, 2024.03.19, 2024.01.01) and failed to add new transactions with any of them. It appears the database has been corrupted.

**Comment by Egareg1** [comment]
New update processed via F-droid : the app is on version 2024.04.29 (1030) and all is working well ! 

I only update with F-droid.

**Comment by guanlisheng** [comment]
thanks, @Egareg1, and good to see it is working well now.

hi @0xD503, if the database is corrupted, you can re-open it from your remote storage (either in cloud storage or your phone's shared storage).
