### ISSUE TITLE
MMEX v2024.04.21 (1029): some reports not working

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/android-money-manager-ex#1688]
Report where money goes to and from does not work and gives error. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:**
 - Device: [e.g. LG G7 ThinQ]
 - OS: [e.g. Android 8.1]
 - Storage: [e.g. Phone storage + Syncthing]
 - Synchronization: [e.g. Enabled with 5min interval and Sync on Start]
 - Encrypted: [e.g. Yes]
 - App Version: [2024.04.21 (1029]

**Additional context**

**Comment by guanlisheng** [comment]
this is related with #1679 and has been fixed since [ v2024.04.29 (1030)](https://f-droid.org/packages/com.money.manager.ex/)
