### ISSUE TITLE
Switch between DBs requires password

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1695]
**Describe the bug**
If there is as example 2 DBs , one with passcode and the second without passcode , switching between them is not possible without enter the passcode if the last opened was that one with the passcode.

**To Reproduce**
1. Creat DB 1 without passcode
2. Creat DB 2 with passcode
3. Exit the app
4. Open the app to enter DB 1
5. Passcode screen appear to enter DB 2 , but i need to open DB 1 , which is not possible until enter the passcode to open the DB 2 first .

**Expected behavior**
Appelety to switch between DBs.

**Device Information:**
 - Device: Redmi note 12
- OS: Android 14
- Storage: Phone storage
- Synchronization: Enabled - never and Sync on Start
- App Version: 2024.05.09

**Comment by guanlisheng** [comment]
this is a known issue, just leave password empty/blank is not encrypted
