### ISSUE TITLE
Arabic translation update

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1698]
Hello ,

i have suggested more than 100 translations
And i couldn't see them in the new release 

![Screenshot_٢٠٢٤-٠٥-١٥-٠٩-٤٢-٣٨-٨٤١_org cromite cromite-edit](https://github.com/moneymanagerex/android-money-manager-ex/assets/7989030/54455780-fa84-46d0-936b-a560a236b313)

**Comment by guanlisheng** [comment]
maybe just b/c there was no i18n change in the new release you mentioned...

**Comment by islam2hamy** [comment]
Sorry i couldn't understand you , could you please give me an example ?

my ex.

![IMG_٢٠٢٤٠٥١٥_١٠٤٧٢٨](https://github.com/moneymanagerex/android-money-manager-ex/assets/7989030/1ff80560-6b97-4296-9bb4-1bc2ec041d91)

**Comment by guanlisheng** [comment]
crowdin to mmex needs some manual change like https://github.com/moneymanagerex/android-money-manager-ex/pull/1699

**Comment by islam2hamy** [comment]
> crowdin to mmex needs some manual change like #1699

Thank you

**Comment by guanlisheng** [comment]
hi @islam2hamy, can you have a try on the latest release v2024.06.14 which includes the Arabic updates

**Comment by islam2hamy** [comment]
Hi @guanlisheng , 
yes it is ok.
today i suggested 7 translations , is it will update automatically ?

**Comment by guanlisheng** [comment]
no, it will be updated periodlly
