### ISSUE TITLE
View reports by parent categories

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1700]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
i need to view reports grouped by parent category ,
and also the the parent category as total for the sub category

**Comment by guanlisheng** [comment]
@wolfsolver as awareness

**Comment by wolfsolver** [comment]
New nested category management can handle more the two level

Main idea for this is to have report with three columns:
- category
- total transaction in category 
- total transaction including subcategories

**Comment by islam2hamy** [comment]
Nice , thank you

**Comment by guanlisheng** [comment]
thanks @wolfsolver and @islam2hamy ,

existing category reports from mmex4destkop would be a great reference. here you go a thread in project forum. 
https://forum.moneymanagerex.org/viewtopic.php?p=25288#p25288

**Comment by wolfsolver** [comment]
@islam2hamy I'm working on new cagetogy management and report for category.

Can something like this is what you like?

as you can see all cagetogy has total of itself and all children, so when collapse you can see the total. Expanding a category you can see value assigned to category itself (example _house : 10) and all children.

Collapse view:

![Screenshot_20240828-101610.png](https://github.com/user-attachments/assets/77e7903a-2d1a-47f3-8b38-a2b9158ca16b)

Expanded view: 

![Screenshot_20240828-101619.png](https://github.com/user-attachments/assets/2b1b0bbc-ebda-4a79-80ee-5806275ff4ca)

**Comment by islam2hamy** [comment]
@wolfsolver 
It looks very good
