### ISSUE TITLE
Auto update/sync Google drive

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1702]
**Describe the  @[bug**

Modify db saved on gdrive and press sync I have an update failure (I have update alert on app but and error with notification on phone)
If i press upgrade button Sync seem to be ok (I have update alert on app but and  confirmation on app and notification on phone, with file updated )

**To Reproduce**
1. Go to 'open and modify a db saved on gdrive'
2. Click on 'sincronizzazione'
3. See error "update error"

**Expected behavior**
"The remote file has update at..."

**Screenshots**
![Screenshot_2024-05-16-16-19-35-28_56d4659ac84df734ec7538fc9956390c](https://github.com/moneymanagerex/android-money-manager-ex/assets/18198681/01a4f871-0d33-442e-a88a-8b15dc0e8a31)
![Screenshot_2024-05-16-16-18-35-14_56d4659ac84df734ec7538fc9956390c](https://github.com/moneymanagerex/android-money-manager-ex/assets/18198681/3e1a17f1-8484-4ab5-92c7-afe3b33a1d46)
![Screenshot_2024-05-16-16-17-47-39_f7aa348215f5d566f9e4ca860f474209](https://github.com/moneymanagerex/android-money-manager-ex/assets/18198681/9beb719a-3206-425b-9314-ecd2c3ca5ea5)
![Screenshot_2024-05-16-16-16-27-20_b783bf344239542886fee7b48fa4b892](https://github.com/moneymanagerex/android-money-manager-ex/assets/18198681/40b2bae6-8453-4cb8-b9c9-fe37bfe9cfde)

**Device Information:**
 - Device: oneplus 8t
 - OS: android oxygenOS 14
 - Storage: [google Drive]
 - Synchronization: Enabled with 5min interval and Sync on Start]
 - Encrypted: NO
 - App Version: 2024.05.09 1032

**Additional context**

**Comment by guanlisheng** [comment]
can you share more detailed steps to help reproduce the issue?

**Comment by Fabio1979Fabio** [comment]
Same problem. Not possibile update on Google drive but Money manager sad completed.

**Comment by Fabio1979Fabio** [comment]
![Uploading Screenshot_20240529_144942_Settings.jpg…]()

**Comment by Fabio1979Fabio** [comment]
![Screenshot_20240529_144942_Settings](https://github.com/moneymanagerex/android-money-manager-ex/assets/161082920/1450ecce-1a0c-441d-ad21-4e73d82aaf60)

**Comment by guanlisheng** [comment]
please refer to https://moneymanagerex.org/blog/mmex-cloud-storage-with-synology-drive/
