### ISSUE TITLE
Crash during automate testing

### ISSUE THREAD

**Issue by WhiteSeele** [moneymanagerex/android-money-manager-ex#1704]
05-03 17:29:18.855 31059 31059 E AndroidRuntime: FATAL EXCEPTION: main
05-03 17:29:18.855 31059 31059 E AndroidRuntime: Process: com.money.manager.ex, PID: 31059
05-03 17:29:18.855 31059 31059 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.money.manager.ex/com.money.manager.ex.search.SearchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManager.isDestroyed()' on a null object reference
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManager.isDestroyed()' on a null object reference
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performDetach(Fragment.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.detach(FragmentStateManager.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at com.money.manager.ex.common.MmxBaseFragmentActivity.onDestroy(MmxBaseFragmentActivity.java)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:6407)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
05-03 17:29:18.855 31059 31059 E AndroidRuntime: 	... 9 more

SDK: API 23

**Comment by guanlisheng** [comment]
hi @WhiteSeele, what kind of automated testing? are you an android developer
