### ISSUE TITLE
can not use and sync via dropbox

### ISSUE THREAD

**Issue by fraput** [moneymanagerex/android-money-manager-ex#1707]
**Describe the bug**
If i install ammx-2024.05.09-release.apk (on my smarthone i will asked new account or existing - or use yor cloud)
when i go to my dropox-app an chose my-file.mmb the file can no be opend - look sreenshots - dropbox can not give a pre-view, by klick open, there is mmx not in the option's to choose (only 3 other aps are offered - look screenshot) - so the way as descriptet is not usable!

an alternate way i hace testete does also not work!
if i use a own folder (\dropsync\mmex\my-fle.mmb) wich ist synchronised by dropsync, then i can first open the file wich is from my ubuntu-desktop.
Then the mmx-app stores the file in /storage/emilated/0/android/sata/com.money.manager.ex/files/database/my-file.mmb
if i say upload, ther is no new file in my dropsync-folder

**Screenshots**
![Screenshot_20240609_184021](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/0512fe1e-fca9-4ccb-b9ce-d28d5bc7e15a)
![Screenshot_20240609_184107](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/5bfcc03a-dd37-4b78-9d16-64a73e849500)
![Screenshot_20240609_184113](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/599287b6-b3b2-45b7-aa84-74809b517112)

**Device Information:**
 - Device: vivo x80 Lite
 - OS: Android 14
 - Storage: Dropbox
 - Synchronization: manualy or 1 hour
 - Encrypted: now
 - App Version: 2024.05.09

**Comment by guanlisheng** [comment]
please get synchronization enabled, refer to https://moneymanagerex.org/docs/features/usecloud/

**Comment by fraput** [comment]
This does not work!

Look Screenshots: 
I have made a change in the File, then my Ubuntu-Dropbox does upload the new file immediately.
(i have also testet to use the file on my local dropsync-foleer wich sync himself with teh dropbox)

both ways i have tried:
but the mmx app use "ONLY" the file in the local storage as written in the first message
/storage/emilated/0/android/sata/com.money.manager.ex/files/database/my-file.mmb - see screenshot

![Screenshot_20240610_134627](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/a2a16f3d-441c-42df-a92a-c9972f45e7fa)
![Screenshot_20240610_134635](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/79a5adf0-8c31-463d-a8b4-3e2d0f7cfe4f)
![Screenshot_20240610_134654](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/33b0d7cd-2483-4b74-9bd6-87841de25aa5)
![Screenshot_20240610_134704](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/cefa4832-8a47-4ce3-8d64-926f47c86877)
![Screenshot_20240610_134934](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/130cae60-511a-415c-a57f-4f5c30899fb1)

**Comment by fraput** [comment]
wich mor info you need - i think i have given oll infos - look at the screenshots :

i tray explain again:

1) on ubuntu 24.04 with MMEX 1.8.0 i have my File 20240609-Test-Android-Kopie.mmb 
2) the mmb-file ist storaged in my home folder ./Dropbox/dropsync/mmx/20240609-Test-Android-Kopie.mmb
3) the folder ./Dropbox allways do automatic sync the local file with the Dropboc-Cloud -  immediately with every change

4) i remove and install new ammx-2024.05.09-release.apk
5) ammx lets create a new db, or open a existing file on my device
5a) the file is not on the device - it is on the dropbox, in this case ...
5b) the app give order to open the file in my cloud (wich ist dropbox)
6) if i now go to my app-dropbox i chose there the folder /dropsync/
6a) if i would open the file 20240609-Test-Android-Kopie.mmb in the dropbox there my phone only give three apps (PassWallet / Google Wallet / Keepass2Android) to open the file.
6b) Ammx is installed but my phon can not handle the mmb-file - my phone does ammx not recognice as a app for open mmb-files ... does ammx by installing herself not set the necessary infos in my phone to open mmb-files?
6c) so i can not start my file from dropbox
6c) is ther the problem - how tells ammx my phon to open mmb-files? 

in the #1703 - ther is a info, that the user installed the app over f-droid on a other decive - is the apk-file from here for installig under google without f-droid not right designed?

**Comment by guanlisheng** [comment]
The APK file from GitHub and f-droid are the same. 
these configurations are helpful, great if you could provide your android dropbox version. 

can you continue 5b to re-open the files from your Dropbox folder to see whether the number looks correct?

**Comment by fraput** [comment]
first of all thank you for your efforts and patience 

Dropbox-App Version 380.2.2

i don't understand what re-opening should show ?
there is no number
i get only a popup message to chose on of the three options, PassWallet or Google Wallet od Keepass2Andriod (behind the popup is only a draw with a horse  no text) - see scrennshot, and there is no option to continue , ther is no number - i only can stop with return

![Screenshot_20240611_202148-1](https://github.com/moneymanagerex/android-money-manager-ex/assets/115357540/168d0995-7c7e-45da-8873-dc2f8f98ad55)

**Comment by guanlisheng** [comment]
in your Android mmex, `main menu -> database -> open`...

Dropbox here is just cloud storage, so far, there is no linkage between the database file and Android mmex yet.

**Comment by guanlisheng** [comment]
forget about the linkage, it is for something else.  please ignore old version as well, as latest version support other data providers (e.g. google Drive) as well.

@fraput 
back to your request here `i want to use the existing file stored in dropbox!`
clicking `main menu -> open database -> other` will have a file explore and you should find Dropbox option there. 

here we go an example to open file stored in Synology Drive.
![mmex_nas](https://github.com/moneymanagerex/android-money-manager-ex/assets/721973/65548c03-1080-42c3-9aa6-2cc9bc5f4a33)

**Comment by guanlisheng** [comment]
I'm confused as your first comment showed that the database file is from Dropbox. 

`main menu -> open database -> other` will open the file from any available data provider, then mmex sync and data provider will handle sync periodically

**Comment by fraput** [comment]
oh sorry, so it works.

if mmx start, there are 2 big buttons one for create and one for existing.

for files on a cloud the information for opening is UNDER the second button, so it sings me not use the above butten "existing".
so i have opend die droppox app - i have wirtten this!

i think the info to open cloud-files also over the button "existing" (and ther serach for the cloud is not) would be necessary to - so it avoid misunderstanding.

I have intrpratet the infos for cloud no so as it was considered.

Sorry for the complicate way to clear the problem and thanks for your patience with me.

1000 Thanks!

**Comment by fraput** [comment]
oh sorry, so it works.

if mmx start, there are 2 big buttons one for create and one for existing.

for files on a cloud the information for opening is UNDER the second button, so it sings me not use the above butten "existing".
so i have opend die droppox app - i have wirtten this!

i think the info to open cloud-files also over the button "existing" (and ther serach for the cloud is not) would be necessary to - so it avoid misunderstanding.

I have intrpratet the infos for cloud no so as it was considered.

Sorry for the complicate way to clear the problem and thanks for your patience with me.

1000 Thanks!

**Comment by guanlisheng** [comment]
great and thanks @fraput. 

any suggestion on the desc to avoid misunderstanding?

here you go an article on mmex + Synology drive, feedback is welcomed.
https://moneymanagerex.org/blog/mmex-cloud-storage-with-synology-drive/
