### ISSUE TITLE
Cannot specify amount to destination account in transfer transaction.

### ISSUE THREAD

**Issue by dmaroulidis** [moneymanagerex/android-money-manager-ex#1711]
**Describe the bug**
Cannot input the destination's account amount to a transfer transaction. There's is only one text field, which shows the transfer amount. If I add a transfer transaction with two values (one deducted from originating account and another one with the amount credited to the destination account) on MMEX desktop and sync the DB to my phone, I can see the correct values in each account, but if I try to edit the transaction I only get the amount to the destination, likely because of #1067. 

**To Reproduce**
1. Create new transaction
2. In the transaction screen that opens fill in all required details. 
3. There's no field where you can input the amount that is transferred to the account, only a field for the amount transferred from the originating account.

**Expected behavior**
I expect two field for the amount transferred, like MMEX on Linux (desktop): one for the amount deducted from the originating account and one for the amount credited to the destination account. In MMEX there's an advanced checkbox which enables the second field (to the destination account). 

**Screenshots**
MMEX desktop:
![Screenshot_20240611_171804](https://github.com/moneymanagerex/android-money-manager-ex/assets/4481276/2032c707-3cf4-4877-975f-d47e0cb85f89)

MMEX Android:
![Screenshot_2024-06-11-17-21-49-64_56d4659ac84df734ec7538fc9956390c](https://github.com/moneymanagerex/android-money-manager-ex/assets/4481276/0e4cc91f-8667-4b11-94fd-f0ee843d6aa5)

**Device Information:**
 - Device: OnePlus 9R
 - OS: Android 14
 - Storage: Phone storage + Nextcloud
 - Synchronization: Enabled with 1 hour interval and Sync on Start
 - Encrypted: No
 - App Version: 2024.05.09 (1032)

**Comment by guanlisheng** [comment]
thanks @dmaroulidis for trying MMEX.

also interested your nextCloud synchronization, so far so good?

**Comment by guanlisheng** [comment]
also, @dmaroulidis, the amountTo would be available when the from/to account in different currencies
