### ISSUE TITLE
App unnecessarily asks for passcode when opening database

### ISSUE THREAD

**Issue by bgvr0607** [moneymanagerex/android-money-manager-ex#1718]
**Describe the bug**
The App asks for a passcode when opening a database that is not protected by password. Also passcode feature in the app is not activated. When clicking ok without entering anything the database is opened normally.

**To Reproduce**
Open any database without password protection, while also passcode in the app is deactivated.

**Expected behavior**
There should not be any dialogue to enter a passcode when the database is not protected and the passcode feature in the app is deactivated.

Device: OnePlus 8T
OS: OxygenOS 14.0 (Android 14)
Storage: Sync to Dropbox
Encrypted: No
App Version: 2024.06.14(1033)

**Comment by guanlisheng** [comment]
this is a known issue to support database encryption (AES256/SQLCipher). 

note that password is for encrypted database while passcode is for mmex application access.
