### ISSUE TITLE
v2024.05.09 (1032) onwards : Scheduled transactions 

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/android-money-manager-ex#1719]
In v1031 there was no automatic entering of scheduled transactions. Now in v1032 onwards the scheduled transactions are automatically entered. There must be a feature in scheduled transaction whether it should be automatic or after reminder notification. In android 14 the sideloaded apps the notifications are blocked. So please add feature to enter manually after a popo up

**Comment by guanlisheng** [comment]
thanks @rmkhalfay for trying mmex, and this feature is related to #1683

**Comment by guanlisheng** [comment]
please try https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.06.25.1034 and going to close this issue.

**Comment by rmkhalfay** [comment]
Thank you for the efforts taken. I have s23 ultra and Android 14. I tried this it gives me a notification but does not give a choice whether to enter the scheduled transaction or not. Sometimes although the transaction is scheduled it is not executed due to some delay.

I would like if it asks me can I enter this transaction or not?
