### ISSUE TITLE
Cannot open encrypted database

### ISSUE THREAD

**Issue by BeHappy2021** [moneymanagerex/android-money-manager-ex#1724]
Android app fails to open an encrypted database (emb) created in the desktop app. Gives an error that the file is not a database when running select(*).... in a toast that quickly disappears.

**Expected behavior**
Expect both apps to be able to open the file.

I have read the other issues about encryption:
[#135](https://github.com/moneymanagerex/android-money-manager-ex/issues/135)
[#1454](https://github.com/moneymanagerex/android-money-manager-ex/issues/1454)

The second one says that the aim for encryption to work across platforms is v1.7.2 but I have a newer version. Just checking to see if this is a me issue or if the update of the desktop app has been pushed back.

**Device Information:**
 - Device: Windows PC and Android phone
 - OS: Windows 10 and Android 13
 - Encrypted: Yes
 - App Version: Desktop = v1.8.0, Android = 2024.06.14

**Comment by guanlisheng** [comment]
thanks, @BeHappy2021 for trying MMEX and its encryption.  

For mmex4desktop, we might have to wait a while currently, the master branch is supporting AES256.

**Comment by guanlisheng** [comment]
some information would be found https://forum.moneymanagerex.org/viewtopic.php?t=11016

**Comment by BeHappy2021** [comment]
Thank you for clarifying this. So from the forum it looks like v1.8.1 will be the version were the encryption works across Android and desktop. That is great news!

**Comment by guanlisheng** [comment]
@vomikan , @whalley and @renato-mmex as fyi

**Comment by BeHappy2021** [comment]
Was just looking around as there have been several updates to the android app and found the link to the [Milestones](https://github.com/moneymanagerex/moneymanagerex/milestones) page for the desktop app.

Updating the encryption in the desktop version to match the android app is listed in the closed issues.

**Comment by guanlisheng** [comment]
yup, and you can have a try on desktop night build version.
