### ISSUE TITLE
Execution scheduled transaction overdue is not working if app stills running


### ISSUE THREAD

**Issue by AceDenghar** [moneymanagerex/android-money-manager-ex#1736]
**Describe the bug**
Hello,

I noticed that, if the app was not shutted off, the execution of scheduled transaction does not work.

I have to kill the app then to launch it again.

So it seems working only on a 'fresh' start of the app. In my case, because I want to use the auto sync feature of the db every 10mn, I set android to not manage battery for the app. So it never stops working.

And even if the notifications of scheduled transaction overdue are working well, the execution of scheduled transactions is not.

Can you check this point ?

It's a fantastic feature and that's the only problem I can detect.

Thanks for all !

PS : sorry for my English

Mathieu.

**To Reproduce**
Configure Android to not manage battery for the app or ensure it's not killed by any other process and wait for the time of scheduled transaction overdue.

**Expected behavior**
Execution for scheduled transaction overdue at setted time, not only at app's launch because it will never append if app is not exited/killed.

**Device Information:**
 - Storage: SDcard (synchronized folder with ResilioSync for multi device use)
 - Synchronization: Enabled with 10min interval and Sync on Start
-  Notification Scheduled transaction overdue : enabled
- Execution Scheduled transaction overdue : enabled
- Notification time : 8:00 am
 - App Version: [e.g. 2024.07.04]

**Additional context**

**Comment by guanlisheng** [comment]
thanks, @AceDenghar for reporting the issue and trying MMEX. so far, this is a known issue.

**Comment by wolfsolver** [comment]
@guanlisheng I think that we can move execution for schedule transactions from main activity into notification. What do you think?

I try to make same changes in next days

**Comment by guanlisheng** [comment]
that is a great idea although a little bit complex. i think you can help improve it with the idea in your mind.

**Comment by wolfsolver** [comment]
Done (with two minor issue where I need some suggestions)
See pr #1742

**Comment by wolfsolver** [comment]
@guanlisheng can you close this issue?

**Comment by guanlisheng** [comment]
hi @wolfsolver , i would like defer it to the reporter @AceDenghar

**Comment by AceDenghar** [comment]
Hi,

Of course I can do that !

Thanks for all, you're great 👍
