### ISSUE TITLE
Split transactions: unable to add or modify for an edge case

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1741]
For split transactions, if the number of transactions is higher than that can be displayed on the screen, we are unable to add a new transaction (button + is displayed when opening the screen but is not displayed when we navigate on this screen).

And the last transaction is not displayed correctly, only half of it. See screenshot. So unable to add a comment.

![Screenshot_2024-07-25-09-08-29-880_com money manager ex](https://github.com/user-attachments/assets/89560d12-4f24-4f94-bf34-947374ce3022)

**Device Information:**
 - Device: POCO M3 Pro 5G
 - OS: Android 13
 - App Version: 2024.07.04.1035

**Comment by luisdev** [comment]
I've just created a split transaction in AMMEX version 2024.07.04 (1035) on my Samsung S22 Ultra with 14 splits (categories) in it and I can see all of them - but the Notes field on the very last split item is hidden. But, if I scroll up a bit, and then scroll down all the way I can see the Notes field that was previously hidden.

What I did notice though, is that the green + button that you use to add new splits to the transaction is missing. If I close the split transaction screen and then open it up again, the green + button reapperas - until I scroll down on that split transaction screen. When I scroll down it disappears and doesn't come back again when I scroll up or down again.

**Comment by jeepcook** [comment]
Thanks for your tests.

Ok exactly the same for me for the second part (green + button that doesn't come back).

For the 1rst part in my Poco M3 Pro 5G, I am unable to display the last note after a scroll up/down.

**Comment by luisdev** [comment]
When I start scrolling down, the green + icon disappears for me and I can't add any more split items. I have to close and re-open the split transaction screen. When I do re-open it, the + icon is there again - until I scroll down. It disappears again as I scroll down. It doesn't re-appear again when I scroll up.

**Comment by jeepcook** [comment]
> When I start scrolling down, the green + icon disappears for me and I can't add any more split items. I have to close and re-open the split transaction screen. When I do re-open it, the + icon is there again - until I scroll down. It disappears again as I scroll down. It doesn't re-appear again when I scroll up.

Yes it's exactly the same bug for me

**Comment by guanlisheng** [comment]
hi @jeepcook , @luisdev , 
can you test it out for the latest release?

**Comment by jeepcook** [comment]
Hi, yes this has been solved.
Thanks.

**Comment by luisdev** [comment]
> hi @jeepcook , @luisdev , can you test it out for the latest release?

Yes, this problem seems to be fixed in build 2024.08.13 (1037).
Thank you
