### ISSUE TITLE
Remote Path Button Does Nothing

### ISSUE THREAD

**Issue by coy-yote** [moneymanagerex/android-money-manager-ex#1751]
**Describe the bug**

On a fresh install, I initially navigate to settings and try to add a remote path. The button registers but does not do anything 

**To Reproduce**

1. Go to settings
2. Tap 'database'
3. Tap 'remote path'

**Expected behavior**

I expect this to launch a file dialogue where I can add a new file

**Screenshots**
Screen recording of what I'm seeing:

https://github.com/user-attachments/assets/4a153c4b-110e-433a-aa6f-a7e95d737b4f

**Device Information:**
 - Device: Pixel 7
 - OS: GrapheneOS // Android 14 // Build  2024080500)
 - Storage: Syncthing is the goal
 - Synchronization: n/a
 - Encrypted: n/a
 - App Version: 2024.08.01

**Comment by luisdev** [comment]
I see the same issue on my Samsung Galaxy S22 Ultra and MMEX 2024.08.01 (1036).

**Comment by wolfsolver** [comment]
It is not a button. Is an information on where (if DB is opened from remote storage archive) the remote file is stored.

@guanlisheng can you confirm?

**Comment by guanlisheng** [comment]
hi @coy-yote, it seems you upgraded from a very old mmex. I suggest `Export Database` to your phone's storage (e.g. Downloads or Documents folder). then reopen it via the MMEX app.

@wolfsolver your understanding is correct, and this remote would be in any BYOC (e.g. phone's storage or cloud providers).

**Comment by coy-yote** [comment]
Thanks for the reply! I ended up downgrading to the previous version in F-Droid (2024.07.04) to set up the export and it worked great. After that I upgraded again and it all worked.

Aug 8, 2024, 07:54 by ***@***.***:

**Comment by guanlisheng** [comment]
hi @coy-yote, this is great and I'm closing this ticket
