### ISSUE TITLE
Doesn't build with jdk 16+

### ISSUE THREAD

**Issue by linsui** [moneymanagerex/android-money-manager-ex#1758]
**Describe the bug**
```
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> superclass access check failed: class butterknife.compiler.ButterKnifeProcessor$RScanner (in unnamed module @0x26dea832) cannot access class com.sun.tools.javac.tree.TreeScanner (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x26dea832
```

https://github.com/JakeWharton/butterknife/issues/1686
https://github.com/JakeWharton/butterknife/issues/1665

butterknife doesn't work with new jdk. It has been discontinued and https://developer.android.com/topic/libraries/view-binding should be used instead.

**To Reproduce**
1. Build with jdk 16+

**Expected behavior**
It should build.

**Screenshots**

**Device Information:**
 - Device: [e.g. LG G7 ThinQ]
 - OS: [e.g. Android 8.1]
 - Storage: [e.g. Phone storage + Syncthing]
 - Synchronization: [e.g. Enabled with 5min interval and Sync on Start]
 - Encrypted: [e.g. Yes]
 - App Version: [e.g. 2023.12.06]

**Additional context**

**Comment by guanlisheng** [comment]
hi @linsui , is it from f-droid ?

**Comment by linsui** [comment]
I'm from F-Droid. :) We have upgrade the buildserver to bookworm and jdk 17 is the default jdk now. https://gitlab.com/fdroid/fdroiddata/-/commit/12a2f57b938adf3363e6c30caa37d6b670ec2562#2283d9a8b793e2d17557fb0131a1cb86f3f2e6fa_243_238

**Comment by guanlisheng** [comment]
thanks, will take a look

**Comment by guanlisheng** [comment]
hi @linsui 
we just deprecated butterknife from master branch, i wonder whether you can help to verify it?

**Comment by linsui** [comment]
> java.lang.IllegalAccessException: class clojure.lang.Reflector cannot access class com.sun.tools.javac.processing.JavacRoundEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @6237e969

There are other libs that doesn't work with jdk 17.

**Comment by guanlisheng** [comment]
hey @linsui , it should be okay with JDK17 now. can you help to verify it again?

**Comment by linsui** [comment]
It works, thanks!
