### ISSUE TITLE
Dropbox sync hangs when using manually opened database

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#176]
Scenario:
- set up dropbox sync, download database, use it normally,
- Open Database. I used another synced db that I use for development.
- run Synchronize option from dashboard.

The Synchronizing File message stays on screen and can not be removed.

I find this to be a weird combination. We should work out what happens in the scenario when a user opens a different database than the one which is specified in Dropbox settings.

Also, I wonder what happens when, in the file selector, Dropbox is chosen as the source. Will the sync work with that?

**Comment by AlessandroLazzari** [comment]
This is a bug!
