### ISSUE TITLE
Key "Equal" in calc does not enter amount

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1786]
**Describe the bug**
In older release, if I remember well, when entering amount and press "=" key the amount is transfered to transaction and calc is closed. Right now press "=" do nothing

**To Reproduce**
1. form home Press "+" button
2. Click on Amount
3. enter value and press "="
4. nothing appaer

**Expected behavior**
step 4 need to close the calc and transfer amount to transaction (as done for "V" key on top right)

**Comment by guanlisheng** [comment]
great catch. had been fixed in master branch
