### ISSUE TITLE
Handling financial year in report

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1790]
In all report (payee, where money go/come/category) date filter contain:
- custom date
- current month
- previous month
- last 30 days
- current year
- last year
- all date

**Describe the solution you'd like**
Under setting / database there is option to specify financial year start (day/month).
Need to have additional entry in range selector for:
- current fiscal year
- previous fiscal year

**Additional context**
For example I use financial year starting 1 of April, so is usefull I this can be handled directly, without manual insert dare in custom date.
I'm my example (August 2024) date will be
- current fiscal year: 01/04/2024-31/03/2035
- previous fiscal year 01/04/2023-31/03/2024

**Comment by wolfsolver** [comment]
@guanlisheng to you think that can also be useful in transaction list option for 
"Current fiscal year"?

![Screenshot_20240901-193610.png](https://github.com/user-attachments/assets/2f24222a-cf85-4cb1-9baa-044be250c98f)

**Comment by guanlisheng** [comment]
that would be great to have financial related.
