### ISSUE TITLE
Scheduled Entries not processing

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1798]
**Describe the bug**
Have lots of scheduled transactions set up and have Money set to not issue notifications about these but to process then automatically. Unfortunately the ones set for 1st September did not process this month when they all worked last month. I tried enabling notifications and these are being created ok. I tried disabling and re-enabling the auto process setting but it only processed one or two of the September transactions and left the rest of them outstanding.

**To Reproduce**
1. Set up scheduled transactions with next due date 01/09/24.
2. Enable processing of scheduled transactions. 
3. Close and reopen money. All transactions for 01/09 should process. But they have not.

**Expected behavior**
Scheduled transactions for 01/09 should process automatically

**Screenshots**
![Screenshot_20240901_112056_Money Manager Ex](https://github.com/user-attachments/assets/cd105de1-c33f-4c38-9207-5ddf75bef146)
![Screenshot_20240901_112136_Money Manager Ex](https://github.com/user-attachments/assets/54af6ce5-0943-45ca-ab3f-b1c6ba951be7)
![Screenshot_20240901_112203_Money Manager Ex](https://github.com/user-attachments/assets/370b3aa3-3728-4418-910d-7de67e728d3d)

**Device Information:**
 - Device: Samsung s22
 - OS: Android 14
 - Storage: 256gb
 - Synchronization: Enabled on opening app.
 - Encrypted: No
 - App Version: 2024.08.13

**Additional context**
This was all working but seems to have stopped

**Comment by guanlisheng** [comment]
hi @smjohns, thanks for reporting the issue. can you share your `三->Settings -> Behavior` screen?

@wolfsolver , do you have any sense on this issue?

**Comment by smjohns** [comment]
![Screenshot_20240901_113714_Money Manager Ex](https://github.com/user-attachments/assets/d5bbbb45-d38a-45a0-8ce5-1c14f68a78fa)

**Comment by guanlisheng** [comment]
great. can you pick one of scheduled transactions and check its `AUTO TRANSACTION` setting?

**Comment by smjohns** [comment]
Oh... That is a new setting? It seems most of my schedule transactions were set to manual. I've changed them to automatic so hopefully they will apply ok next month

**Comment by smjohns** [comment]
Might not be related, but can anyone else replicate an issue where the list of items corrupt when your scroll up and down a list quickly? 

![Screenshot_20240901_115059_Money Manager Ex](https://github.com/user-attachments/assets/d1876e19-557e-41ce-af9a-024d81c694f2)

**Comment by smjohns** [comment]
It is easier to replicate on the schedule transactions list

**Comment by wolfsolver** [comment]
You can also try using last version 2024.08.25 

Keep in mind that schedule now using also use recurring type as in desktop version

Can you check how "Auto transaction" field is set in your recurring transaction?

![Screenshot_20240901-125635-376.png](https://github.com/user-attachments/assets/4a6d312a-d08a-41a0-b140-cffdc56c85fe)

**Comment by smjohns** [comment]
Yes thanks. I think that was the problem. The affected transactions were set to manual although they were created before that setting existed. Hopefully sorted now

**Comment by wolfsolver** [comment]
> Might not be related, but can anyone else replicate an issue where the list of items corrupt when your scroll up and down a list quickly? 

I have a lot of recurring transactions, but no issue when scrolling fast

**Comment by wolfsolver** [comment]
Unable, for me, to reproduce fast scrolling issue

**Comment by wolfsolver** [comment]
@smjohns  is the scroll problem still exist, please open a new issue.

**Comment by smjohns** [comment]
Yes can still replicate but only seems to happen in the a scheduled Transaction list.
