### ISSUE TITLE
Schedule Transactions list display corrupts with rapid scrolling

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1817]
**Describe the bug**
When on scheduled transaction list view if you rapidly scroll top to bottom of the list repeatedly, it triggers the displayed list items to overlay over each other. Haven't been able to replicate on account lists.

**To Reproduce**
1. Go to Scheduled Transactions list when you have lots of transactions (over a single page).
2. Scroll the list to bottom and then scroll to top. Repeat this rapidly into you see the display corrupts. Sometimes this happens with a few scrolls and sometimes you need to repeat 10 or more times.
3. See screenshot.
4. To reset the display, simply exit scheduled transactions and then return to that list or go to another app and then return to money.

**Expected behavior**
List should scroll without this corruption.

**Screenshots**
![Screenshot_20240905_121031_Money Manager Ex](https://github.com/user-attachments/assets/0f6145d7-652d-492e-ad36-15150dd12b13)

**Device Information:**
 - Device: Samsung S22
 - OS: Android 14
 - Storage: 256gb
 - Synchronization: Enabled on app startup only.
 - Encrypted: No
 - App Version: 2024.08.25 (1038)

**Additional context**

**Comment by wolfsolver** [comment]
@smjohns did you still have this issue? I try it on different real device without able to replicate.

**Comment by wolfsolver** [comment]
Top
