### ISSUE TITLE
"Income vs. Expenses" report calculates share transaction with transfer type incorrectly #1684

### ISSUE THREAD

**Issue by sudhegan** [moneymanagerex/android-money-manager-ex#1819]
**Describe the bug**

The bug mention in #1684 is closed but not rectified
still android app  calculates transfer as expense

**To Reproduce**

use mmex with syncthing between Linux (Flatpak) install app and android

**Expected behavior**

the transfer to investment account (share account) should not be calculated as expense

(it should be calculated as in desktop app)

**Screenshots**

**Device Information:**
 - Device: Moto edge 30
 - OS:  Android 14
 - Storage: Phone storage + Syncthing
 - Synchronization: Enabled with 5min interval and Sync on Start
 - Encrypted: no
 - App Version: 2024.08.25

**Additional context**

**PC Information:**
 - Device: Dell Optiplex 3020
 - OS:  Arch linux
 - Storage: PC + Syncthing
 - Synchronization: Enabled with 5min interval and Sync on Start
 - Encrypted: no
 - App Version: 1.8.0 64-bit (Flatpak Install)
-  Built on: Jul 22 2024 15:01:28
-  Database version: 19 (aes128cbc)
-  Git commit: 3325705 (2024-04-29)

**Comment by guanlisheng** [comment]
thanks @sudhegan, will take a look shortly.

**Comment by guanlisheng** [comment]
hi @sudhegan,
Can you describe your case in detail so we can reproduce the issue?

so far, the internal transfer is not counted in both apps.

**Comment by guanlisheng** [comment]
just created a demo database with two accounts and made a $100 transfer from `checking` to `share`.  
is the following/current report expected?

![Screenshot_20240908_135619](https://github.com/user-attachments/assets/276b6da1-e348-4855-9f19-2290d340e1b4)
![Screenshot_20240908_135419](https://github.com/user-attachments/assets/4e01d5c1-64d6-4f66-8296-67eb783eef96)

**Comment by guanlisheng** [comment]
add @nistvan86  to figure out this issue together.

btw, @sudhegan, if everything goes well, would you help write an article about MMEX+Synching?

**Comment by sudhegan** [comment]
i'am attaching the screenshots now, i dont have any experience in writing article but i'm happy to do it with some guiedence, by add means mentioning @nistvan86  right!!

**The income vs expense is offset by 50000**
![Screenshot_20240909-090300-edit-20240909090913](https://github.com/user-attachments/assets/84015ceb-e6e4-4eae-a5ba-b13bbea26b66)

**which is a transfer to share accounts**

![Screenshot_20240909_091150](https://github.com/user-attachments/assets/8f2bcf26-2bd7-4772-926e-b3181b1e0aa7)

**which shows correctly in desktop**

![Screenshot_20240909_090119](https://github.com/user-attachments/assets/e08058a2-11b2-4d75-a376-e8fecb2c701b)

**Comment by nistvan86** [comment]
Reproduce:
- Create 2 accounts: a main checking account, and an investment account
- In the Stock Portfolio tree select the investment account, then create a new initial stock investment for some instrument (right click table -> Create New Stock Investment), with the initial shares of 0. When asked to create an associated Share Account click cancel. The instrument should appear.
- Right click on the instrument, click Add transaction. Select the Main checking account as account, enter some amount (share number * share price = amount), the Type should be Withdrawal, and tick the "Transfer" checkbox next to it. For Payee create some payee eg. "My Broker" or something. Status should be Reconciled. The table now should show the Curr. Total Value calculated.

Here's a minimal db with this: [test.zip](https://github.com/user-attachments/files/16926357/test.zip)

Check:
- Desktop: Go to Income vs. Expense report, it should show nothing, as you ticked "Transfer" which means the stock investment should be considered transfer from one account to another.
- Desktop: Go to the main Dashboard, the Income vs. Expense: Current Month should also show zero expense.
- Android: Both the bottom status bar on the main screen shows expense, as well as the Reports > Income Vs. Expense part.

**Comment by guanlisheng** [comment]
Actually this is an `Withdrawal` transaction, seems with some tricks.
![Snip20240909_7](https://github.com/user-attachments/assets/305720c0-6e70-4a55-9636-e40c36354a38)

**Comment by guanlisheng** [comment]
seem Income vs Expenses  at Android does not honor Investment's metrics though Android's homepage(account list) does.

will take a deep look and get back here soon

![Snip20240909_8](https://github.com/user-attachments/assets/459c57b3-4424-413e-9c29-00f0acb8c2e3)
![Screenshot_20240909_163234](https://github.com/user-attachments/assets/c3ab5e18-a21a-443e-a5fd-9b011a6e108a)

![Screenshot_20240909_163251](https://github.com/user-attachments/assets/d176648c-c6cb-4135-9595-48f4a6b1d9a8)

**Comment by sudhegan** [comment]
the issue is solved in  #1824 #1825
