### ISSUE TITLE
Unreadable error message when opening database

### ISSUE THREAD

**Issue by kartun83** [moneymanagerex/android-money-manager-ex#1820]
**Describe the bug**

**To Reproduce**

1. Create new database in dedicated folder (in my case /mmex on internal storage)
2. Define database as default
3. Add transaction
4. Wait for some time (not sure, may be hour or more)
5. Application refuse to open database, and some truncated message is displayed, but since it's truncated it's totally unclear how to proceed further.

_As temporary workaround clearing app storage and cache allow to open saved DB._

**Expected behavior**
Error message must be fully visible and the error message must explain what was happened and how to proceed further.
In this particular scenario application shouldn't display any error messages and open DB.
If this behavior is related to the Android permissions or other restrictions this must be displayed at the time when the DB is created and storage location is defined.

**Screenshots**
![photo_2024-09-06_23-10-50](https://github.com/user-attachments/assets/507e4953-414b-41ff-86af-9ba98f7f961d) 
![photo_2024-09-06_23-10-38](https://github.com/user-attachments/assets/e28a382d-589f-424b-8c29-2e216225db63)

**Device Information:**
 - Device: Xiaomi 13
 - OS: Android 14 (Paranoid Android 20240822)
 - Storage: Phone storage + Syncthing
 - Synchronization: Enabled with 5min interval and Sync on Start
 - Encrypted: Yes
 - App Version: 2024.08.25

**Additional context**

**Comment by guanlisheng** [comment]
hey, @kartun83 

may I have your database name extension? 
there is a known issue or assumption that "*.emb" has a password while "*.mmb" should have blank password.

**Comment by guanlisheng** [comment]
combining with https://github.com/moneymanagerex/moneymanagerex/issues/6858, I think you can have a try with **.emb** extension.

**Comment by kartun83** [comment]
Yes, it's mmb. By default program suggest creation of mmb and it's not written anywhere it should be manually changed.

**Comment by guanlisheng** [comment]
yup, it is a known issue without a good hint yet. can you help to make it better? @kartun83
