### ISSUE TITLE
Cannot preview attachment, app closes brutally 

### ISSUE THREAD

**Issue by BoubouleThai** [moneymanagerex/android-money-manager-ex#1826]
When I add a file to a transaction in the PC, all is good. The file is attached and I can see it.
In the android app I can read ATTACHMENTS and the name of the the attachment file (I tried with pdf and also jpg)
But when I touch the preview button, the app closes brutally.
pdf attachment or jpg attachment has the same problem. 
![Screenshot_20240912_173603_Money Manager Ex](https://github.com/user-attachments/assets/c5e01595-3fa3-41e5-ab2f-033ea17624f3)
![Screenshot_20240912_173201_Money Manager Ex](https://github.com/user-attachments/assets/6c75666b-29f7-4e7e-a533-ec357e2cc36a)

2024-09-11. 1039 (but same with 1038,1037...)

**Comment by guanlisheng** [comment]
thanks, @BoubouleThai, the attachment preview is still in the pre-mature stage due to complex privacy and permission from the Android ecosystem. 

A workaround** is to use MMEX to try open your files once. then the file's preview would work.

**Comment by BoubouleThai** [comment]
Thanks for answer.
The workaround doesn't work.

So
I read the name of the attachment file in the transaction
Then I go search and open it with the file application in the mmx
attachment application folder. 😊

Le dim. 15 sept. 2024, 06:25, Lisheng Guan ***@***.***> a
écrit :

**Comment by guanlisheng** [comment]
do you follow the suggested (hardcoded) folder tree?

https://moneymanagerex.org/docs/features/attachments/

**Comment by BoubouleThai** [comment]
yes, I follow 😊

Le lun. 16 sept. 2024, 00:42, Lisheng Guan ***@***.***> a
écrit :

**Comment by BoubouleThai** [comment]
I can see there is an attachment, I see the path and name but if I choose
the preview.. mmx android closes

Le lun. 16 sept. 2024, 00:42, Lisheng Guan ***@***.***> a
écrit :

**Comment by guanlisheng** [comment]
if you follow the suggested folder tree to sync the attachments and use MMEX's open -> other to see (actually it is to grant permission), the attachment preview should function.

anyway, this feature is still not mature yet, and will put more effort in the near future. 

+ @wolfsolver as awareness.

**Comment by BoubouleThai** [comment]
Le lundi 16 septembre 2024 à 12:32, Lisheng Guan ***@***.***> a écrit :
if you follow the suggested folder tree to sync the attachments and use MMEX's open -> other to see (actually it is to grant permission), the attachment preview should function.
anyway, this feature is still not mature yet, and will put more effort in the near future.

@wolfsolver as awareness.


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/moneymanagerex/android-money-manager-ex/issues/1826#issuecomment-2352548814",
"url": "https://github.com/moneymanagerex/android-money-manager-ex/issues/1826#issuecomment-2352548814",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]okI will verify and try again.Thanks

**Comment by BoubouleThai** [comment]
When I use mmex's open>other, , I see all my attached files.

If I try to open one I have a message that it is not a database 😉

Go back to the account
Open the transaction with attachment file
Try to preview and the app close and open quickly with a pop-up message
"database is up to date"
If I try again I have an android message telling that this application has
a bug and closes frequently.

my folder tree is like that  : (on google drive)


/MoneyMMX/Attachments/Transaction/

works very good on PC

Le lun. 16 sept. 2024, 12:32, Lisheng Guan ***@***.***> a
écrit :

**Comment by guanlisheng** [comment]
hi @BoubouleThai 
just refined it by providing `Setting -> Per-Database -> Attachment Folder`, 
can you have a verify by installing latest build in https://drive.google.com/file/d/1bMBe0KSuiU5YprrKqT8yzO1epQJjtTtR/view?usp=sharing
