### ISSUE TITLE
Loop error message on second app run

### ISSUE THREAD

**Issue by dcprojects** [moneymanagerex/android-money-manager-ex#1828]
**Describe the bug**

Fresh installation. After 1st run, saved a database and closed the app. Once the app is opened again, an error pop up repeatedly "Error: the passphrase appears to be cleared. This happens by default the fir...". It ask to add a new bank account but you cannot choose currencies (list is empty, unlike first run). 
If you try to open the database from the hamburger menu, the file content is not shown (ask again It ask to add a new bank account but you cannot choose currencies).
Deleting the file from the system file manager still prompt crashes the app on opening (still prompt the error message). Clearing the app data the file can be opened once, but then the error returns on the next app run.

**To Reproduce**
1. Install the app
2. On first run, create "my_db.mmb", set password to "1234" (just to keep it simple)
3. Close the app
4. Open the app, the error message appears. The file cannot be opened.

**Expected behavior**
I expect to open the file saved on the previous session

**Screenshots**

**Device Information:**
 - Device: Sony Xperia 1 VI
 - OS: Android 14
 - Storage: Phone storage
 - Synchronization: not set
 - Encrypted: no
 - App Version: 2024.08.01

**Additional context**
First time user. Forgive me if I missed something, but I don't think I did something unusual, very simple steps(?)

**Comment by guanlisheng** [comment]
thanks @dcprojects

please leave the password empty for no encrypted database in your usage. 

this is a known UEX issue We expect an Android expert to help refine this.   similar ticket #1641

**Comment by dcprojects** [comment]
Thank you very much, indeed it works without password!

I thought the password was mandatory, can I suggest to add an hint when the password dialog is shown? Something simple, like " insert password (optional)" would be enough

**Comment by guanlisheng** [comment]
Sure, and that’s the plan to refine encryption for upcoming release as desktop MMEX v1.8.1 is going to support the same SQLCipher(AES256) soon.
