### ISSUE TITLE
Option to print reports

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#183]
User suggestion
Consider an option to print or export the reports.
Possible outputs would be cloud print, pdf, image, etc.

Export to Excel/CSV is probably the best option here as it does not depend on the output format, unlike PDF.

See #829 for implementation of (PDF) print.

**Comment by MisterY** [comment]
A normal workaround for this would be to use the desktop database and create, print, or export any report one wishes.

**Comment by islam2hamy** [comment]
@guanlisheng  any update for this? (PDF)
