### ISSUE TITLE
Edit Sub-categories impossible in non-nested category model 

### ISSUE THREAD

**Issue by BoubouleThai** [moneymanagerex/android-money-manager-ex#1833]
Since the nested categories appeared (1038) it is impossible to edit a sub-category IF WE don't use the nested categories option

So
- no nested categories is chosen in the settings
- go to the entities > categories
- choose a sub category
- then edit
- then ok
at this moment this main category and all his Sub-categories has been deleted from the categories.
No more 😬
And you will see it also if you edit a categories reports (see my picture attached)

It works good to edit categories IF nested categories is selected in the settings 

![Screenshot_20240916_184732_Money Manager Ex](https://github.com/user-attachments/assets/dd11aef4-57c0-4e87-b87b-b2758d47500a)

**Comment by guanlisheng** [comment]
fixed and will release in the upcoming release...

**Comment by BoubouleThai** [comment]
👍👍😊

Le mer. 18 sept. 2024, 14:06, Lisheng Guan ***@***.***> a
écrit :
