### ISSUE TITLE
"New transaction" opens settings in 1040 

### ISSUE THREAD

**Issue by BoubouleThai** [moneymanagerex/android-money-manager-ex#1836]
"New transaction" opens settings in 1040  😁

**Comment by luisdev** [comment]
Is this because AMMEX wants you to set a value (path) for the new **Attachment Folder** setting?

**Comment by BoubouleThai** [comment]
Yes, thanks

it is for that.
I thought I've closed the issue 🤔

I set a value but cannot set the real value (Google drive folder)
So I create a folder on my phone memory but... cannot see attachments in
transactions.

**Comment by guanlisheng** [comment]
we could set the real value from Google Drive just like MMEX can open database from it.

**Comment by BoubouleThai** [comment]
How can I set the real value from Google drive?
I cannot access to Google drive in the choices?
(see picture attached)

Le jeu. 19 sept. 2024, 06:36, Lisheng Guan ***@***.***> a
écrit :

**Comment by BoubouleThai** [comment]
No
Not the same
If I open a database (other), I can access to all my cloud data (picture 1)
When I want to open the attachment folder I see only the phone (picture 2)


Le jeu. 19 sept. 2024, 11:31, Lisheng Guan ***@***.***> a
écrit :

**Comment by BoubouleThai** [comment]
what screenshot do you want more ?
sent you the 2 screenshots that compare

Le jeu. 19 sept. 2024, 15:00, Lisheng Guan ***@***.***> a
écrit :

**Comment by guanlisheng** [comment]
no any screenshot here.

**Comment by BoubouleThai** [comment]
I send screenshots 2 times answering the email. 
Picture 1
Open a database > other 
![Screenshot_20240919_123230_Files](https://github.com/user-attachments/assets/c8dfc8bc-9a7f-4359-9e3c-c0dabf295e2d)
Picture 2 
Attachment folder menu 
![Screenshot_20240919_123321_Files](https://github.com/user-attachments/assets/d69754d8-7e44-42aa-9e82-5fa68a6d731c)

**Comment by BoubouleThai** [comment]
ok send them directly on Github

I have the same issue on my Galaxy Tab S9

Le jeu. 19 sept. 2024, 16:53, Lisheng Guan ***@***.***> a
écrit :

**Comment by guanlisheng** [comment]
I c.
i'm running into the similar issue with Synology Drive while NextCloud works well. that's wired.

**Comment by BoubouleThai** [comment]
Still the same issue with new 1041

Le dim. 22 sept. 2024, 00:54, Lisheng Guan ***@***.***> a
écrit :

**Comment by guanlisheng** [comment]
Does the same mean "New Transaction" opens setting?  this uex workflow issue should be fixed in v1041

**Comment by BoubouleThai** [comment]
No 😊
Means cannot access to the Google drive cloud
![Screenshot_20240919_123321_Files](https://github.com/user-attachments/assets/571cbf67-ccae-4ae7-80f6-70f61b1c0dbb)

**Comment by guanlisheng** [comment]
no idea about this yet, i guess it was due to Google Drive's settings. 

btw, how about google drive sync issue mentioned in #1717 ?

**Comment by BoubouleThai** [comment]
It is not a Google drive problem because I also cannot see the Dropbox cloud
And now, since the 1040, I also cannot see that there is a an attachment to the transaction (the bottom attachment line is empty) and it is a problem because I cannot manually (without mmx) go open the attachment in the folder because I don't know that it exists

**Comment by guanlisheng** [comment]
you can verify it by copying both the database file and the attachment folder to your Phone's storage (e.g. under Download or Documents).   this might explain why someone chose a solution like the phone's storage + Syncthing 

To avoid crashes, if a transaction has an associated attachment,  MEMX will try to. test its permission first before displaying the preview button.  once the Attachment Folder is set, it will not redirect to the Per-Database setting anymore. 

btw, it works well on NextCloud...

![Screenshot_20240923_142020](https://github.com/user-attachments/assets/0a177584-547e-4d87-a3b7-ea0957dae123)

**Comment by guanlisheng** [comment]
anyway, can you re-create a dedicated issue to track attachments folder on various cloud storage , e.g. google driver, dropbox.
