### ISSUE TITLE
App error messages are truncated

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/android-money-manager-ex#1850]
**Describe the bug**
Various AMMEX pop-up error messages are truncated.

**To Reproduce**
1. Setup AMMEX to use cloud sync, like Dropbox on Onedrive.
2. Create a new transaction and save it.
3. Click 'Synchronize' on the menu.
4. AMMEX shows a truncated success message. ![Screenshot_20240924_214319_Money Manager Ex.jpg](https://github.com/user-attachments/assets/c46955cb-3210-43ae-8f44-b9e8281deb25)

5. Then it is replaced by another truncated message about a "No field notification."

![Screenshot_20240924_214323_Money Manager Ex.jpg](https://github.com/user-attachments/assets/00390428-4bed-449a-a51f-66669a70d7b9)

**Expected behavior**
The text in the message pop-ups should not be truncated after the second row.

**Device Information:**
 - Device: Samsung S22 Ultra
 - OS: Android 14
 - Storage: Phone storage
 - Synchronization: 5min interval and Sync on Start
 - Encrypted: Yes with password
 - Security: Passcode or fingerprint
 - App Version: 2024.09.21 (1041)

**Additional context**
NA.

**Comment by wolfsolver** [comment]
@luisdev Is the issue still present? Did you enable the notification in Android notifications?

**Comment by luisdev** [comment]
This is still an issue on 2024.12.19 (1053) from the Play Store. As per my previous comment, I'm not sure what your request to "enable the notification in Android notifications" means. Where on my Samsung Galaxy S22 Ultra do I enable that notification?

**Comment by wolfsolver** [comment]
Hi
- the message "both local and remote file..." Means that your local copy and remote copy are modified and the app cannot define which one is the correct one. You need to reopen remote file or export your local copy base on what you prefer 
- message error no field notification means that notification for app is not active. Go in android setting - notification and enable notification for app

![Screenshot_20241223-101452](https://github.com/user-attachments/assets/a5694fd5-ae50-4178-bc2c-96e27993f759)

**Comment by luisdev** [comment]
#2030 shows a screenshot where somebody else also gets the truncated message.
