### ISSUE TITLE
Cannot create custom currency

### ISSUE THREAD

**Issue by toby3d** [moneymanagerex/android-money-manager-ex#1851]
**Describe the bug**
I cannot create custom cryptocurrency with short (#1850) unknown error related to SQLite3 database.

**To Reproduce**
1. Go to Entities – Currencies
2. Click on plus button
3. Fill "Currency name" field: `Dogecoin`
4. Fill "Unit name": `DOGE`
5. Fill "Prefix symbol": `Ɖ`
6. Leave all other fields as is and try to save it

**Expected behavior**
Cryptocurrency was created and can be used in other entities.

**Screenshots**
![Screenshot_20240925-154723_Money Manager Ex](https://github.com/user-attachments/assets/2af54fdb-a1b3-423a-9511-d3110b6740fd)

**Device Information:**
 - Device: Xiaomi POCO X3 Pro
 - OS: LineageOS 20 (Android 13)
 - Storage: Phone storage
 - Synchronization: disabled
 - Encrypted: no
 - Security: graphic key
 - App Version: 2024.09.18

**Additional context**
None.

**Comment by guanlisheng** [comment]
thanks @toby3d , just fixed in code and waiting for next release.
