### ISSUE TITLE
Reduce the database size

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#187]
The size of the database created in Android version is about 200KB vs around 60 in desktop version.

**Comment by AlessandroLazzari** [comment]
IMO, it depends on the version of SQLIte that is present in the device. I don't think we can do much. You had something else in mind?

**Comment by MisterY** [comment]
I just installed the app on a friend's device and noticed during sync that the empty file has 200KB. The file I have from the desktop version, with all my data, is 60-80KB usually.
But if it depends on the driver, there's not much we can do about it.

**Comment by MisterY** [comment]
The solution would be to create an empty file using the desktop version.
I believe there is also a difference in that the Android app also creates the default categories.
