### ISSUE TITLE
Both file modified for Syncthing

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1872]
**Describe the bug**

When open app appear "both files are modified"

Android with software from Google store. Wi-fi activated

**To [Reproduce**](url)
1. Go to '...' sync button

**Expected behavior**

**Screenshots**

![Screenshot_2024-11-08-20-33-11-02_39b928e77728c0961d7e0b271f2f78ea](https://github.com/user-attachments/assets/e8a26e65-9a1e-46f1-9334-0e5b716480c0)

![Screenshot_2024-11-08-20-35-09-67_39b928e77728c0961d7e0b271f2f78ea](https://github.com/user-attachments/assets/59a2c5b2-7904-4dad-a4fc-e13ce8bf45fc)

**Device Information:**
 - Device: Oneplus 8t
 - OS: Android 14
 - Storage: Phone storage + Syncthing
 - Synchronization: 5min interval and Sync on Start
 - Encrypted: no
 - Security: no
 - App Version: 2024.11.01

**Comment by guanlisheng** [comment]
Hey @ggraziotti, 
Modifying both files is expected if you modify the files from two sides.  let's refer to the forum thread [link](https://forum.moneymanagerex.org/viewtopic.php?t=9363)

Additionally, per #1705 , seems Syncthing is not well working with Storage Access Framework while MMEX is fully on SAF ([link](https://moneymanagerex.org/blog/mmex-database-sync-across-android-ios-and-desktop/))

**Comment by wolfsolver** [comment]
@ggraziotti did you have try with latest 2024.11.25?
