### ISSUE TITLE
Report : where the money goes shows different currency 

### ISSUE THREAD

**Issue by beeta0298** [moneymanagerex/android-money-manager-ex#1882]
**Describe the bug**
Report : where the money goes shows different currency. For example I used the Indonesian Rupiah. Buat the report shows USD. 

**To Reproduce**
1. Go to 'Report
2. Click on 'where the money goes
3. See error

**Expected behavior**
It should show the base currency not USD 

**Screenshots**

**Device Information:**
 - Device:. Xiaomi 13t
 - OS: [e.g. Android 14
 - Storage: [e.g. Phone storage + Sync
 - Synchronization: [e.g. 10min interval and Sync on Start]
 - Encrypted: No
 - Security: No
 - App Version: [e.g. 2024.11.10]

**Additional context**

**Comment by guanlisheng** [comment]
Hi @beeta0298 , thanks for trying MMEX.

can you share your base currency here  via `三 -> Settings -> Per-Database` ?
