### ISSUE TITLE
Android attachment mark in transaction list

### ISSUE THREAD

**Issue by froux07** [moneymanagerex/android-money-manager-ex#1883]
In the Android version, and in the display of an account's transaction list, for greater clarity, transactions with attachments should be marked. With a star, put the payee in italics or bold ... or anything meaningful.

**Comment by guanlisheng** [comment]
hi @froux07, this is a great suggestion.  

designing.

**Comment by froux07** [comment]
Hi,
Why not the paperclip as in the desktop version?

**Comment by guanlisheng** [comment]
- https://github.com/moneymanagerex/android-money-manager-ex/pull/1957

**Comment by froux07** [comment]
Le jeudi 19 décembre 2024, 22:18:12 UTC+1 Emmanuele a écrit :
> Closed #1883 as completed.
All work fine !!
Good !
