### ISSUE TITLE
Where is the apk file?

### ISSUE THREAD

**Issue by sunilongithub** [moneymanagerex/android-money-manager-ex#1887]
Hello I could not find apk file for app installation on Android device.
My device doesn't execute other app format.
Could you please provide.apk installation file...

**Comment by guanlisheng** [comment]
hi @sunilongithub 

I just uploaded the apk for `v2024.11.10.1044`. can you share your os version

**Comment by sunilongithub** [comment]
Wow, that is so quick, thank you so much.
My android version is 13 /Samsung F62
Best regards.

Sunil

**Comment by wolfsolver** [comment]
@sunilongithub if you like we can enroll your email to Google play store. We are in beta release. If you like fill this form for enroll.
https://forms.gle/2ewm7Pqs9wrKj6gp8
