### ISSUE TITLE
Impossible to use the last 1045

### ISSUE THREAD

**Issue by BoubouleThai** [moneymanagerex/android-money-manager-ex#1895]
The MMX freezes very often without reason 

And :
MMX freezes also each time that I make a search like :
Entities > Categories > Chose a category or sub-category > long touch > view transactions.... Crashes each time 

In the settings nested categories selected or not selected I have the same problem 

Go back to 1044

**Comment by wolfsolver** [comment]
You are right. 
Got error on search parameters fragment at line 337.
I will take a look
