### ISSUE TITLE
transaction copy button function issue

### ISSUE THREAD

**Issue by ShosGithub** [moneymanagerex/android-money-manager-ex#1897]
**Describe the bug**
Starting from version 2024.11.19, when select a transaction and click the Copy button to create new one, the newly created transaction does not contain the content of the original transaction.

**To Reproduce**
1. Go to any transaction
2. Click on copy button

**Comment by guanlisheng** [comment]
thanks @ShosGithub , this is a bug during migration from Integer to Long and going to be fixed
