### ISSUE TITLE
crash when viewing account/entering transaction

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/android-money-manager-ex#1899]
With yesterday update, viewing account details or entering transactions make the application crash.

**To Reproduce**
Create new database
Create account
Add transaction.

When returning to the account window, the app crash.

**Device Information:**
 - Device: salsung a13
 - OS: Android 14
 - Storage:  Phone storage 
 - Synchronization: none
 - Encrypted: no
 - Security: no
 - App Version: . 2024.11.19 (1045)

**Comment by guanlisheng** [comment]
hi @xraynaud, thanks for trying mmex.

is it always happening as we can't reproduce it yet?  @wolfsolver as fyi

**Comment by xraynaud** [comment]
Yes it is always happening on my phone. I tested the update due to the syncing problem the update was supposed to correct. I tried to reinstall the app but it is still happening.

**Comment by wolfsolver** [comment]
@xraynaud  can you share the logs?

**Comment by xraynaud** [comment]
Of course. How do i get the logs?

Le 20 novembre 2024 12:23:52 GMT+01:00, Emmanuele ***@***.***> a écrit :

**Comment by xraynaud** [comment]
For some reason, the app doesn't crash anymore after update to 1046. I don't know if the update has anything to do with this.

**Comment by wolfsolver** [comment]
Probably yes. We discover an issue is some devices and make an hotfix (1046).
Nice to hear this is also a valid fix for you
