### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by lkp** [moneymanagerex/android-money-manager-ex#19]
![2015-01-28 19 02 34](https://cloud.githubusercontent.com/assets/1420210/5943582/7ccb094c-a720-11e4-8f28-81ba5f7579a1.png)
As shown in the picture, the android version has an issue with floating point numbers and rounding. Desktop version does not have this for the exact same database file.

**Comment by MisterY** [comment]
This seems to be resolved in the upcoming v2.0.
