### ISSUE TITLE
Can't open database in Nextcloud folder anymore.

### ISSUE THREAD

**Issue by aFunkyBass** [moneymanagerex/android-money-manager-ex#1900]
**Describe the bug**
I can't open my MMEX database located on a Nextcloud folder. It's been working for months, even though I had the distinct sensation that  it was a bit of unstable. Now, for no apparent reason it stopped working. If I try to open it it says "Remote file is no longer available". Moving the file to a local storage folder it works smothly. I've thoroughly followed [this instructions](https://moneymanagerex.org/blog/mmex-cloud-storage-with-nextcloud/) with no luck.

Both Nextcloud app and MMEX are up to date.

**To Reproduce**
1. Go to 'Open database'
2. Choose the "Nextcloud" storage
3. Navigate into the "Documents" folder
4. Choose the "budget.mmb" file
5. Click "OK" on password (no password)
6. Error reported: "Remote file no longer available"

**Device Information:**
 - Device: Realme 8 
 - OS: Android 12
 - Storage: Nextcloud + Phone storage
 - Synchronization: 5min interval and Sync on Start
 - Encrypted: No
 - Security: None
 - App Version: 2024.11.10 (1044) - F-Droid

**Comment by guanlisheng** [comment]
hi @aFunkyBass, thanks for trying and reporting the issue.

can you add a sub-folder for mmex.db instead?  this is to follow Android's best practice.

**Comment by aFunkyBass** [comment]
@guanlisheng thank your for you quick reply! :)

What do you exactly mean? You mean that I should have a sub-folder containing ONLY the mmex file? Or you mean that the db should not be located on the root of Nextloud?

Currently the file is on: Phone/Nextcloud/Documents/budget.mmb
There are other files alongside, included some backups and other things.

**Comment by wolfsolver** [comment]
"Remote file no longer available" was added recently to prevent issue when opening from SAF got an error. This can be caused by different cause (Remote file is moved, remote file is no longer accessible by SAF...). 
You should found also a notification allert with full path of remote file.
The fact that you got this error as soon you reqest open permision seems that NextCloud did't give you this auth.
I will try to repliacate with some nextcloud free instance (or if you can create a test account for me on your nextcoud instance, and ovbiusly remove after test)

**Comment by guanlisheng** [comment]
this non-root folder is fine. 
> /Nextcloud/Documents/budget.mmb

**Comment by aFunkyBass** [comment]
Hey @wolfsolver  Thank you.

I also have another notification message which disappers so quickly I can barely see it, which reports "Remote read got null" (or something very similar).

Unfortunately I have to leave now I'll try to grant you an access to next cloud in the afternoon (dopo pranzo, visto che sei italiano anche tu)... :)

Thank you guys for your supprt.

**Comment by wolfsolver** [comment]
I get free account on nextcloud and I'm able to reproduce issue.
I will investigate.

**Comment by wolfsolver** [comment]
I got a workarround for this.
From NextCloud Client -> Enable syncronization for your mmb file. This create a file under Android/Media/com.nextcloud.client/Document/yourfile.mbb
From Monay Manger -> Open file directly from ThisDevice -> Android -> Media -> com.nextcloudc.client -> Document
To reupdate nextcloud cloud, open nextcloud client and force sync.

**Comment by aFunkyBass** [comment]
> I got a workarround for this. 

Thank you @wolfsolver, I'll give it a try and let you know

**Comment by guanlisheng** [comment]
can you try to move it into sync function?

**Comment by wolfsolver** [comment]
> > I got a workarround for this. 
> 
> Thank you @wolfsolver, I'll give it a try and let you know

@aFunkyBass sei riuscito a provare il workaround?

**Comment by wolfsolver** [comment]
> can you try to move it into sync function?

The issue is present in two different point:
1) in downloadDatabase at line 338 (InputStream is = resolver.openInputStream(uri)) 
2) in sync while checking existence.

I think this relate to remove file auth in release [2024.11.19.1045](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.11.19.1045).
After a deep analysys, I think that nextcloud prevent direct read of file from main activity. I just made a test on my device by encaplusate this piece of code (see new code

```
    private void downloadDatabase(Uri uri, String localPath) throws Exception {
        ContentResolver resolver = getContext().getContentResolver();

        // Use try-with-resources to automatically close resources
        File tempDatabaseFile = File.createTempFile("database", ".db", getContext().getFilesDir());

        // new code for download file in async task
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    FileOutputStream outputStream = new FileOutputStream(tempDatabaseFile);
                    InputStream is = resolver.openInputStream(uri);
                    long bytesCopied = ByteStreams.copy(is, outputStream);
                    Timber.i("copied %d bytes", bytesCopied);
                } catch (Exception e) {
                    Timber.e(e);
                }
            }
        });
        thread.start();
        thread.join();

```
This enable load file form nextcloud (and also work with gDrive and OneDrive).

Unfortunately during sync process this give me sone issue

**Comment by wolfsolver** [comment]
@aFunkyBass can you give a try to this preTest Release? 
https://drive.google.com/file/d/1tYaL9ws-Cut4w4efvy81XCkzA9GXzvtI/view?usp=sharing
and confirm that you can open without any issue from NextCloud?

**Comment by aFunkyBass** [comment]
> @aFunkyBass sei riuscito a provare il workaround?

@wolfsolver ciao!

The workaround does the job, even though NextCloud reports a file version conflict everytime I try to re-sync it. You can force it and it goes though, obviously this is not the way it's supposed to work... 

Anyway, thanks a lot for taking the bother of finding this temporary solution. :)

**Comment by aFunkyBass** [comment]
> @aFunkyBass can you give a try to this preTest Release? https://drive.google.com/file/d/1tYaL9ws-Cut4w4efvy81XCkzA9GXzvtI/view?usp=sharing and confirm that you can open without any issue from NextCloud (without using workarrountd)?

I'll try it right now.

**Comment by aFunkyBass** [comment]
@wolfsolver It works!

**Comment by wolfsolver** [comment]
@aFunkyBass appena rilasciata su play store.
Puoi disinstallare la versione mia temporanea e procedere con installazione ufficiale

**Comment by aFunkyBass** [comment]
Ciao @wolfsolver Grazie mille... In realtà la versione che usavo era quella di F-Droid, quindi aspetterò il rilascio là.

P.S. la versione temporanea comunque va benissimo.
