### ISSUE TITLE
Error Loading Currency when you duplicate a transaction

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1902]
**Describe the bug**
I've just started noticing that when you use the duplicate transaction option on any of my accounts (all set as UK POUND),  the new duplicate record does not contain any info from the original transaction and instead the app now issues a message "Error Loading Currency as per screenshot.

**To Reproduce**
1. Go into any account.
2. Select any existing transaction.
3. Click on the duplicate transaction button.
4. See error issued.

**Expected behavior**
When you click duplicate transaction it should create a new transaction with same type, payee, amount, notes, etc as original.

**Screenshots**
![Screenshot_20241120_204012_Money Manager Ex](https://github.com/user-attachments/assets/95c595cc-6409-4993-a4a0-3c828134a382)

**Device Information:**
 - Device: Samsung
 - OS: 14 ui6.1 <Oct security patch>
 - Storage: 256gb
 - Synchronization: [never and Sync on Start]
 - Encrypted: no
 - Security: Actived with passcode and fingerprint]
 - App Version: 2024.11.19 1045 - Google Play Version

**Additional context**
I use this all the time so it has broken in recent release.

**Comment by wolfsolver** [comment]
Thanks. Similar error is reported with #1897 
Can you try 2024.11.20 released this morning?

**Comment by smjohns** [comment]
Yes just updated and this has resolved the issue. Thanks for prompt response/fix

**Comment by smjohns** [comment]
Thanks for help on this
