### ISSUE TITLE
Error Message when asking to delete a category or sub-category 

### ISSUE THREAD

**Issue by BoubouleThai** [moneymanagerex/android-money-manager-ex#1915]
Entities >
Categories >
Chose a category or sub-category in the list >
Long press >
Delete

At this moment a message appears (see picture attached)
Error : Incomplete input..... 
![Screenshot_20241123_220403_Money Manager Ex](https://github.com/user-attachments/assets/c430a9c4-fb8f-4259-bf7f-f7027763258a)

**Comment by wolfsolver** [comment]
What if you confirm anyway? is category deleted?

**Comment by BoubouleThai** [comment]
yes
