### ISSUE TITLE
 Unable To Set Newly Added Payees For Transactions.

### ISSUE THREAD

**Issue by Timothy-S-P-Capehart** [moneymanagerex/android-money-manager-ex#1925]
**Describe the bug**

New payee's can be created, but are not saved in transactions.

**To Reproduce**
1. Create a new payee, either from the new transaction dialogue, or by going to create one under the entities menu.
2. Set the new payee for a transaction.
3. Hit the check mark to save the transaction.
4. See that the transaction has been saved, but without a payee.

**Expected behavior**

The payee should be saved as entered.
**Screenshots**

**Device Information:**
 - Device: Samsung Galaxy A53 5G
 - OS: Android 14
 - Storage: SD Card
 - Synchronization: None
 - Encrypted: No
 - Security: No
 - App Version: 2024.11.19 through 2024.11.22

**Additional context**

I was able to add a new a payee a few days ago but now it's not working. I'm not sure if I could have met some upper limit to the number of new pays that are possible. I deleted an old one that only had one transaction and then tried to add a new payee again, but it still didn't work.

**Comment by guanlisheng** [comment]
hi @Timothy-S-P-Capehart 

It is very similar to #1905 and should be fixed in v2024.11.22.  Can you upgrade to v2024.11.25 and have a retry?

**Comment by Timothy-S-P-Capehart** [comment]
Now it seems the app will let me create a new payee, let me save a new transaction with the new payee set, but then when I look at the transaction the payee is blank. If I then edit the transaction and set it to have the new payee, it will save correctly.

Previously I found a work-around by exporting and re-importing the database, but it seems strange that it helped anything.

**Comment by wolfsolver** [comment]
agreeì. There is somethigs strange. @guanlisheng I made some test and replicate a clean db for this.

1) on Android: Payee is added correctly (using new long ID)
2) on Android: Transactions seems to have corretly payeeid
3) on Android: Under report payee i see new payee, but when navigate to see transaction no transaction is show
4) On Desktop: open DB does not show the payee in transaction
5) On Desktop: payee is show in list, but when trying to edit no data is displayed
6) On Desktop: payee report dows not show new payee

Android: 2024.11.25 (1049)
Desktop: 1.8.1
TestCaseDb: [in attach](https://1drv.ms/u/s!AtPBR0zMvFhpju9j0rFsO7-7HGz_XA?e=BCdSru)

**Comment by guanlisheng** [comment]
For Android, your issue is different, can you have a deep look? 

For Desktop, it is due to a flaw that Desktop can only support int32 ID. and SUID is large for it.

**Comment by wolfsolver** [comment]
Ok. So for now this can be closed since my fix will manage android side
