### ISSUE TITLE
Copy version info on About screen

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/android-money-manager-ex#1931]
The following feature would be quite useful when testing AMMEX or reporting bugs:

-  Open the About screen in AMMEX.
-  Double-tap on the version number on that About screen.
-  AMMEX copies the version number to the clipboard.

This allows you to then easily paste the version number into any document. 

This would be very useful when testing AMMEX or reporting bugs.

**Comment by guanlisheng** [comment]
Good idea, @luisdev. btw, can you help to impl it ?

**Comment by wolfsolver** [comment]
We can consider to directly open new issue using this link
https://docs.github.com/en/enterprise-cloud@latest/issues/tracking-your-work-with-issues/using-issues/creating-an-issue
