### ISSUE TITLE
Deletion of subcategories not possible

### ISSUE THREAD

**Issue by trichi-r** [moneymanagerex/android-money-manager-ex#1939]
**Describe the bug**
It is currenrly not possible to delete subcategories, as it falsely claims that it is being referenced.

**To Reproduce**
1. Go to "Entities" > "Categories"
2. Create a new category with a subcategory.
3. Long tap subcategory > delete
4. See error "The selected category cannot be deleted because it is referenced"

**Expected behavior**
I expect an inquiry to make sure if I do want to continue with the deletion, and have it deleted when selecting yes. Note that deletion does work as expected with standard categories, just not with subcategories

**Screenshots**
None

**Device Information:**
 - Device: Nothing Phone 2a
 - OS: Android 14
 - Storage: 256gb
 - Encrypted: No
 - App Version: 2024.11.25

**Additional Context**
This is my first bug report, I'm happy to take advice on how to improve.

**Comment by wolfsolver** [comment]
The main idea is that Categoris that are referenced in transaction or has subcategories can not be deleted.
Are you sure that the category you want to delete is
1) not reference in any transactions
2) does not have sub categories?

**Comment by guanlisheng** [comment]
btw, can you help verify it in the beta version https://play.google.com/store/apps/details?id=com.money.manager.ex.android

**Comment by trichi-r** [comment]
> The main idea is that Categoris that are referenced in transaction or has subcategories can not be deleted. Are you sure that the category you want to delete is
> 
>     1. not reference in any transactions
> 
>     2. does not have sub categories?

That's what I suspected

1. It is not used in any transactions. It happens in a newly created database with newly created categories. Checking the "view transactions" optionon long press confirms that it is not used.

2. The problem only exists with subcategories to begin with. I can delete categories, even if they have existing subcategories. I just can't delete any subcategory by itself. Of course, this means that I can get rid of the subcategory by deleting its supercategory, but that would cause other problems.

![Screenshot_20241201-020922](https://github.com/user-attachments/assets/65c3a74a-ecf7-4150-b0af-4cfc347db9d5)

Example: I can delete "Education" with all its subcategories, but not "Books" by itself, despite it not having any transactions.

**Comment by trichi-r** [comment]
@guanlisheng 

Oh, it works in the beta, I can delete them. The design is a bit different here. Compare to screenshot above.

![Screenshot_20241201-021947](https://github.com/user-attachments/assets/2aff0232-0312-4cfa-95bf-69610966035a)

**Comment by guanlisheng** [comment]
Thanks @trichi-r 
this new flatten design from @wolfsolver would support the category tree well
