### ISSUE TITLE
Unable to remove payee

### ISSUE THREAD

**Issue by Tracachang** [moneymanagerex/android-money-manager-ex#1950]
**Describe the bug**
Payee that had issues with the error PAYEE_V1 can not be deleted.

I cannot delete a payee that had problems "with error PAYEE_V1

I can edit it, but when I try to delete it, I get the message: "Attention The selected payee can not be deleted because it is referenced". However, when I click on "View Transactions" it is completely empty (since I deleted all the transactions before trying to delete the payee).

**To Reproduce**
1. Go to 'Entities' -> 'Payees'
2. Click on 'the payee ' and and click Delete
3. See error

**Expected behavior**
Payee should be deleted

**Device Information:**
 - Device: Pixel 6a
 - OS: Android version 15
 - Storage: Phone storage + Syncthing
 - Synchronization: 10min interval and Sync on Start
 - Encrypted: No
 - Security: No
 - App Version: 2024.11.30 (1050)

**Additional context**
Newly created or older payees can be deleted, but only those that had the "PAYEE_V1 error" conflict.

**Comment by Tracachang** [comment]
I was finally able to delete it.

The steps I followed are:

1) Create a new payee
2) The payee I was trying to delete had a transaction, deleting the transaction wasn't enough to delete the payee, so I tried changing the transaction payee (to the new one created in step 1).
3) Then delete works.

For additional context, if all steps are done using android it can be deleted, but if instead to change the transaction payee using android, this step is done using the desktop version it will not work. I think this is all related to https://github.com/moneymanagerex/moneymanagerex/issues/6992

**Comment by wolfsolver** [comment]
Can you specified if you delete transaction from mobile or you have previus edit record on PC version?

@guanlisheng PC version introduced deletedtime field for deleted transaction, but they still present in db.
Noit sure that my commit can resolve.

**Comment by wolfsolver** [comment]
As last email from @Tracachang my fix Will solve se issue

**Comment by Tracachang** [comment]
> Can you specified if you delete transaction from mobile or you have previus edit record on PC version?

Had both cases.

**Comment by guanlisheng** [comment]
v2024.12.08 (1051)with above fix was released
- in GitHub https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.12.08.1051
- Google Play Open Testing https://play.google.com/apps/testing/com.money.manager.ex.android

if everything goes well, it will be promoted as production version shortly.
