### ISSUE TITLE
0.00€ recurring transactions - Notes not recorded

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1961]
Recurring transaction, if the amount of the transaction is 0.00€ the content of the note is not recorded

**To Reproduce**
1. New transaction
2. Click on recurring transaction
3. add a transaction with a 0.00€ amount and a text in the note area and save
4. go back to recurring transaction, the note is not there

**Device Information:**
 - Device: POCO M3 Pro 5G
 - OS: Android 13
 - Encrypted: No
 - Security: No
 - App Version: 2024.12.10 (1052)

**Comment by wolfsolver** [comment]
unable to reproduce issue.

**Comment by jeepcook** [comment]
> unable to reproduce issue.

Are you sure to have only one recurring transaction before leaving recurring transactions screen? not more.

**Comment by wolfsolver** [comment]
Tested on clean scheduled transacion

I created two scheduled transacion both have note

[https://1drv.ms/v/s!AtPBR0zMvFhpjvB-jSQ4L-pwQ-62cQ](https://1drv.ms/v/s!AtPBR0zMvFhpjvB-jSQ4L-pwQ-62cQ)

**Comment by jeepcook** [comment]
I did a mistake in my first post. In fact I'm not speaking about scheduled/recurring transaction, but for a normal transaction created on an account.
Excuse me.

**Comment by wolfsolver** [comment]
Still not reproducible.
note in normal transaction and split transaction is preserved. keep in mind that note at transaction level can be different from notes in split
 
see my recording: https://1drv.ms/u/s!AtPBR0zMvFhpjvB_P3mak8Ylsm4DpA?e=g0ZcaQ

**Comment by jeepcook** [comment]
Ok, in fact you enter a note in the main transaction before going to the split transactions screen. So your master note is in the split transaction. My manipulation is to have no note in the main transaction, open the split screen, create a transaction with a note and save the split screen. The note is not recorded for this split transaction in this case and if you do operation in this order.

**Comment by wolfsolver** [comment]
Please notice that I didn't enter the master note before enter in split transaction (second example at minutes: 00:33).
Anyway I understend your question, the system does not save the note in split transaction if there only one split.

Can you explain a real case where is needed to make a split with only one element? Split expect to have at least 2 element.

**Comment by jeepcook** [comment]
In fact I'm using split transactions for a lot of case but for a specific case I need to be able to have just one with its own associated note which has to be different from the one registered in master screen.
My example:
- Each month I have to receive 4 payments from different users 
- First time I receive one payment from Simon, so my note for the split one will be Simon
- Second time, another day of the month, I receive a payment from Paul, the note will be Paul
- .......and this for the 4 users.

Hope I am clear, and I see you did a new commit for this needed.

Thanks for your help.

**Comment by wolfsolver** [comment]
Keep in mind that didn't exist in the db a single split.

A transacion wirh One split Is equal tò transacion wirh no split.

So now note Will be copied from split to master, but no split Is recordered.

**Comment by wolfsolver** [comment]
Just   to understand your case .

The note can be placed in normal transaction note. Why you need different note in split?

**Comment by jeepcook** [comment]
> Just to understand your case .
> 
> The note can be placed in normal transaction note. Why you need different note in split?

Because each split transaction has its own note with for example the name of a person
