### ISSUE TITLE
Searching the notes produces no results

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#197]
Searching for text in the Notes field finds no results.

**Comment by AlessandroLazzari** [comment]
Have you try this issue?
Il 19/apr/2015 18:48, "Alen Siljak" <notifications@github.com> ha scritto:

**Comment by MisterY** [comment]
Yes, just now. I have one transaction only and get no results when searching for a part of text in the notes field.

**Comment by AlessandroLazzari** [comment]
Ok then, if you agree should be fixed for the release of version 2.0. What
do you think?

**Comment by MisterY** [comment]
Fortunately, I'm at the PC at the moment. Will look into it right now.

**Comment by AlessandroLazzari** [comment]
OK thanks

**Comment by MisterY** [comment]
Done, Ale. Pull! ;)

**Comment by MisterY** [comment]
Should we do push another beta with this fix and the code cleanup (current pull requests)?
