### ISSUE TITLE
Huge data loss when creating a new account with the same name

### ISSUE THREAD

**Issue by aardbol** [moneymanagerex/android-money-manager-ex#1988]
**Describe the bug**
This is as critical as my previous issue https://github.com/moneymanagerex/android-money-manager-ex/issues/1827. When creating a new account with the same name as another one, the previous one disappears from the favorite account list and eventually from the list of accounts after a restart. I can't seem to get that account back and all records seem to have been lost.

**To Reproduce**
- have a (check) account called xyz
- go to entities > accounts
- create a new term account called xyz and mark it as favorite
- see original xyz disappearing fro the favorite list and new xyz appearing
- go to entities > accounts and edit original xyz; it doesn't work
- restart app (remove also from android history), and see the original xyz also being removed from the accounts list

**Expected behavior**
both accounts exist with the same name because the account type is different, or prevent a new account with the same name from being created by showing an error

**Screenshots**

**Device Information:**
 - OS: Android 15
 - Storage: Phone + Resilio Sync
 - App Version: 2024.12.10 (1052)

**Comment by aardbol** [comment]
I also changed the new account to the checking type of the original one, but it didn't bring back all the records

**Comment by guanlisheng** [comment]
Hi, @aardbol this is indeed a bug when handling the constraint conflict (here is the account name).

for this particular case, we can restore the previous account if you can share your database.

**Comment by aardbol** [comment]
While I appreciate the assistance, sharing the db is not an option. I assume I just have to make the modification via a db application that supports sqllite?

**Comment by guanlisheng** [comment]
Exactly. find the account ID from the transaction list and re-create it via any sqlite cli.

**Comment by guanlisheng** [comment]
v2024.12.22 (1054) will fix this, you can try it out via https://play.google.com/apps/testing/com.money.manager.ex.android

**Comment by aardbol** [comment]
Sounds great. When will the release apk be on github? That's my way of installation

**Comment by wolfsolver** [comment]
https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.12.22.1054

**Comment by aardbol** [comment]
There's no apk

**Comment by wolfsolver** [comment]
Ops @guanlisheng can you update?

**Comment by guanlisheng** [comment]
done. i thought guys can install it from google play

> v2024.12.22 (1054) will fix this, you can try it out via https://play.google.com/apps/testing/com.money.manager.ex.android
