### ISSUE TITLE
Income vs Expenses error in 1054 

### ISSUE THREAD

**Issue by BoubouleThai** [moneymanagerex/android-money-manager-ex#1996]
Hi,

If we want a report Income vs Expenses (in the menu or at the bottom of the account list) 
![Screenshot_20241224_064736_Money Manager Ex](https://github.com/user-attachments/assets/de07cb57-2070-4af9-95e3-6dfbc87cbc7f)

We get an error message
![Screenshot_20241224_065111_Money Manager Ex](https://github.com/user-attachments/assets/41ba4594-ba28-4f4f-a53a-87914d636740)

EDIT : Errors for ALL reports

**Comment by guanlisheng** [comment]
thanks @BoubouleThai, just fixed it and update the apk in place. please retry.

**Comment by BoubouleThai** [comment]
Yes it is OK now
Thanks
👍👍
