### ISSUE TITLE
Someone can recover my database?

### ISSUE THREAD

**Issue by roccorusperstar** [moneymanagerex/android-money-manager-ex#1999]
Hi There,
I cannot update my money manager ex because my current database is not possible to be read with the last version of the software.
I attach my database in txt extension (just rename it in mmb file), please help!
[moneymanagercasaa.txt](https://github.com/user-attachments/files/18244569/moneymanagercasaa.txt)

**Comment by guanlisheng** [comment]
hi @roccorusperstar  can you provide your app version? 

here you go the upgraded file
[moneymanagercasaa.mmb.txt](https://github.com/user-attachments/files/18244803/moneymanagercasaa.mmb.txt)

**Comment by roccorusperstar** [comment]
The version was 1.6.4, portable, for windows 64 bit.
However, your database works with the last version of Money Manager!!!
Thank you!!!

**Comment by roccorusperstar** [comment]
Ouff! one problem persists: no way to set as "visible" only the open accounts. Every given time I enter again in money manager, it makes visible all the accounts, the open and the closed ones!

**Comment by guanlisheng** [comment]
cool. you can always update to the latest mmex on both desktop and mobile.
