### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [moneymanagerex/android-money-manager-ex#2003]
**Describe the bug**
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8724272454

How can we build sqlite3mc?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:**
 - Device: [e.g. LG G7 ThinQ]
 - OS: [e.g. Android 8.1]
 - Storage: [e.g. Phone storage + Syncthing]
 - Synchronization: [e.g. 5min interval and Sync on Start]
 - Encrypted: [e.g. Yes with password]
 - Security: [e.g. Actived with passcode or fingerprint]
 - App Version: [e.g. 2024.01.01]

**Additional context**

**Comment by guanlisheng** [comment]
How does f-droid support aar file?

> 2024-12-26 03:52:34,177 ERROR: Found Android AAR library at app/sqlite3mc/sqlite3mc-1.9.2-sqlite-3.47.2-android.aar

**Comment by guanlisheng** [comment]
it is from https://github.com/utelle/SQLite3MultipleCiphers

**Comment by linsui** [comment]
We need to build it from source.

**Comment by guanlisheng** [comment]
ok, switch back.
can you try the latest tag/release https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.12.27.1056

**Comment by linsui** [comment]
Thanks!
