### ISSUE TITLE
"emb" database is not opened in the Android version and the app closes.

### ISSUE THREAD

**Issue by hpsxrb** [moneymanagerex/android-money-manager-ex#2016]
"emb" database from desktop version 1.8.1, hosted on Google Drive, does not open in the Android version and the app closes.

**Comment by guanlisheng** [comment]
hi @hpsxrb 
supposed you used v2024.12.25, if yes, please upgrade to v2024.12.27 https://play.google.com/apps/testing/com.money.manager.ex.android

**Comment by hpsxrb** [comment]
> hi @hpsxrb supposed you used v2024.12.25, if yes, please upgrade to v2024.12.27 https://play.google.com/apps/testing/com.money.manager.ex.android
Thank you very much. Yes, I had the problem with the normal version of the Google Play Store but with 12.27 everything works.

**Comment by guanlisheng** [comment]
cool. 
thanks for reporting the issue. closing this and feel free to contact us if any further issues.
