### ISSUE TITLE
Please make the database storage path editable

### ISSUE THREAD

**Issue by Chaos99** [moneymanagerex/android-money-manager-ex#21]
Like the title says.

Would make using an other sync service than Dropbox way easier.
Please also make sure to allow the path to be on the external storage.

**Comment by paulle** [comment]
Like the title says.

Would make using an other sync service than Dropbox way easier.
Please also make sure to allow the path to be on the external storage.
I would like to support this feature request. (It's something I always missed).

**Comment by AlessandroLazzari** [comment]
In the new version 2.0.0, the database will always be stored in external storage on the folder MoneyManagerEx (default).
It is always present the functionality of opening the database from other folders.
