### ISSUE TITLE
Allow operations on search results

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#210]
Currently the search results are displayed with the toolbar containing buttons Search and Cancel.
This should be replaced with options that can be used on the resulted records.
Possible group options (on selected transactions):
* select all
* <s>delete</s>
* <s>export to .qif (#211)</s> done
* <s>set status (reconciled, cleared, etc.)</s>

Individual actions (**already exist**):
* <s>duplicate</s>
* <s>delete</s>

**Comment by AlessandroLazzari** [comment]
I agree. Do it immediately after the official release of version 2.0.
​

**Comment by MisterY** [comment]
Use the activity/form from #216.

**Comment by MisterY** [comment]
#249 relates to the remaining item.
