### ISSUE TITLE
Qif export

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#211]
Same as in desktop version.

* <s>Add option to save directly to Dropbox.</s> or
* <s>Let user select the provider to use for file export.<s>
* <s>Add option to export on search results(#210). This should probably be the entry point as it provides the filtering of records to be exported.<s>

References:
- [QIF Specification](http://www.respmech.com/mym2qifw/qif_new.htm)
- [Sharing Files](https://developer.android.com/training/secure-file-sharing/index.html)
- [storage access framework](https://developer.android.com/guide/topics/providers/document-provider.html) on 4.4 and [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider.html) on 4.1.

**Comment by AlessandroLazzari** [comment]
This feature is interesting!

**Comment by MisterY** [comment]
in pull request
