### ISSUE TITLE
Summary Amount gives extended cents

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/android-money-manager-ex#214]
for more details:
https://sourceforge.net/p/moneymanagerex/bugs/667/

**Comment by MisterY** [comment]
Thanks! We'll investigate.

**Comment by AlessandroLazzari** [comment]
@MisterY You're already looking at, if no I'll check this evening.

**Comment by MisterY** [comment]
I tried but can't reproduce. Asked the person who reported the issue to provide more details. If you could try on different devices, it would be great.
The transactions I have all provide a correct summary. Must be missing something.

**Comment by AlessandroLazzari** [comment]
I've done several tests. And the problem does not occur.
The screenshot posted by the user in the issue in SF is relative to version 1.4.17
The user should try to install the beta3 to check if the problem still exists.

**Comment by MisterY** [comment]
OK. I'll post your findings in the forum. Thanks!

**Comment by AlessandroLazzari** [comment]
@vomikan To download the beta version, the user must participate in the community G+ MoneyManagerEx and then give their adherence to this link https://play.google.com/apps/testing/com.money.manager.ex
After you have done these steps, from the play store, can download the version 2.0.0 beta3

**Comment by MisterY** [comment]
Posted. Post awaiting moderation.
