### ISSUE TITLE
Create search results activity

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#216]
This activity receives search parameters and displays the results only (transactions).
Will be useful when called from other parts of application, not only from the Search form.

Also add a business object that makes using the search easy from other parts of the app.

References:
[Fragments](http://developer.android.com/guide/components/fragments.html)

**Comment by MisterY** [comment]
The analysis shows that the transactions are already shown by AllDataFragment. Perhaps using a separate activity would be good, instead of only using the fragment on Search.
However, need to take into consideration the layout on tablets.

**Comment by MisterY** [comment]
This is also a precursor to #211

**Comment by AlessandroLazzari** [comment]
Very probably we should be redesigned completely the activity of research.
We can do that in version 2.1. What do you think?

**Comment by MisterY** [comment]
That was my original idea - to create a generic activity that would be used to display any transaction list. Only later I saw the tablet layout with two panes and the All Data fragment.
So, the current implementation is not bad. Have a look at qif export, for example, and let me know your ideas on how we could improve the search.
Or, if you meant the full text search, that would also be an interesting addition.

**Comment by MisterY** [comment]
One more option would be to use the existing Search activity for display. In tablet layout, the search options would be visible and would display the current filter criteria. In phone/portrait layout only the results would be displayed.
We could add a filter icon in the toolbar. Clicking this would show the current search criteria. So, from any view of transactions, a user would be able to change search criteria.

**Comment by MisterY** [comment]
Reuse the existing activity. When parameters are received from outside, go directly to the results fragment.
