### ISSUE TITLE
Currency update sets the reverse exchange rate

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#22]
I have a few accounts with different currencies. In this case I used only EUR and HUF for a weekend trip.
The exchange transaction EUR->HUF was recorded as a transfer. (50 EUR = 15.000 HUF)
Then the payments were recorded in HUF account. (to total 6,000 HUF)
The remains were transferred HUF->EUR. (11,000 HUF = 30 EUR)

There are also a few transactions in 2 other EUR accounts (cash & bank) since the beginning of the month.

The main screen now shows that the total expenses for the current month amounts to 1,226,029.70 EUR (I wish!). However, there is no chance that the total amount is higher that 1000 EUR.

The currencies have been updated (currency exchange rates) before use.

Edit: I've just reproduced this again on a clean database:

- create EUR account with initial balance 100.
- create HUF account.
- add a transfer 50 EUR -> 15000 HUF
- add a withdrawal of 600 HUF in HUF account
- set the default currency to EUR, for totals.

The total shows 600 EUR. Then I updated the currency exchange rates as they were initially 1:1. After the update, the total ammount for Expenses is 184,003.62 EUR.

Also Summary Total shows 4,416,136.88 EUR although there should now be less that €100.

Edit:
In HomeFragment.java, line 260, as the amounts are added, curTotal equals 50 in the first run, then 4416136 in the second one.

**Comment by MisterY** [comment]
Latest update: I have performed the currency update from the desktop application. 
From what I see, this added 0 to the Scale field for HUF currency. Close, reopen the currency view, and the conversion to base rate is now 0.0033 instead of 306.xx. 
Now the numbers are OK. 
There is a problem somewhere when updating the currencies initially. Perhaps from Android, or a different locale?

**Comment by MisterY** [comment]
# Test 1

PC:
- create db
- create EUR account, initial balance €100
- create HUF account, initial balance 0

- sync via Dropbox

Android:
- create transfer EUR->HUF of €50.

Result: can't edit the HUF amount. The currency for EUR account is displayed as "L". (?)

https://www.dropbox.com/s/fw684qti9fuvxw9/alen.mmb?dl=0

# Test 2

PC:
- create db
- sync via Dropbox

Android:
- create EUR account, initial balance €100
- create HUF account, initial balance 0
- create transfer of €50 EUR->HUF, destination amount 15000 Ft. (amount editable)
- update currencies

Result: the EUR/HUF rate is wrong.

https://www.dropbox.com/s/j0nwm15hjm14bnj/test2.mmb?dl=0

My conclusion is that the error is somewhere in Android currency update. My original issue was solved after I updated currencies in the Windows desktop version of Money Manager Ex.

What was confusing in the original case was that, in Android, the rate was displayed as 306, which looked correct as that is the rate. But in reality the currencies were swapped. The real rate was supposed to be 1/306 = 0.0033. This is the rate that was set after the desktop currency update.

I'll copy this comment into the related GitHub issue, as well.

**Comment by MisterY** [comment]
I checked the database I used for testing a few days ago. There, HUF has a Scale of 1 and Conversion of 306.673.

**Comment by MisterY** [comment]
So, the source for the currency conversion:

```http://www.freecurrencyconverterapi.com/api/convert?q=EUR-HUF&compact=y```
returns 
```{"EUR-HUF":{"val":306.6727}}```

**Comment by AlessandroLazzari** [comment]
Thanks. Merged and fixed!
https://github.com/moneymanagerex/android-money-manager-ex/pull/24
