### ISSUE TITLE
Back button does not close the navigation drawer

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#233]
If I call main menu (top left menu symbol with Home, Open DB, Sync e.t.c. options) - when this menu opened and I've pressed Android "Back" button - instead of closing this menu and going to main screen of application - I am exiting from application...
Should it work this way ?

**Comment by prannou** [comment]
In other android app, the back button close the drawer if it is open (and does not leave the app). So I think we should have the same behaviour. I'll add a pull request with the correction.

**Comment by AlessandroLazzari** [comment]
I agree
Il 04/mag/2015 18:32, "prannou" <notifications@github.com> ha scritto:
