### ISSUE TITLE
Transaction hidden on mmb database, converted from an 0.9.4 mmex emb database

### ISSUE THREAD

**Issue by ccomv** [moneymanagerex/android-money-manager-ex#247]
Hi,
Sorry for this messy title ;P
Let me you explain : 
I have an emb database on mmex version 0.9.x
I've loaded this file successfully on mmex 1.1.2, under win7
I've installed mmex for android, v1.4.17, i know this version seems to not work with encrypted database
On windows, i've save my encrypted database under a uncrypted mmb version.

When i load mmb file on android, i can see my accounts but there are no transactions displayed
Nevertheless, when i search transactions, i've results !!
Does someone has encountered this problem ?
Thanks !

P.

**Comment by AlessandroLazzari** [comment]
Hello, thanks for contacting us.
I think the problem is due to the setting of the display of transactions.
If you go into Settings --> Look and Feel --> Show Transaction and select All Transaction you should see your transactions

**Comment by ccomv** [comment]
Hi,
Just a feedback
My transactions were few weeks aged, indeed
Thanks for your answer

**Comment by MisterY** [comment]
Thanks for the feedback. I have added a feature request that would be useful in any case - #317.
We would love to add quick switch for date period, account, etc. on the list.
