### ISSUE TITLE
Allow entering memo in split transactions

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#253]
Quicken supports memo/notes for each split category record. Therefore, this is also part of QIF standard.
This requires coordination with the desktop team.

**Comment by vomikan** [comment]
I have no idea how to provide this without DB structure changes.

10 мая 2015 г. 19:47 пользователь "Alen Siljak" <notifications@github.com>
написал:
>
> Quicken supports memo/notes for each split category record. Therefore,
this is also part of QIF standard.

**Comment by MisterY** [comment]
Correct. There would have to be a field for memo/notes in the splits in order to support this.

**Comment by vomikan** [comment]
I think here is no any advantages. The 'Notes' field is multyline. It may
be used for comment all split entries.

One more thing is split transfer. It's standard fot QIF. But in mmex it not
supported. But I think this functionality is OK.

воскресенье, 10 мая 2015 г. пользователь Alen Siljak написал:

**Comment by MisterY** [comment]
We already have a request for split transfers from the users. It would be nice if we supported such a scenario at some stage.

**Comment by MisterY** [comment]
+1, More requests from the users.

**Comment by MisterY** [comment]
More requests from the users.

**Comment by Geoplace** [comment]
It would be very useful to support the entire QIF standard.
Also to encorage migration of users from HomeBank to MMEX, because homebank support notes in each split transaction register.

**Comment by kazinci** [comment]
+1, it also would be helpful for me.
I must count the transaction I made with my bankcard to reduce the account management fee: if I use my bank card 30 times in a month I get 90% discount from the fee. So I create for every transaction an expense record with split category if I bought more than one thing. It's pretty good, but later I can't see what I bought exactly. If there would be a field for every split transaction I could note for example where and what I bought.
By doing so, I could compare for example the prices between different shops for the same thing.

**Comment by MisterY** [comment]
Is there any benefit in implementing this in the mobile version separately to the desktop?
I could make a change that adds the notes field to the split categories. This would also be exported to .qif files.
Implementation in the PC version could come at a later stage?

**Comment by Geoplace** [comment]
I'm sure that is very positive this split transaction functionality to start its implementation.
We just have to be sure that desktop version doesn't crash when trying to open the database.
It doesn't matter if they implement the database fields later. The info would be there for the desktop to read it when functions are implemented.

**Comment by vomikan** [comment]
@MisterY please don't add any tables for split notes. 
Use CSV for split notes or, in extreme cases,
JSON. https://www.sqlite.org/json1.html

**Comment by MisterY** [comment]
@vomikan, we still need a field for the notes in the split categories table.

**Comment by MisterY** [comment]
The support for this feature is coming with desktop MMEX 2.0.

**Comment by wolfsolver** [comment]
See issue #1475
