### ISSUE TITLE
Can't sync with Dropbox on Android 4.4

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#255]
Just noticed this issue today on a phone with Android 4.4.
Downloading of the database from Dropbox does not work. The database is never saved to the directory on external storage.
There is a file database.mmb-something, which is probably generated by the app but there is no .mmb file itself.
Other users might be experiencing this same issue. 

When I get this phone again I might investigate further. In the meantime we should test with another phone or an emulator. I'm aware that v4.4 was preventing access to external storage but not sure what exactly was the issue.

**Comment by MisterY** [comment]
Some links:
http://www.androidcentral.com/kitkat-sdcard-changes

**Comment by AlessandroLazzari** [comment]
Hello, I tried this issue in an emulator, but I can not find the problem.
In the beta test I had on my phone the Android version: KitKat with the sync and I never had any problems.
Do you have a Logcat of the issue?

**Comment by MisterY** [comment]
This phone is on Cyanogen Mod but I don't know if that is relevant. I'll try to get a logcat when I have the chance.
Good to see that it doesn't happen in the emulator. 
On this particular phone I could not export a file from Dropbox app onto SD card so it could be caused by something else.

**Comment by MisterY** [comment]
Now everything works. In the meantime I have upgraded the ROM so that may have fixed it.
