### ISSUE TITLE
App crashes when offline

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#257]
User left a remark in Play Store that the app crashes when offline.

I ran into something similar in an emulator that did not have Internet access. We should inspect the Dropbox check on app start.

**Comment by AlessandroLazzari** [comment]
Maybe, it solved with version 2.0.1. I think the problem was the nullObject
of e.getMessage()

**Comment by MisterY** [comment]
Aha, good guess! Yes, the report was for the v2.0.0. 
I'll check the catlog in the emulator to confirm and close the issue if everything is ok.

**Comment by MisterY** [comment]
Reference in Play Store: Sidney Curi on 9 May 2015 at 19:02

**Comment by MisterY** [comment]
Can't reproduce in available devices. Probably fixed by #244.

**Comment by MisterY** [comment]
The strange thing is that I'm not getting an exception in the version that does not contain this fix.
