### ISSUE TITLE
View stock chart from watchlist

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#275]
Similar to chart in currencies.

```
<img src="http://chart.finance.yahoo.com/z?s=AAPL&t=6m&q=l&l=on&z=s&p=m50,m200"/>
```

Ref: http://stackoverflow.com/questions/9807353/getting-stock-graphs-from-yahoo-finance

**Comment by CraftingGamerTom** [comment]
Seems chart.finance.yahoo.com is no longer supported but this feature request is great. A different API is needed.
