### ISSUE TITLE
Make Payee optional

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#278]
The payee should be an optional field on the transaction. The Category is required, however.

Need coordination with the desktop team.

**Comment by MisterY** [comment]
Just for comparison, I checked Quicken. Payee is also not required there. Category is only suggested but also not required.

**Comment by vomikan** [comment]
It's easy to implement this feature if  'Payee not used' option is
activated - 'unknown' payee should be used by default (and Payee dropdown
menu may be hiden.
'Unknown' payee  is already used for an import if payee not defind.

воскресенье, 17 мая 2015 г. пользователь Alen Siljak написал:

**Comment by MisterY** [comment]
Excellent, thanks! I'll have a look at desktop implementation and add this to our backlog.
