### ISSUE TITLE
Menu button does not open the drawer

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#29]
The hardware menu button does not open the <s>sidebar menu</s> drawer on the main screen.

Affected version 2.0.0 Alpha 2.

Toggling the drawer by tapping the menu button would be great.

**Comment by AlessandroLazzari** [comment]
Solved

**Comment by MisterY** [comment]
Excellent! Can't wait for the next release.

**Comment by MisterY** [comment]
For some reason this is not working in the latest version (alpha 3). The code is there but the drawer is not opening. Will check more tomorrow. Thanks for the updates.

**Comment by MisterY** [comment]
What's worse, none of the onKeyDown are being triggered anymore. Not sure if the code in there is significantly important but there are quite a few of them.

**Comment by AlessandroLazzari** [comment]
​​I will verify the reason for the non-functioning of this issue this
weekend.
However, I verified that it is not in the Google Guidelines that the
hardwaere key menu should open the Drawer application. Try a Google
application, if you press the menu button does not open the Drawer

2015-03-13 10:24 GMT+01:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
Right. I noticed that in Play Store. They seem to be moving away from hardware keys, following Apple into having just one hardware key. Guess we'll have to get used to it.
But the interesting thing is that MENU and HOME keys are not caught by onKeyDown handler any more, as of the latest update. Do you have an idea what could be causing it?

**Comment by AlessandroLazzari** [comment]
The cause could be the update to v22 SDK (Android 5.1) that I made last
night.

**Comment by MisterY** [comment]
OK. Most of the onKeyDown handlers are looking for the BACK key, which is still being caught. So the other functionality should not be too affected by this.
