### ISSUE TITLE
The app crashes when editing a transaction

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#30]
version affected: 2.0.0. Alpha 2

In certain situations the app will crash completely. There is no crash dialog for submitting feedback.

One scenario is the following:
- open the app
- open the account transaction list
- edit a transaction
- modify the transaction date
- tap Save

Here is the [logcat](https://www.dropbox.com/s/nc1cz8whtbi161v/2015-03-11-16-48-16.txt?dl=0)

This is hapenning on Android 5.

**Comment by AlessandroLazzari** [comment]
have you upgraded from version 1.4.17 to version 2.0.0 alpha? or is a clean install?

**Comment by AlessandroLazzari** [comment]
I could not simulate the problem. Reading Google help page I modified different code that you can look in this commit:

https://github.com/AlessandroLazzari/android-money-manager-ex/commit/6b63c3f2dfe9411eca5800bfafa407733b4e0cbe

Tonight I perform the merge of these changes on the branch androdi-l-dev main repo.

**Comment by MisterY** [comment]
The database was taken used by 1.4.17.

The application 1.4.17 was removed. Then I installed manually versions from GitHub releases. This was happening regularly. 
Today I removed that version, joined beta testing and installed from Google Play.

**Comment by MisterY** [comment]
Great. Looking forward to the next version. Will provide further info at that point.

**Comment by AlessandroLazzari** [comment]
Hi,
I made the merge of the changes:
https://github.com/moneymanagerex/android-money-manager-ex/commit/8aba4af5d3eae48db6057e81dcd4806bf7e0f2ef
can you try again?

**Comment by MisterY** [comment]
Still the same. New [logcat](https://www.dropbox.com/s/837f6koyor306pu/2015-03-12-09-30-logcat.txt?dl=0).
The interesting part is this:

>03-12 09:25:50.285 E/AndroidRuntime(23352): Process: com.money.manager.ex, PID: 23352
>03-12 09:25:50.285 E/AndroidRuntime(23352): Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /storage/emulated/0/MoneyManagerEx/dropbox/alen.mmb
>03-12 09:25:50.285 E/AndroidRuntime(23352): 	at com.money.manager.ex.adapter.AllDataAdapter$BalanceAmount.doInBackground(AllDataAdapter.java:375)
>03-12 09:25:50.285 E/AndroidRuntime(23352): 	at com.money.manager.ex.adapter.AllDataAdapter$BalanceAmount.doInBackground(AllDataAdapter.java:360)

Need to find more about "attempt to re-open an already-closed object: SQLiteDatabase" happening at AllDataAdapter.java:375.

**Comment by MisterY** [comment]
I've broken down the long command into simpler ones, to see where the exception originates. 

https://github.com/MisterY/android-money-manager-ex/commit/88dde0be9f612c6dd11891fbc02aa6c2f3bbd838

and now the error is completely different. [Logcat](https://www.dropbox.com/s/nf4moqrirqz79ql/2015-03-12-10-23-43.txt?dl=0)

**Comment by MisterY** [comment]
OK, good news - I don't know what **exactly** is the reason but I have a good hint and I know when it happens.
There is a deadlock issue when "balance for each transaction" is used. Db is closed after editing the transaction and the checking account activity tries to read but mDatabase variable has no references. 
My guess is that in one of these getDatabase() calls, it should just check if there are any left and re-open the database connection if there aren't.

**Comment by AlessandroLazzari** [comment]
I was able to simulate the issue. Tonight I try to find a solution.

**Comment by MisterY** [comment]
Excellent!

**Comment by MisterY** [comment]
I can confirm the crash is not happening any more.
