### ISSUE TITLE
Changing font size does not work. Font too small.

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#328]
>Very good app, but changing the font size don't work. Letters are too tiny and for this reason very hard to read. CM12.1 xperia z1c

> Edit: is partly working, for example font size is changing for input, when noting an expense, but the output (report) keeps with the tiny font hard to read output. The option changing the font size should work on all program parts for good readability all over the app. Handling numbers, good readability is very important.

> In the first 2 screenshots changing font size worked, in the last one not.

<img src="https://cloud.githubusercontent.com/assets/462445/8271214/801a7da6-180b-11e5-9aeb-93594c29aa84.png" width="200px" /> <img src="https://cloud.githubusercontent.com/assets/462445/8271216/805e4ef0-180b-11e5-8867-499fbdb97891.png" width="200px" /> <img src="https://cloud.githubusercontent.com/assets/462445/8271215/80508ed2-180b-11e5-8ff1-1902baec5dfb.png" width="200px" />

**Comment by MisterY** [comment]
I can't reproduce this at the moment.

<img src="https://cloud.githubusercontent.com/assets/462445/8376697/346a7372-1c0a-11e5-9dff-e358d99a621f.png" width="200px" />

**Comment by paulle** [comment]
Yes, your screenshot is looking all right, but I tested it on 2 phones (xperia z1c and z3) both with CM12 installed, changing the font size is only partly working as shown in 3 screenshots above.
I've no idea what coud be the reason for this behaviour.

**Comment by MisterY** [comment]
Fix confirmed. Thanks!
Let me know if there are other places where the setting is not applied to the text size.
