### ISSUE TITLE
Crash on manual dropbox sync

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#33]
I'm getting this with the latest build (2.0 Alpha 2).

- set-up Dropbox db sync
- open menu drawer 
- tap on Synchronize

The app crashes.

**Comment by AlessandroLazzari** [comment]
May be I have yet to do a full tour of the application after you have fixed the memory leak problem.
Tonight I'II check.

**Comment by MisterY** [comment]
So far I can tell that it's happening on progressDialog.show(); in MainActivity:startServiceSyncDropbox, line 358. If you can reproduce, that's great.

**Comment by AlessandroLazzari** [comment]
I have not looked at the code but certainly the problem is the context that is passed to ProgressDialog.
This evening fix it.

**Comment by MisterY** [comment]
Fantastic. That's all I ran into so far. Enough for today, I believe. ;)

**Comment by AlessandroLazzari** [comment]
Fixed https://github.com/AlessandroLazzari/android-money-manager-ex/commit/ee62b73e70de330e794023c2b436c6540750d0b6

**Comment by MisterY** [comment]
:+1:
