### ISSUE TITLE
Link to Database anywhere in Dropbox

### ISSUE THREAD

**Issue by GordCaswell** [moneymanagerex/android-money-manager-ex#335]
It would be nice to be able to link to the database located anywhere in the Dropbox, for example in the "Shared" folder, in order to share the database with a spouse; rather than being limited to the Apps\MMEX Mobile folder.

**Comment by MisterY** [comment]
Note: Add a preference in the Dropbox settings to switch to full-tree permissions in Dropbox. 
This would allow a scenario where users want to share the database folder with other users.

**Comment by rjd22** [comment]
I would love to see this feature. Sharing your Money manager with someone else is not possible right now.

**Comment by MisterY** [comment]
This is coming as a part of #845
