### ISSUE TITLE
Try/switch to the Floating Action Button from the support library

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#336]
The SDK support library in version 22.2.0 has introduced the FloatingActionButton. We should try it out and see if the custom library can be replaced by the one from SDK.

References:
[Support Library](http://developer.android.com/tools/support-library/index.html)
[FAB](http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html)
[Tutorial](https://guides.codepath.com/android/floating-action-buttons)

**Comment by MisterY** [comment]
It is a bit more raw and complex than the current implementation. No need for switching while the current one works OK.

**Comment by MisterY** [comment]
The current implementation of fab in the support library is as simple as the component in use at the moment. [Sample](http://stackoverflow.com/questions/30576450/floatingactionbutton-example-with-support-library).
It should be fairly easy to replace. Plus the one from the Support library does not require frame layout.

**Comment by MisterY** [comment]
The library is already providing all the functionality that has to be built around the fab implementation in the framework.

**Comment by MisterY** [comment]
The library is now deprecated and it is recommended to switch to the support library's FAB.
