### ISSUE TITLE
Show balance totals for the past period(s)

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#341]
> a report for the total amount of all accounts over the last 12 months displayed in bars
> 
> There's a function e.g. in Quicken that shows you your total balance as one bar for each month so in total 12 bars for a year. It might be nice if that feature is inserted to the other reports where you have the reports for income and expenses etc.

This would be similar to Income vs Expense report but just showing the balance over the (pre-)selected period of time.

Addition: Another user is asking for the period of last 3 years.

<img src="https://cloud.githubusercontent.com/assets/462445/11766378/dc6c6abc-a184-11e5-8363-78d221c0988f.jpg" width="200px" />

**Comment by MisterY** [comment]
After the clarification, this seems pretty much like the chart view for Income vs Expense report.
There is no balance as such, though, but there are sums for deposits and withdrawals.
