### ISSUE TITLE
Search is case-sensitive in non-Latin locales

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#348]
The <s>search</s> filters in pickers (for example, Payees) are case-insensitive in English but in Russian it is not. 
Requires investigation.
This is manifested when picking a payee or a category and using the filter in the toolbar to narrow down the list.

**Comment by MisterY** [comment]
http://www.sqlite.org/faq.html#q18

**Comment by MisterY** [comment]
SQLite documentation (see above) mentions the International Components for Unicode (ICU) extension ([link](http://www.sqlite.org/src/artifact?ci=trunk&filename=ext/icu/README.txt)).

**Comment by MisterY** [comment]
Perhaps using SQL Cipher would include the Unicode support. This can be combined with the encryption support.
[link](https://groups.google.com/forum/#!topic/sqlcipher/-0nMc1f_UTE)

**Comment by MisterY** [comment]
See [the latest info](http://stackoverflow.com/questions/29669342/unicode-support-for-sqlite-full-text-search-in-android).
