### ISSUE TITLE
Export the reports into Excel/CSV format

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#360]

**Comment by MisterY** [comment]
Can be combined with #183 to provide export feature.

**Comment by paulle** [comment]
Maybe instead of Excel format, better eport in .ods format, so it can be used with excel and libre/open office.

**Comment by MisterY** [comment]
See the workaround suggestion for #183

**Comment by MisterY** [comment]
This would also be handy for GnuCash import.
