### ISSUE TITLE
Support for custom reports

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#363]
Similar to desktop application, users want to be able to create and use custom reports.

The display is HTML so a webView can be used to render reports. 
Export option might also be handy.

**Comment by MisterY** [comment]
Initial implementation could be just the viewer for the already created reports. The reports are found in the Report_v1 table.
Template is the HTML content and the SQL is in SQLContent field.

**Comment by velmuruganc** [comment]
@MisterY , I use custom report very frequently and will pick this up after moving sms transaction feature to stable release.

**Comment by velmuruganc** [comment]
@MisterY, could you please tell me where i can add values like this "R.id.menu_reports". I want to use as "R.id.menu_custom_reports", but throws error "Error:(1065, 55) error: cannot find symbol variable menu_custom_reports"

**Comment by MisterY** [comment]
You should check strings.xml.

**Comment by velmuruganc** [comment]
@MisterY , thanks i got. Also I have completed the UI changes. Now learning the fragments to implement the report activity.

<img width="181" alt="2017-12-18 06_36_01-android emulator - pixel_xl_api_27_5554" src="https://user-images.githubusercontent.com/29807533/34086021-4f896ffe-e3be-11e7-877e-aed775d905d1.png">
<img width="185" alt="2017-12-18 06_36_36-android emulator - pixel_xl_api_27_5554" src="https://user-images.githubusercontent.com/29807533/34086026-5588d0b6-e3be-11e7-8717-cffac8f00a5a.png">

**Comment by MisterY** [comment]
You can have a look at a web browser activity/fragment. I think it is used a few places in the app already, like the intro or donations page. I think it would be the best to have an HTML output from custom reports and display it in a web browser activity.

**Comment by velmuruganc** [comment]
@MisterY, What is the use of adapters. Could you please give some idea in this?

**Comment by MisterY** [comment]
Hi,
I would recommend reading (a lot) about any unclear parts of the code. Specifically:

- https://developer.android.com/reference/android/widget/Adapter.html
- https://www.intertech.com/Blog/android-adapters-adapterviews/
- https://code.tutsplus.com/tutorials/android-from-scratch-understanding-adapters-and-adapter-views--cms-26646
etc.

**Comment by velmuruganc** [comment]
@MisterY, Thanks for the link. I will go thru these topics.

I don't think, we can use the web content for custom report, bcz i dont see any way to inject the data into html content available in report table.

**Comment by MisterY** [comment]
What I had in mind is to use a templating engine. These, at least, are not in short supply:

- https://github.com/HubSpot/jinjava
- http://www.x5software.com/chunk/examples/ChunkExample
- http://www.vogella.com/tutorials/FreeMarker/article.html and https://freemarker.apache.org/
- http://www.vogella.com/tutorials/EclipseJET/article.html

If not, how else would you render custom reports to the user?

**Comment by velmuruganc** [comment]
@MisterY, It would be straight fwd to fetch the result of sql query and show the row/clmns thru views & adapter. This would be similar to how we shows the payee and other reports. May be I am wrong. Let me learn and explore the possible options.

**Comment by MisterY** [comment]
You may be right. I don't use custom reports so I don't really know what exactly is required.
My understanding was that the custom reports are alredy stored as HTML templates.

**Comment by Spoker** [comment]
It would be great if custom reports worked the same as in the desktop version.
Don't forget that de sql output gets transformed through the lua script before being shown in the html. Also, some custom reports use javascript to show the results visually in a graph.

**Comment by MisterY** [comment]
Yes, that is the original purpose of this request. Not to have just any report but to utilise the custom reports that are stored within the database file, matching the desktop functionality as much as is possible with a mobile device. With HTML, this should be possible to an extent.

**Comment by velmuruganc** [comment]
@MisterY , App getting crashed when I call following line in my activity. It looks some issue with constructor. Could you please help me?

CustomReportAdapter reportAdapter = new CustomReportAdapter(this, getCustomReportCursor());

Following is the constructor in CustomReportAdapter,

public CustomReportAdapter(Context context, Cursor cursor) {
        super(context, cursor, false);
    }

**Comment by MisterY** [comment]
Can you at least tell me what the error is? I can not tell what the issue is just by looking at this code.

**Comment by velmuruganc** [comment]
@Spoker, As of now, I could able to generate my own html page as a first step. Do you have any docs that explains how we should inject the sql output to html template?

![image](https://user-images.githubusercontent.com/29807533/34281060-185a65ca-e6e2-11e7-90f9-ef68e90032ad.png)

**Comment by MisterY** [comment]
Please look into some of the libraries I shared earlier. Preferably Jinja, as it will fit into some other work that is going on in parallel.

**Comment by velmuruganc** [comment]
One question. Do we need to call this as custom report or general report? Desktop version ref as general Report.

**Comment by MisterY** [comment]
Hm, it used to be custom reports at a time when this request was created. :)
I have not been following closely. The name "general reports" makes no sense to me, to be honest.
These are user-generated reports or custom reports and the name should indicate their purpose.
However, if that is the name in the desktop version, then so be it.

**Comment by luisdev** [comment]
This would still be a good feature, so I think it should stay open.
