### ISSUE TITLE
Show amounts in original currency in reports

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#365]
The reports that combine accounts in different currencies should provide sums in those same accounts.
The reason is that, as the exchange rate varies, these amounts change in the reports even though they stay the same in the originating currency.

It would be practical to have both values in parallel (the amount in original currency and the converted amount in the base currency). For small amounts, for example when travelling, the amounts in the original currency are irrelevant and the amount converted to base currency might be more important.

**Comment by MisterY** [comment]
This is not very practical in reports like Categories or Payees as there could be many transactions in different currencies involved. Which currency should then be used?
Quicken reports also work like this.

**Comment by MisterY** [comment]
Option to choose a currency for the report would be handy. That would require any conversion to happen in the report and the calculations inside the SQL queries would have to be rewritten.
