### ISSUE TITLE
Enable creation and editing of budgets

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#388]
Part of #184.

**Comment by marty008** [comment]
Being a pedantic type, I would like to be able to copy the 2015 budget to become the 2016 budget with an across the board % being specified and added to each 2015 item.

**Comment by MisterY** [comment]
Great, will add that as a separate feature request.

**Comment by hurrycaner** [comment]
+1 to creation and editing of budgets

**Comment by yaomtc** [comment]
It actually lets you start the process of creating a budget in the app, letting you choose a month and a day. However, nothing past that point, and you can't edit the name. I'll have to just use the desktop app for this for now!

**Comment by MisterY** [comment]
You can also add the missing functionality. 😉
Pull requests are accepted and encouraged.

**Comment by yaomtc** [comment]
Well then, this videographer better start learning how to program! Haha.

(Guess I could donate...)

**Comment by MisterY** [comment]
I was expecting that one. Please see at least the first five minutes of the following video: https://www.youtube.com/watch?v=TK1mBqKvIyU
It may change your mind. I'm also not an Android developer.

**Comment by yaomtc** [comment]
Can create a budget by choosing a month and year, but can't set any dollar amounts.

**Comment by guanlisheng** [comment]
i belive this is the same as MMEX4Desktop.

**Comment by yaomtc** [comment]
You can set dollar amounts on the desktop.

**Comment by yaomtc** [comment]
![Screenshot_20240317_222232](https://github.com/moneymanagerex/android-money-manager-ex/assets/5534045/b27be3f2-c67d-4c3b-bc88-5b05001c870a)

**Comment by guanlisheng** [comment]
I see. 

I thought you were saying to create the budgeting entry itself.
 
editing the budget transactions of a month or year budget is not supported yet.
a workaround is to fall back to desktop mmex
