### ISSUE TITLE
Feature: Sync Dropbox on open or other events

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#39]
There is an excellent suggestion in the reviews on Google Play. It asks for synchronizing Dropbox when the app is opened.
I second that the event-based synchronization is, to some, more convenient than time-based. They could also work in parallel. For example, having a daily sync scheduled + sync on open/close.

There are already settings to immediately sync on change. 
Maybe the sync settings section could be reorganized to have event-based and time-based settings next to one another. 
The options for time-based sync are already there.
The options for event-based sync can be assembled from existing ones + some new ones. 
- on app open (new)
- on change (existing)
- on app close (new, can this even be detected?)

**Comment by AlessandroLazzari** [comment]
This feature is already planned for the release of 2.0, and maybe will be
implemented already this weekend.
The database can be synchronized only when the application is opened, as it
is not possible to intercept the application is closed.
Is never notified the close event of application.

**Comment by MisterY** [comment]
This works beautifully. Is it still necessary to tap "Open Database" in the notification?
