### ISSUE TITLE
"No chart data available" in most (not all) reports

### ISSUE THREAD

**Issue by sliwowitz** [moneymanagerex/android-money-manager-ex#400]
I'm using Money Manager Ex on Android, version 2.7.2. Suddenly most of the reports stopped showing charts, saying "No chart data available" instead. It happens to all reports except for Payees report - that one works, and shows the chart correctly. All other reports (Categories, Income vs. Expenses, etc.) will display the data in the table, but when I click on the chart icon, it says "No chart data available" - even when there's clearly a lot of data present.

**Comment by MisterY** [comment]
Thanks for reporting this! It has been corrected and will be released with the next version.
