### ISSUE TITLE
Recurring Payments Widget

### ISSUE THREAD

**Issue by JHale1966** [moneymanagerex/android-money-manager-ex#408]
Not an issue but a request. Can a widget be created that shows the items in the recurring payment list? This would help out greatly as it would allow me to view them faster than having to go into MMEX all the time.

Thanks!

Jim Hale

**Comment by MisterY** [comment]
Sure! Sounds interesting. A few widgets need a refresh, anyway, so this would be a good opportunity to turn the focus to the widgets next.

**Comment by JHale1966** [comment]
That would be great. Thanks :)
