### ISSUE TITLE
Add transaction type to categories

### ISSUE THREAD

**Issue by nhannv** [moneymanagerex/android-money-manager-ex#409]
Can we add a column transaction type to table category? So that we can filter cat by transcode. Currently, when we create new transaction, we choose Withdrawal but can choose category Income, it's not make sense. Cheer

**Comment by MisterY** [comment]
This has to be agreed by the desktop team first, as it requires a database change.

**Comment by MisterY** [comment]
The request has been rejected by the desktop team.
