### ISSUE TITLE
The wording in recurring transactions overdue is misleading

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#41]
The notification in the drawer shows two transactions overdue:
![notification-error](https://cloud.githubusercontent.com/assets/462445/6636885/7b531b06-c974-11e4-9b47-a505c093b9ca.PNG)

However, in the transactions list,
![recurring-transactions](https://cloud.githubusercontent.com/assets/462445/6636897/9f3f16aa-c974-11e4-82e9-dad9ee6a6a27.PNG)
only one of them is shown as overdue. The other one is due today.

So, perhaps a clearer wording would be more appropriate here? The transaction which is due today shows *Inactive*. Maybe this could be made to say *Due Today* or something similar.

![three](https://cloud.githubusercontent.com/assets/462445/6637078/46162b84-c976-11e4-8994-0394084507cc.PNG)

Note: the snapshot is taken on day 13. The transaction on 12th is overdue, the one on 13th is due, and on 15th is in the future.

**Comment by AlessandroLazzari** [comment]
Can you check this issue?
Il 13/mar/2015 11:33 "Alen Siljak" <notifications@github.com> ha scritto:

**Comment by MisterY** [comment]
I've modified the text compared to the initial report. Now the only issue is that the text *Active* is displayed for the items that are due today. The rest seems to work fine!

**Comment by MisterY** [comment]
Hey, Alessandro, I'm not sure what do you mean here. There might be some
confusion because my initial report stated that the number of transactions
was wrong. But, in reality, it wasn't. I was merely confused by the fact
that, out of the two items, only one was marked as Overdue while the other
simply said "Inactive". Then I realized that the second one was due "today"
so the indicator was correct to show 2 transactions as overdue.
So, perhaps, only updating the word "Inactive" in the recurring
transactions list can be updated to "Due Today", or something that is more
descriptive.
I can also have a look at this. It is a minor issue and could be a good
reason for me to read some more code. :)

Cheers,

Alen

**Comment by MisterY** [comment]
Fixed in v2.0 
#52
