### ISSUE TITLE
Enable widget text customization

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#421]
> is it possible to edit the text in the widget icon?  I want to make the widget smaller and when i do that, it becomes messy!

**Comment by diggy128** [comment]
+1
I've also tried searching for the string to translate it in crowdin, but couldn't find. Is it hard coded?

**Comment by MisterY** [comment]
No text should be hard-coded. Which widget is that? You can also have a look directly in the source code.

**Comment by diggy128** [comment]
It's:
`new_transaction`
in android-money-manager-ex/app/src/main/res/layout/widget_button_add_transaction.xml

for widget:
`R.layout.widget_button_add_transaction`
in android-money-manager-ex/app/src/main/java/com/money/manager/ex/widget/ButtonAddTransactionWidgetProvider.java

Just a wild guess (I don't have a clue about android development)
could it be
`android:id="@+id/buttonNewOperation"` that's wrong?
