### ISSUE TITLE
Support for Assets

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#429]
Support the Asset account type.

**Comment by luisdev** [comment]
What is that "Asset" account type that alensiljak was referring to?

**Comment by wolfsolver** [comment]
Is an asset management available in mmex desktop version (like house, car,...). They can have depreciation ore increase criteria (house increase, car decrease). 
This functionality was removed in AMMEX as in #1258.

**Comment by luisdev** [comment]
Thanks.
So the "Asset" account type was removed from AMMEX because Alen moved his development efforts to the "Python AA" project?

**Comment by alensiljak** [comment]
> Thanks. So the "Asset" account type was removed from AMMEX because Alen moved his development efforts to the "Python AA" project?

I would like to clarify that there is a difference between Asset Management and Asset Allocation, which I added to MMEX. 

This particular request is for Assets type and was requested by a user. They want to have a house, car, etc. as an Asset type, where they can track depreciation or whatever else. It is a common occurrence in personal finance.

Asset Allocation, on the other hand, was used to set the the desired allocation of investment assets (i.e. fixed, equity) and then track their state based on market prices.
The Asset Allocation continued through several different projects and technologies later and is currently maintained in Cashier (https://cashier-ii.alensiljak.eu.org/).
