### ISSUE TITLE
Allow import from anMoney

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#443]
Direct import from anMoney.

Need to research what export files are available from anMoney, and if they can be imported through currently available functionality in the desktop version.

**Comment by ppGrande** [comment]
Any advances on this topic?
I have try with CSV and QIF and I am not able able to make MoneyManagerEx to recognize trasnfers between acoounts

**Comment by MisterY** [comment]
Currently no progress in the Android version. I'd recommend posting an issue in the desktop repository, so that it gets included in the upcoming versions:
https://github.com/moneymanagerex/moneymanagerex
