### ISSUE TITLE
Feature: Remember the last Amount along with the last Category

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#45]
There is a great time-saver of a feature used when entering new transactions, where the last chosen Category is remembered for a Payee. This avoids usually needless selection of the same values over and over.

I would suggest the Amount value to be saved, as well. It would further save time on entering the similar transactions.

Both of these options might (should?) be configurable in the Settings so that the users can set their individual preferences. I understand that not all the users will use the app in the same way so being able to set the preferences that differ from the defaults would be great.

The case where remembering an amount, along with a way to quickly overwrite it in cases where the new amount differs to the saved one, would be much easier for me compared to the case of entering the amount every time when the Payee is the same. 
Something to discuss.

**Comment by AlessandroLazzari** [comment]
There is the option in the settings the user can indicate if he wants to use the last used payee.
There is already the possibility for the user to indicate a default state into settings.
Since version 2.0 the user can duplicate one or more existing transactions.

**Comment by MisterY** [comment]
Duplication is an excellent feature. It mostly replaces the need for remembering the amount. Now we just need some sort of quick search in the transaction list (account).
