### ISSUE TITLE
Allow customization of the period for the income/expense footer/report

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#463]
On Home screen, the income/expense overview (in the footer) and the related report (when tapped on), display the current calendar month only.
Allow setting a custom period for both of these.
i.e. last 30 days or last 7 days might be more useful in certain scenarios

**Comment by MisterY** [comment]
As the report covers a calendar year and months, it should not use the same setting. Just adjust the footer.

**Comment by MisterY** [comment]
Query needs to be adjusted.

**Comment by sjturner54** [comment]
I am paid on 28th so would like to show 1 month from that day. Currently I see high expenditure until 28th

**Comment by MisterY** [comment]
Just to provide some info on the progress:
I've tried changing this but the blocking issue in implementing this is the base query, which calculates the income and expenses per year/month and then simply gets the last month from this result set.
To implement a custom period, a new query needs to be written to list the sums for the selected period only.
