### ISSUE TITLE
Wrong running total for a day

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#467]
>Since you've just changed to 'list deposit transactions first for each date' the running total is no longer correct within a day on the android app.

**Comment by fraheor** [comment]
I have the latest version of the android app and it seems the problem persists

**Comment by MisterY** [comment]
I've had another similar case yesterday. The account Id stored on one transaction was treated differently by SQLite in two different queries. Bizzare. Would you have a screenshot for this case?

**Comment by fraheor** [comment]
Sorry for my late response. I got the version 2.18.7 (build 710) and wasn't able to reproduce

**Comment by MisterY** [comment]
Thank you for the confirmation!
