### ISSUE TITLE
Custom widget for quick creation of transactions

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#474]
> Hi, in a next dev could we have customized widget which could be fitted with frequent operations... Like fuel, or restaurant or else, parameters could be defined by the user...for instance, custom widget will automatically add the sens (-or+) and the category and the user just add the amount.... Could be helpful it repetitive operations on a phone to keep accurate the mmex database in short time

**Comment by vomikan** [comment]
Cool idea!

2015-09-05 17:28 GMT+03:00 Alen Siljak <notifications@github.com>:
