### ISSUE TITLE
Transfers do not list deposits first in the transaction list

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#486]
When there are multiple transfers on a same date, the incoming transfers are not ordered first. Check the behaviour in the desktop application.

**Comment by MisterY** [comment]
This is too difficult to correct in the current setup.
The fact that we are using one record for transfers, which is used in the transactions lists for both accounts, makes it impossible to know whether this is an incoming or outgoing transfer without knowing the context (account being looked at). This excludes the possibility to find this out in the query.
It is possible to know this information only in code when the list is being displayed but by that time the order of the data has already been set.
An account Id parameter needs to be sent to the query, which would then mark as incoming the transactions where this account id is the destination account in Transfers.
