### ISSUE TITLE
Currency exchange rate chart options

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#50]
<s>Allow showing a full-screen (landscape) chart of the currency exchange rate for the currency.</s> Implemented

A few options should be available on the chart:
- reverse currency pair
- modify the date range
- modify chart type (bar, line, ...)

The currency chart is always paired with the default currency for displaying the chart.
The selected options should be persisted so that the next time the chart opens, it uses the last settings for the date range and chart type.

**Comment by MisterY** [comment]
Initial implementation of the 5-day chart is done. Now the input for additional parameters can be added as a toolbar or something similar.

**Comment by AlessandroLazzari** [comment]
Can we close it?

**Comment by MisterY** [comment]
I would like to add a toolbar with the options listed here. Let's leave it open instead of creating a separate issue for that.
Need to allow for custom period selection, chart style, etc.

**Comment by AlessandroLazzari** [comment]
IMO, we continue on this issue.

**Comment by CraftingGamerTom** [comment]
Status update? @AlessandroLazzari @MisterY 

How much of this has been implemented and merged? Anything remaining lets make a new issue.
