### ISSUE TITLE
Recurring Transactions transfer date

### ISSUE THREAD

**Issue by Stonyjohn** [moneymanagerex/android-money-manager-ex#505]
MoneyManagerEx 1.2.2.
The date shown on the listing when a Recurring Transaction is transfered always reverts to the current date. Also there is general confusion between "Payment Date" and "Due Date".I have detailed the problem here:
http://forum.moneymanagerex.org/viewtopic.php?f=5&t=6045&start=10#p12687

**Comment by MisterY** [comment]
Hi,

Is this referring to the Android version or the desktop? The desktop version is using a different repository- https://github.com/moneymanagerex/moneymanagerex.

**Comment by Stonyjohn** [comment]
Opps... my apologies. Yes it's for the desktop version. I couldn't find any way to add a new issue until after pressing several buttons I found yours.

I've now poseted in the correct place. Again, sincere apologies.

**Comment by MisterY** [comment]
No problem. Glad that the issue found its destination. :)
