### ISSUE TITLE
Exception on long-press in the transactions list

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#515]
************ APP DETAILS ************ Version: 2.19.5 Build: 721 ************ CAUSE OF ERROR ************ java.lang.AbstractMethodError: abstract method not implemented at android.view.ActionMode.setRightActionButtonVisibility(ActionMode.java) at android.widget.AbsListView.performLongPress(AbsListView.java:3097) at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3053) at android.os.Handler.handleCallback(Handler.java:808) at android.os.Handler.dispatchMessage(Handler.java:103) at android.os.Looper.loop(Looper.java:193) at android.app.ActivityThread.main(ActivityThread.java:5499) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) at dalvik.system.NativeStart.main(Native Method) ************ DEVICE INFORMATION *********** Brand: Lenovo Device: Android Model: Lenovo A328 Id: KOT49H Product: Lenovo_A328 ************ FIRMWARE ************ SDK: 19 Release: 4.4.2 Incremental: eng.root.1428578002

**Comment by MisterY** [comment]
Can't reproduce on any real or test device.

**Comment by daniele-athome** [comment]
I also got this error on a Huawei device, but there is no such method in the ActionMode class. It's outrageous how some OEMs modify Android.

**Comment by MisterY** [comment]
Absolutely the worst case I've seen so far is tracked [here](https://code.google.com/p/android/issues/detail?id=78377) and Google won't even try to fix it. Not to mention Samsung's devs who modified it in the first place.
