### ISSUE TITLE
new reoccurring transaction - error message recieved

### ISSUE THREAD

**Issue by avma** [moneymanagerex/android-money-manager-ex#516]
Hi,

in new reoccurring transaction screen, while selecting the account, an error message pops up :"CURRANCYFORMATS_V1:  47 not found".
see attached image
my regards
avi
![capture](https://cloud.githubusercontent.com/assets/7680483/9954906/718c0cfc-5df5-11e5-80ad-a2a434713f37.PNG)

**Comment by MisterY** [comment]
Hi, thanks for the feedback. I don't mean to nitpick and would like to note that this issue refers to the desktop version of the application, which has a separate repository:
https://github.com/moneymanagerex/moneymanagerex
Moving the issue there will make it more likely for the desktop team to see. Thanks for understanding.

**Comment by avma** [comment]
Sure, no problem, my bad....

**Comment by MisterY** [comment]
Thanks. I see the issue there - https://github.com/moneymanagerex/moneymanagerex/issues/562.
