### ISSUE TITLE
Error in opening PC database

### ISSUE THREAD

**Issue by thehobbit78** [moneymanagerex/android-money-manager-ex#517]
Hello,
I use MMEX desktop version, but I can't open the db I use on Android; after opening, these errors are showing in sequence:

Error opening readable database
Error init database, currency
Error init database, date format

Then there are no account, operation, etc showed on application.
On this thread:
http://forum.moneymanagerex.org/viewtopic.php?f=20&t=6189
I've attached a sample db.
Much appreciate if somebody can help me solve this problem.
Thanks a lot.

**Comment by MisterY** [comment]
Thanks for the error report. Can you please report the version of MMEX for Android that manifests this behaviour? Also, could you check Play Store for update to 2.20.1. This should resolve some issues in opening a database.

**Comment by thehobbit78** [comment]
Thanks.
Just checked that 2.20.1 version has the same problem.

**Comment by MisterY** [comment]
I can confirm. Happens with this particular database file. Investigating. Thanks for an interesting case.

**Comment by MisterY** [comment]
The technical reason is that the database user version is set as 0. Will now check the database upgrade process (even though there is nothing in the upgrade scripts).

**Comment by MisterY** [comment]
Unfortunately, this does not solve the issue. There is a difference in behaviour between SQLite libraries, though.

On emulator with Android 4.1.1 the database, SQLite 3.7.11, the database opens but none of the data can be read.

Phone with Android 5.1.1, SQLite 3.8.6, reads the database without any issues.

**Comment by MisterY** [comment]
Oh, I see another anomaly. Had one case like this before. There are 100 indexes generated for CheckingAccount table.
I would suggest migrating the data and schema to a new database file using something like [SQLite DbBrowser](http://sqlitebrowser.org/).

**Comment by MisterY** [comment]
This database is not readable on certain Android devices. This may be dependent on the SQLite version or the file encoding.
It would be interesting to know on which platform and with which version of SQLite libraries was the file generated.

**Comment by ceccadroid** [comment]
Hi! I'm the "creator" of #536 
I had created the databese under Android  Lollipo (Asus Fonepad 8 stock).
As indicated in my post, the database is readable also on my Moto X 2013 (Lollipop too) and also under Windows 7 (portable version of MMEX). The only problem was under Xubuntu LInux

**Comment by MisterY** [comment]
I've notified the desktop team by creating an issue in the desktop repository.
