### ISSUE TITLE
Changed account type under Linux Xubuntu

### ISSUE THREAD

**Issue by ceccadroid** [moneymanagerex/android-money-manager-ex#536]
I'm trying to use my database on both Android (one phon and one tablet) and Linux Xubuntu.
I didn't have any problem with my Android devices, but if I try to use the database under LInux, the credit card account is changed in stock account and is completely empty.
Also under windows the database is correct.

**Comment by MisterY** [comment]
Hi, thanks for the feedback. This appears to be more of an issue related to the desktop Linux version. There is a separate repository for the desktop MMEX here - https://github.com/moneymanagerex/moneymanagerex

Recently I have noticed a few cases that can not be correctly opened on Android (the database opens but it appears as if there is no data) while on Windows everything looks ok. And the interesting thing is that this is not MMEX-specific. Using other tools confirms that something is wrong with the version of SQLite libraries on a specific device.
One piece of information that might help would, therefore, be - which version of SQLite was used to create the database and on which platform?

**Comment by MisterY** [comment]
Strange case, similar to #517
