### ISSUE TITLE
Lock app when switching away

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#543]
> There's something that bothers me for a while. I use a password but many times I swith applications (samsung s3) using the bottom middle button. I also forget to switch back to MMex. It would be really safe to have an auto lock feature lets say after 3 min requiring to reenter my password. This is a great feature in my eWallet app too.

Trigger a timer when the user leaves the app? How to find when the app is not being used?

**Comment by diggy128** [comment]
+1
