### ISSUE TITLE
Configurable Notifications trigger day

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#545]
>what I'm looking for is to be able to have a notification before the recurring transaction is going to happen. So for example I'd like to be warned 7 days ahead that my gym subscription will be paid for in one week. I've already had a few times that I wanted to cancel such a payment before it would be made. It was a very helpful feature in the app that I used before MMEX.

Besides the time at which the notifications are triggered, enable setting the number of days before the event (including 0, which is the day of the event).

This might be related to #672 as the notification date will be the Pay Date, rather than Due Date.

**Comment by sjturner54** [comment]
I also miss this from previous programs. It allowed me to trigger transactions on 1st of month even id they were not due till later

**Comment by MisterY** [comment]
The notification now triggers on Payment Date, while it is actually due only on Due Date.
