### ISSUE TITLE
Minimum account balance

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#547]
> for second one is to set the "minimum balance for checking A/C".
> it could be works as reserve for checking a/c's.
> if a checking A/c having balance of INR 100000, and is set at minimum balance like "INR 10000". then this function will stop the transaction from this A/c, after spending INR90000.
> It looks like reserve for A/c.

**Comment by MisterY** [comment]
The feature can now be added as the schema has been updated.
