### ISSUE TITLE
Open Dropbox configuration on "Configure Dropbox" 

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#55]
On the first app run, a screen is shown that contains the buttons 'create new database' and 'configure Dropbox'. 
The 'configure Dropbox' button opens General settings.
The view that opens should be the Dropbox settings to make things simpler for the new users.

**Comment by AlessandroLazzari** [comment]
With the new tutorial, I think that as the last page the user should choose
what to do:
1. new database
2. Configuration dropbox
3. open db on this device
At the moment, the screen that shown when application first run, is
considered deprecated when tutorial when the tutorial is ready.
However'll fix the code so can be incorporated in the new tutorial

**Comment by MisterY** [comment]
I see. Yes, that makes sense. This is closely linked to #53.
