### ISSUE TITLE
How to build from scratch wiki needed

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/android-money-manager-ex#565]
Hi,

I need step by step instructions how to build android-mmex.
What IDE is best etc...

**Comment by MisterY** [comment]
There is nothing special required to build MMEX. The project has been converted from Eclipse to Gradle (Android Studio). It is enough to open the cloned directory and build.
It would be the best if someone did it for the first time and made notes along.
Also the question is what is the starting point and assumptions. Android SDK and IDE installation are fairly simple and have been described at too many places already, including the official documentation.

**Comment by vomikan** [comment]
I've installed Android Studio. How run android-money-manager-ex?
It's running in hiden console. How to see UI?

**Comment by MisterY** [comment]
You need a device that will run the app. There are multiple options available:

- use a real device via USB debugging
- run the Android emulator that comes with the SDK 
- run Genymotion (recommended)
- or some other emulator

Once a device is connected to the PC, run the app from Android Studio and it will offer the devices visible to adb.

**Comment by vomikan** [comment]
Everything are more difficult than I thought.
1. adb can't find Galaxy A300 and I can't use phisical device.
2. -gpu off option needed for Virtual Device on my PC
3. When emulator started I see only black screen and nothing else.

**Comment by vomikan** [comment]
Just connected other device "ASUS K012". It's working!

**Comment by MisterY** [comment]
Good to see that! Are you migrating from the desktop platforms? 😀
I am using Genymotion lately. It gives me the best performance at the moment.
