### ISSUE TITLE
Add a check for showing split categories as separate transactions

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#570]
When performing Search and looking for certain categories, the search results will display split transactions, not individual split category items.
In the search results, add a checkbox for the user to be able to split the Split Categories transactions into individual records. I.e. count splits as individual transactions, as it was a while back.
Have this as an option to switch back and forth, depending on the needs.
This could also be pre-set on the search screen.

See checkin 3473c680da1300f73546ca831b5cebe25faa6f68.

**Comment by MisterY** [comment]
Wait until the new (Split/) Transaction schema. This will then be perfectly simple.
