### ISSUE TITLE
Remember which account groups are collapsed on dashboard

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#59]
I would find it quite handy if the account groups could be collapsed and have them stay this way when the dashboard is displayed the next time.
Perhaps a setting to enable/disable this behaviour.

Example: Collapse 'Credit Card' accounts. The next time the app opens, this account group should show collapsed.

**Comment by AlessandroLazzari** [comment]
Can we implement it in version 2.0?
@MisterY: can you try to implement it yourself this issue?

**Comment by MisterY** [comment]
I can try. This is a neat feature. I'll ask if I have any questions.

**Comment by MisterY** [comment]
Done!

**Comment by MisterY** [comment]
I may be wrong but I have a feeling that the startup is a bit faster?
