### ISSUE TITLE
Feature: Show currency menu on tap

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#60]
In the Currencies list, single tap should bring up the context menu as it is currently not doing anything.

**Comment by AlessandroLazzari** [comment]
Always in list categories, in list payees, in list accounts, etc ... with
long press opens the contextual menus.
I think it could do as has been done for recurring transactions

2015-03-19 17:17 GMT+01:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
Yes, that's what I meant. This is just a reminder for me to do it. :)

**Comment by MisterY** [comment]
Done.
