### ISSUE TITLE
Difference in account balances 

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#606]
Known as "Different account balances in desktop and mobile app" or "difference in running and total account balance"

This issue is used to keep track of incidents where the account balances differ between the desktop and mobile applications. The discrepancy is also identified between the account balance header and the running balance for 'all time' period. The running balance matches the desktop balance. SQLite query provides wrong numbers if it includes the corrupt records.

The recorded cases so far have occurred for two reasons:
1. Database file corruption.
   https://www.sqlite.org/howtocorrupt.html
2. Corrupt records
   The corrupt records sometimes exist and the number they provide in queries is different than when reading the record through a cursor. So far all the identified records have occurred in July 2014. The source of the affected records is still unknown.
   The only way currently to identify a transaction is by deleting the records in a copy of the database until the balances match and the corrupt transaction is found by being the last deleted one.

(Potentially) Related issues: #494, #480, #605

**Comment by MisterY** [comment]
Comparing the A.V. database file in different tools:

- SQLite Browser: incorrect balances
- Genymotion Android 4.1.1 emulator: correct balances
- Samsung Galaxy S3, 5.1.1

**Comment by MisterY** [comment]
JP.C. database case

A transfer record was identified as the amount matched the discrepancy.
The record was deleted and an identical new one created. This resolved the issue.

**Comment by MisterY** [comment]
Related issues: #494, #480

**Comment by MisterY** [comment]
**Klausen**, the amounts differed.
Using DbBrowser, the data was exported from transactions table to CSV, table was deleted, and then imported from CSV. This solved the problem, confirming that there was a physical damage to the database file.

**Comment by ggraziotti** [comment]
To solve, on Windows I have to open db, cancellare transaction table, export to CVS and import on mmex ?
Can you explain me the specs to do ?

**Comment by ggraziotti** [comment]
I noticed that, if on account I show historical data no problem with balance. If I show the others intervals, actual and reconciled balance are different. This information is useful to solve ?
