### ISSUE TITLE
Feature: Persistence of app settings

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#61]
A number of app customizations are not stored in the MMEX database. 

It would be useful to have an ability to export app settings that are not stored in the database.
Or persist them in the database using an Android-specific prefix.
This would allow backup of app customizations (look/feel/behaviour).

Perhaps the better of the two options would be to store the settings in the database. But users could have different settings on different devices so I'm not 100% sure what should go into db and what not.
Exporting a json file into Dropbox would also be a good option.

Now that I updated the title it would be good to clarify that this also implies ability to import and restore app settings from the settings file.

**Comment by AlessandroLazzari** [comment]
In version 2.0 has added the BackupAgent. The backup data MoneyManagerEx for Android is managed automatically by Android.

https://github.com/moneymanagerex/android-money-manager-ex/commit/d4ec0e54202ee32dbeb12f46b7e7f3881705bc65

If you want, you can invoke the backup and restore by adb command.

**Comment by MisterY** [comment]
Great! I need to see how that works.

**Comment by AlessandroLazzari** [comment]
There are many online tutorials. Remember to turn on backup settings on the
device if no does not work.
I I've lost a lot of time for this little problem.
