### ISSUE TITLE
Calendar view for expenses

### ISSUE THREAD

**Issue by tomaszszmigiel** [moneymanagerex/android-money-manager-ex#611]
Overall calendar view of all expenses for all accounts would be nice. It would show the big picture of coming expenses

**Comment by MisterY** [comment]
Hi, could you explain a bit more on how this should look and behave? There is a similar request (#379) but I'm not sure how it should work. Been thinking about this but I see no good way to implement this on a small screen. The current view of transactions is already very close to this with the period selector and the list of transactions. What is missing?

**Comment by tomaszszmigiel** [comment]
Hi Alen, I'm impressed from your quick response. I was thinking about
something similar to Money manager - simple vision 3rd screen in Play
Store. This is calendar view showing the amount in each day. This would be
great visualisation of coming expenses if someone click on specific day it
would show on the bottom details etc. Right now in the application there is
a list of coming expenses and I think it would be nice to visualise it on
real calendar... something similar to Google calendar on android

Thanks
Tomasz
11 lis 2015 09:27 "Alen Siljak" <notifications@github.com> napisał(a):

**Comment by MisterY** [comment]
Yes, I was thinking about something similar, only with individual transactions. That is an interesting suggestion, to include the upcoming recurring transactions as well.

<img src="https://lh3.googleusercontent.com/TuEjSwdC13JHXWfsTq3wkW4Ad-3QkGSDzKQul78M1oFD4fJF2TBxMz5tpb__hDXrqkg=h900" width="200px" />

**Comment by tomaszszmigiel** [comment]
That would be great to see recurring transactions at calendar view. Would
be very helpful.

Another great thing I think easy to be done is a line chart showing your
net value over the months. Just easy snapshot of sum of all accounts on
let's say 1st of each month... right now I'm doing this separately in excel
file... this would show if your overall money is going up or down over the
months.

Overally great application I love main screen which shows all accounts in
one place including credit cards and overall summary of money that I have
everywhere including coming expenses.

One suggestion that can help a lot of people is that maybe there is a
possibility that the month can start from some specific day of the month?
Like I'm getting my salary every 10th of the month so I'm calculating
everything from 10th to 10th this way recurring expenses would work great
if everything will count from 10th to 10th or any other specified day of
the month... I saw comments that people are missing planning for coming
months so see for example how much money they will have in next 6 months...
with calendar option it would be so great tool for planning bigger expenses
like car service insurance etc...

I think you should consider selling pro version as well

Thanks
Tomasz
11 lis 2015 10:44 "Alen Siljak" <notifications@github.com> napisał(a):
