### ISSUE TITLE
Financial Planning

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#615]
This is a bigger story that should summarize all the planning options. The first step is to collect the required features under one story/epic.
- projected balances (#442)
- month view of transactions, including recurring transactions (#611)

It is important to note that recurring transactions can be included only for the upcoming occurrence. Should a longer-term projection be needed, a virtual projection of the recurring transaction should first be generated and then included into the balance calculation. Example: Looking at a 3-month projection with a recurring transaction that happens monthly should result in the three transactions occurring one per month. Take into consideration the recurring transaction end date, number of occurrences, etc.

**Comment by luisdev** [comment]
Should this be closed? Is it abandoned, or just in a backlog?
