### ISSUE TITLE
In Home screen, the Summary always have the value in dollars, regardless the Base Currency selected

### ISSUE THREAD

**Issue by jfmdev** [moneymanagerex/android-money-manager-ex#621]
In the **Home** screen of the app, it shows the balance of each account and a summary with the sum of all accounts balance.

If the _Base Currency_ is USD, it works fine:

| Banck accounts | $ 485.31 |
| ------------- | ------------- |
| Bank account 1  | CFA 100 000  |
| Bank account 2  | CFA 200 000  |
| Summary  | $ 485.31 |

However, if the _Base Currency_ is any other currency, it changes the currency sign but the amount remains the same (as if were dollars):

| Banck accounts | CFA 485.31 |
| ------------- | ------------- |
| Bank account 1  | CFA 100 000  |
| Bank account 2  | CFA 200 000  |
| Summary  | CFA 485.31 |

Or

| Banck accounts | € 485.31 |
| ------------- | ------------- |
| Bank account 1  | CFA 100 000  |
| Bank account 2  | CFA 200 000  |
| Summary  | € 485.31 |

----

> I'm using MoneyManagerEx _Version 2015.11.15 (build 749)_, and Android 4.4.2

**Comment by MisterY** [comment]
It seems that this is quite an old bug. Actually, the question is whether this is really a bug.
Once the base currency is changed, the rates for other currencies are not updated automatically. So, it is practically irrelevant what is the base currency at the time of transaction display.
What matters more are the stored rates of the currencies. This rate is stored at the time of rate update, in relation to the current base rate. If the base rate is switched at a later time, it is necessary to also update the exchange rates.
Perhaps adding a notification message on base currency update would solve this issue?

**Comment by jfmdev** [comment]
I updated the **currency rates** after changing the **base currency** but the error remains (probably because currency rates are always being downloaded as is the base currency is USD): the summary displayed is still the amount in dollars.

**Comment by MisterY** [comment]
Just to clarify the assumption - the base currency is not USD. The initial base currency is taken from the device's locale when the database is created.

**Comment by MisterY** [comment]
I've just tried the scenario with the last published version and it works as I've described. 
- change base currency in the settings
- go back to the Home screen, note that the amount is the same but the currency has changed
- go to Entities -> Currencies
- update currencies by clicking the rotating arrows icon, note that the values actually change
- go back to the Home screen and note that the amount has changed

**Comment by jfmdev** [comment]
I have follow the procedure, the total amount do not changes.

> On a side note, if in the section `Entities -> Currencies`, you select the option **Show only used**, then the  **rotating arrows** icon do not works (it ask confirmation for update the currencies, but after that it do not does nothing: do not shows the loading dialog and do not updates the rates)

However, I think I have found out why you can't reproduce the error: **It seems that this error only happens when all you accounts are in the same currency.**

In my case, if I have two accounts in West African CFA, they display the wrong total amount.
However, if I change the currency of one of the accounts to Dollar or Euro, the total amount displays the correct value.

**Comment by MisterY** [comment]
I'm sorry, the behaviour on my devices and virtual machines is different to what you are experiencing. Could you post some screenshots? Also, please check the Logcat (from About screen) to see if there are any error messages when trying to update currencies.
All my visible accounts are in the same currency and the amounts change after updating the exchange rates. Also, "Show only used" option is selected by default in the Currencies screen.
There might be several issues at hand here.
- Can you try updating individual currency exchange rates to confirm whether the total for a group of accounts is correct, first?
- Could you look at logcat after trying to update rates for the used currencies?
I'm sorry that I can't troubleshoot more since everything seems to work just fine on all the emulators and physical devices I have available.
Thanks!

**Comment by jfmdev** [comment]
Regarding updating the currency exchange with "Show only used", it seems that it's work fine. Apparently, if the rates are updated very quickly, the the loading dialog is not show, given the impression that nothing happened.

And regarding the amount problem, after adding, editing and removing accounts and transactions (in order to find the exact conditions in which the problem occurs), the problem disappeared, and I can not longer reproduce it...

So, I'm going to assume that I had bad luck and I got into some bizarre bug that normally never happens.

Thanks for the help!

**Comment by MisterY** [comment]
:) 
No worries. I'm glad that it worked out although it remains a mystery. I ended up adding the notification on change of the base currency, in any case. That is a useful reminder for something that is perhaps not that obvious and intuitive. (I also completely forgot how that was supposed to work)
Thank you for the interesting exercise of going through code that was not touched in a while.
