### ISSUE TITLE
Category not displayed for Transfers

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#623]
When a transfer is created with a category, and is being opened in the app, the Category is not displayed.
Also, when creating a new transfer transaction in the mobile app, the Category is not saved.

**Comment by ingprod** [comment]
I get the same issue when transfers (account to account) are entred on Android app (2016.01.26 - compil 764), when back to desktop (1.4.2 )  version category is missing.

**Comment by MisterY** [comment]
Would you be able to confirm what happens in the database after each case? Perhaps using http://sqlitebrowser.org/. This would identify where the modification needs to be made. Thanks!

**Comment by MisterY** [comment]
Linked #675

**Comment by MisterY** [comment]
fixed and published
