### ISSUE TITLE
Budget screen is very slow

### ISSUE THREAD

**Issue by gauravjl** [moneymanagerex/android-money-manager-ex#628]
On a fairly large database, if thr budget screen is opened it opens very slowly. Additionally, scrollijg on this screen is extremely slow.

**Comment by gauravjl** [comment]
Additional infomation:
I have budget set for 4 years. Clicking on amy one of the years opens the budget categories but it takes around 6-7 seconds. Scrolling when budget catehories are visible is very slow. Every scroll takes place after 3-4 seconds.

**Comment by MisterY** [comment]
Could you post your device technical details (model, available RAM), please? 
Budget for 4 years has to calculate the actual usage for each budget period for each of the category. Unfortunately, that's a lot of work and can noticeably impact the performance on an older device.

**Comment by gauravjl** [comment]
Device name: YU YUREKA
Device model: AO5510
RAM: 2 GB

Additionally, when I enter a year it still lags. I expect that on clicking on a year, it has to calculate only for tgat particular year and not all 4 years.

**Comment by MisterY** [comment]
Thanks. That seems like a device that should handle this amount of data well. 
Are you getting the same performance if you show All Data in the transactions list for an account with lots of transactions?
This will require some inspection of the code.

**Comment by gauravjl** [comment]
Sorry for the late reply. I have lost my device. Still I will try to answer your query from my memory.

If I showed all transactions from an account, the list loads slowly. But the lag on the budgets screen is very high. In the budgets screen if I scroll up or down, then the scrolling is painfully slow (sometimes it takes some seconds to scroll one page) and the characters are jumbled up rendering all data unreadable. Its as if one line is overlapped by other.

**Comment by MisterY** [comment]
I am sory about your loss of device. The issue is on the backlog and it will require some time to test this scenario and try to optimize the display.

**Comment by MisterY** [comment]
Using RecyclerView should improve things -> #800
