### ISSUE TITLE
Android Notes Field have less capacity than Desktop version

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#635]
>The android App cut the Notes created in the desktop version due that Andorid App NOTES FIELD have less lenght allowed than desktop Version.
Please Harmonize

**Comment by MisterY** [comment]
Can't reproduce with a screen full of text.

**Comment by Geoplace** [comment]
Ok I was experimenting this limitation when I input 1200 aprox.(including spaces) characters in 37 lines.

**Comment by MisterY** [comment]
Right. The limits for SQLite are pretty high and Android now does not impose any limits as far as I know.
This limit was set explicitly in the edit forms for transactions.
Will disappear with the next release.
