### ISSUE TITLE
Discrepancy for category request between android and desktop

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#640]
For TRANSFER Transactions Type Android App doesn't force the Category Assignment that is mandatory for the desktop software on the same operation.

So when I open that transaction created in android the desktop force me to assign the forgotten category.

Please make category required on TRANSFER by Android App as is on DEPOSIT and WITHDRAWAL

**Comment by MisterY** [comment]
I'm sorry, the category makes absolutely no sense on transfers. The reports in the mobile version do not even take it into account.
Having Category field on Transfer transactions accommodates users who want to use this feature but it absolutely can not be forced upon everyone.
I am not aware of any other personal finance software that categorizes transfer transactions. These are neither income nor expense, so why put categories on them? The need to have a Category assigned to the transfer of funds between own accounts indicates some wrong setup.

**Comment by MisterY** [comment]
Here is a related discussion for the opposite functionality - preventing Categories on Transfers: https://github.com/moneymanagerex/moneymanagerex/issues/548
