### ISSUE TITLE
'Apply all' on recurring transactions

### ISSUE THREAD

**Issue by colourqueen** [moneymanagerex/android-money-manager-ex#644]
Hi - this is a feature request.

I'd like to have an option where I can apply recurring transactions ahead of time so that I can budget better. There was the option in Quicken to tag and apply upcoming transactions in one go, using the date they were due. Moneymeanager almost has it in that you can right click and enter next occurrence but it takes today's date. Also you have to do it individually rather than tag a group. 

Thanks

**Comment by colourqueen** [comment]
I am still interested in this - something where I can apply all upcoming transactions for a given number of days - like current month either manually or automatically at the beginning of each month.

**Comment by wolfsolver** [comment]
Now recurring transaction can have recurring mode that can be Manual, Prompt or Auto. Auto transaction will be posted at due date. 

Execution in advanced is not the best practice. On desktop version you can have report for forecast cashflow (month, year, or more) that simulate all schedule transactions

**Comment by colourqueen** [comment]
I would still like this but the request doesn't seem to be gaining much traction

**Comment by wolfsolver** [comment]
Can this new feature #1855 "Forecast Cash Flow Report" match your requirement? if yes we can close this as duplicate since the better solution is not to alter recurring transaction behaviurs

**Comment by wolfsolver** [comment]
@colourqueen cashflow report is in development.... I think in next release could be ready

**Comment by colourqueen** [comment]
Thanks @wolfsolver  that will be really useful
