### ISSUE TITLE
Mobile and desktop files is in sync, but missing today's transaction in desktop view.

### ISSUE THREAD

**Issue by rushy00** [moneymanagerex/android-money-manager-ex#645]
I am maintaining the sync of the files through dropbox.
Even the files are in sync(correct timestamp), somehow desktop view is always missing today's transaction that has been enter in mobile.

**Comment by MisterY** [comment]
Do you mean a Home view in mobile app or the desktop application?

**Comment by rushy00** [comment]
Hi, somehow it is working now.
Let me monitor for tomorrow.

**Comment by MisterY** [comment]
Sure. Please reopen if the issue reappears.

**Comment by PRIHLOP** [comment]
This issue also true if two android phones synchronize over Dropbox.

**Comment by MisterY** [comment]
I have two Android devices and a PC and have not experienced any issues with synchronization for a very long time. Let's try to identify the real cause because the sync seems to be working pretty well.

**Comment by PRIHLOP** [comment]
When two users work simultaneously with one base is a problem appears.
1) The first application downloads data dropboks
2) At the same time, but for a couple of seconds after the application of the other phone also loads data into dropboks, but the application can not recognize that the data has already been changed by another client as the likely front-load dropboks application does not check whether a file has changed in dropboks.
Thus, the database recorded only the changes made by the client who has worked with base later.

**Comment by PRIHLOP** [comment]
Please describe the algorithm that is synchronized with dropboks in the current version of the application.

**Comment by MisterY** [comment]
The logic should be somewhere [here](https://github.com/moneymanagerex/android-money-manager-ex/blob/master/app/src/main/java/com/money/manager/ex/dropbox/DropboxHelper.java#L114). The source code is open, please have a look at your convenience.

**Comment by PRIHLOP** [comment]
Maybe it sync not correctli if add transaction from widget "New Transaction". I use it usually.

**Comment by MisterY** [comment]
Hi, this is expected behaviour. Widget will simply add a transaction to the existing database, not involving additional functionality. Opening the app will run the sync check on startup.
Just pay attention to where the changes are being made. This is a synchronization scenario issue. You can check the Dropbox web interface to confirm the time of the latest database file version sent to Dropbox storage.

**Comment by PRIHLOP** [comment]
Maybe it makes sense to make synchronization more flexible, check the file changes before uploading a local version in dropbox?
After adding a transaction through the widget is loaded base to dropbox, only need to add a function to checking changes before sending the base.
There is an opportunity to do so?

**Comment by MisterY** [comment]
Could you please describe detailed steps for a scenario that would reproduce this issue?

**Comment by PRIHLOP** [comment]
Ok.
1) Create base and setup synchronization of base on two devices though dropbox.
2) On device 1 add transaction from widget "New Transaction", base uploaded to dropbox.
3) On device 2 add transaction from widget "New Transaction", base uploaded to dropbox.
4) Open app on device 2, and see transaction only added from 2 device.

**Comment by MisterY** [comment]
Thank you. I can reproduce it. It is possible that this behaviour was caused by the recent changes that close the app after the transaction has been entered. Will try the same scenario with this behaviour disabled.

**Comment by PRIHLOP** [comment]
Thank for you respond :+1 :)

**Comment by MisterY** [comment]
Numerous improvements in synchronization algorithm were introduced in the current release (2016.08.21.896). Please try either in the Beta channel or the Stable. If still not available at the Play Store, please try from the Releases link here on GitHub.

**Comment by MisterY** [comment]
The delayed upload should really be a delayed synchronisation. If changes are pushed from two devices, the last one will overwrite the first if there is no synchronisation.
