### ISSUE TITLE
Transfer: amount calculation - now impossible to set custom from-/to-amounts

### ISSUE THREAD

**Issue by weasel3** [moneymanagerex/android-money-manager-ex#659]
Latest Version 2016.01.15 build 756 is not properly usable anymore because of the "improvement" #630: Switching to transfer calculates the destination amount automatically. 

It is possible to alter the initial calculated amount to the correct one, but then the "from" - amount will be recalculated! So either i got a slightly wrong "destination" - amount or a wrong "from" - amount! 

There is no exchangerate, that is always the right one! The provided exchangerate should only be used as a suggestion in a transaction, not as immutable! 

When a transaction gets crafted, instead of relying on the fixed exchangerate, the exchangerate should be calculated on the basis of my inputs (from/to amount) and maybe shown on the screen.

Surely, the to-amount could be precalculated on the basis of the mmex-internally known rate but a change by the user must explicitly be allowed without automatically altering the from-amount! 

Example: You get another exchange rate for currency conversion at an airport as at an online broker. Both rates diverge from the provided (downloaded)  rate in mmex.

**Comment by MisterY** [comment]
Resolved by #642 and released in 2016.01.17.758.
Is this still occuring?
