### ISSUE TITLE
Transaction Status filter not functional in other languages 

### ISSUE THREAD

**Issue by crashcoq** [moneymanagerex/android-money-manager-ex#660]
Hello

The new filter button on the latest version can't work fine when I select stable.
Other filter is ok

**Comment by MisterY** [comment]
Which filter?
Which version exactly?
What is "stable"?

**Comment by crashcoq** [comment]
The version is 2016-01-19  719
The filter is ok on English language (filter on none) but don't work on French language.
The filter is add on the account

**Comment by MisterY** [comment]
Thanks for the info. The current version is [2016.01.19.761](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2016.01.19.761). I guess that version number is wrong.
Would you mind attaching a screenshot? I'm still not sure which filter do you have in mind. Thanks!

**Comment by crashcoq** [comment]
It's the 761version.
I can't doing a screenshot on my phone.
I selected a account, the filter is on the first line  after account name and calendar

**Comment by MisterY** [comment]
OK, I see. It must be that the search for the text value is localized. Thank you!

**Comment by crashcoq** [comment]
It's possible to change the word French "stable" to "aucun" on the translation?

**Comment by MisterY** [comment]
Sure. It can be done through our [project at Crowdin](https://crowdin.net/project/android-money-manager-ex). Any contribution is welcome!
