### ISSUE TITLE
Split transaction amount repeated on all lines

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#661]
Version 2016.01.19.761
The split transaction just allowed the same amount on all lines.

When you enter o change the amount it is changed on all lines of the split transaction.

**Comment by MisterY** [comment]
This is a consequence of an event system that sends the event to all input controls.
A contributor to this is that Android does not assign unique ids to controls. So, each number control that contains amount has the same id and therefore receives the entered number.
Unique ids/tags need to be maintained when there are multiple receivers on the form. Fortunately, this is only the case in Splits, for now.

**Comment by Geoplace** [comment]
Well, I was working fine in past versions. I wait for the next release to test it.

**Comment by MisterY** [comment]
That's called [regression](https://en.wikipedia.org/wiki/Software_regression).
