### ISSUE TITLE
Add synchronization with Google Drive

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#680]
Related to #265 

Links:
- [Introducing the Google Drive Android API ](http://googledevelopers.blogspot.co.at/2014/01/introducing-google-drive-android-api.html)
- [Drive API for Android ](https://developers.google.com/drive/android/)

**Comment by Quaturn** [comment]
I want to join in this request.
Please add the support for Google Drive.

**Comment by MisterY** [comment]
Done as a part of #845. This was probably one of the most-requested features.
