### ISSUE TITLE
Support for owncloud synchronization

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#685]
Update: #1278 should resolve this issue.

------------------------------------------------

For a workaround, please see #265 

specifically 
- [OwnCloud app](https://doc.owncloud.org/android/android_app.html)

**Comment by diggy128** [comment]
+1

**Comment by roboticsound** [comment]
I would like to add my +1 to this. Big fan of moneymangerex but I don't trust my financial data being stored outside of my own server.

**Comment by salem83** [comment]
+1

**Comment by kreso75** [comment]
+1

**Comment by MisterY** [comment]
Can anyone confirm if OwnCloud app works well for this purpose? Thanks!

https://doc.owncloud.org/android/android_app.html

**Comment by MyFAQuser** [comment]
I have been using owncloud for quite some time. However, I always access the database on mobile devices through the owncloud app. The MMX windows desktop application works fine when choosing "last used database".

**Comment by MyFAQuser** [comment]
Oh, also since owncloud has added the sync button, it is always best to hit that when "backing out" of the database.

**Comment by snhv** [comment]
OwnCloud/NextCloud is a bit too specific. **Please add support for WebDAV in general.** 
Thanks.

**Comment by MisterY** [comment]
@snhv, we've used CloudRail library for the support of multiple cloud storage services. It would be the best to submit a request to them to support WebDAV. We do not have resources to work on non-core functionality, like synchronization, at the moment. Maintaining multiple providers is a nightmare. If you wish to contribute this functionality, please submit a pull request.

**Comment by alerque** [comment]
Nextcloud (and I believe now ownCloud) both support Android's document provider API. So do dozens of other storage provider and sync apps. Using a buggy third party library that requires a separate account just to configure on top of your existing cloud account is not just inconvenient but actively obnoxious. Supporting Android's standard storage API would alleviate this sore spot not just for owrCloud/Nextcloud but many other potential options as well.

**Comment by MisterY** [comment]
@alerque, my thoughts exactly. That's a good pointer, though. The app could store whatever URL the storage API provides.

**Comment by MisterY** [comment]
#1278 should resolve this, as well as all other cloud provider issues.
