### ISSUE TITLE
Support for historical currency exchange rates

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#686]
The support is coming in desktop application v1.3.
Users are requesting the support for historical exchange rate. However, still no user story to describe the desired behaviour.

**Comment by vomikan** [comment]
It's already in trunk. I will use YQL for get a data.
http://forum.moneymanagerex.org/viewtopic.php?f=7&t=6325

https://github.com/moneymanagerex/moneymanagerex/issues/647

**Comment by MisterY** [comment]
Thanks, @vomikan. What do you use this functionality for? Is there a user story that describes the need to have the historical rates?
I have a request from users but I do not understand why would someone need historical rates. The transfer records have both amounts stored and the current exchange rate is used to show the current amounts recalculated into the base rate. I fail to see the need for using historical rates.

**Comment by vomikan** [comment]
Personally, I don't understand why would someone need historical rates as well.
And Agree that the transfer records have both amounts stored and the current exchange rate is used to show the current amounts calculated into the base rate. But it may be useful for reports.

Some users reports this issue. For example (russian):
https://www.facebook.com/MoneyManagerEx/messages/?threadid=100002243480918&mercurythreadid=user%3A100002243480918&timestamp=1455522892684

https://sourceforge.net/p/moneymanagerex/bugs/752/
etc

**Comment by MisterY** [comment]
I see, thanks. 
The solution for issues like the reports including transfers, however, is to handle Transfers differently than deposits/withdrawals, depending if they are incoming or outgoing transfers. That's what I see in the Android code, at least. So, having a historical rate would not really solve anything. 
OK, good to know. I will wait for a concrete example where this is absolutely necessary.
From what I see at the moment, most of the related issues can be solved by simply adjusting the expectations or minor modifications in the SQL code in reports.

**Comment by MisterY** [comment]
without a user story there is nothing to implement
