### ISSUE TITLE
Error downloading prices for  SAN.MC and ACX.MC 

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#687]
SAN.MC and ACX.MC 

Improve error reporting to the user. Specific case is receiving N/A for the actual price.

**Comment by vomikan** [comment]
To get financial data for SAN.MC mmex download data form the site:

http://download.finance.yahoo.com/d/quotes.csv?s=SAN.MC&f=sl1&e=.csv

Result:
~~~~~

SAN.MC,N/A

------------------------------

Using [YQL] (https://developer.yahoo.com/yql/)

~~~~~
SELECT * FROM yahoo.finance.historicaldata WHERE symbol = "SAN.MC" AND
startDate = "2016-01-01" AND endDate = "2016-02-14"
~~~~~

~~~~~
   "quote": [     {      "Symbol": "SAN.MC",      "Date": "2016-02-12",
 "Open": "3.37",      "High": "3.483",      "Low": "3.333",      "Close":
"3.482",      "Volume": "112999400",      "Adj_Close": "3.482"     },

2016-02-15 13:31 GMT+03:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
That's really weird, considering that they still show the price(s) at the main site (http://finance.yahoo.com/q?s=san.mc&ql=1).
One item here could be to provide better error messages when the record is retrieved but its value is N/A.

**Comment by vomikan** [comment]
It's self evident that we need more YQL API for get current prices for stock and currencies and get historical data (if current price not available).
This issue is refers to  https://github.com/moneymanagerex/moneymanagerex/issues/647

**Comment by MisterY** [comment]
I believe I've already switched all data retrieval to YQL (i.e. [stock prices](https://github.com/moneymanagerex/android-money-manager-ex/blob/84530fadf44aa6ec7e74dd64ca6a81a1a80907c6/src/main/java/com/money/manager/ex/investment/YqlSecurityPriceUpdaterRetrofit.java)). 
The error is reproducible so I just need some time to debug and see what the actual reason is. Perhaps YQL returns the same value?

**Comment by MisterY** [comment]
Yes, this is the problem

    SELECT * FROM yahoo.finance.quotes WHERE symbol = "SAN.MC"

**Comment by vomikan** [comment]
YQL = Yahoo
Should be the same.

**Comment by MisterY** [comment]
As usual, **should** is the key word here. :)

**Comment by vomikan** [comment]
Seems the price available only for the yesterday but not for now.

**Comment by MisterY** [comment]
Not entirely. The .quotes store has the last known price together with the date and time of the last price. Even when new data is not available, there is always the last known price. This happens on holidays, for example, for other stock exchanges and symbols.
However, for these securities all the fields have null values. Not just price. And this goes both for .quote and .quotes stores. They contain records but it only contains a value for EPS (earnings per share). All other values are missing.
Definitiely something wrong with the YQL stores for these quotes.

**Comment by vomikan** [comment]
I mean Yahoo does not provided price for now
~~~~~
select * from yahoo.finance.quote where symbol in ("SAN.MC")
~~~~~
[YQL](https://developer.yahoo.com/yql/console/?q=select%20%2a%20from%20yahoo.finance.quote%20where%20symbol%20in%20%28%22YHOO%22%2C%22AAPL%22%2C%22GOOG%22%2C%22MSFT%22%29&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys#h=select+*+from+yahoo.finance.quote+where+symbol+in+(%22SAN.MC%22))
"LastTradePriceOnly": null,

But provide history
~~~~~
SELECT * FROM yahoo.finance.historicaldata WHERE symbol = "SAN.MC" AND startDate = "2016-02-16" AND endDate = 'today'
~~~~~
~~~~~
    "Symbol": "SAN.MC",
    "Date": "2016-02-16",
    "Open": "3.64",
    "High": "3.669",
    "Low": "3.514",
    "Close": "3.603",
    "Volume": "181468000",
    "Adj_Close": "3.603"
~~~~~

**Comment by MisterY** [comment]
Yes, we meant the same thing. I'm not sure what the best way is to handle this or if we should have a workaround for the Yahoo issue.

**Comment by vomikan** [comment]
Personally, I feel that workaround will good solution. If current price is null - just provide last available price from history. 
What's worse, as soon as mmex become to store stock and currency historical prices.. The current price tomorrow become wrong. As soon as mmex has been started, all missing and incorrect prices should be updated.
