### ISSUE TITLE
Account list gets messed up

### ISSUE THREAD

**Issue by sampalmer** [moneymanagerex/android-money-manager-ex#7]
Sometimes if I go to the main account list and then scroll up or down, the accounts start overlapping:
![screenshot_2014-08-20-19-28-24](https://cloud.githubusercontent.com/assets/4566802/3978956/ba31a620-284e-11e4-85d6-814428363efa.png)

**Comment by MisterY** [comment]
I'm adding "Won't Fix" as I have not experienced this behaviour in the upcoming v2 version. 
If you are a tester, would you mind trying out the current test version?
Otherwise, please report back once v2.0 final is published so we can resolve the issue.
