### ISSUE TITLE
Allow switching rates/prices provider

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#709]
As http://datatables.org/ is down, no data is available through YQL. This means that currency rates and stock prices are not retrievable.
The previous implementation, using .csv results may be reactivated, with an option to select which provider to use.

**Comment by jwestonmoss** [comment]
MisterY Datatables is back up, but yahoo's data is all jacked - stuff is a day old, and it's up and down.  Any idea what's going on?  I've been sending emails and tweeting at Yahoo folks but its silent as the grave

**Comment by MisterY** [comment]
I've used Datatables (via YQL) today to update prices and it seemed ok. Checked it just now and the prices seem to be the same as the ones shown in Yahoo Finance Portfolios.
Both updates, through Yahoo or YQL, seem OK. Thanks for the heads up. I'll pay more attention in the next couple of days. At least I've enabled the previous option so it is possible to update exchange rates and quotes via both providers.
