### ISSUE TITLE
App crashes when tapping on recurring transactions notification

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#71]
Not sure if this feature is complete but in emulator the app will crash when the notification about the due transactions is tapped.
Latest version of code.

**Comment by AlessandroLazzari** [comment]
To be tested

2015-03-27 9:29 GMT+01:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
Same happening on the phone.
