### ISSUE TITLE
Payee doesn't preselect its usual category

### ISSUE THREAD

**Issue by technodrome** [moneymanagerex/android-money-manager-ex#712]
When adding transactions through the desktop MMEX app, when selecting a payee, a category is automatically selected with which this payee is usually paired. For some reason, this stopped working some time ago in AMMEX. Is it possible to reintroduce this feature? It save time and clicks. I cannot think of any reason why this was dropped. Thanks.

**Comment by MisterY** [comment]
For me this still works as usual. I use this feature daily when paying for lunch, for example.

**Comment by technodrome** [comment]
Is there any way I can debug this? Whichever payee I pick, the category stays the same. Using 2016_03_02_r775.apk, cyanogenmod 13.0.-20160228-NIGHLTY-bacon on OnePlus One.

**Comment by MisterY** [comment]
Logcat should have some debug information on pretty much any query to the database. Whenever a Payee is selected, it should also load it's related (last) Category.

**Comment by MisterY** [comment]
It would look something like this:
```
03-03 15:53:58.747 1488-1488/com.money.manager.ex D/MmexContentProvider: Query URI: content://com.money.manager.ex.provider/payee
03-03 15:53:58.747 1488-1488/com.money.manager.ex D/MmexContentProvider: Uri Match Result: 9
03-03 15:53:58.747 1488-1488/com.money.manager.ex D/MmexContentProvider: SELECT [PAYEEID AS _id, PAYEEID, PAYEENAME, CATEGID, SUBCATEGID] FROM payee_v1 WHERE PAYEEID=?; ARGS=[4]
03-03 15:53:58.767 1488-1493/com.money.manager.ex D/dalvikvm: GC_CONCURRENT freed 498K, 5% free 13641K/14279K, paused 17ms+1ms, total 21ms
03-03 15:53:58.777 1488-1488/com.money.manager.ex D/MmexContentProvider: Rows returned: 1
03-03 15:53:58.777 1488-1488/com.money.manager.ex D/MmexContentProvider: Query URI: content://com.money.manager.ex.provider/categorysubcategory
03-03 15:53:58.777 1488-1488/com.money.manager.ex D/MmexContentProvider: Uri Match Result: 17
                                                                          WHERE CATEGID=19 AND SUBCATEGID=-1
03-03 15:53:58.787 1488-1488/com.money.manager.ex D/MmexContentProvider: Rows returned: 1
```

**Comment by technodrome** [comment]
I filtered for com.money so I hope the whole output is there. Here is the logcat. Couldn't find such query there, though.

[2016-03-03-15-55-50.txt](https://github.com/moneymanagerex/android-money-manager-ex/files/157015/2016-03-03-15-55-50.txt)

**Comment by MisterY** [comment]
You can check inside the database, perhaps using http://sqlitebrowser.org/, table Payee. See which Category/Subcategory is linked to the desired Payee.

**Comment by technodrome** [comment]
The data is there all right, it's just not changing the fields in-app. Nothing in the logcat output?

![categ](https://cloud.githubusercontent.com/assets/3662386/13498726/71197bd0-e15b-11e5-93d8-ff98ecaceb83.jpg)

**Comment by MisterY** [comment]
Unfortunately, no. This is probably because the Debug is not set in the version that is built for publishing. You can try a debug build: https://www.dropbox.com/s/0g0pr09hce6fm75/android-money-manager-ex-debug-2016_03_02_r775.apk?dl=0

**Comment by technodrome** [comment]
Uninstalled my version and got this behavior in yours:
1. First time I open "add new transaction" screen and select a Payee
2. Any subsequent Payee change (without leaving the transaction screen TS) will not cause category change, only the first one.
3. Upon closing and entering the TS the same happens again.

Also, logcat mentions: `W-Duplicate finish request for ActivityRecord{944428a u0 com.money.manager.ex/.PayeeActivity t8721 f}`

Logcat appended.
[2016-03-03-16-35-01.txt](https://github.com/moneymanagerex/android-money-manager-ex/files/157074/2016-03-03-16-35-01.txt)

**Comment by MisterY** [comment]
The answer lies [here](https://github.com/moneymanagerex/android-money-manager-ex/blob/master/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java#L789). Yes, the category will be only set if it is empty at the time of selecting the Payee. The same principle goes for adjusting the exchange rates. Any previously-entered data will not be overwritten by the app.

At 3., what exactly do you mean by "the same happens again"?

**Comment by technodrome** [comment]
Well, it kind of beats the purpose. If you change your payee your category should update as well. Just from the user experience standpoint. I think this is how you as an user would expect it to behave (but it might be only me).

3. - I meant the process repeats exactly in the same fashion if you enter a new Add new transaction activity after discarding the previous one.

**Comment by MisterY** [comment]
I see your point. However, as a user I'd tend to disagree. I would not want the app to change my other values when I change the Payee. To handle setting the last Category it is relatively easy to select a Payee first. 
Honestly, I do not see the point in changing both Payee **and** Category on an existing record (or an already filled one) as something like that would not normally happen in real life. What I mean is - if I paid $2 for Dining Out at Ice Cream Shop, it's not going to suddenly change to Magazines at Supermarket or something like that. Changing one field might indicate a mistake or adjustment but two might be too much.
In any case, this is a user preference and could be added to Settings for the app to behave in a desired way. It would be relatively easy to add and contributions are always welcome. :)

**Comment by technodrome** [comment]
Well, your build seems to work, so I hope it will keep working after I upgrade. Maybe uninstallation helped because in the debug-less version this didn't work even the first time I opened the activity. Now it does so I can consider it fixed from my standpoint.

The rest is a matter of personal preference. If I select Payee: airberlin and Category gets preselected to "Travel" but I realize I made a mistake, it makes sense (to me) that if I pick another payee in the same screen it should update category, too.

If my Java skills were good enough, I'd do that, trust me :)
But thanks for really quick replies and excellent support.

**Comment by MisterY** [comment]
:)
You're welcome. If you wish, please add a new item with the request for the preference. I closed this one because it infers there is a bug.
There is not much difference in the build I sent, except that it is a Debug build. The last Release was done just yesterday so the code is the same. But, if the behaviour differs then I'm puzzled.
In any case, should you notice *any* discrepancy, please report and I'll do my best to correct them.
Thank you for the support and participation!
