### ISSUE TITLE
Check wording of dialog boxes

### ISSUE THREAD

**Issue by philip2100** [moneymanagerex/android-money-manager-ex#726]
e.g. canceling the editing of a transaction by backing out, or by using the Cancel button, results in Cancel dialog box confirming discarding the transaction, instead of confirming discarding changes to the transaction

**Comment by MisterY** [comment]
Hi, which language does this refer to?

**Comment by philip2100** [comment]
English (Default)

**Comment by MisterY** [comment]
Thank you! Corrected. The change will be included in the next Beta release.
Please do report if you see more of these. The initial messages were written by non-native English speakers so it is possible that some sentences are still ambiguous.
