### ISSUE TITLE
Add Tags on transactions

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#735]
> In anMoney exists the category, the user classification, the project. In Financisto there are the category, the project, the user «attribute».
> Personally, I use this «user classification» so that many transactions I have a sense of «FOR exactly which month». For example, the payee=<name of the constant client>, category="salary", "period"="March 2016" (I have a few dozen customers with monthly payment, and I need to keep track of who owes me, for what period and how many). Or payee="my son" category="spending money", "period"="March 2016". To do this, now I made the additional classification called "period"; first level: 2013, 2014, ...; second level: January, February, ...
> But for this to work need another two-level classification (in addition to the category). And the ability to group transaction reports this breakdown.﻿

**Comment by luisdev** [comment]
@guanlisheng, are there plans to implement this new Tags feature in MMX Android?

**Comment by guanlisheng** [comment]
no concrete plan as we are still lack of android contributor.

**Comment by luisdev** [comment]
This is still relevant, so I am commenting to remove the "stale" label.

**Comment by luisdev** [comment]
MMX Desktop already supports Tags. So, if a transaction is created on Desktop and then that Desktop database is synced to an Android device and opened in Ammex, does Ammex just "ignore" the Tags field in the transaction?

**Comment by guanlisheng** [comment]
android mmex will ignore these fields.  you can help to confirm here.

**Comment by wolfsolver** [comment]
I think that this can be splitter into two main step:

- [ ] Enable "read mode" to see tag into transactions
- [ ] Add ability to manage tag and edit in mobile

**Comment by luisdev** [comment]
> * Add ability to manage tag and edit in mobile

This would be a great feature in AMMEX.

**Comment by guanlisheng** [comment]
thanks, both for the practical discussion.  

i think we can be on this after restoring Asset and fixing some UEX issues, thought?

**Comment by luisdev** [comment]
Hey github-actions, this is not stale! :-)

**Comment by wolfsolver** [comment]
Initial development in https://github.com/moneymanagerex/android-money-manager-ex/commit/27949a9f1220995f019cad1d0b9fb0816f9c5604

**Comment by luisdev** [comment]
> @alensiljak @luisdev tag management is almost completed. If you would like to try preview you can download [here](https://1drv.ms/u/s!AtPBR0zMvFhpjvErxY2wRA_whChgDA?e=szgTAe) feedback are welcome

THANK YOU. I have installed the preview (2024.142.19 (1053)) and I'm trying to see how it works. When I create a new transaction and tap the new "Tags for transaction" field, nothing happens.

How do I add new tags? And edit them? Will there be a Tags option on the AMMEX menu under Entities?

**Comment by wolfsolver** [comment]
Also added Search Tag in Search windows, so now is possible to find transaction with specific tag

**Comment by luisdev** [comment]
> The full tag functionality is still not under gplay. You need to manually download from my link Ii previous message.

Thanks. I've installed this version and now I see the new functionality. I've created a few tags using the new _\Entities\Tag/Label_ function and I can now attach these tags to my transactions. Very nice! Thank you.

**Comment by luisdev** [comment]
The _Split Transaction_ screen still only shows the three standard fields - _Category_, _Amount_ and _Notes_, like this:  

<kbd>

![AMMEx - Split Trans](https://github.com/user-attachments/assets/0dfb0d49-1ed1-4010-a22f-b8ac5118a808)

</kbd>
 


Please add the new _Tags_ field to this screen so that each item in a split transaction can be assigned one or more different tags.

**Comment by wolfsolver** [comment]
> > The full tag functionality is still not under gplay. You need to manually download from my link Ii previous message.
> 
> Thanks. I've installed this version and now I see the new functionality. I've created a few tags using the new _\Entities\Tag/Label_ function and I can now attach these tags to my transactions. Very nice! I will test further... **Thank you for adding this feature.**

Great. Thank for your support.

New release on gplay has this feature.
