### ISSUE TITLE
Text display problem in overflow menu in Material Light Theme

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#75]
The text of the overflow menu is dark over a grey/dark background (with a white line in front of it) wich makes it difficult to read. It is visible in the "Where the money goes" report section when changing the period with the calendar icon (for exemple). A white (or light green) background with a dark text would be easier to read. This problem is only visible with the "Material Light Theme", not with the "Material Dark Theme".
![screenshot_2015-03-27-21-38-26](https://cloud.githubusercontent.com/assets/2464288/6876679/44783344-d4ca-11e4-8fa9-2a596ed1f338.png)

**Comment by prannou** [comment]
I noticed that deleting these two lines in the theme.xml file remove the white line and change the text color to white : 
<item name="android:icon">@color/md_icons</item>
<item name="android:textColor">@color/md_primary_text</item>

But I couln't find how to change the background color.

**Comment by AlessandroLazzari** [comment]
Fixed

**Comment by prannou** [comment]
Thanks, unfortunately for me it fixes the problem for "Material Light Theme", but now the problem is with "Material Dark Theme" (white text over white background). The white line before the text is only present with Material Light Theme.

**Comment by AlessandroLazzari** [comment]
ok, I will check the problem that you reported!
Thank you
Il 28/mar/2015 11:54 "prannou" <notifications@github.com> ha scritto:

**Comment by AlessandroLazzari** [comment]
However, the reports are the last part of the application that's left for
me to review. Very probably there will be even more the view sub-menu of
the years and/or category. Wait to see the new updates

**Comment by AlessandroLazzari** [comment]
Fixed with Material Dark Theme
