### ISSUE TITLE
Error loading default payee

### ISSUE THREAD

**Issue by fraheor** [moneymanagerex/android-money-manager-ex#753]
When creating a new transaction an error message indicating the app was unable to load the default payee is shown.

**Comment by MisterY** [comment]
Can you report the version in which this is happening and/or try updating to the today's release?

**Comment by fraheor** [comment]
I'm using the latest version in GooglePlay (2016.03.31 - Built 802)

**Comment by MisterY** [comment]
Some users reported that this was corrected in later Betas, which you can try (https://play.google.com/store/apps/details?id=com.money.manager.ex.beta). I have just published the latest code to the Stable app version as only corrections were added to the Beta channel since the release.
