### ISSUE TITLE
Error message on application starts

### ISSUE THREAD

**Issue by fraheor** [moneymanagerex/android-money-manager-ex#755]
When starting the app I'm getting an exception: "Error retrieving the last modified date in checkIfFileIsSync"

![screenshot_2016-04-01-11-00-02](https://cloud.githubusercontent.com/assets/14211002/14209260/9c2a885a-f7f9-11e5-847c-0e8f43f71952.jpg)

**Comment by MisterY** [comment]
Could you try to re-link the Dropbox account? This is most probably due to the change in the Dropbox app name/location. The new app folder is "MoneyManagerEx Android".

**Comment by fraheor** [comment]
You were right. I re-linked the Dropbox account and the error no longer appears. Thanks
