### ISSUE TITLE
Beta and Stable: Unable to duplicate transaction

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#756]
In the Beta App: Compilation 806
(A minutes ago with the last stable update the same happen with this version)

1.- Search for a transaction by category. (Without this step the error stays)
2.- Select a transaction
3.- Use the duplicate function.
4.- When tap "Ok" the Error: "Inserting transaction failed"

**Comment by MisterY** [comment]
Corrected. New Beta to be published right now.

**Comment by Geoplace** [comment]
Working! Thank you.
