### ISSUE TITLE
Unable to remove split register on existing transaction

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#763]
1.-Open existing transaction
2.-Remove one or more of the splited registers.
3.-Click ok (seems that was removed)
4.-Click Ok to close the transaction. (seems that every thing was ok)
5.-Open the transaction againg.
6.-Open the split registers and ther is again what was removed previously.

**Comment by Geoplace** [comment]
At the 812 Compilation.
There is still the same behavior.

**Comment by MisterY** [comment]
The solution is market to be included in the upcoming version, not build 812.
Please try the 813 (2016.04.03-beta) version from [here](https://play.google.com/store/apps/details?id=com.money.manager.ex.beta).

**Comment by Geoplace** [comment]
Yes, The 813 works fine. Regards

**Comment by MisterY** [comment]
Thank you for the confirmation!
