### ISSUE TITLE
Accounts widget shows 0 balance for investment account

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#768]
>Hi, I have created a new account investment, and I created a record of buying title from desktop version. Now on the android app if I open the apps the sum of allnmy account include the title account and it's ok, but if I use the widget on home the title account has 0 as total, so the sum of all account is uncorrect.

**Comment by lcarullo** [comment]
In my opinion on widget must be the sum of all accounts, including stock. If not, is useless that voice on widget :D﻿

**Comment by lcarullo** [comment]
any news about fixing this?

**Comment by MisterY** [comment]
Account Bills Widget

**Comment by lcarullo** [comment]
The second option, cash balance for investment I think is always 0, and I don't think this is the right choise. I think is better rewrite the query for accounts, and in this case I can help if you guide me :D

**Comment by MisterY** [comment]
The first option is also not completely correct because it ignores the cash balance. It is **not** always zero for investment accounts. Quite the contrary, it could include a significant cash balance.
For now, I'll add the stock balances only.
