### ISSUE TITLE
Transaction Sum is not updated

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#775]
Hi

I notice a very strange behavor regarding the sum in split transaction.

Here is attached a database with two split transactions that has identical quantities.

One has the wrong total and the other the right one.

I don't know why the wrong sum is not updated when I open and close the transaction.
I was created when there was probling deleting split registers.

So I need to create a new register because I can't find how to make the sum total be right.

[datos-mony sum.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/202993/datos-mony.sum.zip)

**Comment by MisterY** [comment]
Interesting puzzle of the day. However, the solution is fairly simple. If you look closely at the "wrong" transaction. The Split Category record with the amount of 120 has the opposite sign. In the "right" transaction, this split is Withdrawal, which matches the sign of the main transaction but in the "wrong" transaction the split is Deposit. Hence the difference in the sum, which is absolutely correct.

**Comment by Geoplace** [comment]
Your rigth, i'm not aware of.
Would be useful to color type of split transacción as it Is done on regular
transactions.

Thank you

**Comment by MisterY** [comment]
Yes, that's an excellent suggestion. It should also save some space in the UI. I'll create a new item on the backlog.
