### ISSUE TITLE
Feature: Indicate split in the recurring transactions list

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#78]
In the list of recurring transactions, when there is a split transaction, there is no category displayed.
This is a bit misleading. Since showing multiple categories would be inconvenient, showing some kind of "split indicator" would be preferable. Even just showing word "Split" would be better.

**Comment by AlessandroLazzari** [comment]
in theory it should display no records for the split. I find it correct in your observation. can be fixed immediately after the release of version 2.0.0 maybe with the 2.0.1?i
n your opinion, the fixing of this issue is fast?

**Comment by MisterY** [comment]
Might be. I ran into it while working on split recurring transactions. I'll have a look at it now.

**Comment by MisterY** [comment]
You are right. The category is not shown when there is a split in the Recurring Transactions list.
We can add a "split" indicator at some point in the near future.

**Comment by MisterY** [comment]
The desktop version displays the split details in the standard transaction but blank in the recurring transaction split. Once the decision is made on how to proceed there, we can do the same in the mobile version.
Also, we can use '--split--' or something else in the meantime.
