### ISSUE TITLE
Add ability to remove one of split transactions

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#79]
When editing Recurring Transaction, there is no way to remove one category from the split list.
Possibly the same issue on a standard split transaction (checking account activity).

**Comment by AlessandroLazzari** [comment]
![2015-03-29 22_22_25-clipboard](https://cloud.githubusercontent.com/assets/7428710/6887571/ed5b23d2-d663-11e4-9189-43c7a519e23e.png)

It doesn't work?
It may be that it is not visible in the Dark theme?
I have tried it on a normal transaction, and to me it seems to work.

**Comment by MisterY** [comment]
Aha! Never noticed that. Yes, you are right. The X button is not visible in the dark theme.
