### ISSUE TITLE
Add Transaction widget ignores security passcode on Cancel

### ISSUE THREAD

**Issue by JustFogMaxi** [moneymanagerex/android-money-manager-ex#8]
When the user has been in the normal app (and entered the passcode), pressing 'Cancel' in the Add Transaction widget brings the user back to the main app without asking the pass code.

The widgets Cancel button should always exit the app and not go back to a previous activity.

**Comment by AlessandroLazzari** [comment]
Fix and close issue with commits: https://github.com/AlessandroLazzari/android-money-manager-ex/commit/8fdce8b633a706ac5cd7dd43d3e8c9d5f56cb4a8
