### ISSUE TITLE
Budget graphical display

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#804]
> the budget section, as conceived now has little or no use, not absolutely helps to quickly see the relationship between forecast and actual cash flow (both in the mobile version, both in the desktop version, which is even worse). I enclose two screenshots taken from 2 apps that instead help to see much more of the budget (the graphics of the first screenshot is better), although even in this case without the total budget, drawn from various partial budget (perhaps to be included at the top )

<img src="https://cloud.githubusercontent.com/assets/462445/14701696/e117c1c8-07a6-11e6-908c-54bcc032d6b6.png" width="200px" /> <img src="https://cloud.githubusercontent.com/assets/462445/14701698/e311bd76-07a6-11e6-8e4b-16ec2ef2f7dc.png" width="200px" />
<img src="http://cdn.appcrawlr.com/imageService/aHR0cDovL2EzLm16c3RhdGljLmNvbS91cy9yMzAvUHVycGxlMS92NC9mNS9lMC9iNS9mNWUwYjVjNC02MjdmLWQ4NjgtMzExZi05YmQyZDg1NmJkODcvc2NyZWVuNTY4eDU2OC5qcGVn?w=340&h=280" width="200px" />

**Comment by Backfighter** [comment]
I actually really like how moneypro does it: 
![](https://lh3.googleusercontent.com/umpnv7W_RaO7onYlkNJkuCC_repBOjy_iHhvMn0pzwWBytU-ipm4nu6tCr7EZGcTix30=h900)

![](https://lh3.googleusercontent.com/umpnv7W_RaO7onYlkNJkuCC_repBOjy_iHhvMn0pzwWBytU-ipm4nu6tCr7EZGcTix30=h900)
