### ISSUE TITLE
Enable drill-down for Categories report

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#805]
> The Android version gives you the chance to enter Categories and Subcategories.
> The report for categories only shows Subcategories.
> 
> My request:       make the category report as an overall view for categories with the option to go in detail ( subcategories ) when needed.

**Comment by diggy128** [comment]
+1

**Comment by wolfsolver** [comment]
Already done, now reports 

sample with third level category
<img width="270" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/f9a1cfbf-5745-4027-9c53-fcee7094858e">

close
