### ISSUE TITLE
split transacción mix type sum

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#813]
The substraction is not made.

1. Click split transaction
2. Complete the fist one (minus) amount 5
3. Add a second transaction type deposit (plus) amount 3
4. Click OK 
5. Total show -8 instead of -2

**Comment by MisterY** [comment]
Yes, sorry, the correction for this behaviour was not included in the build that was done on a different build machine. Releasing the right Beta version now.
