### ISSUE TITLE
Headers in search results shift after stop/start cycle

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#820]
1. Run search (for all records)
2. Open one of the listed transactions 
3. Cancel

After returning to the list, the transaction list headers will be shifted or gone.

Rewrite the search results list using the recycler view.

**Comment by MisterY** [comment]
This issue may be solved by moving to RecyclerView, and incorporated with the task of migrating lists to recycler-view, which puts additional priority to the task of list migration.
