### ISSUE TITLE
sync unreconciled transactions issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/android-money-manager-ex#822]
Original issue is: https://sourceforge.net/p/moneymanagerex/bugs/870/

The problem is: if in android-mmex has been created unreconciled transaction then it not saved in global (shared by Dropbox) DB. If later the DB will updated in other mmex instance this transactions will be lost.

**Comment by MisterY** [comment]
That sounds very strange. What would be the steps to reproduce?

**Comment by MisterY** [comment]
The assumption is wrong as the synchronization is not affected by the transaction status. 
The only possibility for a sync conflict to happen is if the database is not synchronized after adding a new transaction through a widget. In this case the app is shutdown in order not to return to the main screen but this seems to also not trigger the synchronization.
Will keep tracking at the original issue.

If the transaction is created in a different way, we can reopen this item.
