### ISSUE TITLE
Add transaction sum for the selected period

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#824]
> It is a good idea to make in Acccount near labels Balance of account and Proved Balance, one more label: Sum of transactions.
> So we can choose period in filter, for example one week or month, and see the sum of transaction for this period for the Account.

Similar to the number of transactions, add the sum for the selected period to the new info dialog in the account transactions view.

**Comment by Snaptags** [comment]
This would be extremely valuable when reconciling transactions in the android app, because you could then compare the sum with the before and after figures of your bank statement get a quick verification that at least the sum of all transactions match.

**Comment by Snaptags** [comment]
Workaround for anyone missing the functionality:

trigger a **search** via the menu button, select the account and the status for the transactions you're reconciling (I'm using "follow-up" until a dedicated "cleared" status exists).

In the search result you'll get a sum at the bottom of the transaction list!
