### ISSUE TITLE
F-Droid repository

### ISSUE THREAD

**Issue by J316** [moneymanagerex/android-money-manager-ex#827]
Make an F-Droid repository to download the app

**Comment by MisterY** [comment]
I never figured out how to do this. Any volunteers?

**Comment by J316** [comment]
https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo

**Comment by MisterY** [comment]
Does this require hosting? I'd prefer to push the release directly to F-Droid, if possible.
Seems like a lot of work for no obvious benefit. The Releases page lists all the published app versions available for download. I'm using that to update an app before it is available in Google Play.
I do agree that it would be nice to show in the F-Droid list of apps, though. MMEX has been suggested in the forums for quite a long time.

**Comment by J316** [comment]
[Not necessarily.](https://f-droid.org/contribute/)

**Comment by MisterY** [comment]
I read the instructions at both of those links at least a dozen times during the past couple of years and I still have no idea what needs to be done in order to get MMEX listed in F-Droid.

**Comment by J316** [comment]
[Submit it](https://f-droid.org/forums/forum/submission-queue/)

**Comment by MisterY** [comment]
I'm afraid the submission has been there since June 3, 2013. Not a very efficient process.
https://f-droid.org/forums/topic/money-manager-ex/

**Comment by J316** [comment]
That's weird. It seems that everything is OK formally, have you tried contacting them to ask for explanations?

**Comment by MisterY** [comment]
No, not really. I don't really know who to contact. They've listed the procedure and it's been followed. To me it looks like a dead end. If you have the time to follow up, please do.
This is pretty low on the priority list. Do request a reopen if there is some progress on the issue. 
The issue is closed because the submission has been made a while back and I don't know or want to host a self-hosted repository.

**Comment by J316** [comment]
You could try to ask [here.](https://f-droid.org/forums/forum/submissions-held/)
But I see there are other valuable apps awaiting, maybe that's why they suggest [to do a Merge Request on GitLab.](https://f-droid.org/forums/topic/read-this-before-posting/)

**Comment by MisterY** [comment]
What I'm saying is that you can also contribute by doing all those things you listed.

**Comment by yaomtc** [comment]
> The app requires non-free build-dependencies, like crashlytics. There is an option to disable it internally, but its still required at build-time. Might be fixable. Also there are some untrusted maven repos which I havent had the time to investigate.

https://gitlab.com/fdroid/rfp/issues/17

So it needs the non-free build dependencies to not be required at build-time. I don't know what he means by untrusted Maven respositories. Is that some kind of certificate issue?

I've recently been trying to depend less on Google, and transition more to open source alternatives. Thanks for providing an APK! Though, it would be great if we could get updates through F-Droid!

**Comment by MisterY** [comment]
There is now an F-Droid repository. See #1111

**Comment by yaomtc** [comment]
Oh neat, thanks.

**Comment by IzzySoft** [comment]
Now that the trackers are gone: shall we make a try for the official repo? Yell if you want to and need help with that.

**Comment by MisterY** [comment]
I think it won't work as long as CloudRail is being used. Need to remove it first. Then it could be published as a sync add-on.

**Comment by IzzySoft** [comment]
Any progress on that? Or an ETA?

**Comment by MisterY** [comment]
The idea is to implement #1278 first, to allow using document providers (i.e. various cloud services) directly through the provider apps. Then the built-in sync can be removed completely.
Unfortunately, no progress and no ETA from my side. Currently have next to 0 time available. 
Hopefully there's some contribution from others otherwise it would probably mean that there's no much need putting the very limited time and efforts into this.

**Comment by IzzySoft** [comment]
Thanks for the details! Please keep me in the loop, as this is what currently blocks [this issue at F-Droid](https://gitlab.com/fdroid/rfp/issues/17).

**Comment by MisterY** [comment]
Thanks a lot, @IzzySoft! We're finally live: https://f-droid.org/app/com.money.manager.ex

**Comment by IzzySoft** [comment]
Great, congrats @MisterY! I'll then remove it from my repo to avoid confusion (different signature). Can revive it anytime should the need arise.
