### ISSUE TITLE
Dropbox permission dir vs dropbox dir

### ISSUE THREAD

**Issue by cke12** [moneymanagerex/android-money-manager-ex#832]
Hi,

I reset my android device and tried setting up Dropbox sync on a fresh install of MMEx.

When I link to Dropbox, it tellse me that it asks for permission to read and write in Dropbox/Apps/MoneyManagerEx Android. I allow it, of course.

When I select a file in that directory, it tells me "The folder in Dropbox/Apps/Money Manager Ex Mobile is empty..."

There's obviously some discrpancy between the permission, and the source directory, and even the existing directory. My existing mmb file lives in Dropbox/Apps/MoneyManagerEx Mobile.

Please look into it. I had to backup, copy and paste app data from an existing working setup on another device to get it to work properly.

![2016-05-20 01 35 22](https://cloud.githubusercontent.com/assets/19475975/15403380/559ed766-1dbe-11e6-9050-41b5e93babc8.png)
![screenshot_2016-05-20-01-33-57](https://cloud.githubusercontent.com/assets/19475975/15403387/5bc63418-1dbe-11e6-99ae-199f8dcbbd02.png)

**Comment by MisterY** [comment]
Most probably the text in the 2nd screenshot wasn't updated in the migration process. The new Dropbox folder is the one specified in the 1st screenshot and the database is expected to be there (MoneyManagerEx Android).
I have not had any issues with several physical devices and emulators. Any issues would be resolved by unlinking/linking Dropbox account.

**Comment by cke12** [comment]
Thanks for the prompt reply! I just copied my existing file from
Dropbox/Apps/MoneyManagerEx Mobile to a new folder
Dropbox/Apps/MoneyManagerEx Android. It works nice now.

**Comment by MisterY** [comment]
Thanks for the confirmation! I will keep this issue open as a reminder to adjust the misleading message.
