### ISSUE TITLE
Add the ability to connect to the MySQL server

### ISSUE THREAD

**Issue by PRIHLOP** [moneymanagerex/android-money-manager-ex#838]
Please add the ability to connect and store database at the MySQL server.

**Comment by MisterY** [comment]
Hi, 

I'm sorry but this looks like the wrong place for such a request. Perhaps the desktop version *could be* adjusted to use MySQL but for Android version such functionality certainly would not make much sense. :)
You can create a new request in the desktop repository.
Cheers
