### ISSUE TITLE
Removed Split transaction register reappear

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#844]
Build 845 (beta)

Steps to reproduce.
1.- Create new split transaction.
2.- Enter two register in the split dialog.
3.-Clic Ok, and then Ok again to store the transaction.
4.- Open again that transaction.
5.- Open the split dialog and swipe right to remove the second split register.
6.- Clic Ok, and then Ok again to store the transaction.
7.- Open again that transaction.
8.- Open the split dialog (BUG) and there is the deleted register and the one that was left had disappered.
9.- The transaction was distorted.

NOTE: When you have three or more registers the Deleted is just restored and not interchanged like in the two register split transaction bug described.

**Comment by MisterY** [comment]
Thank you for identifying this. It seems I forgot to add the removed transaction to the collection of deleted transactions. Fixed!
