### ISSUE TITLE
Upgrade Dropbox API to v2

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#845]
Dropbox is deprecating API v1 soon and migration to API v2 is required.

This migration could also be done by introducing CloudRail library. This would, then, allow easy introduction of additional sync services.

- [Dropbox with CloudRail, authentication](http://stackoverflow.com/questions/34856101/dropbox-authentication-with-cloudrail)
- Dropbox API V1 Deprecated – How to Upgrade With Cloudrail [link](http://www.hnwatcher.com/r/2788001/Dropbox-API-v2-Tutorial-Benefits-of-version-2-and-how-to-integrate-it-Android)

To-do:
- ~~persist authentication for cloud services~~
- ~~enable other sync services~~
- ~~add preference for synchronization period~~
- ~~enable periodic sync (service)~~
- ~~allow resetting sync settings (delete preferences)~~
- try file browser demo from CloudRail
- ~~implement the setting for sync on Wi-Fi only~~
- ~~manual download~~
- ~~manual upload~~
- ~~manual sync~~

**Comment by felixkm** [comment]
Great to see that you are integrating with CloudRail. Let us know if you have any question or if we can help with anything.

**Comment by MisterY** [comment]
Thanks a lot for the feedback, Felix! CloudRail is a great concept.
I do critically need the last-update-date/time in the CloudMetaData for a remote file in order to perform synchronization. I've posted the suggestion/question [here](https://docs.cloudrail.com/discuss/577a26689748b80e00ef3e6d).

**Comment by felixkm** [comment]
We've actually already implemented that for the next version which is to be released this Wednesday. If you shoot me a quick mail to felix@cloudrail.com, I'll send you an early version of it. We're just missing some tests for other new features, so I don't want to make it public already.
