### ISSUE TITLE
Allow translation of the "Help" page in the dropbox settings

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#85]
Actually, the page explaining how dropbox sync works is not translated (in Settings > Dropbox > Help) and can't be translated (it is not in the strings.xml files). I think it would be good to make it translatable, for people who don't speak english.

**Comment by AlessandroLazzari** [comment]
I agree with @prannou.
You could also go hours to the HTML page of answers about with a short tutorial.
@MisterY you that you have become an expert what do you think?

**Comment by MisterY** [comment]
Surely agree. I'll have a look at how it is implemented. A link to the wiki would also be great. 
Does the app require network access? Maybe just sending an intent for the Web page would be enough.

**Comment by MisterY** [comment]
@AlessandroLazzari, is it possible to add the full page for translation at Crowdin?

**Comment by AlessandroLazzari** [comment]
Yes!

2015-04-02 15:06 GMT+02:00 Alen Siljak <notifications@github.com>:

**Comment by AlessandroLazzari** [comment]
I just put the page Drobpox on crowdin in the help folder. If the English of the html page is poor, change the source in the raw folder.

**Comment by MisterY** [comment]
OK, great!
