### ISSUE TITLE
Add exception handling for all sync actions

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#862]
Since every sync-related action might require log-in or experience different network-related exceptions, enclose any action in try/catch blocks.

**Comment by ravisharma117** [comment]
Thank you,
I have factory reset my phone and Now I am able to link to dropbox.

Also, Thank you for such a nice app.

**Comment by ravisharma117** [comment]
I am a .net developer. 
Can I contribute in your windows application?

**Comment by MisterY** [comment]
Hi, Ravi! Thank you for the offer. Any contributions are always welcome. You can contribute either to the Android app, or the desktop app (C++), or with the new prototype of both desktop and mobile (in .Net). Just have a  look at the available repositories under the MMEX organization.
This is all done in our spare time so you can contribute at your convenience and pace. Do get in touch should you require any hints. Also, have a look at the web sites moneymanagerex.org and android.moneymanager.org for more info and links.
Cheers!

**Comment by MisterY** [comment]
There is also an update for CloudRail library that includes several fixes, like network detection
