### ISSUE TITLE
Add search button to the main app toolbar

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#87]
Next to the application name, would it be useful to put the search icon/button?

![image4144](https://cloud.githubusercontent.com/assets/462445/6886391/6360c352-d63c-11e4-83af-cc2bf0d595b0.png)

This will be a convenient entry to further operations, as in #210.

**Comment by AlessandroLazzari** [comment]
If you feel it more useful, we can assess to put the search function on the main toolbar.
Already in the current version 1.4 research has been moved to the drawer.
Nothing forbids us to move it to the Actionbar.

**Comment by MisterY** [comment]
I'd love to implement this but it will be a while before I understand how to work with toolbars correctly. :D

**Comment by MisterY** [comment]
Useful resources:
https://developer.android.com/training/basics/actionbar/adding-buttons.html

**Comment by AlessandroLazzari** [comment]
It is not enough to implement a menu to the Home fragment, with the menu
entry that you want to insert?

**Comment by MisterY** [comment]
I added it to the MainActivity and now it appears twice on lists like Accounts. I'll try your suggestion now.

**Comment by MisterY** [comment]
Thanks for the suggestion. Now it is much better.

**Comment by MisterY** [comment]
For reference, this was implemented in #226.
