### ISSUE TITLE
Swipe to Refresh in the transactions list breaks list scrolling

### ISSUE THREAD

**Issue by vladimir-poleh** [moneymanagerex/android-money-manager-ex#873]
Changes from the 5362cc0 added Swipe to Refresh layout to the transactions list and this change breaks list scrolling up. Now when you are trying to scroll up you will activate Swipe to Refresh instead scroll.

Also refresh is not working and I'm not sure that it is required at all as it is single user app with local database.

**Comment by MisterY** [comment]
Yes, this slipped into the release while not being complete.
However, I can confirm that the refresh *does* work, for example in the Watchlist.

**Comment by MisterY** [comment]
Can you tell me where the scrolling is broken? The transactions list works as usual.

**Comment by MisterY** [comment]
Thanks for reporting. Removed until a solution is found for quickly updating currencies exchange rates and investment prices.

**Comment by vladimir-poleh** [comment]
Steps to reproduce:
1. Open transactions list.
2. Scroll down. Scroll is working as expected.
3. Try scroll up. Refresh spinner is drawn instead scrolling.

**Comment by MisterY** [comment]
Hi, I see that the update progress is displayed but the list still scrolls up. Is your list not scrolling?

**Comment by vladimir-poleh** [comment]
Yes, after update process starting scroll is working. But it is very confusing behavior - you need to start update to fix scrolling.

**Comment by MisterY** [comment]
Agree. Will publish the fix in a new release today.
