### ISSUE TITLE
Apply transaction-related preferences without the app restart 

### ISSUE THREAD

**Issue by vladimir-poleh** [moneymanagerex/android-money-manager-ex#881]
Some Look & Feel settings like "Show Transactions", "Show the balance for each transaction" require app restart, but AppRestartRequiredEvent is not handled by MainActivity as event handlers are unsubscribed at the moment of the event posting.

Flow is following:
1. MainActivity.onStart() // subscribe
...
2. MainActivity.onStop() // unsubscribe
3. Open settings view
4. Post AppRestartRequiredEvent
5. Close settings view
6. MainActivity.onStart() // subscribe

As a workaround it is possible to reload settings used by fragment in the fragment's onResume() method.

**Comment by MisterY** [comment]
Correct. I broke the previous mechanism that stored a flag in the application object.
There are several options that require an app restart. The change of language or theme are the most obvious ones. I will need to look into this. Perhaps in relation to #878.

**Comment by vladimir-poleh** [comment]
I'm using workaround with onResume() in the #882. I think that most of the UI related settings does not require app reload, maybe only language and theme should be initialized at the application start. All other can be properly reloaded without restart.

**Comment by MisterY** [comment]
If you look at the base fragment activity class, the theme is actually applied on creation of every activity independently. This current way has been implemented a long ago. I guess there should be a different way to do that as I've seen apps that switch themes on the fly. Just did not have time to investigate that into more detail.

**Comment by MisterY** [comment]
Yes, that's a good solution for the preferences that affect the transactions list.

**Comment by MisterY** [comment]
Options like these might be handy in the options dialog from #682
