### ISSUE TITLE
Make currency code a free-text field in the currency editor

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#892]
Currently, only the values from the currencies.xml list are allowed. However, this has to be kept up to date and is limiting the users. This should be a free-text field.

**Comment by vladimir-poleh** [comment]
This change will break "Import All Currencies" functionality, but it seems that it's already broken as `currencies_code` and `currencies_symbol` arrays are out of sync. Also I can't find how to call this functionality in the last version.

**Comment by MisterY** [comment]
There's an option in the menu that does this. It reads all the supported currencies in the system and creates records in the current database. 
This should also be redone but would introduce the need for maintenance. We already need to update the initial list of currencies all the time when names and symbols change, which happens all the time.
I would probably vote for an option to allow users to create whatever they want and not limit any options. Import of all currencies should just jump over any existing symbol. A user-friendly option would prompt to overwrite, showing the differences but I'm not sure if anyone is using this functionality.
