### ISSUE TITLE
Cancel button in the Split Category view working incorrectly

### ISSUE THREAD

**Issue by vladimir-poleh** [moneymanagerex/android-money-manager-ex#893]
After clicking Cancel in the Split Category view newly created Category item is not deleted. Transaction have mark that it have multiple categories.
After double clicking of the Split button new category will be added. Each iteration of clicking Split button and canceling in the Split Category view will create new category.

**Comment by MisterY** [comment]
This is more convoluted than I thought. Requires some decent refactoring to make thing simpler. No changes should be performed until the user confirms by pressing OK in the Split form. I fell into the rabbit hole already.
