### ISSUE TITLE
Notification message wrong on upload

### ISSUE THREAD

**Issue by ShosGithub** [moneymanagerex/android-money-manager-ex#895]
‘Database has been successful updated’ appears on the top of the screen while sync still in process.
Also, this information appears even when errors occur, sync fails.

**Comment by MisterY** [comment]
Is this still valid after the updates this week?

**Comment by ShosGithub** [comment]
hi,there

the update error did not happen again,
but the notification still works wrong.
please refer to the attach files

2016年7月26日 02:32，"Alen Siljak" <notifications@github.com>写道：

Is this still valid after the updates this week?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/moneymanagerex/android-money-manager-ex/issues/895#issuecomment-235042410>,
or mute the thread

**Comment by MisterY** [comment]
Hi, it seems that attachments do not go through when replying from email. Could you please attach the screenshots on GitHub?

**Comment by ShosGithub** [comment]
Sure, i will put them later~

2016年7月26日 23:40，"Alen Siljak" <notifications@github.com>写道：

**Comment by ShosGithub** [comment]
![618654906](https://cloud.githubusercontent.com/assets/15169800/17211762/de67f796-54fd-11e6-82d0-0aa9f6b58277.jpg)
![648936275](https://cloud.githubusercontent.com/assets/15169800/17211763/debb91da-54fd-11e6-8bee-ef2f5dc327cc.jpg)

**Comment by ShosGithub** [comment]
when it comes to chinese
![1614963660](https://cloud.githubusercontent.com/assets/15169800/17211889/795b9ff0-54fe-11e6-8ef0-03e60500a2f6.jpg)
![2095773857](https://cloud.githubusercontent.com/assets/15169800/17211888/79577970-54fe-11e6-8c16-c9e7d7b24839.jpg)

**Comment by MisterY** [comment]
Right. I think I've noticed the same a couple of times. The message must have been updated recently. Will correct. Thanks for the details!

**Comment by ShosGithub** [comment]
You are the most welcome.
Thank you for your work.
REALLY a great app!

2016年7月28日 20:18，"Alen Siljak" <notifications@github.com>写道：
