### ISSUE TITLE
Trouble with search

### ISSUE THREAD

**Issue by Urvdmih** [moneymanagerex/android-money-manager-ex#9]
The case-sensitive search everywhere, for example, if there is a counterparty "Dentist" and I enter a word with a lowercase letter "dentist" then it does not find.Necessary to introduce either a large or a part within a word is not first.

**Comment by MisterY** [comment]
Hi! Thanks for the suggestion. Let me know if I understood correctly, please. Also, note that I am referring to the current test version (v2.0).

There is currently a search that can be reached from the main drawer menu. This allows searching, actually filtering, through all the transactions in the database. 

Another feature that I see you referring to is Payee search/filter. This is the one on the Payee selection page. This search *is* case sensitive and will find the combination of text inside the Payee's name irrespective of the letter casing.
This concept of search/filter is also found on Categories, Currencies, and other entities inside the program so the same principles apply. To affect the behaviour of this search, there is a setting in General Settings, called "Searching by text contents and not by text beginning with", that handles how the search works. As the name implies, it allows either for searching the name from the beginning, or from anywhere within the text.

The behaviour of the current test version is significantly different so I would ask you to confirm whether it is to your liking now.

**Comment by MisterY** [comment]
After #206, I can confirm that the search is looking for parts of the word and ignores casing.
The fix will be released in v2.0 and is currently available in Beta channel.
