### ISSUE TITLE
Force close with back button when selecting a payee if there are no payee

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#90]
If there is no payee in the database and the user use the back or up button from the page of selection of payee (for a transaction) the application force close (error while trying to do cursor.getInt(...) in the setResult method). I'll add a pull request with the correction.

**Comment by AlessandroLazzari** [comment]
is a bug that I've entered with the last commit, most likely. I have not
tested this case. Sorry for the problem.

**Comment by AlessandroLazzari** [comment]
Fixed
