### ISSUE TITLE
Unable to select local database

### ISSUE THREAD

**Issue by Athanagorn** [moneymanagerex/android-money-manager-ex#906]
Hello again!

While testing the currency bug, I created some new databases for test, and I had the following problem:

I can't select a local database file to open if it doesn't appears in the "recent file" list. When I tap "Other" and goes to the MoneyManagerEx folder, I can see all the files but the are grayed and I can't select them.
![screenshot_20160725-103837](https://cloud.githubusercontent.com/assets/20598877/17095408/952c5b22-5254-11e6-9354-424479d91f51.png)

**Comment by MisterY** [comment]
This is due to the system file picker. There is a story to implement a custom file selector because not all Android versions have a default file selector.

**Comment by MisterY** [comment]
#846

**Comment by MisterY** [comment]
As a workaround, you can install Total Commander and use that as the file selector.

**Comment by MisterY** [comment]
You should also be able to open a database from a file manager directly, like other file types.

**Comment by MisterY** [comment]
Will be implemented with #846
