### ISSUE TITLE
Income/expense chart is broken in last version.

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/android-money-manager-ex#910]
In the version downloaded from the Google store today, the income/expense chart is broken. X axis seems to plot amounts and y axis months. There is no bar but a vertical line with a number above. Y axis ranges from 0 to 12 when selecting only a year, 0-24 when selecting 2 years.

**Comment by MisterY** [comment]
Thanks for the info. The update of the chart library broke the compatibility and now the indices on the axes are wrong, it seems.
