### ISSUE TITLE
cannot reset PIN even if I have reinstalled the app (Android)

### ISSUE THREAD

**Issue by itmagician** [moneymanagerex/android-money-manager-ex#916]
Hello,
App still requires to enter PIN. I have erased all data, reinstalled the App. It is still needs PIN.
I use version from Google Play, xiaomi redmi note 3 pro miui 7.17.9.0.
I also don't understand why my old PIN haven't been accepted, I'm not sure that I'm able to forgot my personal birth day :)
Regards, Anton

**Comment by MisterY** [comment]
The pin is stored in the database and the database is not deleted when the app is uninstalled. This is a critical feature so that users do not lose data by accidentally uninstalling the app.
