### ISSUE TITLE
Automatic synchronisation does not work

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#918]
The periodic synchronisation does not work.
Apart from fixing the immediate issue, the synchronisation could be rewritten to use the sync framework. 

References
- https://www.bignerdranch.com/blog/choosing-the-right-background-scheduler-in-android/
- http://stackoverflow.com/questions/14376470/scheduling-recurring-task-in-android
- https://developer.android.com/reference/java/util/concurrent/ScheduledExecutorService.html
- http://blog.udinic.com/2013/07/24/write-your-own-android-sync-adapter/
- https://developer.android.com/training/sync-adapters/index.html
- http://www.vogella.com/tutorials/AndroidTaskScheduling/article.html
- https://developer.android.com/reference/android/app/AlarmManager.html

**Comment by snarchio** [comment]
In the Manifest there is a missing receiver so the system can't call the right receiver
Here is the patch attached
[0001-Missing-receiver-for-the-periodic-sync.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/406371/0001-Missing-receiver-for-the-periodic-sync.zip)

**Comment by MisterY** [comment]
Thanks for spotting this! I will correct this in a week or so as I don't have access to Android development tools at the moment.
