### ISSUE TITLE
Use a different picker for default currency setting 

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#93]
The picker for the default currency selection is different to the one on the account creation. As it has no filter bar, it should be replaced with the one that has.

The one that is used for editing currencies and selecting them in account editing, has a filter available, which helps when selecting a currency.

**Comment by prannou** [comment]
I agree. It will be easier to have the selection with filter and it adds consistency to the app.

**Comment by AlessandroLazzari** [comment]
Ok. I agree with you. If you want we can proceed to implementation.
