### ISSUE TITLE
Unable to set automatic synchronization when no connection

### ISSUE THREAD

**Issue by snarchio** [moneymanagerex/android-money-manager-ex#930]
In `SyncSchedulerBroadcastReceiver.startHeartbeat(...)` the check `if (!sync.isActive()) return;` prevent to set the periodic alarm if no internet connection or if no wifi connection and OnlyOnWifi is checked

I think the method SyncManager.isActive() must be splitted into two methods conveniently called, one to check settings and another for connection

**Comment by MisterY** [comment]
Done. In the future, the Android sync framework will probably be utilized for this purpose.
