### ISSUE TITLE
App closes when adding a payee

### ISSUE THREAD

**Issue by havocesp** [moneymanagerex/android-money-manager-ex#948]
Automatically exit from app when add new payer

Screenshots at #949

**Comment by MisterY** [comment]
Could you provide some more details, please?

**Comment by havocesp** [comment]
It ocurs just when I touch in ok button to confirm the payee add.
App dont crash but just get out to Andriid desktop.

**Comment by MisterY** [comment]
Thanks for the info. However, that does not tell me much.
What is your Android version? Can you provide a log that shows any errors?
I can confirm that this functionality works as expected on Android versions 4.0.3 to 6.0.1. 
Please provide a test case that confirms the behaviour. I can not do much on an issue that can't be reproduced.

**Comment by havocesp** [comment]
I have Android 5.1.1 and my device is Samsung Galaxy A3.

**Comment by MisterY** [comment]
I am using the app daily on a 5.1.1 Samsung A6. Definitely not experiencing any issues in the Currencies section. Please check the Logcat.
I would like to add a switch to enable debug logging in the upcoming versions. This would allow better troubleshooting for the devices experiencing any issues.

**Comment by MisterY** [comment]
Can you describe the way you are entering a Payee? Is it on the Payees screen or from a new transaction directly?

**Comment by MisterY** [comment]
Any response?

**Comment by havocesp** [comment]
In the payee screen directly.

**Comment by havocesp** [comment]
But i am trying now and it work well with last update.

**Comment by MisterY** [comment]
Thanks for the feedback! I have also improved the error reporting mechanism recently. Any exceptions should now also be displayed on the screen. Just let me know should you experience any issues going forward.
