### ISSUE TITLE
Currency screen lot of errors

### ISSUE THREAD

**Issue by havocesp** [moneymanagerex/android-money-manager-ex#949]
When try to  refresh currency exchange rate app shows 1 toast error by each currency. 

And 1 add on request. Let user create own currency or add some newer digital currency like Bitcoins or ethereum.

Regatds

**Comment by MisterY** [comment]
Please be more concise, provide technical details that allow correcting any issues identified. I can not reproduce any of the reported issues. Closing.

**Comment by havocesp** [comment]
Sorry. I am Android developer but in ths case I am just a user I could send a screenshot or maybe a shor video showing how it happens.

**Comment by MisterY** [comment]
Yes, please. Anything that would help. I can not reproduce this. The currencies work as expected on several test devices and emulators, using Android versions 4.0.3 to 6.0.1.
Considering you are an Android developer, I would also highly encourage you to inspect the issue on the affected device and provide a solution. This is an Open Source project and contributions from users are the only way to move forward.
I am also just a user, like you. There are no permanent project members.

**Comment by havocesp** [comment]
Yes now a have some free time and I have been taking a look to code ... just an overview but I am working in some other projects and I do no have enough time to investigate.

I going to take al least some  screenshots  guve some minutes.

**Comment by MisterY** [comment]
OK, no worries. I might have a look when I find some time.

**Comment by havocesp** [comment]
I have shared some screenshots  fron my Google Drive, here is the link:

https://drive.google.com/folderview?id=0B4zGD4zYIaOedjFMYnM5NE0wX00

Regards

**Comment by MisterY** [comment]
Thanks. These messages should be safe to ignore. It means that a currency could not be read from a locale available in the system. However, I will use this item to improve the error messaging for this scenario.
In practical use, most currencies are already inside the MMEX database. Perhaps #812 will help in this case.

**Comment by MisterY** [comment]
The correction will come in the next release. Please try the next Beta version to try it out.
Creating custom currencies will be possible after #892.
