### ISSUE TITLE
Styling issues on Create New Recurring Transaction

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#95]
- ~~Split checkbox overlaps the text on create new recurring transaction on KitKat.~~ - fixed
- "Add" button text on split tx hard to see.
- ~~remove split transaction not visible in Dark theme, as per #79, but the functionality works.~~ - tracked under #79.

**Comment by AlessandroLazzari** [comment]
I am aware, I have not had the time to fix. Do you fix it?

**Comment by MisterY** [comment]
I'm currently playing around with this screen, working on the title for the split, so I'll just create all the issues that I run into first.

**Comment by AlessandroLazzari** [comment]
You could put the button Add with layout flat at the bottom of the listview. Or if not, why not implement in this activity on a floating action button (FAB). Indeed, I think it would be the best solution for you.

**Comment by MisterY** [comment]
That's a good idea. Right now, I think, it's mostly styling issues. But you are right, I'd also rather implement the floating button, then.
