### ISSUE TITLE
App restarts when adding Payee.

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/android-money-manager-ex#956]
Since last beta upgrade (today), the app restarts when touching the Payee field. The app also crash (back to launcher) when touching the 'preferences' or  'about' menu. I'm using Android 5.0.2 (Huawei P8 lite).

**Comment by MisterY** [comment]
Please always report the exact version number. There were at least three versions released today.

**Comment by MisterY** [comment]
Cannot reproduce with the build 886.

**Comment by xraynaud** [comment]
How can I get build number if I can't load the about page ?

**Comment by xraynaud** [comment]
I have just check the play store and found a new version available. It works all right with this new version (build 886). Sorry.

**Comment by MisterY** [comment]
Play Store page, App system info, or any type of tool like Titanium Backup, for example.

**Comment by MisterY** [comment]
No worries. Thanks for reporting, in any case. This is the whole point of the Beta channel.
