### ISSUE TITLE
Wrong amounts on Split Transaction, new recurring transaction

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#96]
In split screen, when mixing deposit and withdrawal transactions, the income is wrongly calculated. It gets negative prefix and the total amount is displayed wrongly when going back to the New Recurring Transaction screen.

**Comment by MisterY** [comment]
The desktop version works in a very specific way:
- The transaction must have a positive amount.
- For any "negative" amount, the transaction type has to be adjusted (from income to withdrawal, for example) and the number changed to positive.

This means that only the cases with negative values would not be accepted by the app.

**Comment by guanlisheng** [comment]
I think the existing behavior is pretty normal while the negative amount is abnormal in accounting 

LiSheng

**Comment by MisterY** [comment]
True, for double-entry bookkeeping both numbers have to be positive - one debit and the other credit.
But for one ledger systems, I would expect to have debit and credit transaction based on the sign (+/-). Maybe I'm wrong?

Both of these cases can be handled in code. I will adjust the behaviour to match the desktop version, where the Amount always has to be positive and the sign depends on the Type.

**Comment by MisterY** [comment]
The practical problem is that there is no field to indicate the transaction type in the Split Transactions.

**Comment by guanlisheng** [comment]
I think both ways should use unsigned amount + type.

LiSheng

**Comment by MisterY** [comment]
Aha, OK, I see. In the Splits, we do use the negative amounts.
This is the confusing bit.

**Comment by guanlisheng** [comment]
Yep and this is not big issue since it is inherited from the parent transaction instead of the splits themselves. 

LiSheng

**Comment by MisterY** [comment]
I understand how to resolve the issue now. 

But I must admit I do not understand the point of the transaction type. The sign should be enough to determine whether the transaction is debit or credit. The correct sum is always produced by adding all the amounts. Whether for category, an account, a period, or any other way.
And there is no magic in figuring out whether something is a debit or a credit. Category and a number should be enough to determine this. I would just love to see some explanation on why this principle was used.
I find it quite redundant to have to know the transaction type in order to know whether to add or subtract the two numbers (20  +/-  20) when a simple sign would do (20  +  -20).

**Comment by guanlisheng** [comment]
One basic requirement is to sum both the withdrawal and deposit . We cannot do that base on the sign.

LiSheng

**Comment by MisterY** [comment]
Fixed!

**Comment by MisterY** [comment]
Switching from Withdrawal to Deposit not handling well. Needs checking.

**Comment by MisterY** [comment]
Now complete, with #109.
