### ISSUE TITLE
Newer Local database overwritten by cloud sync

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#970]
Using today last beta version

1. Running app w/ WiFi online
2. Turn off wifi
3.  Add new transacción and save it.
4. Turn on wifi
5. Click synchronization from the menu
6. The old database is downloaded from Dropbox.
7. The last register was lost.

**Comment by MisterY** [comment]
Thanks! Will test this further. Just one question - was the remote file updated in the meantime?

**Comment by MisterY** [comment]
Quick help for you, though - every download operation also now creates a backup file. Have a look at your database location and check the bak file.

**Comment by Geoplace** [comment]
No the only writter to the database is my device.
Maybe these is related with the fact that when the app is open with no internet connection the sync option in the menu disappear and even I turn it on the app doesn't recognize it Until it is close and open again.

Thank you for the back file tip.

**Comment by MisterY** [comment]
The local change indicator was not saved if the sync was not active. Therefore, the changes were ignored. Fixed. 
Plus the synchronisation algorithm has been rewritten (#972).
