### ISSUE TITLE
Collapsing accounts and summary on top

### ISSUE THREAD

**Issue by mehranm** [moneymanagerex/android-money-manager-ex#980]
When opening up the app, all the accounts expanded and summary is shown on the bottom and not visible unless scrolled up. Rather the summary needs to be displayed on top and accounts collapsed. Thanks

**Comment by MisterY** [comment]
The preferences for account groups visibility are saved. You can collapse the groups and the setting will be kept.
This would also tie into #808 and/or some sort of redesign of the Home screen.

**Comment by mehranm** [comment]
Thanks for the feedback. Great.
