### ISSUE TITLE
Report is filtered by subcategory rather than Category

### ISSUE THREAD

**Issue by ghost** [moneymanagerex/android-money-manager-ex#983]
The report " Where the Money Goes" displayed as pie chart and list filtered by subcategory, though the heading says Category! This is too much details as there are many subcategories. Could there be an option to select Category or Sub-category? Thanks

**Comment by luisdev** [comment]
I agree that this is still an issue. It would be ideal if this was a configurable option so that you can select whether the report is filtered by category or subcategory.

**Comment by wolfsolver** [comment]
With new nested category there no more difference between category and subcategory,

Report show all nested category as in this sample

You can see for example my Veicoli : Moto : Benzina

<img width="270" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/f9a1cfbf-5745-4027-9c53-fcee7094858e">

I think that can be close
