### ISSUE TITLE
Favourite cash account not visible in Home

### ISSUE THREAD

**Issue by mehranm** [moneymanagerex/android-money-manager-ex#984]
In Android app, I have set my cash account to favourite and tick setting box to show only favourite accounts but my favourite cash account is not visible.

**Comment by MisterY** [comment]
I've been using the app with such settings for years without issues. Could you double check? I can't reproduce this.

**Comment by mehranm** [comment]
I figured it out. There are two separate locations for the star. One when the account is edited. The other when displaying the account. Are they supposed to do the same thing? They don't seem to be in sync? I was enabling Favourite  when editing the account and that didn't work. Mehran

**Comment by MisterY** [comment]
Yes, they are(or should be) doing the same thing. Both will set the account as favourite when the star is marked. Just tried and it seems to be applied when going back to the main screen. Could you specify a test case that demonstrates this behaviour?

**Comment by mehranm** [comment]
I think it was syncing issue between Windows version and Android app, which I do through Dropbox! If I apply that just in the Android app it works. Thanks for your help.

**Comment by MisterY** [comment]
Thanks for the confirmation!
