### ISSUE TITLE
Show the current database name in the toolbar

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#986]

**Comment by diggy128** [comment]
I'm guessing here that the purpose is to better identify which database is open.
I have another proposition though: Show the database name in the app window title replacing "Money manager Ex" and move the app name to the slide menu next to the app icon.

The reasoning is simple: When you open the app you know what app you're using and further more the search and sync icons relate to the database itself so it would make sense to have the database name besides them.

**Comment by MisterY** [comment]
Great idea! The app bar supports subtitles so it should be easy to add the database name there.
