### ISSUE TITLE
Paragraph Condensing

### ISSUE THREAD

**Issue by ghost** [moneymanagerex/android-money-manager-ex#990]
Similar to font condensing could we have paragraph condensing? There seems to be so much empty space between each accounts on the Home screen on my Samsung Note. I'm not sure if this is very different on others handsets. Thanks

**Comment by mehranm** [comment]
Not really an issue but suggedtion. Thanks

**Comment by MisterY** [comment]
Hi, could you submit a screenshot to show what exactly you have in mind? Thanks!

**Comment by mehranm** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/21218122/18436149/1f4a3836-793a-11e6-816b-6961ee34ecd3.jpg)

Thank you

**Comment by MisterY** [comment]
Great, thanks. Adjusting the landscape layouts would be a good start.
